import {
  assertDecimalString,
  assertHash,
  assertNonEmptyString,
  decodeCanonicalJson,
  decodeExactObject,
  deepFreeze,
  encodeCanonicalJson,
  fieldArray,
  hashDomain,
  type CanonicalJson,
  type Hash,
} from "../../../../packages/canonical-codec/src/index.ts";
import { erc20AssetPortBindingV1 } from "../../../../packages/asset-ref/src/index.ts";
import type { ExecutionFactSourceV1, ProgramInterpretationDraftV1, TransportFactV1 } from "../../../../packages/capability-interpreters/src/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type SchemaRef } from "../../../../packages/capability-contracts/src/index.ts";
import type { FamilyRuntimeStageV1, FamilyStageDefinitionV1, FamilyStageGenericInvocationV1 } from "../../../../packages/family-sdk/runtime/index.ts";
import type { FrozenProgramEnvelopeV1, ProgramSourceAnchorV1 } from "../../../../packages/request-program/src/index.ts";
import { sealInstancePublication, validateInstancePublication, type InstancePublicationV1 } from "../../../../packages/catalog/src/index.ts";
import { decodeCandidateEvidenceRef, familyCandidateKey as centralFamilyCandidateKey, type CandidateRecordV1, type CanonicalCutoffV1, type RecentLogEvidenceRefV1 } from "../../../../packages/discovery/src/index.ts";
import { PSM_FAMILY_AUTHORING_HASH } from "../family-definition.ts";
import { PSM_FAMILY_ID, PSM_FAMILY_VERSION } from "../manifest.ts";
import { decodePsmCandidate, nominatePsm, verifyPsmIdentityStage, identityDescriptorHash, materializePsm, resealPsmState, derivePsmRoutes } from "../stages.ts";
import type { PsmCandidateV1, PsmCutoffV1, PsmIdentityV1, PsmMaterializedStateV1, PsmStateReadFactsV1, PsmObservationV1, PsmIdentityReadFactsV1 } from "../types.ts";

const VERSION = asCapabilityVersion(PSM_FAMILY_VERSION);
export const PSM_STAGE_IDS = Object.freeze({
  nomination: `family.${PSM_FAMILY_ID}.nomination`,
  identity: `family.${PSM_FAMILY_ID}.identity`,
  materialization: `family.${PSM_FAMILY_ID}.materialization`,
  projection: `family.${PSM_FAMILY_ID}.projection`,
  rehydration: `family.${PSM_FAMILY_ID}.rehydration`,
});
export const PSM_STAGE_SCHEMA_HASHES = Object.freeze({
  nomination: hashDomain("aloha/psm/stage-schema/v1", "nomination"),
  identity: hashDomain("aloha/psm/stage-schema/v1", "identity"),
  materialization: hashDomain("aloha/psm/stage-schema/v1", "materialization"),
  projection: hashDomain("aloha/psm/stage-schema/v1", "projection"),
  rehydration: hashDomain("aloha/psm/stage-schema/v1", "rehydration"),
});
type Stage = keyof typeof PSM_STAGE_IDS;
type CandidateRecord = Omit<CandidateRecordV1, "evidence"> & { readonly evidence: readonly RecentLogEvidenceRefV1[] };
interface IdentityMemo { readonly kind: "psm-identity-memo"; readonly familyId: typeof PSM_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identity: PsmIdentityV1; }
interface NominationPayload { readonly kind: "psm-nomination-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["candidate"]; readonly requestId: Hash; }
interface IdentityPayload { readonly kind: "psm-identity-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["identity"]; readonly requestId: Hash; }
interface MaterializationPayload { readonly kind: "psm-materialization-input"; readonly identityMemo: IdentityMemo; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface MaterializationOutput { readonly kind: "psm-materialization-output"; readonly familyId: typeof PSM_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identityMemoHash: Hash; readonly identityFactsHash: Hash; readonly instanceKey: string; readonly state: PsmMaterializedStateV1; readonly evidenceRoot: Hash; }
interface ProjectionPayload { readonly kind: "psm-projection-input"; readonly identityMemo: IdentityMemo; readonly materialization: MaterializationOutput; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface RehydrationPayload { readonly kind: "psm-rehydration-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["reference"]; readonly referenceHash: Hash; readonly requestId: Hash; }

function canonical(value: unknown): CanonicalJson { return decodeCanonicalJson(encodeCanonicalJson(value)); }
function address(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x[0-9a-fA-F]{40}$/.test(text)) throw new TypeError(`${path} must be an address`); return `0x${text.slice(2).toLowerCase()}`; }
function bytes(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x(?:[0-9a-f]{2})*$/.test(text)) throw new TypeError(`${path} must be lowercase bytes`); return text; }
function cutoff(value: unknown, path: string): CanonicalCutoffV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function sameCutoff(left: PsmCutoffV1, right: PsmCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
function sameSource(left: ExecutionFactSourceV1, right: ProgramSourceAnchorV1): boolean { return left.chainId === right.chainId && left.blockNumber === right.number && left.blockHash === right.hash && left.stateRoot === right.stateRoot; }
function factData(value: string): CanonicalJson { const raw = value.slice(2); const bytesValue = new Uint8Array(raw.length / 2); for (let i = 0; i < bytesValue.length; i += 1) bytesValue[i] = Number.parseInt(raw.slice(i * 2, i * 2 + 2), 16); return decodeCanonicalJson(new TextDecoder().decode(bytesValue)); }
function invalidCode(error: unknown, fallback: string): string { const raw = error instanceof Error ? error.message : String(error); const code = raw.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); return /^[a-z][a-z0-9-]*$/.test(code) ? code : fallback; }
function requestId(phase: string, target: string, cutoffValue: CanonicalCutoffV1, snapshot: Hash, operation: string): Hash { return hashDomain("aloha/psm/runtime-request/v1", { phase, target, cutoff: cutoffValue, candidateSnapshotHash: snapshot, operation }); }
function referenceHash(candidate: CandidateRecord, cutoffValue: CanonicalCutoffV1): Hash { return hashDomain("aloha/psm/rehydration-reference/v1", { familyDefinitionHash: candidate.familyDefinitionHash, familyCandidateKey: candidate.familyCandidateKey, candidateSubjectHash: candidate.candidateSubjectHash, instanceNominationKey: candidate.instanceNominationKey, cutoff: cutoffValue }); }

function candidateRecord(value: unknown, path = "psm.candidate"): CandidateRecord {
  const decoded = decodeExactObject<CandidateRecord>(value, {
    kind: (item, itemPath) => { if (item !== "aloha.candidate-record") throw new TypeError(`${itemPath} kind mismatch`); return item; },
    version: (item, itemPath) => { if (item !== "2") throw new TypeError(`${itemPath} version mismatch`); return item; },
    familyId: (item, itemPath) => { if (item !== PSM_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return PSM_FAMILY_ID; },
    familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath),
    instanceNominationKey: (item, itemPath) => address(item, itemPath),
    familyCandidateKey: (item, itemPath) => assertHash(item, itemPath),
    candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath),
    candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath),
    evidence: (item, itemPath) => fieldArray(item, (entry, entryPath) => { const evidence = decodeCandidateEvidenceRef(entry, entryPath); if (evidence.kind !== "recent-log") throw new TypeError("psm candidate evidence must be recent-log"); return evidence; }, itemPath),
  }, path);
  if (decoded.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH) throw new TypeError("psm candidate definition mismatch");
  if (decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("psm candidate key mismatch");
  if (decoded.evidence.length === 0) throw new TypeError("psm candidate evidence empty");
  const keys = decoded.evidence.map(item => hashDomain("aloha/candidate-evidence-ref/v1", item));
  if (new Set(keys).size !== keys.length || keys.some((item, index) => item !== [...keys].sort()[index])) throw new TypeError("psm candidate evidence order");
  if (decoded.evidence.some(item => address(item.address, "psm.candidate.evidence.address") !== decoded.instanceNominationKey)) throw new TypeError("psm candidate evidence target mismatch");
  return deepFreeze(decoded);
}
function reconstructCandidate(record: CandidateRecord, cutoffValue: CanonicalCutoffV1): PsmCandidateV1 {
  let selected: PsmCandidateV1 | null = null;
  for (const evidence of record.evidence) {
    const observation: PsmObservationV1 = { kind: "log", target: evidence.address, blockNumber: evidence.blockNumber, blockHash: evidence.blockHash, txHash: evidence.txHash, logIndex: evidence.logIndex, rawLocatorHash: evidence.rawLocatorHash, cutoff: cutoffValue };
    const seed = { target: evidence.address, evidence: observation };
    const nomination = nominatePsm(seed);
    if (nomination.status !== "nominated" || nomination.candidate.instanceNominationKey !== record.instanceNominationKey || nomination.candidate.candidateSnapshotHash !== record.candidateSubjectHash) throw new TypeError("psm candidate lineage mismatch");
    if (selected !== null) throw new TypeError("psm candidate has multiple snapshots");
    selected = nomination.candidate;
  }
  if (selected === null || !sameCutoff(selected.evidence.cutoff, cutoffValue)) throw new TypeError("psm candidate snapshot missing");
  return selected;
}
function identity(value: unknown, path: string): PsmIdentityV1 {
  const decoded = decodeExactObject<PsmIdentityV1>(value, {
    cutoff: (item, itemPath) => cutoff(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), factsHash: (item, itemPath) => assertHash(item, itemPath),
    facts: (item, itemPath) => decodeExactObject(item, { target: (field, fieldPath) => address(field, fieldPath), inputAsset: (field, fieldPath) => address(field, fieldPath), outputAsset: (field, fieldPath) => address(field, fieldPath) }, itemPath),
  }, path);
  if (decoded.instanceKey !== decoded.facts.target || decoded.factsHash !== hashDomain("aloha/psm/identity-facts/v1", decoded.facts)) throw new TypeError("psm identity hash mismatch");
  return deepFreeze(decoded);
}
function identityMemo(value: unknown, path = "psm.identityMemo"): IdentityMemo {
  const decoded = decodeExactObject<IdentityMemo>(value, {
    kind: (item, itemPath) => { if (item !== "psm-identity-memo") throw new TypeError(`${itemPath} kind mismatch`); return "psm-identity-memo"; }, familyId: (item, itemPath) => { if (item !== PSM_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return PSM_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), identity: (item, itemPath) => identity(item, itemPath),
  }, path);
  if (decoded.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceNominationKey !== decoded.identity.instanceKey || decoded.candidateSnapshotHash !== decoded.identity.candidateSnapshotHash) throw new TypeError("psm identity memo lineage mismatch");
  return deepFreeze(decoded);
}
function state(value: unknown, path: string): PsmMaterializedStateV1 {
  const decoded = decodeExactObject<PsmMaterializedStateV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), feeWad: (item, itemPath) => assertDecimalString(item, itemPath), assetScale: (item, itemPath) => assertDecimalString(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), stateHash: (item, itemPath) => assertHash(item, itemPath) }, path);
  if (decoded.stateHash !== resealPsmState(decoded)) throw new TypeError("psm state hash mismatch");
  return deepFreeze(decoded);
}
function materializationOutput(value: unknown, path = "psm.materializationOutput"): MaterializationOutput {
  const decoded = decodeExactObject<MaterializationOutput>(value, { kind: (item, itemPath) => { if (item !== "psm-materialization-output") throw new TypeError(`${itemPath} kind mismatch`); return "psm-materialization-output"; }, familyId: (item, itemPath) => { if (item !== PSM_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return PSM_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), state: (item, itemPath) => state(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path);
  if (decoded.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceKey !== decoded.state.instanceKey || decoded.identityFactsHash !== decoded.state.identityFactsHash || decoded.candidateSnapshotHash !== decoded.evidenceRoot) throw new TypeError("psm materialization lineage mismatch");
  return deepFreeze(decoded);
}
function readPlan(value: unknown, expected: readonly string[], path: string): readonly string[] { const result = fieldArray(value, (item, itemPath) => assertNonEmptyString(item, itemPath), path); if (result.length !== expected.length || result.some((item, index) => item !== expected[index])) throw new TypeError(`${path} read plan mismatch`); return Object.freeze([...result]); }
function hashValue(value: unknown, path: string): Hash { return assertHash(value, path); }
function nominationPayload(value: unknown, path = "psm.nominationPayload"): NominationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-nomination-input") throw new TypeError(`${itemPath} kind mismatch`); return "psm-nomination-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["candidate"], itemPath) as readonly ["candidate"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function identityPayload(value: unknown, path = "psm.identityPayload"): IdentityPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-identity-input") throw new TypeError(`${itemPath} kind mismatch`); return "psm-identity-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["identity"], itemPath) as readonly ["identity"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function materializationPayload(value: unknown, path = "psm.materializationPayload"): MaterializationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-materialization-input") throw new TypeError(`${itemPath} kind mismatch`); return "psm-materialization-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function projectionPayload(value: unknown, path = "psm.projectionPayload"): ProjectionPayload { const decoded = decodeExactObject<ProjectionPayload>(value, { kind: (item, itemPath) => { if (item !== "psm-projection-input") throw new TypeError(`${itemPath} kind mismatch`); return "psm-projection-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), materialization: (item, itemPath) => materializationOutput(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.materialization.instanceKey !== decoded.identityMemo.identity.instanceKey || decoded.materialization.identityFactsHash !== decoded.identityMemo.identity.factsHash || decoded.materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", decoded.identityMemo)) throw new TypeError("psm projection lineage mismatch"); return decoded; }
function rehydrationPayload(value: unknown, path = "psm.rehydrationPayload"): RehydrationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-rehydration-input") throw new TypeError(`${itemPath} kind mismatch`); return "psm-rehydration-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["reference"], itemPath) as readonly ["reference"], referenceHash: (item, itemPath) => hashValue(item, itemPath), requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function boundFact(program: FrozenProgramEnvelopeV1, facts: readonly TransportFactV1[], expected: Hash): Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }> { if (facts.length !== 1) throw new TypeError("psm transport fact partition mismatch"); const fact = facts[0]!; if (fact.kind === "transportFailure" || fact.requestId !== expected || fact.requestFingerprint !== program.requestFingerprint || !sameSource(fact.source, program.source)) throw new TypeError("psm transport fact binding mismatch"); return fact; }
function decodeFact(value: Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }>): CanonicalJson { return factData(bytes(value.dataHex, "psm.fact.dataHex")); }
function ack(value: unknown, kind: string): Hash { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== kind) throw new TypeError(`${itemPath} kind mismatch`); return kind; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, value: (item, itemPath) => assertHash(item, itemPath) }).value; }
function outputObject(value: unknown, path: string): CanonicalJson { const result = canonical(value); if (result === null || typeof result !== "object" || Array.isArray(result)) throw new TypeError(`${path} must be an object`); return result; }
function nominationOutput(value: unknown, path = "psm.nominationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-nomination-verified") throw new TypeError(`${itemPath} kind mismatch`); return "psm-nomination-verified"; }, familyId: (item, itemPath) => { if (item !== PSM_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return PSM_FAMILY_ID; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }
function identityOutput(value: unknown, path = "psm.identityOutput"): CanonicalJson { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "identityVerified") throw new TypeError(`${itemPath} kind mismatch`); return "identityVerified"; }, familyInstanceKey: (item, itemPath) => address(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); const memo = decoded.identityMemo; if (decoded.familyInstanceKey !== memo.identity.instanceKey || decoded.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || decoded.descriptorHash !== identityDescriptorHash(memo.identity) || decoded.evidenceRoot !== memo.candidateSnapshotHash) throw new TypeError("psm identity output lineage mismatch"); return outputObject(decoded, path); }
function materializationOutputCodec(value: unknown): CanonicalJson { return outputObject(materializationOutput(value), "psm.materializationOutput"); }
function publicationOutput(value: unknown): CanonicalJson { const decoded = canonical(value); if (decoded === null || typeof decoded !== "object" || Array.isArray(decoded)) throw new TypeError("psm projection output must be object"); validateInstancePublication(decoded as unknown as InstancePublicationV1); return decoded; }
function rehydrationOutput(value: unknown, path = "psm.rehydrationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-rehydration-verified") throw new TypeError(`${itemPath} kind mismatch`); return "psm-rehydration-verified"; }, familyId: (item, itemPath) => { if (item !== PSM_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return PSM_FAMILY_ID; }, instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }

function requireStage(input: FamilyStageGenericInvocationV1, expected: Stage): void { if (input.stage !== expected) throw new TypeError(`psm-${expected}-stage-mismatch`); }
function noPrior(input: FamilyStageGenericInvocationV1): void { if (input.identityMemo !== null || input.materializationOutput !== null) throw new TypeError("psm unexpected prior output"); }
function prepareNomination(input: FamilyStageGenericInvocationV1): NominationPayload { requireStage(input, "nomination"); noPrior(input); const c = cutoff(input.cutoff, "psm.nomination.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "psm-nomination-input", candidate, cutoff: c, readPlan: ["candidate"], requestId: requestId("nomination", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "candidate") }; }
function prepareIdentity(input: FamilyStageGenericInvocationV1): IdentityPayload { requireStage(input, "identity"); noPrior(input); const c = cutoff(input.cutoff, "psm.identity.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "psm-identity-input", candidate, cutoff: c, readPlan: ["identity"], requestId: requestId("identity", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "identity") }; }
function prepareMaterialization(input: FamilyStageGenericInvocationV1): MaterializationPayload { requireStage(input, "materialization"); if (input.identityMemo === null || input.materializationOutput !== null) throw new TypeError("psm materialization prior output mismatch"); const c = cutoff(input.cutoff, "psm.materialization.cutoff"); const memo = identityMemo(input.identityMemo); if (!sameCutoff(c, memo.identity.cutoff)) throw new TypeError("psm materialization cutoff mismatch"); return { kind: "psm-materialization-input", identityMemo: memo, cutoff: c, readPlan: ["state"], requestId: requestId("materialization", memo.identity.instanceKey, c, memo.candidateSnapshotHash, "state") }; }
function prepareProjection(input: FamilyStageGenericInvocationV1): ProjectionPayload { requireStage(input, "projection"); if (input.identityMemo === null || input.materializationOutput === null) throw new TypeError("psm projection prior output missing"); const c = cutoff(input.cutoff, "psm.projection.cutoff"); const memo = identityMemo(input.identityMemo); const materialization = materializationOutput(input.materializationOutput); if (!sameCutoff(c, memo.identity.cutoff) || materialization.instanceKey !== memo.identity.instanceKey || materialization.identityFactsHash !== memo.identity.factsHash || materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo)) throw new TypeError("psm projection lineage mismatch"); return { kind: "psm-projection-input", identityMemo: memo, materialization, cutoff: c, readPlan: ["state"], requestId: requestId("projection", memo.identity.instanceKey, c, memo.candidateSnapshotHash, "state") }; }
function prepareRehydration(input: FamilyStageGenericInvocationV1): RehydrationPayload { requireStage(input, "rehydration"); noPrior(input); const c = cutoff(input.cutoff, "psm.rehydration.cutoff"); const candidate = candidateRecord(input.candidate); const reference = referenceHash(candidate, c); return { kind: "psm-rehydration-input", candidate, cutoff: c, readPlan: ["reference"], referenceHash: reference, requestId: requestId("rehydration", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, reference) }; }

function identityFact(value: unknown): { readonly candidateSnapshotHash: Hash; readonly reads: PsmIdentityReadFactsV1 } { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-identity-facts") throw new TypeError(`${itemPath} kind mismatch`); return "psm-identity-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), reads: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), target: (field, fieldPath) => address(field, fieldPath), reverseTarget: (field, fieldPath) => address(field, fieldPath), inputAsset: (field, fieldPath) => address(field, fieldPath), outputAsset: (field, fieldPath) => address(field, fieldPath) }, itemPath) }, "psm.identityFact"); return decoded; }
function stateFact(value: unknown): PsmStateReadFactsV1 { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "psm-state-facts") throw new TypeError(`${itemPath} kind mismatch`); return "psm-state-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, read: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), instanceKey: (field, fieldPath) => address(field, fieldPath), feeWad: (field, fieldPath) => assertDecimalString(field, fieldPath), assetScale: (field, fieldPath) => assertDecimalString(field, fieldPath) }, itemPath) }, "psm.stateFact"); return decoded.read; }
function publication(payload: ProjectionPayload, program: FrozenProgramEnvelopeV1): InstancePublicationV1 { const identityValue = payload.identityMemo.identity; const routes = derivePsmRoutes(identityValue); const transitions = routes.map(route => ({ inputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.inputAsset), portRef: hashDomain("aloha/psm/port/v1", { instanceKey: route.instanceKey, role: "input", asset: route.inputAsset }), ordinal: "0" }], outputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.outputAsset), portRef: hashDomain("aloha/psm/port/v1", { instanceKey: route.instanceKey, role: "output", asset: route.outputAsset }), ordinal: "0" }], opaqueTransitionRef: hashDomain("aloha/psm/transition/v1", route), constraintRefs: [payload.materialization.state.stateHash], staticProjectionHash: hashDomain("aloha/psm/static-transition/v1", route) })); const memo = canonical(payload.identityMemo); return sealInstancePublication({ familyId: PSM_FAMILY_ID, familyDefinitionHash: PSM_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.materialization.familyCandidateKey, instanceKey: identityValue.instanceKey, cutoff: payload.cutoff, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(identityValue), staticProjectionMemoHash: hashDomain("aloha/psm/static-projection/v1", { routes, stateHash: payload.materialization.state.stateHash }), requestedArtifactDependencyRoot: hashDomain("aloha/psm/requested-artifacts/v1", { identityFactsHash: identityValue.factsHash, stateHash: payload.materialization.state.stateHash }), validityDependencyRoot: hashDomain("aloha/psm/validity/v1", { source: program.source, identityFactsHash: identityValue.factsHash, stateHash: payload.materialization.state.stateHash }), transitions, evidenceRoot: payload.materialization.evidenceRoot }); }
function interpretNomination(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = nominationPayload(input.payload); reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "psm-nomination-reverted" }; const value = ack(decodeFact(fact), "psm-nomination-facts"); if (value !== payload.candidate.candidateSubjectHash) throw new TypeError("psm nomination acknowledgement mismatch"); return { kind: "verified", output: { kind: "psm-nomination-verified", familyId: PSM_FAMILY_ID, candidateSubjectHash: value, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: hashDomain("aloha/psm/nomination-reference/v1", { candidateSubjectHash: value, cutoff: payload.cutoff }) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "psm-nomination-invalid") }; } }
function interpretIdentity(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = identityPayload(input.payload); const candidate = reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "psm-identity-reverted" }; const decoded = identityFact(decodeFact(fact)); if (decoded.candidateSnapshotHash !== candidate.candidateSnapshotHash) throw new TypeError("psm identity fact snapshot mismatch"); const result = verifyPsmIdentityStage({ candidate, reads: decoded.reads }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const memo: IdentityMemo = { kind: "psm-identity-memo", familyId: PSM_FAMILY_ID, familyDefinitionHash: PSM_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSnapshotHash: candidate.candidateSnapshotHash, identity: result.identity }; return { kind: "verified", output: { kind: "identityVerified", familyInstanceKey: result.identity.instanceKey, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(result.identity), evidenceRoot: candidate.candidateSnapshotHash } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "psm-identity-invalid") }; } }
function interpretMaterialization(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = materializationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "psm-materialization-reverted" }; const read = stateFact(decodeFact(fact)); if (!sameCutoff(read.cutoff, payload.cutoff) || read.instanceKey !== payload.identityMemo.identity.instanceKey) throw new TypeError("psm state fact lineage mismatch"); const result = materializePsm({ identity: payload.identityMemo.identity, read }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const output: MaterializationOutput = { kind: "psm-materialization-output", familyId: PSM_FAMILY_ID, familyDefinitionHash: PSM_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.identityMemo.familyCandidateKey, instanceNominationKey: payload.identityMemo.instanceNominationKey, candidateSnapshotHash: payload.identityMemo.candidateSnapshotHash, identityMemoHash: hashDomain("aloha/identity-memo/v1", payload.identityMemo), identityFactsHash: payload.identityMemo.identity.factsHash, instanceKey: result.state.instanceKey, state: result.state, evidenceRoot: payload.identityMemo.candidateSnapshotHash }; return { kind: "verified", output }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "psm-materialization-invalid") }; } }
function interpretProjection(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = projectionPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "psm-projection-reverted" }; const read = stateFact(decodeFact(fact)); const result = materializePsm({ identity: payload.identityMemo.identity, read }); if (result.status !== "verified") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; if (result.state.stateHash !== payload.materialization.state.stateHash) throw new TypeError("psm projection state lineage mismatch"); return { kind: "verified", output: publication(payload, input.program) }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "psm-projection-invalid") }; } }
function interpretRehydration(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = rehydrationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "psm-rehydration-reverted" }; const value = ack(decodeFact(fact), "psm-rehydration-facts"); if (value !== payload.referenceHash) throw new TypeError("psm rehydration acknowledgement mismatch"); return { kind: "verified", output: { kind: "psm-rehydration-verified", familyId: PSM_FAMILY_ID, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: value } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "psm-rehydration-invalid") }; } }

function definitionBase(stage: Stage, payloadCodec: { readonly schemaRef: SchemaRef; readonly decodeExact: (value: unknown) => unknown }, outputSchemaRef: Hash, outputCodec: { readonly decodeExact: (value: unknown) => CanonicalJson }, prepareIssueValue: FamilyStageDefinitionV1["prepareIssueValue"], interpret: FamilyStageDefinitionV1["interpret"]): FamilyStageDefinitionV1 { return deepFreeze({ stage, capabilityId: asCapabilityId(PSM_STAGE_IDS[stage]), version: VERSION, schemaHash: asSchemaRef(PSM_STAGE_SCHEMA_HASHES[stage]), payloadCodec: deepFreeze(payloadCodec), dependencyIds: Object.freeze([]), outputSchemaRef, implementationClosureHash: hashDomain("aloha/psm/runtime-implementation/v1", { stage, module: "families/psm/src/runtime/definitions.ts" }), outputCodecHash: hashDomain("aloha/psm/runtime-output-codec/v1", stage), outputCodec: deepFreeze(outputCodec), prepareIssueValue, interpret }); }
const codecs = Object.freeze({ nomination: { schemaRef: asSchemaRef(PSM_STAGE_SCHEMA_HASHES.nomination), decodeExact: (value: unknown) => nominationPayload(value) }, identity: { schemaRef: asSchemaRef(PSM_STAGE_SCHEMA_HASHES.identity), decodeExact: (value: unknown) => identityPayload(value) }, materialization: { schemaRef: asSchemaRef(PSM_STAGE_SCHEMA_HASHES.materialization), decodeExact: (value: unknown) => materializationPayload(value) }, projection: { schemaRef: asSchemaRef(PSM_STAGE_SCHEMA_HASHES.projection), decodeExact: (value: unknown) => projectionPayload(value) }, rehydration: { schemaRef: asSchemaRef(PSM_STAGE_SCHEMA_HASHES.rehydration), decodeExact: (value: unknown) => rehydrationPayload(value) } });
const outputSchema = (stage: Stage): Hash => hashDomain("aloha/psm/runtime-output-schema/v1", stage);
export const PSM_NOMINATION_DEFINITION = definitionBase("nomination", codecs.nomination, outputSchema("nomination"), { decodeExact: value => nominationOutput(value) }, prepareNomination, interpretNomination);
export const PSM_IDENTITY_DEFINITION = definitionBase("identity", codecs.identity, outputSchema("identity"), { decodeExact: value => identityOutput(value) }, prepareIdentity, interpretIdentity);
export const PSM_MATERIALIZATION_DEFINITION = definitionBase("materialization", codecs.materialization, outputSchema("materialization"), { decodeExact: value => materializationOutputCodec(value) }, prepareMaterialization, interpretMaterialization);
export const PSM_PROJECTION_DEFINITION = definitionBase("projection", codecs.projection, outputSchema("projection"), { decodeExact: value => publicationOutput(value) }, prepareProjection, interpretProjection);
export const PSM_REHYDRATION_DEFINITION = definitionBase("rehydration", codecs.rehydration, outputSchema("rehydration"), { decodeExact: value => rehydrationOutput(value) }, prepareRehydration, interpretRehydration);
export const PSM_STAGE_DEFINITIONS: readonly FamilyStageDefinitionV1[] = Object.freeze([PSM_NOMINATION_DEFINITION, PSM_IDENTITY_DEFINITION, PSM_MATERIALIZATION_DEFINITION, PSM_PROJECTION_DEFINITION, PSM_REHYDRATION_DEFINITION]);
export function requirePsmStageDefinition(stage: FamilyRuntimeStageV1): FamilyStageDefinitionV1 { const definition = PSM_STAGE_DEFINITIONS.find(item => item.stage === stage); if (!definition) throw new TypeError(`psm stage definition missing: ${stage}`); return definition; }
