import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  METHOD_TRACE_FIELDS,
  parseMethodTraceFields,
  type MethodTraceField,
} from "../learning/method-trace.js";

type MethodTrace = Record<MethodTraceField, string> & {
  sourceFile: string;
  blockIndex: number;
  architectureMatrix: string;
};

/** Walk up from a path to the git repo root (dir containing .git); fallback = cwd. */
function repoRoot(from: string): string {
  let dir = resolve(dirname(from));
  for (let i = 0; i < 30; i++) {
    if (existsSync(join(dir, ".git"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

function isPlaceholder(v: string): boolean {
  const t = v.trim();
  return t === ""
    || /^<[A-Za-z]/.test(t)
    || /<[A-Za-z][^<>]*>/.test(t)
    || /^(todo|tbd|n\/a|na|fill|pending)$/i.test(t);
}

const TASK_CLASS_MENU = "competitor_path | bundle_postmortem | architecture_review | replay_fixture | protocol_leg | implementation";

function parseTrace(block: string, sourceFile: string, blockIndex: number, md: string): MethodTrace | null {
  const fields = parseMethodTraceFields(block);
  fields.task_class = fields.task_class.replace(/#.*$/, "").trim();

  if (isPlaceholder(fields.task_class) || fields.task_class === TASK_CLASS_MENU) return null;
  // skip an unfilled TEMPLATE block (e.g. the README example): a real trace has a filled distill_for_opus.
  if (isPlaceholder(fields.distill_for_opus)) return null;

  return {
    ...fields,
    sourceFile,
    blockIndex,
    architectureMatrix: fields.task_class === "architecture_review"
      ? extractArchitectureMatrix(md)
      : "",
  };
}

function extractArchitectureMatrix(md: string): string {
  const section = md.match(/(?:^|\n)##\s*Architecture Coverage Matrix[\s\S]*?(?=\n##\s|$)/i)?.[0] ?? "";
  return section
    .split(/\r?\n/)
    .filter((line) => line.trim().startsWith("|"))
    .join("\n")
    .trim();
}

function harvestFile(path: string): MethodTrace[] {
  const md = readFileSync(path, "utf8");
  const sourceFile = basename(path);
  return [...md.matchAll(/##\s*Method Trace[\s\S]*?(?=\n##\s|$)/gi)]
    .map((match, index) => parseTrace(match[0], sourceFile, index, md))
    .filter((trace): trace is MethodTrace => trace !== null);
}

function renderTraceField(field: MethodTraceField, value: string, emphasize = false): string[] {
  const valueLines = value.split("\n");
  if (valueLines.length === 1) {
    return [`- ${field}: ${emphasize ? `**${value}**` : value}`];
  }

  const lines = [`- ${field}:`];
  if (!emphasize) {
    lines.push(...valueLines.map((line) => `  ${line}`));
    return lines;
  }

  lines.push(...valueLines.map((line, index) => {
    const prefix = index === 0 ? "**" : "";
    const suffix = index === valueLines.length - 1 ? "**" : "";
    return `  ${prefix}${line}${suffix}`;
  }));
  return lines;
}

function renderTraceLibrary(traces: MethodTrace[]): string {
  const lines = [
    "# Method Traces — Opus/Fable project-method library (generated by `npm run distill-harvest`; do not hand-edit)",
    "> Single entry point for Opus to learn this project's analysis methods. Regenerate after new rounds.",
    "> Source: `## Method Trace` blocks in docs/research/reports/*.md (Hermes rounds) + docs/analysis/*.md (daily).",
    "",
  ];

  if (traces.length === 0) {
    lines.push("_(no Method Traces harvested yet — they accrue as rounds run.)_");
    return `${lines.join("\n")}\n`;
  }

  const taskClasses = [...new Set(traces.map((trace) => trace.task_class))].sort();
  for (const taskClass of taskClasses) {
    lines.push(`## ${taskClass}`);

    const entries = traces
      .filter((trace) => trace.task_class === taskClass)
      .sort((a, b) => a.sourceFile.localeCompare(b.sourceFile) || a.blockIndex - b.blockIndex);

    for (const trace of entries) {
      lines.push(`### ${trace.sourceFile}`);
      for (const field of METHOD_TRACE_FIELDS) {
        lines.push(...renderTraceField(field, trace[field], field === "distill_for_opus"));
      }
      if (trace.architectureMatrix) {
        lines.push(trace.architectureMatrix);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n").replace(/\n+$/u, "")}\n`;
}

function main(): void {
  const root = repoRoot(fileURLToPath(import.meta.url));
  const outPath = join(root, "docs", "distill", "method-traces.md");
  // Hermes round docs (reports/) AND daily Fable analysis outputs (analysis/) — one Opus library.
  const scanDirs = [
    join(root, "docs", "research", "reports"),
    join(root, "docs", "analysis"),
  ];
  const files = scanDirs
    .filter((dir) => existsSync(dir))
    .flatMap((dir) =>
      readdirSync(dir, { withFileTypes: true })
        .filter((entry) => entry.isFile() && entry.name.endsWith(".md") && entry.name !== "README.md")
        .map((entry) => join(dir, entry.name)),
    )
    .sort();

  const traces = files.flatMap(harvestFile)
    .sort((a, b) =>
      a.task_class.localeCompare(b.task_class)
      || a.sourceFile.localeCompare(b.sourceFile)
      || a.blockIndex - b.blockIndex,
    );

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderTraceLibrary(traces));

  const sourceCount = new Set(traces.map((trace) => trace.sourceFile)).size;
  console.log(`harvested ${traces.length} traces from ${sourceCount} files into docs/distill/method-traces.md`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
