import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { defineFundingFamilyContract } from "../../../packages/funding/src/index.ts";
import { MORPHO_FLASH_ACTION_OWNER_ID, MORPHO_FLASH_CAPABILITY_IDS, MORPHO_FLASH_FAMILY_ID, MORPHO_FLASH_FAMILY_VERSION, MORPHO_FLASH_INSTANCE_CONTRACT_SCHEMA_HASH, MORPHO_FLASH_OWNER_REF, MORPHO_FLASH_SINGLETON_SOURCE_PLAN_ID, MORPHO_FLASH_SOURCE_PLAN_ID } from "./manifest.ts";

const moduleRoot = "families/morpho-flash/src";
const version = asCapabilityVersion(MORPHO_FLASH_FAMILY_VERSION);
export const MORPHO_FLASH_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/morpho-flash/source-plan-schema/v1", MORPHO_FLASH_SOURCE_PLAN_ID));
export const MORPHO_FLASH_SINGLETON_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/morpho-flash/singleton-source-plan-schema/v1", MORPHO_FLASH_SINGLETON_SOURCE_PLAN_ID));
export const MORPHO_FLASH_FUNDING_CONTRACT = defineFundingFamilyContract({ familyId: MORPHO_FLASH_FAMILY_ID, version: MORPHO_FLASH_FAMILY_VERSION, actionOwnerId: MORPHO_FLASH_ACTION_OWNER_ID });
type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.morpho-flash.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/morpho-flash/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([MORPHO_FLASH_SOURCE_PLAN_ID, MORPHO_FLASH_SINGLETON_SOURCE_PLAN_ID]) } : {}) }); }
function slot(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { const dependencyIds = name === "state" ? [] : [asCapabilityId(MORPHO_FLASH_CAPABILITY_IDS.state)]; return Object.freeze({ capabilityId: asCapabilityId(MORPHO_FLASH_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/morpho-flash/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/morpho-flash/extension-interpreter/v1", name), dependencyIds: Object.freeze(dependencyIds), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "MORPHO_FLASH_RUNTIME" }); }
const nomination = core("nomination", "MORPHO_FLASH_NOMINATION_DEFINITION"); const identity = core("identity", "MORPHO_FLASH_IDENTITY_DEFINITION"); const materialization = core("materialization", "MORPHO_FLASH_MATERIALIZATION_DEFINITION"); const projection = core("projection", "MORPHO_FLASH_PROJECTION_DEFINITION"); const rehydration = core("rehydration", "MORPHO_FLASH_REHYDRATION_DEFINITION"); const state = slot("state"); const coarse = slot("coarse"); const exact = slot("exact");
export const MORPHO_FLASH_ACTION_OWNER = Object.freeze({ ownerId: MORPHO_FLASH_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/morpho-flash/action-schema/v1", "flash-loan")), implementationHash: hashDomain("aloha/morpho-flash/action-implementation/v1", "flash-loan"), actionKinds: Object.freeze(["flash-loan"]), modulePath: `${moduleRoot}/action.ts`, exportName: "MORPHO_FLASH_ACTION_PORT" });
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.morpho-flash.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/morpho-flash/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.morpho-flash.state-observation", version, schemaHash: asSchemaRef(hashDomain("aloha/morpho-flash/fact-schema/v1", "state")) }), Object.freeze({ factContractId: "family.morpho-flash.funding-obligation", version, schemaHash: asSchemaRef(MORPHO_FLASH_FUNDING_CONTRACT.schemaHash) }), Object.freeze({ factContractId: "family.morpho-flash.optional-instance-partition", version, schemaHash: asSchemaRef(MORPHO_FLASH_INSTANCE_CONTRACT_SCHEMA_HASH) })]);
const runtimeAdapter = Object.freeze({ modulePath: `${moduleRoot}/search-adapter.ts`, exportName: "MORPHO_FLASH_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: Object.freeze({ state: asCapabilityId(MORPHO_FLASH_CAPABILITY_IDS.state), coarse: asCapabilityId(MORPHO_FLASH_CAPABILITY_IDS.coarse), exact: asCapabilityId(MORPHO_FLASH_CAPABILITY_IDS.exact) }), actionOwnerIds: Object.freeze({ action: MORPHO_FLASH_ACTION_OWNER_ID }) });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: MORPHO_FLASH_FAMILY_ID, version: MORPHO_FLASH_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/morpho-flash/plugin-code/v1", { moduleRoot, core: [nomination, identity, materialization, projection, rehydration], extensions: [state, coarse, exact], runtimeAdapter, actionOwner: MORPHO_FLASH_ACTION_OWNER, facts }), authorityDeclarationHash: hashDomain("aloha/morpho-flash/authority/v1", MORPHO_FLASH_OWNER_REF), sourcePlans: [{ sourcePlanId: MORPHO_FLASH_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: MORPHO_FLASH_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "MORPHO_FLASH_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "MORPHO_FLASH_SOURCE_NOMINATION_PROGRAM", schemaHash: MORPHO_FLASH_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "MORPHO_FLASH_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "MORPHO_FLASH_NOMINATION_INDEPENDENT_ORACLE" } } } }, { sourcePlanId: MORPHO_FLASH_SINGLETON_SOURCE_PLAN_ID, completeness: "complete-snapshot", historyStartBlock: null, schemaHash: MORPHO_FLASH_SINGLETON_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "MORPHO_FLASH_SINGLETON_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "MORPHO_FLASH_SINGLETON_NOMINATION_PROGRAM", schemaHash: MORPHO_FLASH_SINGLETON_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "MORPHO_FLASH_SINGLETON_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "MORPHO_FLASH_SINGLETON_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: nomination as never, identity: identity as never, materialization: materialization as never, projection: projection as never, rehydration: rehydration as never }, extensions: { [MORPHO_FLASH_CAPABILITY_IDS.state]: { kind: "present", module: state }, [MORPHO_FLASH_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [MORPHO_FLASH_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: runtimeAdapter }, actionOwners: [MORPHO_FLASH_ACTION_OWNER], acceptanceDeclarations: facts };
export const MORPHO_FLASH_DEFINITION_INPUT = defineFamily(input);
export const MORPHO_FLASH_AUTHORING_HASH: Hash = familyAuthoringDigest(MORPHO_FLASH_DEFINITION_INPUT);
