import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { assertFundingRepaymentObligation, makeFundingRepaymentObligation, type FundingEffectExpectationV1 } from "../../../packages/funding/src/index.ts";
import { MORPHO_BLUE_SINGLETON, MORPHO_FLASH_ACTION_OWNER_ID, MORPHO_FLASH_CALLBACK_SELECTOR, MORPHO_FLASH_EVIDENCE_TOPIC, MORPHO_FLASH_FAMILY_ID, MORPHO_FLASH_FAMILY_VERSION, MORPHO_FLASH_LOAN_SELECTOR, MORPHO_FLASH_MANIFEST, MORPHO_FLASH_SOURCE_WINDOW_BLOCKS } from "./manifest.ts";
import { encodeMorphoFlashLoan, positiveAmount } from "./kernel/math.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type MorphoFlashActionV1, type MorphoFlashCandidateV1, type MorphoFlashCutoffV1, type MorphoFlashEffectV1, type MorphoFlashExecutionIntentV1, type MorphoFlashIdentityReadFactsV1, type MorphoFlashIdentityV1, type MorphoFlashMaterializedStateV1, type MorphoFlashObservationV1, type MorphoFlashQuoteV1, type MorphoFlashRouteV1, type MorphoFlashStateReadFactsV1 } from "./types.ts";

export const MORPHO_FLASH_CONTRACT_PATTERN = "morpho-flash-contract-log" as const;
export interface MorphoFlashCandidateSeedV1 { readonly target: string; readonly evidence: MorphoFlashObservationV1 }
export function decodeMorphoFlashCandidate(observation: MorphoFlashObservationV1, pattern: typeof MORPHO_FLASH_CONTRACT_PATTERN): MorphoFlashCandidateSeedV1 | null { if (pattern !== MORPHO_FLASH_CONTRACT_PATTERN || observation.kind !== "log" || observation.topic !== MORPHO_FLASH_EVIDENCE_TOPIC) return null; const target = canonicalAddress(observation.target); return Object.freeze({ target, evidence: Object.freeze({ ...observation, target }) }); }
export function instanceNominationKey(input: MorphoFlashCandidateSeedV1 | MorphoFlashCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: MorphoFlashObservationV1): Hash { return hashDomain("aloha/morpho-flash/candidate-snapshot/v1", { familyId: MORPHO_FLASH_FAMILY_ID, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, topic: input.topic, rawLocatorHash: input.rawLocatorHash }); }
export type MorphoFlashNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: MorphoFlashCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominateMorphoFlash(input: MorphoFlashCandidateSeedV1): MorphoFlashNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff); const block = BigInt(input.evidence.blockNumber); const end = BigInt(cutoff.number); if (block > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (block < end - BigInt(MORPHO_FLASH_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target); const evidence = Object.freeze({ ...input.evidence, target, cutoff }); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: canonicalAddress(target), candidateSnapshotHash: candidateSnapshotHash(evidence), cutoff }) }); }
export function candidateFamilyKey(candidate: MorphoFlashCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }

export type MorphoFlashIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: MorphoFlashIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "singleton-mismatch" | "reverse-identity-mismatch" | "asset-invalid" | "receiver-invalid" | "token-code-missing" };
export function verifyMorphoFlashIdentityStage(input: { readonly candidate: MorphoFlashCandidateV1; readonly reads: MorphoFlashIdentityReadFactsV1 }): MorphoFlashIdentityOutcomeV1 { const reads = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), reverseLender: canonicalAddress(input.reads.reverseLender), asset: canonicalAddress(input.reads.asset), receiver: canonicalAddress(input.reads.receiver), feeBps: positiveAmount(input.reads.feeBps, "feeBps", true).toString() }; if (!cutoffEqual(reads.cutoff, input.candidate.cutoff)) throw new TypeError("morpho-flash identity cutoff mismatch"); if (reads.target !== canonicalAddress(MORPHO_BLUE_SINGLETON) || canonicalAddress(input.candidate.target) !== reads.target) return { status: "chain-proven-rejected", reasonCode: "singleton-mismatch" }; if (reads.reverseLender !== reads.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; if (reads.asset === "0x0000000000000000000000000000000000000000") return { status: "chain-proven-rejected", reasonCode: "asset-invalid" }; if (reads.receiver === "0x0000000000000000000000000000000000000000") return { status: "chain-proven-rejected", reasonCode: "receiver-invalid" }; if (!reads.assetHasCode || !reads.receiverHasCode) return { status: "chain-proven-rejected", reasonCode: "token-code-missing" }; const facts = Object.freeze({ lender: reads.target, asset: reads.asset, receiver: reads.receiver, feeBps: reads.feeBps }); const factsHash = hashDomain("aloha/morpho-flash/identity-facts/v1", facts); const instanceKey = hashDomain("aloha/morpho-flash/instance/v1", facts); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: reads.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey, factsHash, facts }) }); }
export function identityDescriptorHash(identity: MorphoFlashIdentityV1): Hash { return hashDomain("aloha/morpho-flash/instance-descriptor/v1", { familyId: MORPHO_FLASH_FAMILY_ID, version: MORPHO_FLASH_FAMILY_VERSION, instanceKey: identity.instanceKey, factsHash: identity.factsHash }); }

export type MorphoFlashMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: MorphoFlashMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" | "liquidity-invalid" };
export function materializeMorphoFlash(input: { readonly identity: MorphoFlashIdentityV1; readonly read: MorphoFlashStateReadFactsV1 }): MorphoFlashMaterializationOutcomeV1 { const read = { ...input.read, cutoff: assertCutoff(input.read.cutoff) }; if (!cutoffEqual(read.cutoff, input.identity.cutoff)) throw new TypeError("morpho-flash materialization cutoff mismatch"); if (read.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; try { positiveAmount(read.availableLiquidity, "availableLiquidity"); } catch { return { status: "chain-proven-rejected", reasonCode: "liquidity-invalid" }; } const stateHash = hashDomain("aloha/morpho-flash/materialized-state/v1", { identityFactsHash: input.identity.factsHash, availableLiquidity: read.availableLiquidity }); return Object.freeze({ status: "verified", state: Object.freeze({ ...read, identityFactsHash: input.identity.factsHash, stateHash }) }); }
export function resealMorphoFlashState(state: MorphoFlashMaterializedStateV1): Hash { return hashDomain("aloha/morpho-flash/materialized-state/v1", { identityFactsHash: state.identityFactsHash, availableLiquidity: state.availableLiquidity }); }

export function deriveMorphoFlashRoutes(identity: MorphoFlashIdentityV1): readonly MorphoFlashRouteV1[] { const route = { instanceKey: identity.instanceKey, lender: identity.facts.lender, asset: identity.facts.asset, receiver: identity.facts.receiver }; return Object.freeze([Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/morpho-flash/route-binding/v1", route) })]); }
export function assertMorphoFlashRoute(route: MorphoFlashRouteV1, identity: MorphoFlashIdentityV1): void { const expected = hashDomain("aloha/morpho-flash/route-binding/v1", { instanceKey: route.instanceKey, lender: route.lender, asset: route.asset, receiver: route.receiver }); if (route.instanceKey !== identity.instanceKey || route.lender !== identity.facts.lender || route.asset !== identity.facts.asset || route.receiver !== identity.facts.receiver || route.routeBindingHash !== expected) throw new TypeError("morpho-flash route identity mismatch"); }
export type MorphoFlashCoarseOutcomeV1 = { readonly status: "rankable"; readonly quote: MorphoFlashQuoteV1 } | { readonly status: "unavailable"; readonly reasonCode: "invalid-observation" | "route-mismatch" | "liquidity-insufficient" };
export function coarseMorphoFlash(input: { readonly identity: MorphoFlashIdentityV1; readonly state: MorphoFlashMaterializedStateV1; readonly route: MorphoFlashRouteV1; readonly amountIn: string }): MorphoFlashCoarseOutcomeV1 { try { assertMorphoFlashRoute(input.route, input.identity); const amount = positiveAmount(input.amountIn, "amountIn"); if (amount > BigInt(input.state.availableLiquidity)) return { status: "unavailable", reasonCode: "liquidity-insufficient" }; const payload = { cutoff: input.identity.cutoff, routeBindingHash: input.route.routeBindingHash, amountIn: amount.toString(), repaymentAmount: amount.toString() }; return Object.freeze({ status: "rankable", quote: Object.freeze({ ...payload, quoteHash: hashDomain("aloha/morpho-flash/quote/v1", payload) }) }); } catch (error) { return { status: "unavailable", reasonCode: error instanceof TypeError && error.message.includes("route") ? "route-mismatch" : "invalid-observation" }; } }
export function exactMorphoFlash(input: { readonly identity: MorphoFlashIdentityV1; readonly state: MorphoFlashMaterializedStateV1; readonly route: MorphoFlashRouteV1; readonly amountIn: string }): MorphoFlashCoarseOutcomeV1 { return coarseMorphoFlash(input); }

function effectExpectations(identity: MorphoFlashIdentityV1, quote: MorphoFlashQuoteV1): readonly MorphoFlashEffectV1[] { return Object.freeze([{ asset: identity.facts.asset, account: "lender", direction: "decrease", amount: quote.amountIn }, { asset: identity.facts.asset, account: "receiver", direction: "increase", amount: quote.amountIn }, { asset: identity.facts.asset, account: "receiver", direction: "decrease", amount: quote.repaymentAmount }, { asset: identity.facts.asset, account: "lender", direction: "increase", amount: quote.repaymentAmount }]); }
export function buildMorphoFlashAction(input: { readonly identity: MorphoFlashIdentityV1; readonly quote: MorphoFlashQuoteV1; readonly callbackDataHex?: string }): MorphoFlashActionV1 { const callbackDataHex = input.callbackDataHex ?? "0x"; const calldata = encodeMorphoFlashLoan(input.identity.facts.asset, input.quote.amountIn, callbackDataHex, MORPHO_FLASH_LOAN_SELECTOR); const actionIntentHash = hashDomain("aloha/morpho-flash/action-intent/v1", { cutoff: input.identity.cutoff, target: input.identity.facts.lender, calldata, exactQuoteHash: input.quote.quoteHash }); const effects = effectExpectations(input.identity, input.quote); const obligation = makeFundingRepaymentObligation({ familyId: MORPHO_FLASH_FAMILY_ID, instanceKey: input.identity.instanceKey, lender: input.identity.facts.lender, receiver: input.identity.facts.receiver, asset: input.identity.facts.asset, principal: input.quote.amountIn, fee: "0", actionIntentHash, effects: effects.map(effect => ({ ...effect, account: effect.account === "receiver" ? "executor" as const : effect.account })) as readonly FundingEffectExpectationV1[] }); const payload = { cutoff: input.identity.cutoff, target: input.identity.facts.lender, calldata, exactQuoteHash: input.quote.quoteHash, actionIntentHash, obligationHash: obligation.obligationHash }; return Object.freeze({ ...payload, obligation, actionHash: hashDomain("aloha/morpho-flash/action/v1", payload) }); }
export const MORPHO_FLASH_ACTION_PORT = Object.freeze({ actionOwnerId: MORPHO_FLASH_ACTION_OWNER_ID, actionKind: "flash-loan", build: buildMorphoFlashAction });
export function expectedMorphoFlashEffects(action: MorphoFlashActionV1): readonly MorphoFlashEffectV1[] { return Object.freeze([{ asset: action.obligation.asset, account: "lender", direction: "decrease", amount: action.obligation.principal }, { asset: action.obligation.asset, account: "receiver", direction: "increase", amount: action.obligation.principal }, { asset: action.obligation.asset, account: "receiver", direction: "decrease", amount: action.obligation.repayment }, { asset: action.obligation.asset, account: "lender", direction: "increase", amount: action.obligation.repayment }]); }
export function compileMorphoFlashExecution(input: { readonly identity: MorphoFlashIdentityV1; readonly action: MorphoFlashActionV1 }): MorphoFlashExecutionIntentV1 { if (input.action.target !== input.identity.facts.lender || !cutoffEqual(input.action.cutoff, input.identity.cutoff)) throw new TypeError("morpho-flash execution binding mismatch"); const expectedIntent = hashDomain("aloha/morpho-flash/action-intent/v1", { cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, exactQuoteHash: input.action.exactQuoteHash }); if (expectedIntent !== input.action.actionIntentHash) throw new TypeError("morpho-flash action intent mismatch"); const obligation = assertFundingRepaymentObligation(input.action.obligation); if (obligation.actionIntentHash !== expectedIntent || input.action.actionHash !== hashDomain("aloha/morpho-flash/action/v1", { cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, exactQuoteHash: input.action.exactQuoteHash, actionIntentHash: expectedIntent, obligationHash: obligation.obligationHash })) throw new TypeError("morpho-flash execution obligation lineage mismatch"); return Object.freeze({ kind: "morpho-flash-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, exactQuoteHash: input.action.exactQuoteHash, obligationHash: obligation.obligationHash, expectedEffects: expectedMorphoFlashEffects(input.action) }); }
export function captureMorphoFlashEvidence(input: { readonly observation: MorphoFlashObservationV1; readonly pattern: typeof MORPHO_FLASH_CONTRACT_PATTERN }): MorphoFlashCandidateSeedV1 | null { return decodeMorphoFlashCandidate(input.observation, input.pattern); }
export const MORPHO_FLASH_RUNTIME = Object.freeze({ manifest: MORPHO_FLASH_MANIFEST, discover: decodeMorphoFlashCandidate, capture: captureMorphoFlashEvidence, nominate: nominateMorphoFlash, identity: verifyMorphoFlashIdentityStage, materialize: materializeMorphoFlash, routes: deriveMorphoFlashRoutes, coarse: coarseMorphoFlash, exact: exactMorphoFlash, execute: compileMorphoFlashExecution });
export const MORPHO_FLASH_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateMorphoFlash });
export const MORPHO_FLASH_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyMorphoFlashIdentityStage });
export const MORPHO_FLASH_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeMorphoFlash });
export const MORPHO_FLASH_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveMorphoFlashRoutes });
export const MORPHO_FLASH_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveMorphoFlashRoutes });
