import { hashDomain, type Hash } from "../../../../packages/canonical-codec/src/index.ts";
export function positiveAmount(value: string, path = "amount"): bigint { if (!/^\d+$/.test(value)) throw new TypeError(`${path} must be a decimal integer`); const amount = BigInt(value); if (amount <= 0n) throw new TypeError(`${path} must be positive`); return amount; }
export function validDecimals(value: number, path: string): number { if (!Number.isSafeInteger(value) || value < 0 || value > 36) throw new TypeError(`${path} decimals invalid`); return value; }
export function fluidDebtAmount(input: { readonly collateralAmount: string; readonly debtBps: string; readonly collateralDecimals: number; readonly debtDecimals: number }): string { const collateral = positiveAmount(input.collateralAmount, "collateralAmount"); const bps = positiveAmount(input.debtBps, "debtBps"); let amount = collateral * bps / 10_000n; const delta = input.collateralDecimals - input.debtDecimals; if (delta > 0) amount /= 10n ** BigInt(delta); else if (delta < 0) amount *= 10n ** BigInt(-delta); return amount.toString(); }
export function effectRoot(effects: readonly { readonly token: string; readonly account: string; readonly delta: string }[]): Hash { return hashDomain("aloha/fluid-credit/effect-root/v1", effects.map((effect, index) => ({ index, ...effect }))); }
export function encodeAddressWord(value: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(value)) throw new TypeError("address word invalid"); return value.slice(2).toLowerCase().padStart(64, "0"); }
export function encodeIntWord(value: string): string { const number = BigInt(value); if (number < -(1n << 255n) || number >= (1n << 255n)) throw new TypeError("int word overflow"); return (number < 0n ? (1n << 256n) + number : number).toString(16).padStart(64, "0"); }
export function encodeUintWord(value: string, allowZero = false): string { if (!/^\d+$/.test(value)) throw new TypeError("uint must be decimal"); const number = BigInt(value); if (!allowZero && number <= 0n) throw new TypeError("uint must be positive"); return number.toString(16).padStart(64, "0"); }
export function encodeFluidOperate(nftId: string, collateralDelta: string, debtDelta: string, receiver: string): string { return `0x032d2276${encodeUintWord(nftId, true)}${encodeIntWord(collateralDelta)}${encodeIntWord(debtDelta)}${encodeAddressWord(receiver)}`; }
