import assert from "node:assert/strict";
import test from "node:test";
import {
  encodeCanonicalBytes,
  hashDomain,
  sha256Hex,
  type Hash,
} from "../../../packages/canonical-codec/src/index.ts";
import { sealReleaseIntent } from "../../../specs/release-intent/src/index.ts";
import { observeFullFamilyReleaseArtifacts } from "../src/full-family-release-artifacts.ts";

const bytes = (value: string): Uint8Array => new TextEncoder().encode(value);
const h = (value: string): Hash => hashDomain("test/full-family-release-artifact-observer/v1", value);
const stages = ["identity", "materialization", "nomination", "projection", "rehydration"] as const;

function generatedSource(name: string, value: unknown, exported: boolean): Uint8Array {
  return bytes(`/* generated by @aloha/catalog-generator; DO NOT EDIT */\n${exported ? "export " : ""}const ${name} = Object.freeze(${JSON.stringify(value)})${exported ? ";" : " as unknown as GeneratedFamilyRuntimeDescriptorV1;"}\nthrow new Error("must not execute");\n`);
}

function stageRef(familyId: string, familyDefinitionHash: Hash, stage: (typeof stages)[number] | "capability") {
  return {
    familyId,
    familyDefinitionHash,
    stage,
    capabilityId: `family.${familyId}.${stage === "capability" ? "coarse" : stage}`,
    version: "1.0.0",
    schemaHash: h(`schema:${stage}`),
    interpreterHash: h(`interpreter:${stage}`),
    ownerRef: h(`owner:${stage}`),
  };
}

interface FixtureOptions {
  readonly artifactFamilyId?: string;
  readonly duplicateFamilyCatalogEntry?: boolean;
  readonly extraReleaseFamily?: boolean;
  readonly runtimeDefinitionRootSplice?: boolean;
  readonly sourcePlanRootSplice?: boolean;
}

function fixture(options: FixtureOptions = {}) {
  const releaseFamilyId = "alpha-family";
  const artifactFamilyId = options.artifactFamilyId ?? releaseFamilyId;
  const releaseFamilies = [{
    familyId: releaseFamilyId,
    manifestRoot: h("manifest:alpha"),
    modulePath: "families/alpha-family/src/public.ts",
    exportName: "ALPHA_FAMILY_DEFINITION",
  }];
  if (options.extraReleaseFamily === true) {
    releaseFamilies.push({
      familyId: "missing-family",
      manifestRoot: h("manifest:missing"),
      modulePath: "families/missing-family/src/public.ts",
      exportName: "MISSING_FAMILY_DEFINITION",
    });
  }
  const release = sealReleaseIntent(releaseFamilies, [{
    strategyId: "route-cycle",
    manifestRoot: h("strategy-manifest"),
    modulePath: "strategies/route-cycle/src/index.ts",
    exportName: "ROUTE_CYCLE_STRATEGY",
  }]);
  const familyDefinitionHash = h("family-definition");
  const capabilityRef = stageRef(artifactFamilyId, familyDefinitionHash, "capability");
  const actionOwnerRef = h("action-owner");
  const sourcePlanRef = {
    ownerRef: h("source-owner"),
    sourcePlanRef: h("source-plan-ref"),
    familyDefinitionHash,
    completeness: "complete-snapshot" as const,
    historyStartBlock: null,
  };
  const lifecycleRefs = {
    nomination: stageRef(artifactFamilyId, familyDefinitionHash, "nomination"),
    identity: stageRef(artifactFamilyId, familyDefinitionHash, "identity"),
    materialization: stageRef(artifactFamilyId, familyDefinitionHash, "materialization"),
    projection: stageRef(artifactFamilyId, familyDefinitionHash, "projection"),
    rehydration: stageRef(artifactFamilyId, familyDefinitionHash, "rehydration"),
  };
  const catalogEntry = {
    familyId: artifactFamilyId,
    familyDefinitionHash,
    issuerRef: h("issuer"),
    authorityRef: h("authority"),
    lifecycleRefs,
    extensionRefs: [capabilityRef],
    actionOwnerRefs: [actionOwnerRef],
    factContractRefs: [{ factContractId: "family.alpha.fact", version: "1.0.0", schemaHash: h("fact") }],
    sourcePlanRefs: [sourcePlanRef],
    definitionCatalogLeafDigest: h("family-leaf"),
    capabilityCatalogRoot: h("capability-catalog"),
  };
  const catalogEntries = options.duplicateFamilyCatalogEntry === true ? [catalogEntry, catalogEntry] : [catalogEntry];
  const familyCatalogRoot = hashDomain("aloha/family-definition-catalog/v1", catalogEntries.map(entry => entry.definitionCatalogLeafDigest).sort());
  const familyCatalog = {
    schemaVersion: 1,
    releaseIntentRoot: release.releaseIntentRoot,
    capabilityIndexRoot: h("capability-index"),
    proposedCapabilitySetRoot: h("proposed-capabilities"),
    entries: catalogEntries,
    definitionCatalogRoot: familyCatalogRoot,
  };

  const program = {
    modulePath: "families/alpha-family/src/nomination.ts",
    exportName: "ALPHA_NOMINATION_PROGRAM",
    closureRoot: h("nomination-program-closure"),
    schemaHash: h("nomination-program-schema"),
  };
  const mutationCorpus = {
    modulePath: "families/alpha-family/test/nomination-corpus.ts",
    exportName: "ALPHA_NOMINATION_CORPUS",
    closureRoot: h("nomination-corpus-closure"),
  };
  const independentOracle = {
    modulePath: "families/alpha-family/test/nomination-oracle.ts",
    exportName: "ALPHA_NOMINATION_ORACLE",
    closureRoot: h("nomination-oracle-closure"),
  };
  const sourcePlanBase = {
    sourcePlanId: "alpha-source",
    modulePath: "families/alpha-family/src/source-plan.ts",
    exportName: "ALPHA_SOURCE_PLAN",
    closureRoot: h("source-plan-closure"),
    schemaHash: h("source-plan-schema"),
    planRef: sourcePlanRef,
  };
  const sourcePlanLeaf = hashDomain("aloha/family-source-plan-leaf/v1", {
    sourcePlanId: sourcePlanBase.sourcePlanId,
    modulePath: sourcePlanBase.modulePath,
    exportName: sourcePlanBase.exportName,
    closureRoot: sourcePlanBase.closureRoot,
    schemaHash: sourcePlanBase.schemaHash,
    planRef: {
      ownerRef: sourcePlanRef.ownerRef,
      sourcePlanRef: sourcePlanRef.sourcePlanRef,
      completeness: sourcePlanRef.completeness,
      historyStartBlock: sourcePlanRef.historyStartBlock,
    },
  });
  const nominationProgramRoot = hashDomain("aloha/family-source-plan-nomination-program/v1", program);
  const nominationProposalBase = { program, mutationCorpus, independentOracle, nominationProgramRoot };
  const nominationProposal = {
    ...nominationProposalBase,
    proposalLeafDigest: hashDomain("aloha/source-plan-nomination-program-proposal-leaf/v1", {
      sourcePlanLeafDigest: sourcePlanLeaf,
      ...nominationProposalBase,
    }),
  };
  const sourcePlan = { ...sourcePlanBase, leafDigest: sourcePlanLeaf, nominationProgramProposal: nominationProposal };
  const runtimeStages = stages.map(stage => ({
    stage,
    modulePath: `families/alpha-family/src/${stage}.ts`,
    exportName: `ALPHA_${stage.toUpperCase()}_DEFINITION`,
    closureRoot: h(`stage-closure:${stage}`),
    stageRef: lifecycleRefs[stage],
  }));
  const stageDefinitionRoot = hashDomain("aloha/family-runtime-definition-set/v1", runtimeStages.map(stage => ({
    stage: stage.stage,
    modulePath: stage.modulePath,
    exportName: stage.exportName,
    closureRoot: stage.closureRoot,
    stageRef: stage.stageRef,
  })));
  const extension = {
    modulePath: "families/alpha-family/src/public.ts",
    exportName: "ALPHA_COARSE",
    closureRoot: h("extension-closure"),
    capabilityRef,
  };
  const actionOwner = {
    modulePath: "families/alpha-family/src/public.ts",
    exportName: "ALPHA_SWAP_ACTION",
    closureRoot: h("action-closure"),
    ownerRef: actionOwnerRef,
    ownerId: "swap",
    version: "1.0.0",
    schemaHash: h("action-schema"),
    implementationHash: h("action-implementation"),
    actionKinds: ["swap"],
  };
  const adapterBase = {
    role: "search/v1",
    modulePath: "families/alpha-family/src/search-adapter.ts",
    exportName: "ALPHA_SEARCH_ADAPTER",
    closureRoot: h("adapter-closure"),
    capabilityRefs: { coarse: capabilityRef },
    actionOwnerRefs: { swap: actionOwnerRef },
  };
  const adapterRefPayload = {
    stage: capabilityRef.stage,
    capabilityId: capabilityRef.capabilityId,
    version: capabilityRef.version,
    schemaHash: capabilityRef.schemaHash,
    interpreterHash: capabilityRef.interpreterHash,
    ownerRef: capabilityRef.ownerRef,
  };
  const adapter = {
    ...adapterBase,
    leafDigest: hashDomain("aloha/family-runtime-adapter-leaf/v1", {
      role: adapterBase.role,
      modulePath: adapterBase.modulePath,
      exportName: adapterBase.exportName,
      closureRoot: adapterBase.closureRoot,
      capabilityRefs: [{ role: "coarse", ref: adapterRefPayload }],
      actionOwnerRefs: [{ role: "swap", ownerRef: actionOwnerRef }],
    }),
  };
  const runtimeFamily = {
    entry: catalogEntry,
    publicEntry: {
      modulePath: "families/alpha-family/src/public.ts",
      exportName: "ALPHA_FAMILY_DEFINITION",
      closureRoot: h("public-entry-closure"),
    },
    stages: runtimeStages,
    sourcePlans: [sourcePlan],
    extensions: [extension],
    actionOwners: [actionOwner],
    runtimeAdapters: [adapter],
    runtimeAdapterRoot: hashDomain("aloha/family-runtime-adapter-set/v1", [adapter.leafDigest]),
    sourcePlanRoot: options.sourcePlanRootSplice === true
      ? h("spliced-source-plan-root")
      : hashDomain("aloha/family-source-plan-set/v1", [sourcePlanLeaf]),
    stageDefinitionRoot,
  };

  const strategyImplementationRoot = h("strategy-implementation");
  const strategyDefinitionHash = h("strategy-definition");
  const strategyLeaf = hashDomain("aloha/definition-catalog-leaf/v1", {
    leafId: "strategy:route-cycle",
    definitionHash: strategyDefinitionHash,
    requestedDependencyClosure: [],
    implementationClosureRoot: strategyImplementationRoot,
  });
  const strategyCatalogRoot = hashDomain("aloha/strategy-definition-catalog/v1", [strategyLeaf]);
  const strategyCatalog = {
    schemaVersion: 1,
    releaseIntentRoot: release.releaseIntentRoot,
    capabilityIndexRoot: familyCatalog.capabilityIndexRoot,
    proposedCapabilitySetRoot: familyCatalog.proposedCapabilitySetRoot,
    entries: [{
      strategyId: "route-cycle",
      strategyDefinitionHash,
      issuerRef: h("strategy-issuer"),
      requiredCapabilityRefs: [],
      planningProblemIssuer: h("planning-issuer"),
      constraintSchemaRefs: [h("constraint")],
      factContractRefs: [h("strategy-fact")],
      definitionCatalogLeafDigest: strategyLeaf,
      strategyVersion: "1.0.0",
      requestedCapabilityDependencyRoot: h("strategy-dependency-root"),
      implementationClosureRoot: strategyImplementationRoot,
      planningTemplate: {
        kind: "closed-loop-template",
        entryAssetPolicy: "any-graph-asset",
        minLegs: "2",
        maxLegs: "4",
        candidateLimit: "64",
        edgeReuse: "forbid",
        constraintSchemaRefs: [h("constraint")],
      },
    }],
    definitionCatalogRoot: strategyCatalogRoot,
  };
  const globalRoot = hashDomain("aloha/definition-catalog/v1", [catalogEntry.definitionCatalogLeafDigest, strategyLeaf].sort());
  const runtimeWithoutRoot = {
    schemaVersion: 1,
    releaseIntentRoot: release.releaseIntentRoot,
    definitionCatalogRoot: options.runtimeDefinitionRootSplice === true ? h("spliced-global-root") : globalRoot,
    proposedCapabilitySetRoot: familyCatalog.proposedCapabilitySetRoot,
    nominationProgramSetRoot: hashDomain("aloha/source-plan-nomination-program-set/v1", [nominationProposal.proposalLeafDigest]),
    families: [runtimeFamily],
  };
  const runtime = {
    ...runtimeWithoutRoot,
    descriptorRoot: hashDomain("aloha/generated-family-runtime-descriptor/v1", runtimeWithoutRoot),
  };
  const releaseBytes = encodeCanonicalBytes(release);
  const familyCatalogSourceBytes = generatedSource("FAMILY_CATALOG", familyCatalog, true);
  const runtimeCompositionSourceBytes = generatedSource("FAMILY_RUNTIME_DESCRIPTOR", runtime, false);
  const strategyCatalogSourceBytes = generatedSource("STRATEGY_CATALOG", strategyCatalog, true);
  return { release, releaseBytes, familyCatalogSourceBytes, runtimeCompositionSourceBytes, strategyCatalogSourceBytes };
}

test("observer derives a complete inert full-family projection from four independent byte sources", () => {
  const value = fixture();
  const observed = observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: value.releaseBytes,
    familyCatalogSourceBytes: value.familyCatalogSourceBytes,
    runtimeCompositionSourceBytes: value.runtimeCompositionSourceBytes,
    strategyCatalogSourceBytes: value.strategyCatalogSourceBytes,
  });
  assert.equal(observed.releaseIntentRoot, value.release.releaseIntentRoot);
  assert.equal(observed.sourceContentSha256.releaseIntent, sha256Hex(value.releaseBytes));
  assert.equal(observed.families[0]?.familyId, "alpha-family");
  assert.equal(observed.families[0]?.capabilityOwnerRefs[0]?.capabilityId, "family.alpha-family.coarse");
  assert.equal(observed.globalDefinitionCatalogRoot.kind, "complete");
});

test("observer reports the global root as missing when Strategy catalog bytes are absent", () => {
  const value = fixture();
  const observed = observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: value.releaseBytes,
    familyCatalogSourceBytes: value.familyCatalogSourceBytes,
    runtimeCompositionSourceBytes: value.runtimeCompositionSourceBytes,
  });
  assert.equal(observed.globalDefinitionCatalogRoot.kind, "missing");
  if (observed.globalDefinitionCatalogRoot.kind !== "missing") assert.fail("missing Strategy catalog must not produce a global root");
  assert.equal(observed.globalDefinitionCatalogRoot.reason, "strategy-catalog-source-not-supplied");
  assert.equal(observed.globalDefinitionCatalogRoot.familyDefinitionCatalogRoot, observed.familyDefinitionCatalogRoot);
  assert.deepEqual(observed.sourceContentSha256.strategyCatalog, {
    kind: "missing",
    reason: "strategy-catalog-source-not-supplied",
  });
});

test("observer rejects dynamic generated initializers without executing them", () => {
  const value = fixture();
  assert.throws(() => observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: value.releaseBytes,
    familyCatalogSourceBytes: bytes("/* generated by @aloha/catalog-generator; DO NOT EDIT */\nexport const FAMILY_CATALOG = Object.freeze(buildCatalog());\n"),
    runtimeCompositionSourceBytes: value.runtimeCompositionSourceBytes,
  }), /literal|non-JSON/);
});

test("observer rejects release/catalog/runtime exact-set mismatch and missing release Families", () => {
  for (const value of [fixture({ artifactFamilyId: "other-family" }), fixture({ extraReleaseFamily: true })]) {
    assert.throws(() => observeFullFamilyReleaseArtifacts({
      releaseIntentCanonicalBytes: value.releaseBytes,
      familyCatalogSourceBytes: value.familyCatalogSourceBytes,
      runtimeCompositionSourceBytes: value.runtimeCompositionSourceBytes,
    }), /exact set mismatch/);
  }
});

test("observer rejects duplicate Families", () => {
  const value = fixture({ duplicateFamilyCatalogEntry: true });
  assert.throws(() => observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: value.releaseBytes,
    familyCatalogSourceBytes: value.familyCatalogSourceBytes,
    runtimeCompositionSourceBytes: value.runtimeCompositionSourceBytes,
  }), /duplicate entry/);
});

test("observer rejects global-root and source-plan-root splices", () => {
  const global = fixture({ runtimeDefinitionRootSplice: true });
  assert.throws(() => observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: global.releaseBytes,
    familyCatalogSourceBytes: global.familyCatalogSourceBytes,
    runtimeCompositionSourceBytes: global.runtimeCompositionSourceBytes,
    strategyCatalogSourceBytes: global.strategyCatalogSourceBytes,
  }), /global definition catalog root mismatch/);

  const sourcePlan = fixture({ sourcePlanRootSplice: true });
  assert.throws(() => observeFullFamilyReleaseArtifacts({
    releaseIntentCanonicalBytes: sourcePlan.releaseBytes,
    familyCatalogSourceBytes: sourcePlan.familyCatalogSourceBytes,
    runtimeCompositionSourceBytes: sourcePlan.runtimeCompositionSourceBytes,
  }), /source plan root mismatch/);
});
