import assert from "node:assert/strict";
import test from "node:test";
import { decodeCanonicalJson, sha256Hex } from "../../../packages/canonical-codec/src/index.ts";
import { observeGeneratedJsonConstant } from "../src/index.ts";

const bytes = (value: string): Uint8Array => new TextEncoder().encode(value);
const header = "/* generated by @aloha/catalog-generator; DO NOT EDIT */\n";

test("generated observer extracts one exact exported JSON constant without executing source", () => {
  const source = bytes(`${header}import { explode } from "./must-not-run.ts";
export const FAMILY_CATALOG = Object.freeze({
  "schemaVersion": 1,
  "families": [{ "familyId": "univ2-standard", "enabled": true }],
  "optional": null
});
explode();
`);
  const observed = observeGeneratedJsonConstant(source, {
    sourceFileName: "generated/family-catalog/index.ts",
    constantName: "FAMILY_CATALOG",
    requireExported: true,
    assertionTypeName: null,
  });
  assert.equal(observed.sourceContentSha256, sha256Hex(source));
  assert.deepEqual(decodeCanonicalJson(observed.canonicalValueBytes), {
    families: [{ enabled: true, familyId: "univ2-standard" }],
    optional: null,
    schemaVersion: 1,
  });
});

test("generated observer accepts only the exact non-exported runtime descriptor assertion", () => {
  const observed = observeGeneratedJsonConstant(bytes(`${header}const FAMILY_RUNTIME_DESCRIPTOR = Object.freeze(
  { "schemaVersion": 1, "families": [] }
) as unknown as GeneratedFamilyRuntimeDescriptorV1;
`), {
    sourceFileName: "generated/runtime-composition/index.ts",
    constantName: "FAMILY_RUNTIME_DESCRIPTOR",
    requireExported: false,
    assertionTypeName: "GeneratedFamilyRuntimeDescriptorV1",
  });
  assert.deepEqual(decodeCanonicalJson(observed.canonicalValueBytes), { families: [], schemaVersion: 1 });
});

test("generated observer rejects executable, duplicate, forged-header and wrong-declaration shapes", () => {
  const cases = [
    `${header}export const X = Object.freeze(build());\n`,
    `${header}export const X = Object.freeze({ "safe": call() });\n`,
    `${header}export const X = Object.freeze({ ...other });\n`,
    `${header}export const X = Object.freeze({ "a": 1, "a": 2 });\n`,
    `${header}const X = Object.freeze({ "a": 1 });\n`,
    `${header}export let X = Object.freeze({ "a": 1 });\n`,
    `${header}export const X = Object.freeze({ ["a"]: 1 });\n`,
    `export const X = Object.freeze({ "a": 1 });\n`,
    `${header}export const X = Object.freeze({ "a": 1 }) as unknown as Forged;\n`,
    `${header}export const X = Object.freeze({ "a": 1 });\nexport const X = Object.freeze({ "a": 2 });\n`,
  ];
  for (const source of cases) {
    assert.throws(() => observeGeneratedJsonConstant(bytes(source), {
      sourceFileName: "generated.ts",
      constantName: "X",
      requireExported: true,
      assertionTypeName: null,
    }));
  }
});
