import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { METRONOME_SYNTH_ACTION_OWNER_ID, METRONOME_SYNTH_CAPABILITY_IDS, METRONOME_SYNTH_FAMILY_ID, METRONOME_SYNTH_FAMILY_VERSION, METRONOME_SYNTH_OWNER_REF, METRONOME_SYNTH_SOURCE_PLAN_ID, METRONOME_SYNTH_SOURCE_PLAN_SCHEMA_HASH, METRONOME_SYNTH_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(METRONOME_SYNTH_FAMILY_VERSION); const moduleRoot = "families/metronome-synth/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${METRONOME_SYNTH_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/metronome-synth/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([METRONOME_SYNTH_SOURCE_PLAN_ID]) } : {}) }); }
function absent(name: "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(METRONOME_SYNTH_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-synth/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/metronome-synth/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "METRONOME_SYNTH_RUNTIME" }); }
function present(name: "state"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(METRONOME_SYNTH_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-synth/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/metronome-synth/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "METRONOME_SYNTH_RUNTIME" }); }
const n = core("nomination", "METRONOME_SYNTH_NOMINATION_RUNTIME"); const i = core("identity", "METRONOME_SYNTH_IDENTITY_RUNTIME"); const m = core("materialization", "METRONOME_SYNTH_MATERIALIZATION_RUNTIME"); const p = core("projection", "METRONOME_SYNTH_PROJECTION_RUNTIME"); const r = core("rehydration", "METRONOME_SYNTH_REHYDRATION_RUNTIME"); const state = present("state");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.metronome-synth.pool-identity", version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-synth/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.metronome-synth.direction-projection", version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-synth/fact-schema/v1", "projection")) })]);
const actionOwner = Object.freeze({ ownerId: METRONOME_SYNTH_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-synth/action-schema/v1", "swap")), implementationHash: hashDomain("aloha/metronome-synth/action-implementation/v1", "swap"), actionKinds: Object.freeze(["swap"]), modulePath: `${moduleRoot}/action.ts`, exportName: "METRONOME_SYNTH_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: METRONOME_SYNTH_FAMILY_ID, version: METRONOME_SYNTH_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/metronome-synth/plugin-code/v1", { n, i, m, p, r, state, facts, actionOwner }), authorityDeclarationHash: hashDomain("aloha/metronome-synth/authority/v1", METRONOME_SYNTH_OWNER_REF), sourcePlans: [{ sourcePlanId: METRONOME_SYNTH_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: METRONOME_SYNTH_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "METRONOME_SYNTH_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/metronome-synth/src/source-plan.ts", exportName: "METRONOME_SYNTH_SOURCE_NOMINATION_PROGRAM", schemaHash: METRONOME_SYNTH_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/metronome-synth/src/nomination-qualification.ts", exportName: "METRONOME_SYNTH_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/metronome-synth/src/nomination-qualification.ts", exportName: "METRONOME_SYNTH_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [METRONOME_SYNTH_CAPABILITY_IDS.state]: { kind: "present", module: state }, [METRONOME_SYNTH_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "requires-future-extension" }, [METRONOME_SYNTH_CAPABILITY_IDS.exact]: { kind: "absent", reason: "requires-future-extension" } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "METRONOME_SYNTH_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(METRONOME_SYNTH_CAPABILITY_IDS.state) }, actionOwnerIds: { swap: METRONOME_SYNTH_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const METRONOME_SYNTH_DEFINITION = defineFamily(input); export const METRONOME_SYNTH_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(METRONOME_SYNTH_DEFINITION); export { METRONOME_SYNTH_FAMILY_DEFINITION_HASH, METRONOME_SYNTH_OWNER_REF };
