import { assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { familyCandidateKey as discoveryFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { METRONOME_SYNTH_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { METRONOME_SYNTH_FAMILY_ID } from "./manifest.ts";
import { materializeMetronomeSynth } from "./instance.ts";
import { assertMetronomeSynthRoute, deriveMetronomeSynthRoutes } from "./routes.ts";
import { canonicalAddress, type MetronomeSynthIdentityV1, type MetronomeSynthMaterializedStateV1, type MetronomeSynthRouteV1 } from "./types.ts";

type Source = ReturnType<typeof familySearchSource>;
type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: Source; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly amountHash: Hash; readonly identity: MetronomeSynthIdentityV1; readonly protocolRoute: MetronomeSynthRouteV1 };
type StateResponse = { readonly kind: "metronome-synth-state-read-response"; readonly requestId: Hash; readonly source: Source; readonly routeBindingHash: Hash; readonly amountHash: Hash; readonly instanceKey: string; readonly projectionHash: Hash; readonly quoteReturnDataHex: string };

function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { return assertNonEmptyString(value, path); }
function bytes(value: unknown, path: string): string { const result = text(value, path); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result)) throw new TypeError(`${path} must be even-length hex bytes`); return result.toLowerCase(); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, `metronome-synth-${reasonCode}`, canonical(evidence)); }
function word(value: bigint, path: string): string { if (value < 0n || value >= (1n << 256n)) throw new RangeError(`${path} is outside uint256`); return value.toString(16).padStart(64, "0"); }
function addressWord(value: string, path: string): string { return canonicalAddress(value).slice(2).padStart(64, "0"); }
function call(selector: string, words: readonly string[]): string { if (!/^0x[0-9a-fA-F]{8}$/.test(selector)) throw new TypeError("metronome synth selector is not canonical"); return `${selector}${words.join("")}`.toLowerCase(); }
function abiPair(value: string, path: string): string { const hex = bytes(value, path); if (hex.length !== 130) throw new TypeError(`${path} must contain two ABI uint256 words`); return hex; }
function decodeIdentity(value: unknown): MetronomeSynthIdentityV1 {
  const outer = record(value, "metronome-synth.route.identityMemo"); assertExactKeys(outer, ["kind", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "identity"], "metronome-synth.identityMemo"); if (outer.kind !== "metronome-synth-identity-memo" || outer.familyId !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError("metronome-synth identity memo discriminator mismatch"); const definitionHash = assertHash(outer.familyDefinitionHash, "metronome-synth.identityMemo.familyDefinitionHash"); const nominationKey = canonicalAddress(text(outer.instanceNominationKey, "metronome-synth.identityMemo.instanceNominationKey")); if (definitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH || assertHash(outer.familyCandidateKey, "metronome-synth.identityMemo.familyCandidateKey") !== discoveryFamilyCandidateKey(definitionHash, nominationKey)) throw new TypeError("metronome-synth identity memo family binding mismatch");
  const source = record(outer.identity, "metronome-synth.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "metronome-synth.identity"); const facts = record(source.facts, "metronome-synth.identity.facts"); assertExactKeys(facts, ["pool", "tokens", "directions", "oracleBinding", "quoteSemantics"], "metronome-synth.identity.facts"); if (facts.quoteSemantics !== "metronome-quote-swap-out-v1") throw new TypeError("metronome-synth quote semantics mismatch"); if (!Array.isArray(facts.tokens) || !Array.isArray(facts.directions)) throw new TypeError("metronome-synth projection arrays required"); const tokens = facts.tokens.map((item, index) => canonicalAddress(text(item, `metronome-synth.identity.facts.tokens[${index}]`))); const directions = facts.directions.map((item, index) => { const pair = record(item, `metronome-synth.identity.facts.directions[${index}]`); assertExactKeys(pair, ["tokenIn", "tokenOut"], `metronome-synth.identity.facts.directions[${index}]`); return Object.freeze({ tokenIn: canonicalAddress(text(pair.tokenIn, `metronome-synth.identity.facts.directions[${index}].tokenIn`)), tokenOut: canonicalAddress(text(pair.tokenOut, `metronome-synth.identity.facts.directions[${index}].tokenOut`)) }); }); const decodedFacts = Object.freeze({ pool: canonicalAddress(text(facts.pool, "metronome-synth.identity.facts.pool")), tokens: Object.freeze(tokens), directions: Object.freeze(directions), oracleBinding: bytes(facts.oracleBinding, "metronome-synth.identity.facts.oracleBinding") as `0x${string}`, quoteSemantics: "metronome-quote-swap-out-v1" as const }) as MetronomeSynthIdentityV1["facts"];
  const identity = Object.freeze({ cutoff: familySearchSource(source.cutoff, "metronome-synth.identity.cutoff") as MetronomeSynthIdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "metronome-synth.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "metronome-synth.identity.instanceKey")), factsHash: assertHash(source.factsHash, "metronome-synth.identity.factsHash"), facts: decodedFacts }); if (identity.instanceKey !== identity.facts.pool || identity.factsHash !== hashDomain("aloha/metronome-synth/identity-facts/v1", identity.facts)) throw new TypeError("metronome-synth identity facts hash mismatch"); if (nominationKey !== identity.instanceKey || assertHash(outer.candidateSnapshotHash, "metronome-synth.identityMemo.candidateSnapshotHash") !== identity.candidateSnapshotHash) throw new TypeError("metronome-synth identity memo lineage mismatch"); return identity;
}
function context(input: FamilySearchLegRequestV1): Context { const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== METRONOME_SYNTH_FAMILY_ID || route.familyDefinitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH) throw new TypeError("metronome-synth search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("metronome-synth identity memo hash mismatch"); const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = decodeIdentity(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("metronome-synth search instance binding mismatch"); const protocolRoute = deriveMetronomeSynthRoutes(identity).find(item => erc20AssetRefV1(source.chainId, item.inputAsset) === amount.inputAssetRef && erc20AssetRefV1(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("metronome-synth search amount assets do not match identity"); assertMetronomeSynthRoute(protocolRoute, identity); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, amountHash: familySearchAmountHash(amount), identity, protocolRoute }); }
function requestId(ctx: Context): Hash { return hashDomain("aloha/metronome-synth/search-state-request/v3", { familyDefinitionHash: METRONOME_SYNTH_FAMILY_AUTHORING_HASH, routeBindingHash: ctx.routeBindingHash, instanceKey: ctx.identity.instanceKey, amountHash: ctx.amountHash, source: ctx.source }); }
function readRequest(ctx: Context) { const id = requestId(ctx); return Object.freeze({ kind: "family-search.current-source-read" as const, requestId: id, source: ctx.source, target: ctx.identity.instanceKey, data: call("0x2adcb0c6", [addressWord(ctx.protocolRoute.inputAsset, "metronome synth tokenIn"), addressWord(ctx.protocolRoute.outputAsset, "metronome synth tokenOut"), word(BigInt(ctx.amount.amountIn), "metronome synth amountIn")]), responseEncoding: "abi-uint256-pair" }); }
function stateResponse(ctx: Context, id: Hash, returnDataHex: string): StateResponse { const quoteReturnDataHex = abiPair(returnDataHex, "metronome-synth.state.returnDataHex"); const projectionHash = hashDomain("aloha/metronome-synth/search-projection/v3", { cutoff: ctx.source, instanceKey: ctx.identity.instanceKey, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, quoteReturnDataHex }); return Object.freeze({ kind: "metronome-synth-state-read-response", requestId: id, source: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, projectionHash, quoteReturnDataHex }); }
function decodeStateResponse(value: CanonicalJson, ctx: Context, id: Hash): StateResponse { const source = record(value, "metronome-synth.stateResponse"); assertExactKeys(source, ["kind", "requestId", "source", "routeBindingHash", "amountHash", "instanceKey", "projectionHash", "quoteReturnDataHex"], "metronome-synth.stateResponse"); if (source.kind !== "metronome-synth-state-read-response" || assertHash(source.requestId, "metronome-synth.stateResponse.requestId") !== id) throw new TypeError("metronome-synth state response request mismatch"); const responseSource = familySearchSource(source.source, "metronome-synth.stateResponse.source"); const routeBindingHash = assertHash(source.routeBindingHash, "metronome-synth.stateResponse.routeBindingHash"); const amountHash = assertHash(source.amountHash, "metronome-synth.stateResponse.amountHash"); const instanceKey = canonicalAddress(text(source.instanceKey, "metronome-synth.stateResponse.instanceKey")); if (!sameFamilySearchSource(responseSource, ctx.source) || routeBindingHash !== ctx.routeBindingHash || amountHash !== ctx.amountHash || instanceKey !== ctx.identity.instanceKey) throw new TypeError("metronome-synth state response lineage mismatch"); const quoteReturnDataHex = abiPair(text(source.quoteReturnDataHex, "metronome-synth.stateResponse.quoteReturnDataHex"), "metronome-synth.stateResponse.quoteReturnDataHex"); const projectionHash = assertHash(source.projectionHash, "metronome-synth.stateResponse.projectionHash"); if (projectionHash !== hashDomain("aloha/metronome-synth/search-projection/v3", { cutoff: responseSource, instanceKey, routeBindingHash, amountHash, quoteReturnDataHex })) throw new TypeError("metronome-synth projection hash mismatch"); return Object.freeze({ kind: "metronome-synth-state-read-response", requestId: id, source: responseSource, routeBindingHash, amountHash, instanceKey, projectionHash, quoteReturnDataHex }); }
function stateArtifact(ctx: Context, response: StateResponse): FamilySearchStateArtifactV1 { const result = materializeMetronomeSynth({ identity: ctx.identity, read: { cutoff: response.source as MetronomeSynthMaterializedStateV1["cutoff"], instanceKey: response.instanceKey, projectionHash: response.projectionHash } }); if (result.status !== "verified") throw new TypeError(`metronome-synth state ${result.reasonCode}`); const payload = canonical(response); const payloadHash = familySearchPayloadHash("state", payload); return Object.freeze({ kind: "state", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot: hashDomain("aloha/metronome-synth/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, projectionHash: response.projectionHash, quoteReturnDataHex: response.quoteReturnDataHex }), sourceRequestId: response.requestId }); }
function assertState(ctx: Context, artifact: FamilySearchStateArtifactV1): StateResponse { if (artifact.kind !== "state" || artifact.status !== "verified" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("metronome-synth state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("metronome-synth state artifact hash mismatch"); const response = decodeStateResponse(payload, ctx, artifact.sourceRequestId); const state = materializeMetronomeSynth({ identity: ctx.identity, read: { cutoff: response.source as MetronomeSynthMaterializedStateV1["cutoff"], instanceKey: response.instanceKey, projectionHash: response.projectionHash } }); if (state.status !== "verified" || artifact.factsRoot !== hashDomain("aloha/metronome-synth/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, projectionHash: response.projectionHash, quoteReturnDataHex: response.quoteReturnDataHex })) throw new TypeError("metronome-synth state facts root mismatch"); return response; }

const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH) throw new TypeError("metronome-synth search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); const physical = readRequest(ctx); let raw: FamilySearchSourceReadResultV1; try { raw = await request.readPort.read({ request: physical, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: physical.requestId, error: String(error) }); } if (raw.kind !== "returned") return unavailable("state", raw.reasonCode || "source-read-unavailable", raw); if (raw.requestId !== physical.requestId || !sameFamilySearchSource(raw.source, physical.source)) throw new TypeError("metronome-synth source response binding mismatch"); try { const response = stateResponse(ctx, physical.requestId, raw.dataHex); return Object.freeze({ kind: "verified" as const, artifact: stateArtifact(ctx, response) }); } catch (error) { return unavailable("state", "malformed-abi-return", { requestId: physical.requestId, dataHex: raw.dataHex, error: String(error) }); } } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); const state = assertState(ctx, request.state); return unavailable("coarse", "dependent-quote-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, quoteReturnDataHex: state.quoteReturnDataHex }); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); const state = assertState(ctx, request.state); const coarse = request.coarse; return unavailable("exact", "dependent-quote-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, quoteReturnDataHex: state.quoteReturnDataHex, coarse }); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "qualified-effect-observation-or-simulation-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, required: "qualified-effect-observation-or-simulation" }); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async (request: FamilySearchRunRequestV1) => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const METRONOME_SYNTH_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
