import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { metronomeSynthProjection, type Pair } from "../kernel/projection.ts";
import { METRONOME_SYNTH_ACTION_OWNER_ID, METRONOME_SYNTH_FAMILY_DEFINITION_HASH, METRONOME_SYNTH_MANIFEST, METRONOME_SYNTH_SOURCE_PLAN_ID, METRONOME_SYNTH_SOURCE_WINDOW_BLOCKS } from "./manifest.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type MetronomeSynthActionV1, type MetronomeSynthCandidateV1, type MetronomeSynthExecutionIntentV1, type MetronomeSynthIdentityReadFactsV1, type MetronomeSynthIdentityV1, type MetronomeSynthMaterializedStateV1, type MetronomeSynthObservationV1, type MetronomeSynthRouteV1, type MetronomeSynthStateReadFactsV1 } from "./types.ts";
export type MetronomeSynthDiscoveryPatternV1 = "metronome-synth-surface" | "metronome-synth-call";
export interface MetronomeSynthCandidateSeedV1 { readonly target: string; readonly evidence: MetronomeSynthObservationV1; }
export function decodeMetronomeSynthCandidate(observation: MetronomeSynthObservationV1, pattern: MetronomeSynthDiscoveryPatternV1): MetronomeSynthCandidateSeedV1 | null { if ((pattern === "metronome-synth-surface" || pattern === "metronome-synth-call") && (observation.kind === "address-surface" || observation.kind === "call" || observation.kind === "log")) return Object.freeze({ target: canonicalAddress(observation.target), evidence: observation }); return null; }
export function instanceNominationKey(input: MetronomeSynthCandidateSeedV1 | MetronomeSynthCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: MetronomeSynthObservationV1): Hash { return hashDomain("aloha/metronome-synth/candidate-snapshot/v1", { familyDefinitionHash: METRONOME_SYNTH_FAMILY_DEFINITION_HASH, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, rawLocatorHash: input.rawLocatorHash }); }
export type MetronomeSynthNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: MetronomeSynthCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominateMetronomeSynth(input: MetronomeSynthCandidateSeedV1): MetronomeSynthNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff), n = BigInt(input.evidence.blockNumber), end = BigInt(cutoff.number); if (n > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (n < end - BigInt(METRONOME_SYNTH_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: instanceNominationKey({ target, evidence: input.evidence }), candidateSnapshotHash: candidateSnapshotHash({ ...input.evidence, target }), evidence: Object.freeze({ ...input.evidence, target, cutoff }) }) }); }
export function candidateFamilyKey(candidate: MetronomeSynthCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }
export type MetronomeSynthIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: MetronomeSynthIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "reverse-identity-mismatch" | "empty-token-set" | "invalid-direction" };
export function verifyMetronomeSynthIdentityStage(input: { readonly candidate: MetronomeSynthCandidateV1; readonly reads: MetronomeSynthIdentityReadFactsV1 }): MetronomeSynthIdentityOutcomeV1 { const r = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), reverseTarget: canonicalAddress(input.reads.reverseTarget), pool: canonicalAddress(input.reads.pool), tokens: input.reads.tokens.map(canonicalAddress), activeDirections: input.reads.activeDirections.map(pair => Object.freeze({ tokenIn: canonicalAddress(pair.tokenIn), tokenOut: canonicalAddress(pair.tokenOut) })), oracleBinding: input.reads.oracleBinding.toLowerCase() as `0x${string}` }; if (!cutoffEqual(r.cutoff, input.candidate.evidence.cutoff)) throw new TypeError("metronome synth identity cutoff mismatch"); if (r.target !== canonicalAddress(input.candidate.target) || r.reverseTarget !== r.target || r.pool !== r.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; if (r.tokens.length < 2) return { status: "chain-proven-rejected", reasonCode: "empty-token-set" }; let projection; try { projection = metronomeSynthProjection({ pool: r.pool, tokens: r.tokens, activeDirections: r.activeDirections as readonly Pair[], oracleBinding: r.oracleBinding }); } catch { return { status: "chain-proven-rejected", reasonCode: "invalid-direction" }; } const facts = Object.freeze({ ...projection }); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: r.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey: r.pool, factsHash: hashDomain("aloha/metronome-synth/identity-facts/v1", facts), facts }) }); }
export function identityDescriptorHash(identity: MetronomeSynthIdentityV1): Hash { return hashDomain("aloha/metronome-synth/instance-descriptor/v1", { familyDefinitionHash: METRONOME_SYNTH_FAMILY_DEFINITION_HASH, factsHash: identity.factsHash, instanceKey: identity.instanceKey }); }
export type MetronomeSynthMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: MetronomeSynthMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" };
export function materializeMetronomeSynth(input: { readonly identity: MetronomeSynthIdentityV1; readonly read: MetronomeSynthStateReadFactsV1 }): MetronomeSynthMaterializationOutcomeV1 { const r = { ...input.read, cutoff: assertCutoff(input.read.cutoff), instanceKey: canonicalAddress(input.read.instanceKey) }; if (!cutoffEqual(r.cutoff, input.identity.cutoff)) throw new TypeError("metronome synth state cutoff mismatch"); if (r.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; const stateHash = hashDomain("aloha/metronome-synth/materialized-state/v1", { identityFactsHash: input.identity.factsHash, projectionHash: r.projectionHash }); return Object.freeze({ status: "verified", state: Object.freeze({ ...r, identityFactsHash: input.identity.factsHash, stateHash }) }); }
export function deriveMetronomeSynthRoutes(identity: MetronomeSynthIdentityV1): readonly MetronomeSynthRouteV1[] { return Object.freeze(identity.facts.directions.map((pair: Pair) => { const route = { instanceKey: identity.instanceKey, inputAsset: pair.tokenIn, outputAsset: pair.tokenOut }; return Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/metronome-synth/route-binding/v1", route) }); })); }
export function assertMetronomeSynthRoute(route: MetronomeSynthRouteV1, identity: MetronomeSynthIdentityV1): void { if (route.instanceKey !== identity.instanceKey || !identity.facts.directions.some((pair: Pair) => pair.tokenIn === route.inputAsset && pair.tokenOut === route.outputAsset)) throw new TypeError("metronome synth route identity mismatch"); }
export type MetronomeSynthCoarseOutcomeV1 = { readonly status: "unavailable"; readonly reasonCode: "dependent-quote-not-in-release" };
export function coarseMetronomeSynth(): MetronomeSynthCoarseOutcomeV1 { return Object.freeze({ status: "unavailable", reasonCode: "dependent-quote-not-in-release" }); }
export type MetronomeSynthExactOutcomeV1 = MetronomeSynthCoarseOutcomeV1;
export function exactMetronomeSynth(): MetronomeSynthExactOutcomeV1 { return Object.freeze({ status: "unavailable", reasonCode: "dependent-quote-not-in-release" }); }
export function buildMetronomeSynthAction(input: { readonly identity: MetronomeSynthIdentityV1; readonly calldata: string }): MetronomeSynthActionV1 { if (!/^0x[0-9a-fA-F]*$/.test(input.calldata) || input.calldata.length % 2 !== 0) throw new TypeError("metronome synth calldata is not canonical"); const payload = { cutoff: input.identity.cutoff, target: canonicalAddress(input.identity.instanceKey), calldata: input.calldata, bindingHash: input.identity.factsHash }; return Object.freeze({ ...payload, actionHash: hashDomain("aloha/metronome-synth/action/v1", payload) }); }
export const METRONOME_SYNTH_ACTION_PORT = Object.freeze({ actionOwnerId: METRONOME_SYNTH_ACTION_OWNER_ID, build: buildMetronomeSynthAction });
export function compileMetronomeSynthExecution(input: { readonly identity: MetronomeSynthIdentityV1; readonly action: MetronomeSynthActionV1 }): MetronomeSynthExecutionIntentV1 { if (input.action.target !== canonicalAddress(input.identity.instanceKey)) throw new TypeError("metronome synth execution target mismatch"); return Object.freeze({ kind: "metronome-synth-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, bindingHash: input.action.bindingHash }); }
export function captureMetronomeSynthEvidence(input: { readonly observation: MetronomeSynthObservationV1; readonly pattern: MetronomeSynthDiscoveryPatternV1 }): MetronomeSynthCandidateSeedV1 | null { return decodeMetronomeSynthCandidate(input.observation, input.pattern); }
export const METRONOME_SYNTH_RUNTIME = Object.freeze({ manifest: METRONOME_SYNTH_MANIFEST, discover: decodeMetronomeSynthCandidate, capture: captureMetronomeSynthEvidence, nominate: nominateMetronomeSynth, identity: verifyMetronomeSynthIdentityStage, materialize: materializeMetronomeSynth, routes: deriveMetronomeSynthRoutes, coarse: coarseMetronomeSynth, exact: exactMetronomeSynth, execute: compileMetronomeSynthExecution });
export const METRONOME_SYNTH_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateMetronomeSynth });
export const METRONOME_SYNTH_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyMetronomeSynthIdentityStage });
export const METRONOME_SYNTH_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeMetronomeSynth });
export const METRONOME_SYNTH_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveMetronomeSynthRoutes });
export const METRONOME_SYNTH_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveMetronomeSynthRoutes });
