import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { ROCKSOLID_ACTION_OWNER_ID, ROCKSOLID_CAPABILITY_IDS, ROCKSOLID_FAMILY_DEFINITION_HASH, ROCKSOLID_FAMILY_ID, ROCKSOLID_FAMILY_VERSION, ROCKSOLID_OWNER_REF, ROCKSOLID_SOURCE_PLAN_ID, ROCKSOLID_SOURCE_PLAN_SCHEMA_HASH } from "./manifest.ts";
const version = asCapabilityVersion(ROCKSOLID_FAMILY_VERSION); const moduleRoot = "families/rocksolid/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${ROCKSOLID_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/rocksolid/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([ROCKSOLID_SOURCE_PLAN_ID]) } : {}) }); }
function slot(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(ROCKSOLID_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/rocksolid/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/rocksolid/extension-interpreter/v1", name), dependencyIds: Object.freeze(name === "state" ? [] : [asCapabilityId(ROCKSOLID_CAPABILITY_IDS.state)]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "ROCKSOLID_RUNTIME" }); }
const n = core("nomination", "ROCKSOLID_NOMINATION_DEFINITION"); const i = core("identity", "ROCKSOLID_IDENTITY_DEFINITION"); const m = core("materialization", "ROCKSOLID_MATERIALIZATION_DEFINITION"); const p = core("projection", "ROCKSOLID_PROJECTION_DEFINITION"); const r = core("rehydration", "ROCKSOLID_REHYDRATION_DEFINITION"); const state = slot("state"); const coarse = slot("coarse"); const exact = slot("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.rocksolid.identity", version, schemaHash: asSchemaRef(hashDomain("aloha/rocksolid/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.rocksolid.quote", version, schemaHash: asSchemaRef(hashDomain("aloha/rocksolid/fact-schema/v1", "quote")) })]);
const actionOwner = Object.freeze({ ownerId: ROCKSOLID_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/rocksolid/action-schema/v1", "sync-deposit")), implementationHash: hashDomain("aloha/rocksolid/action-implementation/v1", "sync-deposit"), actionKinds: Object.freeze(["sync-deposit"]), modulePath: `${moduleRoot}/action.ts`, exportName: "ROCKSOLID_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: ROCKSOLID_FAMILY_ID, version: ROCKSOLID_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/rocksolid/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, facts, actionOwner }), authorityDeclarationHash: hashDomain("aloha/rocksolid/authority/v1", ROCKSOLID_OWNER_REF), sourcePlans: [{ sourcePlanId: ROCKSOLID_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: ROCKSOLID_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "ROCKSOLID_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/rocksolid/src/source-plan.ts", exportName: "ROCKSOLID_SOURCE_NOMINATION_PROGRAM", schemaHash: ROCKSOLID_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/rocksolid/src/nomination-qualification.ts", exportName: "ROCKSOLID_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/rocksolid/src/nomination-qualification.ts", exportName: "ROCKSOLID_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [ROCKSOLID_CAPABILITY_IDS.state]: { kind: "present", module: state }, [ROCKSOLID_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [ROCKSOLID_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "ROCKSOLID_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(ROCKSOLID_CAPABILITY_IDS.state), coarse: asCapabilityId(ROCKSOLID_CAPABILITY_IDS.coarse), exact: asCapabilityId(ROCKSOLID_CAPABILITY_IDS.exact) }, actionOwnerIds: { "sync-deposit": ROCKSOLID_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const ROCKSOLID_DEFINITION = defineFamily(input); export const ROCKSOLID_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(ROCKSOLID_DEFINITION); export { ROCKSOLID_FAMILY_DEFINITION_HASH, ROCKSOLID_OWNER_REF };
