import { assertDecimalString, assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { familyCandidateKey as discoveryFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchCoarseArtifactV1, type FamilySearchExactArtifactV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ROCKSOLID_FAMILY_DEFINITION_HASH, ROCKSOLID_FAMILY_ID } from "./manifest.ts";
import { exactRocksolid } from "./exact.ts";
import { materializeRocksolid } from "./instance.ts";
import { coarseRocksolid } from "./pricing.ts";
import { assertRocksolidRoute, deriveRocksolidRoutes } from "./routes.ts";
import { canonicalAddress, type RocksolidIdentityV1, type RocksolidMaterializedStateV1, type RocksolidQuoteV1, type RocksolidRouteV1 } from "./types.ts";

type Source = ReturnType<typeof familySearchSource>;
type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: Source; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly amountHash: Hash; readonly identity: RocksolidIdentityV1; readonly protocolRoute: RocksolidRouteV1 };
type StateResponse = { readonly kind: "rocksolid-state-read-response"; readonly requestId: Hash; readonly source: Source; readonly routeBindingHash: Hash; readonly amountHash: Hash; readonly instanceKey: string; readonly stateHash: Hash; readonly quoteReturnDataHex: string };

function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { return assertNonEmptyString(value, path); }
function bytes(value: unknown, path: string): string { const result = text(value, path); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result)) throw new TypeError(`${path} must be even-length hex bytes`); return result.toLowerCase(); }
function abiUint256(value: string, path: string): string { const hex = bytes(value, path); if (hex.length !== 66) throw new TypeError(`${path} must be one ABI uint256 word`); return hex; }
function assetRef(chainId: string, value: string): Hash { return erc20AssetRefV1(chainId, value); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, `rocksolid-${reasonCode}`, canonical(evidence)); }
function word(value: bigint, path: string): string { if (value < 0n || value >= (1n << 256n)) throw new RangeError(`${path} is outside uint256`); return value.toString(16).padStart(64, "0"); }
function call(selector: string, words: readonly string[]): string { if (!/^0x[0-9a-fA-F]{8}$/.test(selector)) throw new TypeError("rocksolid selector is not canonical"); return `${selector}${words.join("")}`.toLowerCase(); }

function decodeIdentity(value: unknown): RocksolidIdentityV1 {
  const outer = record(value, "rocksolid.route.identityMemo"); assertExactKeys(outer, ["kind", "version", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "identity"], "rocksolid.identityMemo");
  if (outer.kind !== "rocksolid-identity-memo" || outer.version !== 1 || outer.familyId !== ROCKSOLID_FAMILY_ID) throw new TypeError("rocksolid identity memo discriminator mismatch");
  const definitionHash = assertHash(outer.familyDefinitionHash, "rocksolid.identityMemo.familyDefinitionHash"); const nominationKey = text(outer.instanceNominationKey, "rocksolid.identityMemo.instanceNominationKey");
  if (definitionHash !== ROCKSOLID_FAMILY_DEFINITION_HASH || assertHash(outer.familyCandidateKey, "rocksolid.identityMemo.familyCandidateKey") !== discoveryFamilyCandidateKey(definitionHash, nominationKey)) throw new TypeError("rocksolid identity memo family binding mismatch");
  const source = record(outer.identity, "rocksolid.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "rocksolid.identity"); const facts = record(source.facts, "rocksolid.identity.facts"); assertExactKeys(facts, ["target", "asset", "receiptToken", "depositSelector"], "rocksolid.identity.facts");
  const decodedFacts = Object.freeze({ target: canonicalAddress(text(facts.target, "rocksolid.identity.facts.target")), asset: canonicalAddress(text(facts.asset, "rocksolid.identity.facts.asset")), receiptToken: canonicalAddress(text(facts.receiptToken, "rocksolid.identity.facts.receiptToken")), depositSelector: bytes(facts.depositSelector, "rocksolid.identity.facts.depositSelector") as `0x${string}` });
  const identity = Object.freeze({ cutoff: familySearchSource(source.cutoff, "rocksolid.identity.cutoff") as RocksolidIdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "rocksolid.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "rocksolid.identity.instanceKey")), factsHash: assertHash(source.factsHash, "rocksolid.identity.factsHash"), facts: decodedFacts });
  if (identity.instanceKey !== identity.facts.target || identity.facts.asset === identity.facts.receiptToken || identity.factsHash !== hashDomain("aloha/rocksolid/identity-facts/v1", identity.facts)) throw new TypeError("rocksolid identity facts hash mismatch");
  if (nominationKey !== identity.instanceKey || assertHash(outer.candidateSnapshotHash, "rocksolid.identityMemo.candidateSnapshotHash") !== identity.candidateSnapshotHash) throw new TypeError("rocksolid identity memo lineage mismatch");
  return identity;
}
function context(input: FamilySearchLegRequestV1): Context { const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== ROCKSOLID_FAMILY_ID || route.familyDefinitionHash !== ROCKSOLID_FAMILY_DEFINITION_HASH) throw new TypeError("rocksolid search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("rocksolid identity memo hash mismatch"); const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = decodeIdentity(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("rocksolid search instance binding mismatch"); const protocolRoute = deriveRocksolidRoutes(identity).find(item => assetRef(source.chainId, item.inputAsset) === amount.inputAssetRef && assetRef(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("rocksolid search amount assets do not match identity"); assertRocksolidRoute(protocolRoute, identity); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, amountHash: familySearchAmountHash(amount), identity, protocolRoute }); }
function requestId(ctx: Context): Hash { return hashDomain("aloha/rocksolid/search-state-request/v3", { familyDefinitionHash: ROCKSOLID_FAMILY_DEFINITION_HASH, routeBindingHash: ctx.routeBindingHash, instanceKey: ctx.identity.instanceKey, amountHash: ctx.amountHash, source: ctx.source }); }
function readRequest(ctx: Context) { const id = requestId(ctx); return Object.freeze({ kind: "family-search.current-source-read" as const, requestId: id, source: ctx.source, target: ctx.identity.instanceKey, data: call("0xc6e6f592", [word(BigInt(ctx.amount.amountIn), "rocksolid amountIn")]), responseEncoding: "abi-uint256" }); }
function stateResponse(ctx: Context, id: Hash, returnDataHex: string): StateResponse { const quoteReturnDataHex = abiUint256(returnDataHex, "rocksolid.state.returnDataHex"); return Object.freeze({ kind: "rocksolid-state-read-response", requestId: id, source: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, stateHash: hashDomain("aloha/rocksolid/search-state/v4", { cutoff: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, quoteReturnDataHex }), quoteReturnDataHex }); }
function decodeStateResponse(value: CanonicalJson, ctx: Context, id: Hash): StateResponse { const source = record(value, "rocksolid.stateResponse"); assertExactKeys(source, ["kind", "requestId", "source", "routeBindingHash", "amountHash", "instanceKey", "stateHash", "quoteReturnDataHex"], "rocksolid.stateResponse"); if (source.kind !== "rocksolid-state-read-response" || assertHash(source.requestId, "rocksolid.stateResponse.requestId") !== id) throw new TypeError("rocksolid state response request mismatch"); const responseSource = familySearchSource(source.source, "rocksolid.stateResponse.source"); const routeBindingHash = assertHash(source.routeBindingHash, "rocksolid.stateResponse.routeBindingHash"); const amountHash = assertHash(source.amountHash, "rocksolid.stateResponse.amountHash"); const instanceKey = canonicalAddress(text(source.instanceKey, "rocksolid.stateResponse.instanceKey")); if (!sameFamilySearchSource(responseSource, ctx.source) || routeBindingHash !== ctx.routeBindingHash || amountHash !== ctx.amountHash || instanceKey !== ctx.identity.instanceKey) throw new TypeError("rocksolid state response lineage mismatch"); const quoteReturnDataHex = abiUint256(text(source.quoteReturnDataHex, "rocksolid.stateResponse.quoteReturnDataHex"), "rocksolid.stateResponse.quoteReturnDataHex"); const stateHash = assertHash(source.stateHash, "rocksolid.stateResponse.stateHash"); if (stateHash !== hashDomain("aloha/rocksolid/search-state/v4", { cutoff: responseSource, routeBindingHash, amountHash, instanceKey, quoteReturnDataHex })) throw new TypeError("rocksolid state hash mismatch"); return Object.freeze({ kind: "rocksolid-state-read-response", requestId: id, source: responseSource, routeBindingHash, amountHash, instanceKey, stateHash, quoteReturnDataHex }); }
function materialized(ctx: Context, response: StateResponse): RocksolidMaterializedStateV1 { const result = materializeRocksolid({ identity: ctx.identity, read: { cutoff: response.source as RocksolidMaterializedStateV1["cutoff"], instanceKey: response.instanceKey, stateHash: response.stateHash } }); if (result.status !== "verified") throw new TypeError(`rocksolid state ${result.reasonCode}`); return result.state; }
function stateArtifact(ctx: Context, response: StateResponse): FamilySearchStateArtifactV1 { const state = materialized(ctx, response); const payload = canonical(response); const payloadHash = familySearchPayloadHash("state", payload); return Object.freeze({ kind: "state", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot: hashDomain("aloha/rocksolid/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, stateHash: state.stateHash }), sourceRequestId: response.requestId }); }
function assertState(ctx: Context, artifact: FamilySearchStateArtifactV1): StateResponse { if (artifact.kind !== "state" || artifact.status !== "verified" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("rocksolid state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("rocksolid state artifact hash mismatch"); const response = decodeStateResponse(payload, ctx, artifact.sourceRequestId); const state = materialized(ctx, response); if (artifact.factsRoot !== hashDomain("aloha/rocksolid/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, stateHash: state.stateHash })) throw new TypeError("rocksolid state facts root mismatch"); return response; }
function decodeQuote(value: unknown, path: string): RocksolidQuoteV1 { const source = record(value, path); assertExactKeys(source, ["cutoff", "routeBindingHash", "amountIn", "amountOut", "quoteHash"], path); const body = { cutoff: familySearchSource(source.cutoff, `${path}.cutoff`) as RocksolidQuoteV1["cutoff"], routeBindingHash: assertHash(source.routeBindingHash, `${path}.routeBindingHash`), amountIn: assertDecimalString(source.amountIn, `${path}.amountIn`), amountOut: assertDecimalString(source.amountOut, `${path}.amountOut`) }; const quote = Object.freeze({ ...body, quoteHash: assertHash(source.quoteHash, `${path}.quoteHash`) }); if (quote.quoteHash !== hashDomain("aloha/rocksolid/quote/v1", body)) throw new TypeError(`${path}.quoteHash mismatch`); return quote; }
function assertQuoteContext(ctx: Context, quote: RocksolidQuoteV1): void { if (!sameFamilySearchSource(quote.cutoff, ctx.source) || quote.routeBindingHash !== ctx.protocolRoute.routeBindingHash || quote.amountIn !== ctx.amount.amountIn) throw new TypeError("rocksolid quote lineage mismatch"); }
function assertCoarse(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: RocksolidMaterializedStateV1, artifact: FamilySearchCoarseArtifactV1): RocksolidQuoteV1 { if (artifact.kind !== "coarse" || artifact.status !== "rankable" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash || artifact.objectiveRef !== ctx.objective.objectiveRef || artifact.amountHash !== ctx.amountHash || artifact.stateFactsRoot !== stateArtifactValue.factsRoot) throw new TypeError("rocksolid coarse artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("coarse", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash })) throw new TypeError("rocksolid coarse artifact hash mismatch"); const quote = decodeQuote(payload, "rocksolid.coarse.payload"); assertQuoteContext(ctx, quote); if (artifact.input.assetRef !== ctx.amount.inputAssetRef || artifact.input.amount !== ctx.amount.amountIn || artifact.output?.assetRef !== ctx.amount.outputAssetRef || artifact.output?.amount !== quote.amountOut || artifact.conservativeOutputUpperBound !== quote.amountOut || artifact.projectionHash !== hashDomain("aloha/rocksolid/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash })) throw new TypeError("rocksolid coarse artifact lineage mismatch"); return quote; }
function coarseArtifact(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: RocksolidMaterializedStateV1, quote: RocksolidQuoteV1): FamilySearchCoarseArtifactV1 { const payload = canonical(quote); const payloadHash = familySearchPayloadHash("coarse", payload); return Object.freeze({ kind: "coarse", status: "rankable", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash }), projectionHash: hashDomain("aloha/rocksolid/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }), stateFactsRoot: stateArtifactValue.factsRoot, input: { assetRef: ctx.amount.inputAssetRef, amount: quote.amountIn }, output: { assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }, conservativeOutputUpperBound: quote.amountOut, inputCapacityUpperBound: null, rankKey: hashDomain("aloha/rocksolid/search-coarse-rank/v1", { objectiveRef: ctx.objective.objectiveRef, routeBindingHash: ctx.routeBindingHash, quoteHash: quote.quoteHash }), reasonCode: null }); }
function exactArtifact(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: RocksolidMaterializedStateV1, quote: RocksolidQuoteV1): FamilySearchExactArtifactV1 { const payload = canonical({ quote }); const payloadHash = familySearchPayloadHash("exact", payload); const evaluationHash = hashDomain("aloha/rocksolid/search-exact-evaluation/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }); return Object.freeze({ kind: "exact", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "exact", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash }), evaluationHash, stateFactsRoot: stateArtifactValue.factsRoot, inputs: [{ assetRef: ctx.amount.inputAssetRef, amount: quote.amountIn }], outputs: [{ assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }], obligationRoot: hashDomain("aloha/rocksolid/search-obligation/v1", { evaluationHash, routeBindingHash: ctx.routeBindingHash }), reasonCode: null }); }
const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== ROCKSOLID_FAMILY_DEFINITION_HASH) throw new TypeError("rocksolid search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); const physical = readRequest(ctx); let raw: FamilySearchSourceReadResultV1; try { raw = await request.readPort.read({ request: physical, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: physical.requestId, error: String(error) }); } if (raw.kind !== "returned") return unavailable("state", raw.reasonCode || "source-read-unavailable", raw); if (raw.requestId !== physical.requestId || !sameFamilySearchSource(raw.source, physical.source)) throw new TypeError("rocksolid source response binding mismatch"); try { const response = stateResponse(ctx, physical.requestId, raw.dataHex); return Object.freeze({ kind: "verified" as const, artifact: stateArtifact(ctx, response) }); } catch (error) { return unavailable("state", "malformed-abi-return", { requestId: physical.requestId, dataHex: raw.dataHex, error: String(error) }); } } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); const response = assertState(ctx, request.state); const result = coarseRocksolid({ identity: ctx.identity, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn, returnDataHex: response.quoteReturnDataHex }); if (result.status !== "rankable") return unavailable("coarse", result.reasonCode, result); return Object.freeze({ kind: "verified" as const, artifact: coarseArtifact(ctx, request.state, materialized(ctx, response), result.quote) }); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); const response = assertState(ctx, request.state); const state = materialized(ctx, response); const coarse = assertCoarse(ctx, request.state, state, request.coarse); const result = exactRocksolid({ identity: ctx.identity, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn, returnDataHex: response.quoteReturnDataHex }); if (result.status !== "rankable") return unavailable("exact", result.reasonCode, result); if (result.quote.quoteHash !== coarse.quoteHash) throw new TypeError("rocksolid exact/coarse quote mismatch"); return Object.freeze({ kind: "verified" as const, artifact: exactArtifact(ctx, request.state, state, result.quote) }); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "qualified-effect-observation-or-simulation-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, required: "qualified-effect-observation-or-simulation" }); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async (request: FamilySearchRunRequestV1) => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const ROCKSOLID_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
