import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { WSTETH_ACTION_OWNER_ID, WSTETH_CAPABILITY_IDS, WSTETH_FAMILY_DEFINITION_HASH, WSTETH_FAMILY_ID, WSTETH_FAMILY_VERSION, WSTETH_OWNER_REF, WSTETH_SOURCE_PLAN_ID, WSTETH_SOURCE_PLAN_SCHEMA_HASH } from "./manifest.ts";
const version = asCapabilityVersion(WSTETH_FAMILY_VERSION); const moduleRoot = "families/wsteth/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${WSTETH_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/wsteth/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([WSTETH_SOURCE_PLAN_ID]) } : {}) }); }
function slot(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(WSTETH_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/wsteth/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/wsteth/extension-interpreter/v1", name), dependencyIds: Object.freeze(name === "state" ? [] : [asCapabilityId(WSTETH_CAPABILITY_IDS.state)]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "WSTETH_RUNTIME" }); }
const n = core("nomination", "WSTETH_NOMINATION_DEFINITION"); const i = core("identity", "WSTETH_IDENTITY_DEFINITION"); const m = core("materialization", "WSTETH_MATERIALIZATION_DEFINITION"); const p = core("projection", "WSTETH_PROJECTION_DEFINITION"); const r = core("rehydration", "WSTETH_REHYDRATION_DEFINITION"); const state = slot("state"); const coarse = slot("coarse"); const exact = slot("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.wsteth.token-identity", version, schemaHash: asSchemaRef(hashDomain("aloha/wsteth/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.wsteth.conversion-quote", version, schemaHash: asSchemaRef(hashDomain("aloha/wsteth/fact-schema/v1", "quote")) })]);
const actionOwner = Object.freeze({ ownerId: WSTETH_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/wsteth/action-schema/v1", "wrap-unwrap")), implementationHash: hashDomain("aloha/wsteth/action-implementation/v1", "wrap-unwrap"), actionKinds: Object.freeze(["wrap", "unwrap"]), modulePath: `${moduleRoot}/action.ts`, exportName: "WSTETH_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: WSTETH_FAMILY_ID, version: WSTETH_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/wsteth/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, facts, actionOwner }), authorityDeclarationHash: hashDomain("aloha/wsteth/authority/v1", WSTETH_OWNER_REF), sourcePlans: [{ sourcePlanId: WSTETH_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: WSTETH_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "WSTETH_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/wsteth/src/source-plan.ts", exportName: "WSTETH_SOURCE_NOMINATION_PROGRAM", schemaHash: WSTETH_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/wsteth/src/nomination-qualification.ts", exportName: "WSTETH_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/wsteth/src/nomination-qualification.ts", exportName: "WSTETH_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [WSTETH_CAPABILITY_IDS.state]: { kind: "present", module: state }, [WSTETH_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [WSTETH_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "WSTETH_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(WSTETH_CAPABILITY_IDS.state), coarse: asCapabilityId(WSTETH_CAPABILITY_IDS.coarse), exact: asCapabilityId(WSTETH_CAPABILITY_IDS.exact) }, actionOwnerIds: { "wrap-unwrap": WSTETH_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const WSTETH_DEFINITION = defineFamily(input); export const WSTETH_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(WSTETH_DEFINITION); export { WSTETH_FAMILY_DEFINITION_HASH, WSTETH_OWNER_REF };
