export const DODO_DECIMAL_ONE = 10n ** 18n;
export const DODO_UINT256_MAX = (1n << 256n) - 1n;
export type DodoRState = 0 | 1 | 2;
export interface DodoPmmState { readonly i: bigint; readonly K: bigint; readonly B: bigint; readonly Q: bigint; readonly B0: bigint; readonly Q0: bigint; readonly R: DodoRState }
export type DodoPmmQuoteResult = { readonly status: "quote"; readonly amountOut: bigint; readonly grossAmountOut: bigint; readonly lpFee: bigint; readonly mtFee: bigint } | { readonly status: "unresolved"; readonly reason: "implementation-semantics-required" };
type Raw = { readonly status: "quote"; readonly amountOut: bigint } | { readonly status: "unresolved"; readonly reason: "implementation-semantics-required" };
function u(value: bigint, label: string): bigint { if (value < 0n || value > DODO_UINT256_MAX) throw new RangeError(`${label} outside uint256`); return value; }
function add(a: bigint, b: bigint, label: string): bigint { return u(u(a,label)+u(b,label),label); }
function sub(a: bigint, b: bigint, label: string): bigint { u(a,label);u(b,label);if(b>a)throw new RangeError(`${label} underflow`);return a-b; }
function mul(a: bigint,b:bigint,label:string):bigint{u(a,label);u(b,label);if(a!==0n&&b>DODO_UINT256_MAX/a)throw new RangeError(`${label} overflow`);return a*b;}
function nz(value:bigint):bigint{if(value===0n)throw new RangeError("division by zero");return value;}
function mulFloor(a:bigint,b:bigint):bigint{return mul(a,b,"decimal multiplication")/DODO_DECIMAL_ONE;}
function divFloor(a:bigint,b:bigint):bigint{return mul(a,DODO_DECIMAL_ONE,"decimal division")/nz(b);}
function divCeil(a:bigint,b:bigint):bigint{const n=mul(a,DODO_DECIMAL_ONE,"decimal division");return n===0n?0n:(n-1n)/nz(b)+1n;}
function sqrt(value:bigint):bigint{u(value,"sqrt");if(value<2n)return value;let x=1n<<(BigInt(value.toString(2).length)+1n)/2n,n=(x+value/x)>>1n;while(n<x){x=n;n=(x+value/x)>>1n;}return x;}
const quote=(amountOut:bigint):Raw=>Object.freeze({status:"quote",amountOut:u(amountOut,"quote output")});
const unresolved=():Raw=>Object.freeze({status:"unresolved",reason:"implementation-semantics-required"});

function integrate(V0:bigint,V1:bigint,V2:bigint,i:bigint,k:bigint):Raw{if(V0<=0n)throw new RangeError("target is zero");const fair=mul(i,sub(V1,V2,"V1-V2"),"fair");if(k===0n)return quote(fair/DODO_DECIMAL_ONE);const penalty=mulFloor(k,divFloor(mul(V0,V0,"V0 squared")/nz(V1),V2));const coefficient=add(sub(DODO_DECIMAL_ONE,k,"one minus k"),penalty,"coefficient");return quote(mul(coefficient,fair,"coefficient times fair")/(DODO_DECIMAL_ONE**2n));}
function solve(V0:bigint,V1:bigint,delta:bigint,i:bigint,k:bigint):Raw{if(V0<=0n)throw new RangeError("target is zero");if(delta===0n)return quote(0n);if(k===0n){const fair=mulFloor(i,delta);return quote(fair>V1?V1:fair);}if(k===DODO_DECIMAL_ONE){const id=mul(i,delta,"i times delta");if(id===0n)return quote(0n);if(V1>DODO_UINT256_MAX/id)return unresolved();const temp=mul(id,V1,"id times V1")/nz(mul(V0,V0,"V0 squared"));return quote(mul(V1,temp,"V1 times temp")/add(temp,DODO_DECIMAL_ONE,"temp plus one"));}const part2=add(mul(mul(k,V0,"k V0")/nz(V1),V0,"k V0 squared"),mul(i,delta,"i delta"),"part2");let b=mul(sub(DODO_DECIMAL_ONE,k,"one minus k"),V1,"b");const positive=part2>b;b=positive?part2-b:b-part2;b/=DODO_DECIMAL_ONE;const discriminant=add(mul(b,b,"b squared"),mulFloor(mul(sub(DODO_DECIMAL_ONE,k,"one minus k"),4n,"four k"),mul(mulFloor(k,V0),V0,"k V0 squared")),"discriminant");const root=sqrt(discriminant),denominator=mul(sub(DODO_DECIMAL_ONE,k,"one minus k"),2n,"denominator"),numerator=positive?sub(root,b,"root minus b"):add(b,root,"b plus root");if(positive&&numerator===0n)return unresolved();const V2=divCeil(numerator,denominator);return quote(V2>V1?0n:V1-V2);}
function addRaw(prefix:bigint,suffix:Raw):Raw{return suffix.status==="quote"?quote(add(prefix,suffix.amountOut,"crossing output")):suffix;}
function sellBase(s:DodoPmmState,pay:bigint):Raw{if(s.R===0)return solve(s.Q0,s.Q0,pay,s.i,s.K);if(s.R===1){const payOne=sub(s.B0,s.B,"B0-B"),receive=sub(s.Q,s.Q0,"Q-Q0");if(pay<payOne){const q=integrate(s.B0,add(s.B,pay,"B+pay"),s.B,s.i,s.K);return q.status==="quote"?quote(q.amountOut<receive?q.amountOut:receive):q;}if(pay===payOne)return quote(receive);return addRaw(receive,solve(s.Q0,s.Q0,sub(pay,payOne,"crossing pay"),s.i,s.K));}return solve(s.Q0,s.Q,pay,s.i,s.K);}
function sellQuote(s:DodoPmmState,pay:bigint):Raw{if(s.i===0n)throw new RangeError("oracle price is zero");const reciprocal=DODO_DECIMAL_ONE**2n/s.i;if(s.R===0)return solve(s.B0,s.B0,pay,reciprocal,s.K);if(s.R===1)return solve(s.B0,s.B,pay,reciprocal,s.K);const payOne=sub(s.Q0,s.Q,"Q0-Q"),receive=sub(s.B,s.B0,"B-B0");if(pay<payOne){const q=integrate(s.Q0,add(s.Q,pay,"Q+pay"),s.Q,reciprocal,s.K);return q.status==="quote"?quote(q.amountOut<receive?q.amountOut:receive):q;}if(pay===payOne)return quote(receive);return addRaw(receive,solve(s.B0,s.B0,sub(pay,payOne,"crossing pay"),reciprocal,s.K));}
export function quoteDodoPmmExactInput(input:{readonly state:DodoPmmState;readonly sellBase:boolean;readonly payAmount:bigint;readonly lpFeeRate:bigint;readonly mtFeeRate:bigint}):DodoPmmQuoteResult{const {state:s}=input;for(const [label,value] of Object.entries(s))u(BigInt(value),label);if(s.K>DODO_DECIMAL_ONE||![0,1,2].includes(s.R))throw new RangeError("invalid PMM state");u(input.payAmount,"pay");u(input.lpFeeRate,"lp fee");u(input.mtFeeRate,"mt fee");if(input.lpFeeRate>DODO_DECIMAL_ONE||input.mtFeeRate>DODO_DECIMAL_ONE)throw new RangeError("fee exceeds one");const raw=input.sellBase?sellBase(s,input.payAmount):sellQuote(s,input.payAmount);if(raw.status!=="quote")return raw;const lpFee=mulFloor(raw.amountOut,input.lpFeeRate),mtFee=mulFloor(raw.amountOut,input.mtFeeRate),amountOut=sub(sub(raw.amountOut,lpFee,"lp fee"),mtFee,"mt fee");return Object.freeze({status:"quote",amountOut,grossAmountOut:raw.amountOut,lpFee,mtFee});}
