[package]
name = "blockscan-enumerator"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "blockscan_enumerator"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi6"] }
napi-derive = "2"
num-bigint = "0.4"
num-integer = "0.1"

[build-dependencies]
napi-build = "2"
