import {
  assertDecimalString,
  assertHash,
  assertNonEmptyString,
  decodeCanonicalJson,
  decodeExactObject,
  deepFreeze,
  encodeCanonicalJson,
  fieldArray,
  hashDomain,
  type CanonicalJson,
  type Hash,
} from "../../../../packages/canonical-codec/src/index.ts";
import { erc20AssetPortBindingV1 } from "../../../../packages/asset-ref/src/index.ts";
import type { ExecutionFactSourceV1, ProgramInterpretationDraftV1, TransportFactV1 } from "../../../../packages/capability-interpreters/src/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type SchemaRef } from "../../../../packages/capability-contracts/src/index.ts";
import type { FamilyRuntimeStageV1, FamilyStageDefinitionV1, FamilyStageGenericInvocationV1 } from "../../../../packages/family-sdk/runtime/index.ts";
import type { FrozenProgramEnvelopeV1, ProgramSourceAnchorV1 } from "../../../../packages/request-program/src/index.ts";
import { sealInstancePublication, validateInstancePublication, type InstancePublicationV1 } from "../../../../packages/catalog/src/index.ts";
import { candidateEvidenceRoot, candidateSubjectHash, decodeCandidateEvidenceRef, familyCandidateKey as centralFamilyCandidateKey, type CandidateEvidenceRefV1, type CandidateRecordV1, type CanonicalCutoffV1 } from "../../../../packages/discovery/src/index.ts";
import { UNIV3_STANDARD_FAMILY_AUTHORING_HASH } from "../family-definition.ts";
import { UNIV3_POOL_CREATED_TOPIC, UNIV3_STANDARD_FAMILY_ID, UNIV3_STANDARD_FAMILY_VERSION, UNIV3_SWAP_TOPIC } from "../manifest.ts";
import { decodeUniV3Candidate, sourceCandidateSnapshotHash } from "../discovery.ts";
import { nominateUniV3 } from "../nomination.ts";
import { verifyUniV3IdentityStage, identityDescriptorHash } from "../identity.ts";
import { materializeUniV3, resealUniV3State } from "../instance.ts";
import { deriveUniV3Routes } from "../routes.ts";
import type { UniV3CandidateV1, UniV3CutoffV1, UniV3IdentityV1, UniV3IdentityReadFactsV1, UniV3MaterializedStateV1, UniV3StateReadFactsV1, UniV3ObservationV1 } from "../types.ts";

const VERSION = asCapabilityVersion(UNIV3_STANDARD_FAMILY_VERSION);
export const UNIV3_STAGE_IDS = Object.freeze({ nomination: `family.${UNIV3_STANDARD_FAMILY_ID}.nomination`, identity: `family.${UNIV3_STANDARD_FAMILY_ID}.identity`, materialization: `family.${UNIV3_STANDARD_FAMILY_ID}.materialization`, projection: `family.${UNIV3_STANDARD_FAMILY_ID}.projection`, rehydration: `family.${UNIV3_STANDARD_FAMILY_ID}.rehydration` });
export const UNIV3_STAGE_SCHEMA_HASHES = Object.freeze({ nomination: hashDomain("aloha/univ3-standard/stage-schema/v1", "nomination"), identity: hashDomain("aloha/univ3-standard/stage-schema/v1", "identity"), materialization: hashDomain("aloha/univ3-standard/stage-schema/v1", "materialization"), projection: hashDomain("aloha/univ3-standard/stage-schema/v1", "projection"), rehydration: hashDomain("aloha/univ3-standard/stage-schema/v1", "rehydration") });
type Stage = keyof typeof UNIV3_STAGE_IDS;
type CandidateRecord = Omit<CandidateRecordV1, "evidence"> & { readonly evidence: readonly CandidateEvidenceRefV1[] };
interface IdentityMemo { readonly kind: "univ3-identity-memo"; readonly familyId: typeof UNIV3_STANDARD_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSubjectHash: Hash; readonly candidateEvidenceRoot: Hash; readonly identity: UniV3IdentityV1; }
interface NominationPayload { readonly kind: "univ3-nomination-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["candidate"]; readonly requestId: Hash; }
interface IdentityPayload { readonly kind: "univ3-identity-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["identity"]; readonly requestId: Hash; }
interface MaterializationPayload { readonly kind: "univ3-materialization-input"; readonly identityMemo: IdentityMemo; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface MaterializationOutput { readonly kind: "univ3-materialization-output"; readonly familyId: typeof UNIV3_STANDARD_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSubjectHash: Hash; readonly candidateEvidenceRoot: Hash; readonly identityMemoHash: Hash; readonly identityFactsHash: Hash; readonly instanceKey: string; readonly state: UniV3MaterializedStateV1; }
interface ProjectionPayload { readonly kind: "univ3-projection-input"; readonly identityMemo: IdentityMemo; readonly materialization: MaterializationOutput; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface RehydrationPayload { readonly kind: "univ3-rehydration-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly priorPublication: InstancePublicationV1; readonly identityMemo: IdentityMemo; readonly readPlan: readonly ["reference"]; readonly referenceHash: Hash; readonly requestId: Hash; }

function canonical(value: unknown): CanonicalJson { return decodeCanonicalJson(encodeCanonicalJson(value)); }
function address(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x[0-9a-fA-F]{40}$/.test(text)) throw new TypeError(`${path} must be an address`); return `0x${text.slice(2).toLowerCase()}`; }
function bytes(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x(?:[0-9a-f]{2})*$/.test(text)) throw new TypeError(`${path} must be lowercase bytes`); return text; }
function signedDecimal(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^-?\d+$/.test(text) || (text.startsWith("-") && text.length === 1)) throw new TypeError(`${path} must be a signed decimal string`); return text; }
function integer(value: unknown, path: string): number { if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new TypeError(`${path} must be a safe integer`); return value; }
function cutoff(value: unknown, path: string): CanonicalCutoffV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function sameCutoff(left: UniV3CutoffV1, right: UniV3CutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
function sameSource(left: ExecutionFactSourceV1, right: ProgramSourceAnchorV1): boolean { return left.chainId === right.chainId && left.blockNumber === right.number && left.blockHash === right.hash && left.stateRoot === right.stateRoot; }
function factData(value: string): CanonicalJson { const raw = value.slice(2); const bytesValue = new Uint8Array(raw.length / 2); for (let i = 0; i < bytesValue.length; i += 1) bytesValue[i] = Number.parseInt(raw.slice(i * 2, i * 2 + 2), 16); return decodeCanonicalJson(new TextDecoder().decode(bytesValue)); }
function invalidCode(error: unknown, fallback: string): string { const raw = error instanceof Error ? error.message : String(error); const code = raw.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); return /^[a-z][a-z0-9-]*$/.test(code) ? code : fallback; }
function requestId(phase: string, target: string, cutoffValue: CanonicalCutoffV1, snapshot: Hash, operation: string): Hash { return hashDomain("aloha/univ3-standard/runtime-request/v1", { phase, target, cutoff: cutoffValue, candidateSnapshotHash: snapshot, operation }); }
function requestedArtifactDependencyRoot(identity: UniV3IdentityV1): Hash { return hashDomain("aloha/univ3-standard/requested-artifacts/v2", { identityFactsHash: identity.factsHash }); }
function validityDependencyRoot(identity: UniV3IdentityV1): Hash { return hashDomain("aloha/univ3-standard/identity-validity/v2", { identityFactsHash: identity.factsHash, descriptorHash: identityDescriptorHash(identity) }); }
function referenceHash(candidate: CandidateRecord, cutoffValue: CanonicalCutoffV1, publication: InstancePublicationV1): Hash { return hashDomain("aloha/univ3-standard/rehydration-reference/v3", { oldInstancePublicationHash: publication.instancePublicationHash, familyCandidateKey: candidate.familyCandidateKey, candidateSubjectHash: candidate.candidateSubjectHash, cutoff: cutoffValue, requestedArtifactDependencyRoot: publication.requestedArtifactDependencyRoot, descriptorHash: publication.descriptorHash, validityDependencyRoot: publication.validityDependencyRoot }); }

function candidateRecord(value: unknown, path = "univ3.candidate"): CandidateRecord {
  const decoded = decodeExactObject<CandidateRecord>(value, { kind: (item, itemPath) => { if (item !== "aloha.candidate-record") throw new TypeError(`${itemPath} kind mismatch`); return item; }, version: (item, itemPath) => { if (item !== "2") throw new TypeError(`${itemPath} version mismatch`); return item; }, familyId: (item, itemPath) => { if (item !== UNIV3_STANDARD_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return UNIV3_STANDARD_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), evidence: (item, itemPath) => fieldArray(item, (entry, entryPath) => decodeCandidateEvidenceRef(entry, entryPath), itemPath) }, path);
  if (decoded.familyDefinitionHash !== UNIV3_STANDARD_FAMILY_AUTHORING_HASH) throw new TypeError("univ3 candidate definition mismatch");
  if (decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("univ3 candidate key mismatch");
  if (decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("univ3 candidate subject mismatch");
  if (decoded.candidateEvidenceRoot !== candidateEvidenceRoot(decoded.evidence)) throw new TypeError("univ3 candidate evidence root mismatch");
  if (decoded.evidence.length === 0) throw new TypeError("univ3 candidate evidence empty");
  const keys = decoded.evidence.map(item => hashDomain("aloha/candidate-evidence-ref/v1", item));
  if (new Set(keys).size !== keys.length || keys.some((item, index) => item !== [...keys].sort()[index])) throw new TypeError("univ3 candidate evidence order");
  if (decoded.evidence.some(item => item.kind === "recent-log" && address(item.address, "univ3.candidate.evidence.address") !== decoded.instanceNominationKey)) throw new TypeError("univ3 candidate evidence target mismatch");
  if (decoded.evidence.some(item => item.kind === "recent-log" && item.topic.toLowerCase() !== UNIV3_POOL_CREATED_TOPIC && item.topic.toLowerCase() !== UNIV3_SWAP_TOPIC)) throw new TypeError("univ3 candidate evidence topic mismatch");
  return deepFreeze(decoded);
}
function reconstructCandidate(record: CandidateRecord, cutoffValue: CanonicalCutoffV1): UniV3CandidateV1 {
  let selectedEvidence: UniV3CandidateV1["evidence"] | null = null;
  for (const evidence of record.evidence) {
    if (evidence.kind === "source-plan") {
      const target = address(record.instanceNominationKey, "univ3.sourceCandidate.target");
      sourceCandidateSnapshotHash(target, cutoffValue, evidence);
      if (selectedEvidence === null) selectedEvidence = Object.freeze({ kind: "source-plan", cutoff: cutoffValue, target, source: evidence });
      continue;
    }
    const topic = evidence.topic.toLowerCase();
    const pattern = topic === UNIV3_POOL_CREATED_TOPIC ? "univ3-pool-created" : topic === UNIV3_SWAP_TOPIC ? "univ3-swap-log" : null;
    if (pattern === null) throw new TypeError("univ3 candidate evidence pattern mismatch");
    const observation: UniV3ObservationV1 = { kind: "log", target: evidence.address, blockNumber: evidence.blockNumber, blockHash: evidence.blockHash, txHash: evidence.txHash, logIndex: evidence.logIndex, rawLocatorHash: evidence.rawLocatorHash, cutoff: cutoffValue, topic0: evidence.topic };
    const seed = decodeUniV3Candidate(observation, pattern);
    if (seed === null) throw new TypeError("univ3 candidate evidence decode failed");
    const nomination = nominateUniV3(seed);
    if (nomination.status !== "nominated" || nomination.candidate.instanceNominationKey !== record.instanceNominationKey) throw new TypeError("univ3 candidate lineage mismatch");
    if (selectedEvidence === null) selectedEvidence = nomination.candidate.evidence;
  }
  if (selectedEvidence === null || !sameCutoff(selectedEvidence.cutoff, cutoffValue)) throw new TypeError("univ3 candidate evidence missing");
  const target = address(record.instanceNominationKey, "univ3.candidate.target");
  return Object.freeze({ target, instanceNominationKey: target, candidateSnapshotHash: record.candidateSubjectHash, evidence: selectedEvidence });
}
function decodeIdentity(value: unknown, path: string): UniV3IdentityV1 {
  const decoded = decodeExactObject<UniV3IdentityV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), factsHash: (item, itemPath) => assertHash(item, itemPath), facts: (item, itemPath) => decodeExactObject(item, { pool: (field, fieldPath) => address(field, fieldPath), factory: (field, fieldPath) => address(field, fieldPath), token0: (field, fieldPath) => address(field, fieldPath), token1: (field, fieldPath) => address(field, fieldPath), fee: (field, fieldPath) => assertDecimalString(field, fieldPath), tickSpacing: (field, fieldPath) => integer(field, fieldPath), reversePool: (field, fieldPath) => address(field, fieldPath) }, itemPath) }, path);
  if (decoded.instanceKey !== decoded.facts.pool || decoded.factsHash !== hashDomain("aloha/univ3-standard/identity-facts/v1", decoded.facts)) throw new TypeError("univ3 identity hash mismatch");
  return deepFreeze(decoded);
}
function identityMemo(value: unknown, path = "univ3.identityMemo"): IdentityMemo { const decoded = decodeExactObject<IdentityMemo>(value, { kind: (item, itemPath) => { if (item !== "univ3-identity-memo") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-identity-memo"; }, familyId: (item, itemPath) => { if (item !== UNIV3_STANDARD_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return UNIV3_STANDARD_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), identity: (item, itemPath) => decodeIdentity(item, itemPath) }, path); if (decoded.familyDefinitionHash !== UNIV3_STANDARD_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceNominationKey !== decoded.identity.instanceKey || decoded.candidateSubjectHash !== decoded.identity.candidateSnapshotHash) throw new TypeError("univ3 identity memo lineage mismatch"); return deepFreeze(decoded); }
function assertCandidateMemoLineage(candidate: CandidateRecord, memo: IdentityMemo): void { if (candidate.familyDefinitionHash !== memo.familyDefinitionHash || candidate.familyCandidateKey !== memo.familyCandidateKey || candidate.instanceNominationKey !== memo.instanceNominationKey || candidate.candidateSubjectHash !== memo.candidateSubjectHash || candidate.candidateEvidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("univ3 candidate memo lineage mismatch"); }
function decodeState(value: unknown, path: string): UniV3MaterializedStateV1 {
  const decoded = decodeExactObject<UniV3MaterializedStateV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), pool: (item, itemPath) => address(item, itemPath), sqrtPriceX96: (item, itemPath) => assertDecimalString(item, itemPath), tick: (item, itemPath) => integer(item, itemPath), liquidity: (item, itemPath) => assertDecimalString(item, itemPath), fee: (item, itemPath) => assertDecimalString(item, itemPath), tickSpacing: (item, itemPath) => integer(item, itemPath), tickBitmap: (item, itemPath) => fieldArray(item, (entry, entryPath) => decodeExactObject(entry, { word: (field, fieldPath) => integer(field, fieldPath), bits: (field, fieldPath) => assertDecimalString(field, fieldPath) }, entryPath), itemPath), ticks: (item, itemPath) => fieldArray(item, (entry, entryPath) => decodeExactObject(entry, { tick: (field, fieldPath) => integer(field, fieldPath), liquidityNet: (field, fieldPath) => signedDecimal(field, fieldPath) }, entryPath), itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), stateHash: (item, itemPath) => assertHash(item, itemPath) }, path);
  if (decoded.stateHash !== resealUniV3State(decoded)) throw new TypeError("univ3 state hash mismatch");
  return deepFreeze(decoded);
}
function materializationOutput(value: unknown, path = "univ3.materializationOutput"): MaterializationOutput { const decoded = decodeExactObject<MaterializationOutput>(value, { kind: (item, itemPath) => { if (item !== "univ3-materialization-output") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-materialization-output"; }, familyId: (item, itemPath) => { if (item !== UNIV3_STANDARD_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return UNIV3_STANDARD_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), state: (item, itemPath) => decodeState(item, itemPath) }, path); if (decoded.familyDefinitionHash !== UNIV3_STANDARD_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceKey !== decoded.instanceNominationKey || decoded.instanceKey !== decoded.state.pool || decoded.identityFactsHash !== decoded.state.identityFactsHash) throw new TypeError("univ3 materialization lineage mismatch"); return deepFreeze(decoded); }
function readPlan(value: unknown, expected: readonly string[], path: string): readonly string[] { const result = fieldArray(value, (item, itemPath) => assertNonEmptyString(item, itemPath), path); if (result.length !== expected.length || result.some((item, index) => item !== expected[index])) throw new TypeError(`${path} read plan mismatch`); return Object.freeze([...result]); }
function hashValue(value: unknown, path: string): Hash { return assertHash(value, path); }
function nominationPayload(value: unknown, path = "univ3.nominationPayload"): NominationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-nomination-input") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-nomination-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["candidate"], itemPath) as readonly ["candidate"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function identityPayload(value: unknown, path = "univ3.identityPayload"): IdentityPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-identity-input") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-identity-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["identity"], itemPath) as readonly ["identity"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function materializationPayload(value: unknown, path = "univ3.materializationPayload"): MaterializationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-materialization-input") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-materialization-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function projectionPayload(value: unknown, path = "univ3.projectionPayload"): ProjectionPayload { const decoded = decodeExactObject<ProjectionPayload>(value, { kind: (item, itemPath) => { if (item !== "univ3-projection-input") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-projection-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), materialization: (item, itemPath) => materializationOutput(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.materialization.instanceKey !== decoded.identityMemo.identity.instanceKey || decoded.materialization.identityFactsHash !== decoded.identityMemo.identity.factsHash || decoded.materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", decoded.identityMemo) || decoded.materialization.candidateSubjectHash !== decoded.identityMemo.candidateSubjectHash || decoded.materialization.candidateEvidenceRoot !== decoded.identityMemo.candidateEvidenceRoot) throw new TypeError("univ3 projection lineage mismatch"); return decoded; }
function rehydrationPayload(value: unknown, path = "univ3.rehydrationPayload"): RehydrationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-rehydration-input") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-rehydration-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), priorPublication: (item) => { const publication = canonical(item) as unknown as InstancePublicationV1; validateInstancePublication(publication); return publication; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["reference"], itemPath) as readonly ["reference"], referenceHash: (item, itemPath) => hashValue(item, itemPath), requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function boundFact(program: FrozenProgramEnvelopeV1, facts: readonly TransportFactV1[], expected: Hash): Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }> { if (facts.length !== 1) throw new TypeError("univ3 transport fact partition mismatch"); const fact = facts[0]!; if (fact.kind === "transportFailure" || fact.requestId !== expected || fact.requestFingerprint !== program.requestFingerprint || !sameSource(fact.source, program.source)) throw new TypeError("univ3 transport fact binding mismatch"); return fact; }
function decodeFact(value: Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }>): CanonicalJson { return factData(bytes(value.dataHex, "univ3.fact.dataHex")); }
function ack(value: unknown, kind: string): Hash { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== kind) throw new TypeError(`${itemPath} kind mismatch`); return kind; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, value: (item, itemPath) => assertHash(item, itemPath) }).value; }
function outputObject(value: unknown, path: string): CanonicalJson { const result = canonical(value); if (result === null || typeof result !== "object" || Array.isArray(result)) throw new TypeError(`${path} must be an object`); return result; }
function nominationOutput(value: unknown, path = "univ3.nominationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-nomination-verified") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-nomination-verified"; }, familyId: (item, itemPath) => { if (item !== UNIV3_STANDARD_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return UNIV3_STANDARD_FAMILY_ID; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }
function identityOutput(value: unknown, path = "univ3.identityOutput"): CanonicalJson { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "identityVerified") throw new TypeError(`${itemPath} kind mismatch`); return "identityVerified"; }, familyInstanceKey: (item, itemPath) => address(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); const memo = decoded.identityMemo; if (decoded.familyInstanceKey !== memo.identity.instanceKey || decoded.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || decoded.descriptorHash !== identityDescriptorHash(memo.identity) || decoded.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("univ3 identity output lineage mismatch"); return outputObject(decoded, path); }
function materializationOutputCodec(value: unknown): CanonicalJson { return outputObject(materializationOutput(value), "univ3.materializationOutput"); }
function publicationOutput(value: unknown): CanonicalJson { const decoded = canonical(value); if (decoded === null || typeof decoded !== "object" || Array.isArray(decoded)) throw new TypeError("univ3 projection output must be object"); const publication = decoded as unknown as InstancePublicationV1; validateInstancePublication(publication); const memo = identityMemo(publication.identityMemo, "univ3.projectionOutput.identityMemo"); if (publication.familyId !== UNIV3_STANDARD_FAMILY_ID || publication.familyDefinitionHash !== memo.familyDefinitionHash || publication.familyCandidateKey !== memo.familyCandidateKey || publication.instanceKey !== memo.identity.instanceKey || publication.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || publication.descriptorHash !== identityDescriptorHash(memo.identity) || publication.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("univ3 publication lineage mismatch"); return decoded; }
function rehydrationOutput(value: unknown, path = "univ3.rehydrationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "verifiedMemoReuseProof") throw new TypeError(`${itemPath} kind mismatch`); return "verifiedMemoReuseProof"; }, familyId: (item, itemPath) => { if (item !== UNIV3_STANDARD_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return UNIV3_STANDARD_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), oldInstancePublicationHash: (item, itemPath) => assertHash(item, itemPath), requestedArtifactDependencyRoot: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), validityDependencyRoot: (item, itemPath) => assertHash(item, itemPath), candidateToCanonicalIdentityBindingProof: (item, itemPath) => assertHash(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath), proofHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }

function requireStage(input: FamilyStageGenericInvocationV1, expected: Stage): void { if (input.stage !== expected) throw new TypeError(`univ3-${expected}-stage-mismatch`); }
function noPrior(input: FamilyStageGenericInvocationV1): void { if (input.identityMemo !== null || input.materializationOutput !== null || input.reusePublication != null) throw new TypeError("univ3 unexpected prior output"); }
function prepareNomination(input: FamilyStageGenericInvocationV1): NominationPayload { requireStage(input, "nomination"); noPrior(input); const c = cutoff(input.cutoff, "univ3.nomination.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "univ3-nomination-input", candidate, cutoff: c, readPlan: ["candidate"], requestId: requestId("nomination", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "candidate") }; }
function prepareIdentity(input: FamilyStageGenericInvocationV1): IdentityPayload { requireStage(input, "identity"); noPrior(input); const c = cutoff(input.cutoff, "univ3.identity.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "univ3-identity-input", candidate, cutoff: c, readPlan: ["identity"], requestId: requestId("identity", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "identity") }; }
function prepareMaterialization(input: FamilyStageGenericInvocationV1): MaterializationPayload { requireStage(input, "materialization"); if (input.identityMemo === null || input.materializationOutput !== null) throw new TypeError("univ3 materialization prior output mismatch"); const c = cutoff(input.cutoff, "univ3.materialization.cutoff"); const candidate = candidateRecord(input.candidate, "univ3.materialization.candidate"); const memo = identityMemo(input.identityMemo); assertCandidateMemoLineage(candidate, memo); if (!sameCutoff(c, memo.identity.cutoff)) throw new TypeError("univ3 materialization cutoff mismatch"); return { kind: "univ3-materialization-input", identityMemo: memo, cutoff: c, readPlan: ["state"], requestId: requestId("materialization", memo.identity.instanceKey, c, memo.candidateSubjectHash, "state") }; }
function prepareProjection(input: FamilyStageGenericInvocationV1): ProjectionPayload { requireStage(input, "projection"); if (input.identityMemo === null || input.materializationOutput === null) throw new TypeError("univ3 projection prior output missing"); const c = cutoff(input.cutoff, "univ3.projection.cutoff"); const candidate = candidateRecord(input.candidate, "univ3.projection.candidate"); const memo = identityMemo(input.identityMemo); assertCandidateMemoLineage(candidate, memo); const materialization = materializationOutput(input.materializationOutput); if (!sameCutoff(c, memo.identity.cutoff) || materialization.instanceKey !== memo.identity.instanceKey || materialization.identityFactsHash !== memo.identity.factsHash || materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || materialization.candidateSubjectHash !== memo.candidateSubjectHash || materialization.candidateEvidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("univ3 projection lineage mismatch"); return { kind: "univ3-projection-input", identityMemo: memo, materialization, cutoff: c, readPlan: ["state"], requestId: requestId("projection", memo.identity.instanceKey, c, memo.candidateSubjectHash, "state") }; }
function prepareRehydration(input: FamilyStageGenericInvocationV1): RehydrationPayload { requireStage(input, "rehydration"); if (input.identityMemo !== null || input.materializationOutput !== null || input.reusePublication === null) throw new TypeError("univ3 rehydration prior publication required"); const c = cutoff(input.cutoff, "univ3.rehydration.cutoff"); const candidate = candidateRecord(input.candidate); const priorPublication = canonical(input.reusePublication) as unknown as InstancePublicationV1; validateInstancePublication(priorPublication); const priorMemo = identityMemo(priorPublication.identityMemo, "univ3.rehydration.priorIdentityMemo"); if (priorPublication.familyId !== UNIV3_STANDARD_FAMILY_ID || priorPublication.familyDefinitionHash !== UNIV3_STANDARD_FAMILY_AUTHORING_HASH || priorPublication.instanceKey !== candidate.instanceNominationKey || priorPublication.requestedArtifactDependencyRoot !== requestedArtifactDependencyRoot(priorMemo.identity) || priorPublication.descriptorHash !== identityDescriptorHash(priorMemo.identity) || priorPublication.validityDependencyRoot !== validityDependencyRoot(priorMemo.identity)) throw new TypeError("univ3 memo reuse dependency or identity mismatch"); const identity = deepFreeze({ ...priorMemo.identity, cutoff: c, candidateSnapshotHash: candidate.candidateSubjectHash }); const currentIdentityMemo = deepFreeze({ kind: "univ3-identity-memo" as const, familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: UNIV3_STANDARD_FAMILY_AUTHORING_HASH, familyCandidateKey: candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSubjectHash: candidate.candidateSubjectHash, candidateEvidenceRoot: candidate.candidateEvidenceRoot, identity }); const reference = referenceHash(candidate, c, priorPublication); return { kind: "univ3-rehydration-input", candidate, cutoff: c, priorPublication, identityMemo: currentIdentityMemo, readPlan: ["reference"], referenceHash: reference, requestId: requestId("rehydration", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, reference) }; }

function identityFact(value: unknown): { readonly candidateSnapshotHash: Hash; readonly reads: UniV3IdentityReadFactsV1 } { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-identity-facts") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-identity-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), reads: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), factory: (field, fieldPath) => address(field, fieldPath), token0: (field, fieldPath) => address(field, fieldPath), token1: (field, fieldPath) => address(field, fieldPath), fee: (field, fieldPath) => assertDecimalString(field, fieldPath), tickSpacing: (field, fieldPath) => integer(field, fieldPath), reversePool: (field, fieldPath) => address(field, fieldPath) }, itemPath) }, "univ3.identityFact"); return decoded; }
function stateFact(value: unknown): UniV3StateReadFactsV1 { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "univ3-state-facts") throw new TypeError(`${itemPath} kind mismatch`); return "univ3-state-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, read: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), sqrtPriceX96: (field, fieldPath) => assertDecimalString(field, fieldPath), tick: (field, fieldPath) => integer(field, fieldPath), liquidity: (field, fieldPath) => assertDecimalString(field, fieldPath), fee: (field, fieldPath) => assertDecimalString(field, fieldPath), tickSpacing: (field, fieldPath) => integer(field, fieldPath), tickBitmap: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { word: (wordField, wordPath) => integer(wordField, wordPath), bits: (bitsField, bitsPath) => assertDecimalString(bitsField, bitsPath) }, entryPath), fieldPath), ticks: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { tick: (tickField, tickPath) => integer(tickField, tickPath), liquidityNet: (netField, netPath) => signedDecimal(netField, netPath) }, entryPath), fieldPath) }, itemPath) }, "univ3.stateFact"); return decoded.read; }
function publication(payload: ProjectionPayload, _program: FrozenProgramEnvelopeV1): InstancePublicationV1 { const identityValue = payload.identityMemo.identity; const routes = deriveUniV3Routes(identityValue); const transitions = routes.map(route => ({ inputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.inputToken), portRef: hashDomain("aloha/univ3-standard/port/v1", { instanceKey: route.instanceKey, role: "input", token: route.inputToken }), ordinal: "0" }], outputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.outputToken), portRef: hashDomain("aloha/univ3-standard/port/v1", { instanceKey: route.instanceKey, role: "output", token: route.outputToken }), ordinal: "0" }], opaqueTransitionRef: hashDomain("aloha/univ3-standard/transition/v1", route), constraintRefs: [payload.materialization.state.stateHash], staticProjectionHash: hashDomain("aloha/univ3-standard/static-transition/v1", route) })); const memo = canonical(payload.identityMemo); return sealInstancePublication({ familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: UNIV3_STANDARD_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.materialization.familyCandidateKey, instanceKey: identityValue.instanceKey, cutoff: payload.cutoff, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(identityValue), staticProjectionMemoHash: hashDomain("aloha/univ3-standard/static-projection/v1", { routes, stateHash: payload.materialization.state.stateHash }), requestedArtifactDependencyRoot: requestedArtifactDependencyRoot(identityValue), validityDependencyRoot: validityDependencyRoot(identityValue), transitions, evidenceRoot: payload.materialization.candidateEvidenceRoot }); }
function interpretNomination(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = nominationPayload(input.payload); reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "univ3-nomination-reverted" }; const value = ack(decodeFact(fact), "univ3-nomination-facts"); if (value !== payload.candidate.candidateSubjectHash) throw new TypeError("univ3 nomination acknowledgement mismatch"); return { kind: "verified", output: { kind: "univ3-nomination-verified", familyId: UNIV3_STANDARD_FAMILY_ID, candidateSnapshotHash: value, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: hashDomain("aloha/univ3-standard/nomination-reference/v1", { candidateSnapshotHash: value, cutoff: payload.cutoff }) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "univ3-nomination-invalid") }; } }
function interpretIdentity(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = identityPayload(input.payload); const candidate = reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "univ3-identity-reverted" }; const decoded = identityFact(decodeFact(fact)); if (decoded.candidateSnapshotHash !== candidate.candidateSnapshotHash) throw new TypeError("univ3 identity fact snapshot mismatch"); const result = verifyUniV3IdentityStage({ candidate, reads: decoded.reads }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const memo: IdentityMemo = { kind: "univ3-identity-memo", familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: UNIV3_STANDARD_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, candidateEvidenceRoot: payload.candidate.candidateEvidenceRoot, identity: result.identity }; return { kind: "verified", output: { kind: "identityVerified", familyInstanceKey: result.identity.instanceKey, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(result.identity), evidenceRoot: memo.candidateEvidenceRoot } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "univ3-identity-invalid") }; } }
function interpretMaterialization(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = materializationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "univ3-materialization-reverted" }; const read = stateFact(decodeFact(fact)); if (!sameCutoff(read.cutoff, payload.cutoff) || read.pool !== payload.identityMemo.identity.instanceKey) throw new TypeError("univ3 state fact lineage mismatch"); const result = materializeUniV3({ identity: payload.identityMemo.identity, read }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const output: MaterializationOutput = { kind: "univ3-materialization-output", familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: UNIV3_STANDARD_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.identityMemo.familyCandidateKey, instanceNominationKey: payload.identityMemo.instanceNominationKey, candidateSubjectHash: payload.identityMemo.candidateSubjectHash, candidateEvidenceRoot: payload.identityMemo.candidateEvidenceRoot, identityMemoHash: hashDomain("aloha/identity-memo/v1", payload.identityMemo), identityFactsHash: payload.identityMemo.identity.factsHash, instanceKey: result.state.pool, state: result.state }; return { kind: "verified", output }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "univ3-materialization-invalid") }; } }
function interpretProjection(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = projectionPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "univ3-projection-reverted" }; const read = stateFact(decodeFact(fact)); const result = materializeUniV3({ identity: payload.identityMemo.identity, read }); if (result.status !== "verified") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; if (result.state.stateHash !== payload.materialization.state.stateHash) throw new TypeError("univ3 projection state lineage mismatch"); return { kind: "verified", output: publication(payload, input.program) }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "univ3-projection-invalid") }; } }
function interpretRehydration(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = rehydrationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "univ3-rehydration-reverted" }; const value = ack(decodeFact(fact), "univ3-rehydration-facts"); if (value !== payload.referenceHash) throw new TypeError("univ3 rehydration acknowledgement mismatch"); const identityMemoHash = hashDomain("aloha/identity-memo/v1", payload.identityMemo); const candidateToCanonicalIdentityBindingProof = hashDomain("aloha/candidate-to-canonical-identity-binding/v1", { familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: payload.candidate.familyDefinitionHash, familyCandidateKey: payload.candidate.familyCandidateKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, oldInstancePublicationHash: payload.priorPublication.instancePublicationHash, identityMemoHash, descriptorHash: payload.priorPublication.descriptorHash }); const proofPayload = { kind: "verifiedMemoReuseProof" as const, familyId: UNIV3_STANDARD_FAMILY_ID, familyDefinitionHash: payload.candidate.familyDefinitionHash, familyCandidateKey: payload.candidate.familyCandidateKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, oldInstancePublicationHash: payload.priorPublication.instancePublicationHash, requestedArtifactDependencyRoot: payload.priorPublication.requestedArtifactDependencyRoot, descriptorHash: payload.priorPublication.descriptorHash, validityDependencyRoot: payload.priorPublication.validityDependencyRoot, candidateToCanonicalIdentityBindingProof, identityMemo: payload.identityMemo, identityMemoHash, evidenceRoot: payload.candidate.candidateEvidenceRoot }; return { kind: "verified", output: { ...proofPayload, proofHash: hashDomain("aloha/verified-memo-reuse-proof/v1", proofPayload) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "univ3-rehydration-invalid") }; } }

function definitionBase(stage: Stage, payloadCodec: { readonly schemaRef: SchemaRef; readonly decodeExact: (value: unknown) => unknown }, outputSchemaRef: Hash, outputCodec: { readonly decodeExact: (value: unknown) => CanonicalJson }, prepareIssueValue: FamilyStageDefinitionV1["prepareIssueValue"], interpret: FamilyStageDefinitionV1["interpret"]): FamilyStageDefinitionV1 { return deepFreeze({ stage, capabilityId: asCapabilityId(UNIV3_STAGE_IDS[stage]), version: VERSION, schemaHash: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES[stage]), payloadCodec: deepFreeze(payloadCodec), dependencyIds: Object.freeze([]), outputSchemaRef, implementationClosureHash: hashDomain("aloha/univ3-standard/runtime-implementation/v1", { stage, module: "families/univ3-standard/src/runtime/definitions.ts" }), outputCodecHash: hashDomain("aloha/univ3-standard/runtime-output-codec/v1", stage), outputCodec: deepFreeze(outputCodec), prepareIssueValue, interpret }); }
const codecs = Object.freeze({ nomination: { schemaRef: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES.nomination), decodeExact: (value: unknown) => nominationPayload(value) }, identity: { schemaRef: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES.identity), decodeExact: (value: unknown) => identityPayload(value) }, materialization: { schemaRef: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES.materialization), decodeExact: (value: unknown) => materializationPayload(value) }, projection: { schemaRef: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES.projection), decodeExact: (value: unknown) => projectionPayload(value) }, rehydration: { schemaRef: asSchemaRef(UNIV3_STAGE_SCHEMA_HASHES.rehydration), decodeExact: (value: unknown) => rehydrationPayload(value) } });
const outputSchema = (stage: Stage): Hash => hashDomain("aloha/univ3-standard/runtime-output-schema/v1", stage);
export const UNIV3_NOMINATION_DEFINITION = definitionBase("nomination", codecs.nomination, outputSchema("nomination"), { decodeExact: value => nominationOutput(value) }, prepareNomination, interpretNomination);
export const UNIV3_IDENTITY_DEFINITION = definitionBase("identity", codecs.identity, outputSchema("identity"), { decodeExact: value => identityOutput(value) }, prepareIdentity, interpretIdentity);
export const UNIV3_MATERIALIZATION_DEFINITION = definitionBase("materialization", codecs.materialization, outputSchema("materialization"), { decodeExact: value => materializationOutputCodec(value) }, prepareMaterialization, interpretMaterialization);
export const UNIV3_PROJECTION_DEFINITION = definitionBase("projection", codecs.projection, outputSchema("projection"), { decodeExact: value => publicationOutput(value) }, prepareProjection, interpretProjection);
export const UNIV3_REHYDRATION_DEFINITION = definitionBase("rehydration", codecs.rehydration, outputSchema("rehydration"), { decodeExact: value => rehydrationOutput(value) }, prepareRehydration, interpretRehydration);
export const UNIV3_STAGE_DEFINITIONS: readonly FamilyStageDefinitionV1[] = Object.freeze([UNIV3_NOMINATION_DEFINITION, UNIV3_IDENTITY_DEFINITION, UNIV3_MATERIALIZATION_DEFINITION, UNIV3_PROJECTION_DEFINITION, UNIV3_REHYDRATION_DEFINITION]);
export function requireUniV3StageDefinition(stage: FamilyRuntimeStageV1): FamilyStageDefinitionV1 { const definition = UNIV3_STAGE_DEFINITIONS.find(item => item.stage === stage); if (!definition) throw new TypeError(`univ3 stage definition missing: ${stage}`); return definition; }
