import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ETHERTOKEN_NATIVE_REDEEM_ACTION_OWNER_ID, ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS, ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID, ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION, ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID, ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, ETHERTOKEN_NATIVE_REDEEM_OWNER_REF, ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID, ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_SCHEMA_HASH, ETHERTOKEN_NATIVE_REDEEM_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION); const moduleRoot = "families/ethertoken-native-redeem/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID, ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/ethertoken-native-redeem/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_RUNTIME" }); }
const n = core("nomination", "ETHERTOKEN_NATIVE_REDEEM_NOMINATION_DEFINITION"); const i = core("identity", "ETHERTOKEN_NATIVE_REDEEM_IDENTITY_DEFINITION"); const m = core("materialization", "ETHERTOKEN_NATIVE_REDEEM_MATERIALIZATION_DEFINITION"); const p = core("projection", "ETHERTOKEN_NATIVE_REDEEM_PROJECTION_DEFINITION"); const r = core("rehydration", "ETHERTOKEN_NATIVE_REDEEM_REHYDRATION_DEFINITION"); const exact = present("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.ethertoken-native-redeem.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.ethertoken-native-redeem.effect-observation", version, schemaHash: asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/fact-schema/v1", "effects")) })]);
const actionOwner = Object.freeze({ ownerId: ETHERTOKEN_NATIVE_REDEEM_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/action-schema/v1", "redeem")), implementationHash: hashDomain("aloha/ethertoken-native-redeem/action-implementation/v1", "redeem"), actionKinds: Object.freeze(["redeem"]), modulePath: `${moduleRoot}/action.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_ACTION_PORT" });
const qualificationRefs = Object.freeze({ mutationCorpus: Object.freeze({ modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_NOMINATION_MUTATION_CORPUS" }), independentOracle: Object.freeze({ modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_NOMINATION_INDEPENDENT_ORACLE" }) });
const sourcePlans = Object.freeze([
  Object.freeze({ sourcePlanId: ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID, completeness: "nomination-only" as const, historyStartBlock: null, schemaHash: ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_RUNTIME", nominationProgram: Object.freeze({ kind: "present" as const, program: Object.freeze({ modulePath: `${moduleRoot}/source-plan.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_SOURCE_NOMINATION_PROGRAM", schemaHash: ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_SCHEMA_HASH, ...qualificationRefs }) }) }),
  Object.freeze({ sourcePlanId: ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID, completeness: "rolling-observation" as const, historyStartBlock: null, schemaHash: ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_RUNTIME", nominationProgram: Object.freeze({ kind: "present" as const, program: Object.freeze({ modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_HISTORY_NOMINATION_PROGRAM", schemaHash: ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, ...qualificationRefs }) }) }),
]);
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID, version: ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/ethertoken-native-redeem/plugin-code/v1", { n, i, m, p, r, exact, actionOwner, facts, sourcePlans }), authorityDeclarationHash: hashDomain("aloha/ethertoken-native-redeem/authority/v1", ETHERTOKEN_NATIVE_REDEEM_OWNER_REF), sourcePlans }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS.state]: { kind: "absent", reason: "not-in-release" }, [ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "not-in-release" }, [ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "ETHERTOKEN_NATIVE_REDEEM_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { exact: asCapabilityId(ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS.exact) }, actionOwnerIds: { redeem: ETHERTOKEN_NATIVE_REDEEM_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const ETHERTOKEN_NATIVE_REDEEM_DEFINITION = defineFamily(input); export const ETHERTOKEN_NATIVE_REDEEM_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(ETHERTOKEN_NATIVE_REDEEM_DEFINITION); export { ETHERTOKEN_NATIVE_REDEEM_FAMILY_DEFINITION_HASH, ETHERTOKEN_NATIVE_REDEEM_OWNER_REF };
