import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { asSchemaRef } from "../../../packages/capability-contracts/src/index.ts";
export const ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID = "ethertoken-native-redeem" as const;
export const ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION = "1.0.0" as const;
export const ETHERTOKEN_NATIVE_REDEEM_SOURCE_WINDOW_BLOCKS = 50 as const;
export const ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID = "ethertoken-native-redeem.fixed-cutoff-50-block" as const;
export const ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/source-plan-schema/v1", ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID));
export const ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID = "ethertoken-native-redeem.destruction-rolling-observation" as const;
export const ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/ethertoken-native-redeem/history-source-plan-schema/v1", ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID));
export const ETHERTOKEN_NATIVE_REDEEM_DESTRUCTION_TOPIC = "0x9a1b418bc061a5d80270261562e6986a35d995f8051145f277be16103abd3453" as const;
export const ETHERTOKEN_NATIVE_REDEEM_CAPABILITY_IDS = Object.freeze({ state: "family.ethertoken-native-redeem.state", coarse: "family.ethertoken-native-redeem.coarse", exact: "family.ethertoken-native-redeem.exact" } as const);
export const ETHERTOKEN_NATIVE_REDEEM_ACTION_OWNER_ID = "family.ethertoken-native-redeem.redeem-action" as const;
export const ETHERTOKEN_NATIVE_REDEEM_MANIFEST = Object.freeze({ familyId: ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID, version: ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION, domain: "protocol" as const, sourcePlans: Object.freeze([{ id: ETHERTOKEN_NATIVE_REDEEM_SOURCE_PLAN_ID, windowBlocks: ETHERTOKEN_NATIVE_REDEEM_SOURCE_WINDOW_BLOCKS, evidenceChannel: "nominate" as const }, { id: ETHERTOKEN_NATIVE_REDEEM_HISTORY_SOURCE_PLAN_ID, historyStartBlock: null, evidenceChannel: "complete-denominator" as const }]), core: Object.freeze(["nomination", "identity", "materialization", "projection", "rehydration"] as const), extensions: Object.freeze(["state", "coarse", "exact"] as const), actionOwners: Object.freeze([ETHERTOKEN_NATIVE_REDEEM_ACTION_OWNER_ID]) });
export const ETHERTOKEN_NATIVE_REDEEM_FAMILY_DEFINITION_HASH: Hash = hashDomain("aloha/ethertoken-native-redeem/family-definition/v1", ETHERTOKEN_NATIVE_REDEEM_MANIFEST);
export const ETHERTOKEN_NATIVE_REDEEM_OWNER_REF: Hash = hashDomain("aloha/ethertoken-native-redeem/owner/v1", { familyId: ETHERTOKEN_NATIVE_REDEEM_FAMILY_ID, version: ETHERTOKEN_NATIVE_REDEEM_FAMILY_VERSION });
