import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
export interface EtherTokenNativeRedeemCutoffV1 { readonly chainId: string; readonly number: string; readonly hash: Hash; readonly stateRoot: Hash; }
export interface EtherTokenNativeRedeemObservationV1 { readonly kind: "log" | "call" | "address-surface"; readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly target: string; readonly rawLocatorHash: Hash; readonly topic?: Hash | null; }
export interface EtherTokenNativeRedeemCandidateV1 { readonly target: string; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly evidence: EtherTokenNativeRedeemObservationV1; }
export interface EtherTokenNativeRedeemIdentityReadFactsV1 { readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly target: string; readonly reverseTarget: string; readonly token: string; readonly actor: string; }
export interface EtherTokenNativeRedeemIdentityV1 { readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: { readonly token: string; readonly actor: string; }; }
export interface EtherTokenNativeRedeemStateReadFactsV1 { readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly instanceKey: string; readonly factsHash: Hash; }
export interface EtherTokenNativeRedeemMaterializedStateV1 extends EtherTokenNativeRedeemStateReadFactsV1 { readonly identityFactsHash: Hash; readonly stateHash: Hash; }
export interface EtherTokenNativeRedeemRouteV1 { readonly instanceKey: string; readonly inputAsset: string; readonly outputAsset: "native"; readonly routeBindingHash: Hash; }
export interface EtherTokenNativeRedeemQuoteV1 { readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly routeBindingHash: Hash; readonly amountIn: string; readonly amountOut: string; readonly quoteHash: Hash; }
export interface EtherTokenNativeRedeemActionV1 { readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly target: string; readonly calldata: string; readonly exactQuoteHash: Hash; readonly actionHash: Hash; }
export interface EtherTokenNativeRedeemExecutionIntentV1 { readonly kind: "ethertoken-native-redeem-execution-intent"; readonly cutoff: EtherTokenNativeRedeemCutoffV1; readonly target: string; readonly calldata: string; readonly actionHash: Hash; readonly exactQuoteHash: Hash; }
export function canonicalAddress(value: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(value)) throw new TypeError("ethertoken address must be 20 bytes"); return `0x${value.slice(2).toLowerCase()}`; }
export function assertCutoff(value: EtherTokenNativeRedeemCutoffV1): EtherTokenNativeRedeemCutoffV1 { if (!/^\d+$/.test(value.chainId) || !/^\d+$/.test(value.number) || !/^0x[0-9a-f]{64}$/.test(value.hash) || !/^0x[0-9a-f]{64}$/.test(value.stateRoot)) throw new TypeError("ethertoken cutoff is not canonical"); return Object.freeze({ ...value }); }
export function cutoffEqual(left: EtherTokenNativeRedeemCutoffV1, right: EtherTokenNativeRedeemCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
export function familyCandidateKey(instanceNominationKey: string): Hash { return hashDomain("aloha/family-candidate/v1", { family: "ethertoken-native-redeem", instanceNominationKey }); }
