import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { PSM_ACTION_OWNER_ID, PSM_CAPABILITY_IDS, PSM_FAMILY_ID, PSM_FAMILY_VERSION, PSM_OWNER_REF, PSM_SOURCE_PLAN_ID, PSM_SOURCE_PLAN_SCHEMA_HASH, PSM_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(PSM_FAMILY_VERSION); const moduleRoot = "families/psm/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${PSM_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/psm/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([PSM_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(PSM_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/psm/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/psm/extension-interpreter/v1", name), dependencyIds: Object.freeze(name === "state" ? [] : [asCapabilityId(PSM_CAPABILITY_IDS.state)]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "PSM_RUNTIME" }); }
const n = core("nomination", "PSM_NOMINATION_RUNTIME"); const i = core("identity", "PSM_IDENTITY_RUNTIME"); const m = core("materialization", "PSM_MATERIALIZATION_RUNTIME"); const p = core("projection", "PSM_PROJECTION_RUNTIME"); const r = core("rehydration", "PSM_REHYDRATION_RUNTIME"); const state = present("state"); const coarse = present("coarse"); const exact = present("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.psm.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/psm/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.psm.fee-state", version, schemaHash: asSchemaRef(hashDomain("aloha/psm/fact-schema/v1", "state")) })]);
const actionOwner = Object.freeze({ ownerId: PSM_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/psm/action-schema/v1", "swap")), implementationHash: hashDomain("aloha/psm/action-implementation/v1", "swap"), actionKinds: Object.freeze(["swap"]), modulePath: `${moduleRoot}/action.ts`, exportName: "PSM_SWAP_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: PSM_FAMILY_ID, version: PSM_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/psm/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, actionOwner, facts }), authorityDeclarationHash: hashDomain("aloha/psm/authority/v1", PSM_OWNER_REF), sourcePlans: [{ sourcePlanId: PSM_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: PSM_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "PSM_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/psm/src/source-plan.ts", exportName: "PSM_SOURCE_NOMINATION_PROGRAM", schemaHash: PSM_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/psm/src/nomination-qualification.ts", exportName: "PSM_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/psm/src/nomination-qualification.ts", exportName: "PSM_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [PSM_CAPABILITY_IDS.state]: { kind: "present", module: state }, [PSM_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [PSM_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "PSM_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(PSM_CAPABILITY_IDS.state), coarse: asCapabilityId(PSM_CAPABILITY_IDS.coarse), exact: asCapabilityId(PSM_CAPABILITY_IDS.exact) }, actionOwnerIds: { swap: PSM_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const PSM_DEFINITION = defineFamily(input); export const PSM_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(PSM_DEFINITION); export { PSM_FAMILY_DEFINITION_HASH, PSM_OWNER_REF };
