import { assertDecimalString, assertExactKeys, assertHash, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchCoarseArtifactV1, type FamilySearchExactArtifactV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { PSM_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { PSM_FAMILY_ID } from "./manifest.ts";
import { coarsePsm, derivePsmRoutes, exactPsm, materializePsm, assertPsmRoute } from "./stages.ts";
import { canonicalAddress, type PsmIdentityV1, type PsmMaterializedStateV1, type PsmQuoteV1, type PsmRouteV1 } from "./types.ts";

type Source = ReturnType<typeof familySearchSource>;
type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: Source; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly amountHash: Hash; readonly identity: PsmIdentityV1; readonly protocolRoute: PsmRouteV1 };
type StateResponse = { readonly kind: "psm-state-read-response"; readonly requestId: Hash; readonly source: Source; readonly routeBindingHash: Hash; readonly amountHash: Hash; readonly instanceKey: string; readonly feeWad: string; readonly assetScale: string; readonly stateHash: Hash };

function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { if (typeof value !== "string" || value.length === 0) throw new TypeError(`${path} must be a non-empty string`); return value; }
function bytes(value: unknown, path: string): string { const result = text(value, path); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result)) throw new TypeError(`${path} must be even-length hex bytes`); return result.toLowerCase(); }
function sameSource(left: Source, right: Source): boolean { return sameFamilySearchSource(left, right); }
function assetRef(chainId: string, value: string): Hash { return erc20AssetRefV1(chainId, value); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, reasonCode, canonical(evidence)); }
function decodeUint256(value: string, path: string): bigint { const hex = bytes(value, path); if (hex.length !== 66) throw new TypeError(`${path} must be one ABI uint256 word`); return BigInt(`0x${hex.slice(2)}`); }

function identityMemo(value: unknown): PsmIdentityV1 {
  const outer = record(value, "psm.route.identityMemo"); const candidate = "identity" in outer ? (() => { assertExactKeys(outer, ["kind", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "identity"], "psm.identityMemo"); if (outer.familyId !== PSM_FAMILY_ID || outer.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH) throw new TypeError("psm identity memo family mismatch"); return outer.identity; })() : value;
  const source = record(candidate, "psm.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "psm.identity"); const facts = record(source.facts, "psm.identity.facts"); assertExactKeys(facts, ["target", "inputAsset", "outputAsset"], "psm.identity.facts");
  const decoded = Object.freeze({ cutoff: familySearchSource(source.cutoff, "psm.identity.cutoff") as PsmIdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "psm.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "psm.identity.instanceKey")), factsHash: assertHash(source.factsHash, "psm.identity.factsHash"), facts: Object.freeze({ target: canonicalAddress(text(facts.target, "psm.identity.facts.target")), inputAsset: canonicalAddress(text(facts.inputAsset, "psm.identity.facts.inputAsset")), outputAsset: canonicalAddress(text(facts.outputAsset, "psm.identity.facts.outputAsset")) }) });
  if (decoded.instanceKey !== decoded.facts.target || decoded.factsHash !== hashDomain("aloha/psm/identity-facts/v1", decoded.facts)) throw new TypeError("psm identity facts hash mismatch"); return decoded;
}

function context(input: FamilySearchLegRequestV1): Context {
  const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== PSM_FAMILY_ID || route.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH) throw new TypeError("psm search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("psm identity memo binding mismatch");
  const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = identityMemo(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("psm search instance binding mismatch"); const protocolRoute = derivePsmRoutes(identity).find(item => assetRef(source.chainId, item.inputAsset) === amount.inputAssetRef && assetRef(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("psm search amount assets do not match identity"); assertPsmRoute(protocolRoute, identity); const amountHash = familySearchAmountHash(amount); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, amountHash, identity, protocolRoute });
}

function requestId(ctx: Context): Hash { return hashDomain("aloha/psm/search-state-request/v3", { familyDefinitionHash: PSM_FAMILY_AUTHORING_HASH, routeBindingHash: ctx.routeBindingHash, instanceKey: ctx.identity.instanceKey, amountHash: ctx.amountHash, source: ctx.source }); }
function readRequest(ctx: Context, field: "tin" | "input-decimals" | "output-decimals"): { readonly requestId: Hash; readonly request: { readonly kind: "family-search.current-source-read"; readonly requestId: Hash; readonly source: Source; readonly target: string; readonly data: string; readonly responseEncoding: "abi-uint256" } } {
  const root = requestId(ctx); const target = field === "tin" ? ctx.identity.instanceKey : field === "input-decimals" ? ctx.identity.facts.inputAsset : ctx.identity.facts.outputAsset; const data = field === "tin" ? "0x568d4b6f" : "0x313ce567"; const id = hashDomain("aloha/psm/search-state-read/v3", { root, field, target, data }); return Object.freeze({ requestId: id, request: Object.freeze({ kind: "family-search.current-source-read" as const, requestId: id, source: ctx.source, target, data, responseEncoding: "abi-uint256" }) });
}
function stateResponse(ctx: Context, id: Hash, feeWad: bigint, inputDecimals: bigint, outputDecimals: bigint): StateResponse {
  if (inputDecimals > 36n || outputDecimals > 36n || outputDecimals < inputDecimals) throw new RangeError("PSM token decimals cannot produce an integer asset scale");
  const assetScale = 10n ** (outputDecimals - inputDecimals); const fee = feeWad.toString(); const scale = assetScale.toString(); return Object.freeze({ kind: "psm-state-read-response", requestId: id, source: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, feeWad: fee, assetScale: scale, stateHash: hashDomain("aloha/psm/search-state/v4", { cutoff: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, feeWad: fee, assetScale: scale }) });
}
function decodeState(value: CanonicalJson, ctx: Context, id: Hash): StateResponse { const source = record(value, "psm.stateResponse"); assertExactKeys(source, ["kind", "requestId", "source", "routeBindingHash", "amountHash", "instanceKey", "feeWad", "assetScale", "stateHash"], "psm.stateResponse"); if (source.kind !== "psm-state-read-response" || assertHash(source.requestId, "psm.stateResponse.requestId") !== id) throw new TypeError("psm state response request mismatch"); const responseSource = familySearchSource(source.source, "psm.stateResponse.source"); const routeBindingHash = assertHash(source.routeBindingHash, "psm.stateResponse.routeBindingHash"); const amountHash = assertHash(source.amountHash, "psm.stateResponse.amountHash"); const instanceKey = canonicalAddress(text(source.instanceKey, "psm.stateResponse.instanceKey")); if (!sameSource(responseSource, ctx.source) || routeBindingHash !== ctx.routeBindingHash || amountHash !== ctx.amountHash || instanceKey !== ctx.identity.instanceKey) throw new TypeError("psm state response lineage mismatch"); const feeWad = assertDecimalString(source.feeWad, "psm.stateResponse.feeWad"); const assetScale = assertDecimalString(source.assetScale, "psm.stateResponse.assetScale"); const stateHash = assertHash(source.stateHash, "psm.stateResponse.stateHash"); if (stateHash !== hashDomain("aloha/psm/search-state/v4", { cutoff: responseSource, routeBindingHash, amountHash, instanceKey, feeWad, assetScale })) throw new TypeError("psm state hash mismatch"); return Object.freeze({ kind: "psm-state-read-response", requestId: id, source: responseSource, routeBindingHash, amountHash, instanceKey, feeWad, assetScale, stateHash }); }
function materialized(ctx: Context, response: StateResponse): PsmMaterializedStateV1 { const result = materializePsm({ identity: ctx.identity, read: { cutoff: response.source as PsmIdentityV1["cutoff"], instanceKey: response.instanceKey, feeWad: response.feeWad, assetScale: response.assetScale } }); if (result.status !== "verified") throw new TypeError(`psm state ${result.reasonCode}`); return result.state; }
function stateArtifact(ctx: Context, response: StateResponse): FamilySearchStateArtifactV1 { const state = materialized(ctx, response); const payload = canonical(response); const payloadHash = familySearchPayloadHash("state", payload); return Object.freeze({ kind: "state", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot: state.stateHash, sourceRequestId: response.requestId }); }
function assertState(ctx: Context, artifact: FamilySearchStateArtifactV1): { readonly response: StateResponse; readonly state: PsmMaterializedStateV1 } { if (artifact.kind !== "state" || artifact.status !== "verified" || !sameSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("psm state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("psm state artifact hash mismatch"); const response = decodeState(payload, ctx, artifact.sourceRequestId); const state = materialized(ctx, response); if (artifact.factsRoot !== state.stateHash) throw new TypeError("psm state facts root mismatch"); return { response, state }; }
function decodeQuote(value: unknown, path: string): PsmQuoteV1 { const source = record(value, path); assertExactKeys(source, ["cutoff", "routeBindingHash", "amountIn", "amountOut", "feeWad", "assetScale", "quoteHash"], path); const payload = { cutoff: familySearchSource(source.cutoff, `${path}.cutoff`) as PsmQuoteV1["cutoff"], routeBindingHash: assertHash(source.routeBindingHash, `${path}.routeBindingHash`), amountIn: assertDecimalString(source.amountIn, `${path}.amountIn`), amountOut: assertDecimalString(source.amountOut, `${path}.amountOut`), feeWad: assertDecimalString(source.feeWad, `${path}.feeWad`), assetScale: assertDecimalString(source.assetScale, `${path}.assetScale`) }; const quote = Object.freeze({ ...payload, quoteHash: assertHash(source.quoteHash, `${path}.quoteHash`) }); if (quote.quoteHash !== hashDomain("aloha/psm/quote/v1", payload)) throw new TypeError(`${path}.quoteHash mismatch`); return quote; }
function assertQuoteContext(ctx: Context, quote: PsmQuoteV1, state?: PsmMaterializedStateV1): void { if (!sameSource(quote.cutoff, ctx.source) || quote.routeBindingHash !== ctx.protocolRoute.routeBindingHash || quote.amountIn !== ctx.amount.amountIn || (state !== undefined && (quote.feeWad !== state.feeWad || quote.assetScale !== state.assetScale))) throw new TypeError("psm quote lineage mismatch"); }
function assertCoarse(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: PsmMaterializedStateV1, artifact: FamilySearchCoarseArtifactV1): PsmQuoteV1 { if (artifact.kind !== "coarse" || artifact.status !== "rankable" || !sameSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash || artifact.objectiveRef !== ctx.objective.objectiveRef || artifact.amountHash !== ctx.amountHash || artifact.stateFactsRoot !== stateArtifactValue.factsRoot) throw new TypeError("psm coarse artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("coarse", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash })) throw new TypeError("psm coarse artifact hash mismatch"); const quote = decodeQuote(payload, "psm.coarse.payload"); assertQuoteContext(ctx, quote, state); if (artifact.input.assetRef !== ctx.amount.inputAssetRef || artifact.input.amount !== ctx.amount.amountIn || artifact.output?.assetRef !== ctx.amount.outputAssetRef || artifact.output?.amount !== quote.amountOut || artifact.conservativeOutputUpperBound !== quote.amountOut || artifact.projectionHash !== hashDomain("aloha/psm/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash })) throw new TypeError("psm coarse artifact lineage mismatch"); return quote; }
function coarseArtifact(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: PsmMaterializedStateV1, quote: PsmQuoteV1): FamilySearchCoarseArtifactV1 { const payload = canonical(quote); const payloadHash = familySearchPayloadHash("coarse", payload); return Object.freeze({ kind: "coarse", status: "rankable", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash }), projectionHash: hashDomain("aloha/psm/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }), stateFactsRoot: stateArtifactValue.factsRoot, input: { assetRef: ctx.amount.inputAssetRef, amount: ctx.amount.amountIn }, output: { assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }, conservativeOutputUpperBound: quote.amountOut, inputCapacityUpperBound: null, rankKey: hashDomain("aloha/psm/search-coarse-rank/v1", { objectiveRef: ctx.objective.objectiveRef, routeBindingHash: ctx.routeBindingHash, quoteHash: quote.quoteHash }), reasonCode: null }); }
function exactArtifact(ctx: Context, stateArtifactValue: FamilySearchStateArtifactV1, state: PsmMaterializedStateV1, quote: PsmQuoteV1): FamilySearchExactArtifactV1 { const payload = canonical({ quote }); const payloadHash = familySearchPayloadHash("exact", payload); const evaluationHash = hashDomain("aloha/psm/search-exact-evaluation/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }); return Object.freeze({ kind: "exact", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "exact", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash }), evaluationHash, stateFactsRoot: stateArtifactValue.factsRoot, inputs: [{ assetRef: ctx.amount.inputAssetRef, amount: quote.amountIn }], outputs: [{ assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }], obligationRoot: hashDomain("aloha/psm/search-obligation/v1", { evaluationHash, routeBindingHash: ctx.routeBindingHash }), reasonCode: null }); }
function exactParts(ctx: Context, artifact: FamilySearchExactArtifactV1): { readonly quote: PsmQuoteV1 } { if (artifact.kind !== "exact" || artifact.status !== "verified" || !sameSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash || artifact.objectiveRef !== ctx.objective.objectiveRef || artifact.amountHash !== ctx.amountHash) throw new TypeError("psm exact artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("exact", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "exact", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: ctx.amountHash, payloadHash })) throw new TypeError("psm exact artifact hash mismatch"); const source = record(payload, "psm.exact.payload"); assertExactKeys(source, ["quote"], "psm.exact.payload"); const quote = decodeQuote(source.quote, "psm.exact.quote"); assertQuoteContext(ctx, quote); if (artifact.inputs.length !== 1 || artifact.outputs.length !== 1 || artifact.inputs[0]?.assetRef !== ctx.amount.inputAssetRef || artifact.inputs[0]?.amount !== ctx.amount.amountIn || artifact.outputs[0]?.assetRef !== ctx.amount.outputAssetRef || artifact.outputs[0]?.amount !== quote.amountOut || artifact.evaluationHash !== hashDomain("aloha/psm/search-exact-evaluation/v1", { quoteHash: quote.quoteHash, stateHash: artifact.stateFactsRoot })) throw new TypeError("psm exact artifact lineage mismatch"); return { quote }; }
const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== PSM_FAMILY_AUTHORING_HASH) throw new TypeError("psm search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); const root = requestId(ctx); const reads = (Object.freeze(["tin", "input-decimals", "output-decimals"] as const)).map(field => readRequest(ctx, field)); const results: bigint[] = []; for (const physical of reads) { let raw: FamilySearchSourceReadResultV1; try { raw = await request.readPort.read({ request: physical.request, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: physical.requestId, source: physical.request.source, error: String(error) }); } if (raw.kind !== "returned") return unavailable("state", raw.reasonCode || "source-read-unavailable", raw); if (raw.requestId !== physical.requestId || !sameSource(raw.source, physical.request.source)) throw new TypeError("psm source response binding mismatch"); try { results.push(decodeUint256(raw.dataHex, `psm.${physical.requestId}.dataHex`)); } catch (error) { return invalid("state", error); } await request.currentSource.assertCurrent(); } const [feeWad, inputDecimals, outputDecimals] = results; if (feeWad === undefined || inputDecimals === undefined || outputDecimals === undefined) throw new TypeError("psm state read partition mismatch"); await request.currentSource.assertCurrent(); const response = stateResponse(ctx, root, feeWad, inputDecimals, outputDecimals); return Object.freeze({ kind: "verified" as const, artifact: stateArtifact(ctx, response) }); } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); const current = assertState(ctx, request.state); const result = coarsePsm({ identity: ctx.identity, state: current.state, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn }); if (result.status !== "rankable") return unavailable("coarse", result.reasonCode, result); return Object.freeze({ kind: "verified" as const, artifact: coarseArtifact(ctx, request.state, current.state, result.quote) }); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); const current = assertState(ctx, request.state); const coarse = assertCoarse(ctx, request.state, current.state, request.coarse); const result = exactPsm({ identity: ctx.identity, state: current.state, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn }); if (result.status !== "rankable") return unavailable("exact", result.reasonCode, result); if (result.quote.quoteHash !== coarse.quoteHash) throw new TypeError("psm exact/coarse quote mismatch"); return Object.freeze({ kind: "verified" as const, artifact: exactArtifact(ctx, request.state, current.state, result.quote) }); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "qualified-effect-observation-or-simulation-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, required: "qualified-effect-observation-or-simulation" }); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async request => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run }); };

export const PSM_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
