import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { PSM_FAMILY_DEFINITION_HASH, PSM_MANIFEST, PSM_SOURCE_PLAN_ID, PSM_SOURCE_WINDOW_BLOCKS, PSM_ACTION_OWNER_ID } from "./manifest.ts";
import { PSM_WAD, psmSellQuote } from "../kernel/quote.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type PsmActionV1, type PsmCandidateV1, type PsmCutoffV1, type PsmExecutionIntentV1, type PsmIdentityReadFactsV1, type PsmIdentityV1, type PsmMaterializedStateV1, type PsmQuoteV1, type PsmRouteV1, type PsmStateReadFactsV1, type PsmObservationV1 } from "./types.ts";
export type PsmDiscoveryPatternV1 = "psm-surface" | "psm-call";
export interface PsmCandidateSeedV1 { readonly target: string; readonly evidence: PsmObservationV1; }
export function decodePsmCandidate(observation: PsmObservationV1, pattern: PsmDiscoveryPatternV1): PsmCandidateSeedV1 | null { if ((pattern === "psm-surface" || pattern === "psm-call") && (observation.kind === "address-surface" || observation.kind === "call")) return Object.freeze({ target: canonicalAddress(observation.target), evidence: observation }); return null; }
export function instanceNominationKey(input: PsmCandidateSeedV1 | PsmCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: PsmObservationV1): Hash { return hashDomain("aloha/psm/candidate-snapshot/v1", { familyDefinitionHash: PSM_FAMILY_DEFINITION_HASH, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, rawLocatorHash: input.rawLocatorHash }); }
export type PsmNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: PsmCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominatePsm(input: PsmCandidateSeedV1): PsmNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff); const block = BigInt(input.evidence.blockNumber); const end = BigInt(cutoff.number); if (block > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (block < end - BigInt(PSM_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target); const key = instanceNominationKey({ target, evidence: input.evidence }); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: key, candidateSnapshotHash: candidateSnapshotHash({ ...input.evidence, target }), evidence: Object.freeze({ ...input.evidence, target, cutoff }) }) }); }
export function candidateFamilyKey(candidate: PsmCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }
export type PsmIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: PsmIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "reverse-identity-mismatch" };
export function verifyPsmIdentityStage(input: { readonly candidate: PsmCandidateV1; readonly reads: PsmIdentityReadFactsV1 }): PsmIdentityOutcomeV1 { const r = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), reverseTarget: canonicalAddress(input.reads.reverseTarget), inputAsset: canonicalAddress(input.reads.inputAsset), outputAsset: canonicalAddress(input.reads.outputAsset) }; if (!cutoffEqual(r.cutoff, input.candidate.evidence.cutoff)) throw new TypeError("PSM identity cutoff mismatch"); if (r.target !== canonicalAddress(input.candidate.target) || r.reverseTarget !== r.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; const facts = Object.freeze({ target: r.target, inputAsset: r.inputAsset, outputAsset: r.outputAsset }); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: r.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey: r.target, factsHash: hashDomain("aloha/psm/identity-facts/v1", facts), facts }) }); }
export function identityDescriptorHash(identity: PsmIdentityV1): Hash { return hashDomain("aloha/psm/instance-descriptor/v1", { familyDefinitionHash: PSM_FAMILY_DEFINITION_HASH, factsHash: identity.factsHash, instanceKey: identity.instanceKey }); }
export type PsmMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: PsmMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" };
export function materializePsm(input: { readonly identity: PsmIdentityV1; readonly read: PsmStateReadFactsV1 }): PsmMaterializationOutcomeV1 { const r = { ...input.read, cutoff: assertCutoff(input.read.cutoff), instanceKey: canonicalAddress(input.read.instanceKey) }; if (!cutoffEqual(r.cutoff, input.identity.cutoff)) throw new TypeError("PSM state cutoff mismatch"); if (r.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; const fee = BigInt(r.feeWad), scale = BigInt(r.assetScale); if (fee < 0n || fee > PSM_WAD || scale <= 0n) throw new RangeError("PSM state bounds"); const stateHash = hashDomain("aloha/psm/materialized-state/v1", { identityFactsHash: input.identity.factsHash, feeWad: r.feeWad, assetScale: r.assetScale }); return Object.freeze({ status: "verified", state: Object.freeze({ ...r, identityFactsHash: input.identity.factsHash, stateHash }) }); }
export function resealPsmState(state: PsmMaterializedStateV1): Hash { return hashDomain("aloha/psm/materialized-state/v1", { identityFactsHash: state.identityFactsHash, feeWad: state.feeWad, assetScale: state.assetScale }); }
export function derivePsmRoutes(identity: PsmIdentityV1): readonly PsmRouteV1[] { const route = { instanceKey: identity.instanceKey, inputAsset: identity.facts.inputAsset, outputAsset: identity.facts.outputAsset }; return Object.freeze([Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/psm/route-binding/v1", route) })]); }
export function assertPsmRoute(route: PsmRouteV1, identity: PsmIdentityV1): void { if (route.instanceKey !== identity.instanceKey || route.inputAsset !== identity.facts.inputAsset || route.outputAsset !== identity.facts.outputAsset) throw new TypeError("PSM route identity mismatch"); const expected = hashDomain("aloha/psm/route-binding/v1", { instanceKey: route.instanceKey, inputAsset: route.inputAsset, outputAsset: route.outputAsset }); if (route.routeBindingHash !== expected) throw new TypeError("PSM route binding mismatch"); }
export type PsmCoarseOutcomeV1 = { readonly status: "rankable"; readonly quote: PsmQuoteV1 } | { readonly status: "unavailable"; readonly reasonCode: "invalid-state" };
export function coarsePsm(input: { readonly identity: PsmIdentityV1; readonly state: PsmMaterializedStateV1; readonly route: PsmRouteV1; readonly amountIn: string }): PsmCoarseOutcomeV1 { try { assertPsmRoute(input.route, input.identity); const amountIn = BigInt(input.amountIn), feeWad = BigInt(input.state.feeWad), assetScale = BigInt(input.state.assetScale); const amountOut = psmSellQuote(amountIn, feeWad, assetScale); const payload = { cutoff: input.state.cutoff, routeBindingHash: input.route.routeBindingHash, amountIn: amountIn.toString(), amountOut: amountOut.toString(), feeWad: feeWad.toString(), assetScale: assetScale.toString() }; return Object.freeze({ status: "rankable", quote: Object.freeze({ ...payload, quoteHash: hashDomain("aloha/psm/quote/v1", payload) }) }); } catch { return { status: "unavailable", reasonCode: "invalid-state" }; } }
export type PsmExactOutcomeV1 = PsmCoarseOutcomeV1;
export function exactPsm(input: Parameters<typeof coarsePsm>[0]): PsmExactOutcomeV1 { return coarsePsm(input); }
export function buildPsmAction(input: { readonly identity: PsmIdentityV1; readonly quote: PsmQuoteV1; readonly calldata: string }): PsmActionV1 { if (!/^0x[0-9a-fA-F]*$/.test(input.calldata) || input.calldata.length % 2 !== 0) throw new TypeError("PSM calldata is not canonical"); const payload = { cutoff: input.identity.cutoff, target: canonicalAddress(input.identity.instanceKey), calldata: input.calldata, exactQuoteHash: input.quote.quoteHash }; return Object.freeze({ ...payload, actionHash: hashDomain("aloha/psm/action/v1", payload) }); }
export const PSM_SWAP_ACTION_PORT = Object.freeze({ actionOwnerId: PSM_ACTION_OWNER_ID, build: buildPsmAction });
export function compilePsmExecution(input: { readonly identity: PsmIdentityV1; readonly action: PsmActionV1 }): PsmExecutionIntentV1 { if (input.action.target !== canonicalAddress(input.identity.instanceKey)) throw new TypeError("PSM execution target mismatch"); return Object.freeze({ kind: "psm-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, exactQuoteHash: input.action.exactQuoteHash }); }
export function capturePsmEvidence(input: { readonly observation: PsmObservationV1; readonly pattern: PsmDiscoveryPatternV1 }): PsmCandidateSeedV1 | null { return decodePsmCandidate(input.observation, input.pattern); }
export const PSM_RUNTIME = Object.freeze({ manifest: PSM_MANIFEST, discover: decodePsmCandidate, capture: capturePsmEvidence, nominate: nominatePsm, identity: verifyPsmIdentityStage, materialize: materializePsm, routes: derivePsmRoutes, coarse: coarsePsm, exact: exactPsm, execute: compilePsmExecution });
export const PSM_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominatePsm });
export const PSM_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyPsmIdentityStage });
export const PSM_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializePsm });
export const PSM_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: derivePsmRoutes });
export const PSM_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: derivePsmRoutes });
