/** Shared neutral contract; it must not import GateCore, release composition, or any adapter. */
export const GATE_REASON_CODES = [
  "invalid-input",
  "schema-invalid",
  "hash-mismatch",
  "artifact-ref-mismatch",
  "artifact-claim-missing",
  "artifact-claim-mismatch",
  "artifact-content-mismatch",
  "resolver-policy-missing",
  "resolver-policy-mismatch",
  "retention-lease-missing",
  "retention-lease-mismatch",
  "lease-invalid",
  "lease-expired",
  "lease-insufficient",
  "store-epoch-mismatch",
  "registry-mismatch",
  "registry-material-mismatch",
  "external-trust-anchor-mismatch",
  "external-issuer-key-mismatch",
  "external-registry-approval-mismatch",
  "external-certificate-signature-mismatch",
  "external-release-approval-mismatch",
  "issuer-untrusted",
  "qualification-membership-missing",
  "qualification-revoked",
  "qualification-stale",
  "observer-qualification-missing",
  "observer-qualification-mismatch",
  "verifier-qualification-missing",
  "verifier-qualification-mismatch",
  "mutation-set-mismatch",
  "oracle-coverage-mismatch",
  "snapshot-mismatch",
  "observation-mismatch",
  "production-receipt-missing",
  "production-receipt-mismatch",
  "process-observation-missing",
  "process-anchor-mismatch",
  "process-splice",
  "predicate-observation-missing",
  "predicate-observation-mismatch",
  "predicate-composition-mismatch",
  "predicate-failed",
  "invocation-mismatch",
  "invocation-signature-mismatch",
  "invocation-binding-mismatch",
  "invocation-key-mismatch",
  "invocation-role-mismatch",
  "invocation-audience-mismatch",
  "invocation-registry-mismatch",
  "invocation-query-mismatch",
  "invocation-snapshot-mismatch",
  "invocation-expired",
  "invocation-ttl-exceeded",
  "canonical-bytes-mismatch",
  "release-authority-unavailable",
] as const;

export type GateReasonCode = (typeof GATE_REASON_CODES)[number];
export type GateVerdict = "pass" | "fail" | "invalid";
