import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ERC4626_SILO_REDEEM_ACTION_OWNER_ID, ERC4626_SILO_REDEEM_CAPABILITY_IDS, ERC4626_SILO_REDEEM_FAMILY_ID, ERC4626_SILO_REDEEM_FAMILY_VERSION, ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_ID, ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, ERC4626_SILO_REDEEM_OWNER_REF, ERC4626_SILO_REDEEM_SOURCE_PLAN_ID, ERC4626_SILO_REDEEM_SOURCE_PLAN_SCHEMA_HASH, ERC4626_SILO_REDEEM_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(ERC4626_SILO_REDEEM_FAMILY_VERSION); const moduleRoot = "families/erc4626-silo-redeem/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${ERC4626_SILO_REDEEM_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/erc4626-silo-redeem/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([ERC4626_SILO_REDEEM_SOURCE_PLAN_ID, ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(ERC4626_SILO_REDEEM_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626-silo-redeem/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/erc4626-silo-redeem/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "ERC4626_SILO_REDEEM_RUNTIME" }); }
const n = core("nomination", "ERC4626_SILO_REDEEM_NOMINATION_DEFINITION"); const i = core("identity", "ERC4626_SILO_REDEEM_IDENTITY_DEFINITION"); const m = core("materialization", "ERC4626_SILO_REDEEM_MATERIALIZATION_DEFINITION"); const p = core("projection", "ERC4626_SILO_REDEEM_PROJECTION_DEFINITION"); const r = core("rehydration", "ERC4626_SILO_REDEEM_REHYDRATION_DEFINITION"); const exact = present("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.erc4626-silo-redeem.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626-silo-redeem/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.erc4626-silo-redeem.effect-observation", version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626-silo-redeem/fact-schema/v1", "effects")) })]);
const actionOwner = Object.freeze({ ownerId: ERC4626_SILO_REDEEM_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626-silo-redeem/action-schema/v1", "redeem")), implementationHash: hashDomain("aloha/erc4626-silo-redeem/action-implementation/v1", "redeem"), actionKinds: Object.freeze(["redeem"]), modulePath: `${moduleRoot}/action.ts`, exportName: "ERC4626_SILO_REDEEM_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: ERC4626_SILO_REDEEM_FAMILY_ID, version: ERC4626_SILO_REDEEM_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/erc4626-silo-redeem/plugin-code/v1", { n, i, m, p, r, exact, actionOwner, facts }), authorityDeclarationHash: hashDomain("aloha/erc4626-silo-redeem/authority/v1", ERC4626_SILO_REDEEM_OWNER_REF), sourcePlans: [{ sourcePlanId: ERC4626_SILO_REDEEM_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: ERC4626_SILO_REDEEM_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "ERC4626_SILO_REDEEM_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/erc4626-silo-redeem/src/source-plan.ts", exportName: "ERC4626_SILO_REDEEM_SOURCE_NOMINATION_PROGRAM", schemaHash: ERC4626_SILO_REDEEM_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/erc4626-silo-redeem/src/nomination-qualification.ts", exportName: "ERC4626_SILO_REDEEM_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/erc4626-silo-redeem/src/nomination-qualification.ts", exportName: "ERC4626_SILO_REDEEM_NOMINATION_INDEPENDENT_ORACLE" } } } }, { sourcePlanId: ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_ID, completeness: "rolling-observation", historyStartBlock: null, schemaHash: ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/erc4626-silo-redeem/src/history-source-plan.ts", exportName: "ERC4626_SILO_REDEEM_HISTORY_NOMINATION_PROGRAM", schemaHash: ERC4626_SILO_REDEEM_HISTORY_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/erc4626-silo-redeem/src/nomination-qualification.ts", exportName: "ERC4626_SILO_REDEEM_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/erc4626-silo-redeem/src/nomination-qualification.ts", exportName: "ERC4626_SILO_REDEEM_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [ERC4626_SILO_REDEEM_CAPABILITY_IDS.state]: { kind: "absent", reason: "not-in-release" }, [ERC4626_SILO_REDEEM_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "not-in-release" }, [ERC4626_SILO_REDEEM_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "ERC4626_SILO_REDEEM_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { exact: asCapabilityId(ERC4626_SILO_REDEEM_CAPABILITY_IDS.exact) }, actionOwnerIds: { redeem: ERC4626_SILO_REDEEM_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const ERC4626_SILO_REDEEM_DEFINITION = defineFamily(input); export const ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(ERC4626_SILO_REDEEM_DEFINITION); export { ERC4626_SILO_REDEEM_FAMILY_DEFINITION_HASH, ERC4626_SILO_REDEEM_OWNER_REF };
