import { ERC4626_SILO_REDEEM_MANIFEST } from "./manifest.ts";
import { captureErc4626SiloRedeemEvidence } from "./capture.ts";
import { decodeErc4626SiloRedeemCandidate } from "./discovery.ts";
import { exactErc4626SiloRedeem } from "./exact.ts";
import { compileErc4626SiloRedeemExecution } from "./execution.ts";
import { verifyErc4626SiloRedeemIdentityStage } from "./identity.ts";
import { materializeErc4626SiloRedeem } from "./instance.ts";
import { nominateErc4626SiloRedeem } from "./nomination.ts";
import { coarseErc4626SiloRedeem } from "./pricing.ts";
import { deriveErc4626SiloRedeemRoutes } from "./routes.ts";
export const ERC4626_SILO_REDEEM_RUNTIME = Object.freeze({ manifest: ERC4626_SILO_REDEEM_MANIFEST, discover: decodeErc4626SiloRedeemCandidate, capture: captureErc4626SiloRedeemEvidence, nominate: nominateErc4626SiloRedeem, identity: verifyErc4626SiloRedeemIdentityStage, materialize: materializeErc4626SiloRedeem, routes: deriveErc4626SiloRedeemRoutes, coarse: coarseErc4626SiloRedeem, exact: exactErc4626SiloRedeem, execute: compileErc4626SiloRedeemExecution });
export const ERC4626_SILO_REDEEM_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateErc4626SiloRedeem });
export const ERC4626_SILO_REDEEM_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyErc4626SiloRedeemIdentityStage });
export const ERC4626_SILO_REDEEM_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeErc4626SiloRedeem });
export const ERC4626_SILO_REDEEM_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveErc4626SiloRedeemRoutes });
export const ERC4626_SILO_REDEEM_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveErc4626SiloRedeemRoutes });
export { ERC4626_SILO_REDEEM_SEARCH_RUNTIME_ADAPTER_FACTORY } from "./search-adapter.ts";
export { ERC4626_SILO_REDEEM_NOMINATION_DEFINITION, ERC4626_SILO_REDEEM_IDENTITY_DEFINITION, ERC4626_SILO_REDEEM_MATERIALIZATION_DEFINITION, ERC4626_SILO_REDEEM_PROJECTION_DEFINITION, ERC4626_SILO_REDEEM_REHYDRATION_DEFINITION, ERC4626_SILO_REDEEM_STAGE_DEFINITIONS, ERC4626_SILO_REDEEM_STAGE_IDS, requireErc4626SiloRedeemStageDefinition } from "./runtime/definitions.ts";
