import { assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { candidateSubjectHash, familyCandidateKey as discoveryFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchLegRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { ERC4626_SILO_REDEEM_FAMILY_ID } from "./manifest.ts";
import { materializeErc4626SiloRedeem } from "./instance.ts";
import { assertErc4626SiloRedeemRoute, deriveErc4626SiloRedeemRoutes } from "./routes.ts";
import { canonicalAddress, type Erc4626SiloRedeemIdentityV1, type Erc4626SiloRedeemRouteV1 } from "./types.ts";

type Source = ReturnType<typeof familySearchSource>;
type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: Source; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly amountHash: Hash; readonly identity: Erc4626SiloRedeemIdentityV1; readonly protocolRoute: Erc4626SiloRedeemRouteV1 };
type StateResponse = { readonly kind: "erc4626-silo-redeem-state-read-response"; readonly requestId: Hash; readonly source: Source; readonly routeBindingHash: Hash; readonly amountHash: Hash; readonly instanceKey: string; readonly previewReturnDataHex: string; readonly stateHash: Hash };

function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { return assertNonEmptyString(value, path); }
function bytes(value: unknown, path: string): string { const result = text(value, path); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result)) throw new TypeError(`${path} must be even-length hex bytes`); return result.toLowerCase(); }
function sameSource(left: Source, right: Source): boolean { return sameFamilySearchSource(left, right); }
function assetRef(chainId: string, value: string): Hash { return erc20AssetRefV1(chainId, value); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, `erc4626-silo-redeem-${reasonCode}`, canonical(evidence)); }
function word(value: bigint, path: string): string { if (value < 0n || value >= (1n << 256n)) throw new RangeError(`${path} is outside uint256`); return value.toString(16).padStart(64, "0"); }
function call(selector: string, words: readonly string[]): string { if (!/^0x[0-9a-fA-F]{8}$/.test(selector)) throw new TypeError("erc4626 silo selector is not canonical"); return `${selector}${words.join("")}`.toLowerCase(); }
function abiUint(value: string, path: string): string { const result = bytes(value, path); if (result.length !== 66) throw new TypeError(`${path} must be one ABI uint256 word`); return result; }

function decodeIdentity(value: unknown): Erc4626SiloRedeemIdentityV1 {
  const outer = record(value, "erc4626-silo-redeem.route.identityMemo"); assertExactKeys(outer, ["kind", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "candidateEvidenceRoot", "identity"], "erc4626-silo-redeem.identityMemo");
  if (outer.kind !== "erc4626-silo-redeem-identity-memo" || outer.familyId !== ERC4626_SILO_REDEEM_FAMILY_ID) throw new TypeError("erc4626 silo identity memo discriminator mismatch");
  const definitionHash = assertHash(outer.familyDefinitionHash, "erc4626-silo-redeem.identityMemo.familyDefinitionHash"); const nominationKey = canonicalAddress(text(outer.instanceNominationKey, "erc4626-silo-redeem.identityMemo.instanceNominationKey")); const subjectHash = assertHash(outer.candidateSnapshotHash, "erc4626-silo-redeem.identityMemo.candidateSnapshotHash"); assertHash(outer.candidateEvidenceRoot, "erc4626-silo-redeem.identityMemo.candidateEvidenceRoot");
  if (definitionHash !== ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH || assertHash(outer.familyCandidateKey, "erc4626-silo-redeem.identityMemo.familyCandidateKey") !== discoveryFamilyCandidateKey(definitionHash, nominationKey) || subjectHash !== candidateSubjectHash(definitionHash, nominationKey)) throw new TypeError("erc4626 silo identity memo family binding mismatch");
  const source = record(outer.identity, "erc4626-silo-redeem.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "erc4626-silo-redeem.identity"); const facts = record(source.facts, "erc4626-silo-redeem.identity.facts"); assertExactKeys(facts, ["vault", "payoutToken", "actor"], "erc4626-silo-redeem.identity.facts");
  const decodedFacts = Object.freeze({ vault: canonicalAddress(text(facts.vault, "erc4626-silo-redeem.identity.facts.vault")), payoutToken: canonicalAddress(text(facts.payoutToken, "erc4626-silo-redeem.identity.facts.payoutToken")), actor: canonicalAddress(text(facts.actor, "erc4626-silo-redeem.identity.facts.actor")) });
  const identity = Object.freeze({ cutoff: familySearchSource(source.cutoff, "erc4626-silo-redeem.identity.cutoff") as Erc4626SiloRedeemIdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "erc4626-silo-redeem.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "erc4626-silo-redeem.identity.instanceKey")), factsHash: assertHash(source.factsHash, "erc4626-silo-redeem.identity.factsHash"), facts: decodedFacts });
  if (identity.instanceKey !== identity.facts.vault || identity.factsHash !== hashDomain("aloha/erc4626-silo-redeem/identity-facts/v1", identity.facts)) throw new TypeError("erc4626 silo identity facts hash mismatch"); if (nominationKey !== identity.instanceKey || subjectHash !== identity.candidateSnapshotHash) throw new TypeError("erc4626 silo identity memo lineage mismatch"); return identity;
}
function context(input: FamilySearchLegRequestV1): Context { const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== ERC4626_SILO_REDEEM_FAMILY_ID || route.familyDefinitionHash !== ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH) throw new TypeError("erc4626 silo search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("erc4626 silo identity memo hash mismatch"); const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = decodeIdentity(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("erc4626 silo search instance binding mismatch"); const protocolRoute = deriveErc4626SiloRedeemRoutes(identity).find(item => assetRef(source.chainId, item.inputAsset) === amount.inputAssetRef && assetRef(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("erc4626 silo search amount assets do not match identity"); assertErc4626SiloRedeemRoute(protocolRoute, identity); canonicalAddress(amount.recipient); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, amountHash: familySearchAmountHash(amount), identity, protocolRoute }); }
function requestId(ctx: Context): Hash { return hashDomain("aloha/erc4626-silo-redeem/search-state-request/v2", { familyDefinitionHash: ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH, routeBindingHash: ctx.routeBindingHash, instanceKey: ctx.identity.instanceKey, amountHash: ctx.amountHash, source: ctx.source }); }
function readRequest(ctx: Context) { const id = requestId(ctx); return Object.freeze({ kind: "family-search.current-source-read" as const, requestId: id, source: ctx.source, target: ctx.identity.instanceKey, data: call("0x4cdad506", [word(BigInt(ctx.amount.amountIn), "erc4626 silo previewRedeem shares")]), responseEncoding: "abi-uint256" as const }); }
function stateResponse(ctx: Context, id: Hash, returnDataHex: string): StateResponse { const previewReturnDataHex = abiUint(returnDataHex, "erc4626 silo state.previewReturnDataHex"); return Object.freeze({ kind: "erc4626-silo-redeem-state-read-response", requestId: id, source: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, previewReturnDataHex, stateHash: hashDomain("aloha/erc4626-silo-redeem/search-state/v3", { cutoff: ctx.source, instanceKey: ctx.identity.instanceKey, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, previewReturnDataHex }) }); }
function decodeStateResponse(value: CanonicalJson, ctx: Context, id: Hash): StateResponse { const source = record(value, "erc4626 silo stateResponse"); assertExactKeys(source, ["kind", "requestId", "source", "routeBindingHash", "amountHash", "instanceKey", "previewReturnDataHex", "stateHash"], "erc4626 silo stateResponse"); if (source.kind !== "erc4626-silo-redeem-state-read-response" || assertHash(source.requestId, "erc4626 silo stateResponse.requestId") !== id) throw new TypeError("erc4626 silo state response request mismatch"); const responseSource = familySearchSource(source.source, "erc4626 silo stateResponse.source"); const routeBindingHash = assertHash(source.routeBindingHash, "erc4626 silo stateResponse.routeBindingHash"); const amountHash = assertHash(source.amountHash, "erc4626 silo stateResponse.amountHash"); const instanceKey = canonicalAddress(text(source.instanceKey, "erc4626 silo stateResponse.instanceKey")); const previewReturnDataHex = abiUint(text(source.previewReturnDataHex, "erc4626 silo stateResponse.previewReturnDataHex"), "erc4626 silo stateResponse.previewReturnDataHex"); const stateHash = assertHash(source.stateHash, "erc4626 silo stateResponse.stateHash"); if (!sameSource(responseSource, ctx.source) || routeBindingHash !== ctx.routeBindingHash || amountHash !== ctx.amountHash || instanceKey !== ctx.identity.instanceKey || stateHash !== hashDomain("aloha/erc4626-silo-redeem/search-state/v3", { cutoff: responseSource, instanceKey, routeBindingHash, amountHash, previewReturnDataHex })) throw new TypeError("erc4626 silo state response lineage mismatch"); return Object.freeze({ kind: "erc4626-silo-redeem-state-read-response", requestId: id, source: responseSource, routeBindingHash, amountHash, instanceKey, previewReturnDataHex, stateHash }); }
function stateArtifact(ctx: Context, response: StateResponse): FamilySearchStateArtifactV1 { const factsHash = hashDomain("aloha/erc4626-silo-redeem/state-read/v1", { cutoff: response.source, instanceKey: response.instanceKey, amountHash: ctx.amountHash, previewReturnDataHex: response.previewReturnDataHex }); const materialized = materializeErc4626SiloRedeem({ identity: ctx.identity, read: { cutoff: response.source as Erc4626SiloRedeemIdentityV1["cutoff"], instanceKey: response.instanceKey, factsHash } }); if (materialized.status !== "verified") throw new TypeError(`erc4626 silo state ${materialized.reasonCode}`); const payload = canonical(response); const payloadHash = familySearchPayloadHash("state", payload); return Object.freeze({ kind: "state", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot: hashDomain("aloha/erc4626-silo-redeem/state-facts/v1", { factsHash, stateHash: materialized.state.stateHash, previewReturnDataHex: response.previewReturnDataHex }), sourceRequestId: response.requestId }); }
function assertState(ctx: Context, artifact: FamilySearchStateArtifactV1): StateResponse { if (artifact.kind !== "state" || artifact.status !== "verified" || !sameSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("erc4626 silo state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("erc4626 silo state artifact hash mismatch"); const response = decodeStateResponse(payload, ctx, artifact.sourceRequestId); const factsHash = hashDomain("aloha/erc4626-silo-redeem/state-read/v1", { cutoff: response.source, instanceKey: response.instanceKey, amountHash: ctx.amountHash, previewReturnDataHex: response.previewReturnDataHex }); const materialized = materializeErc4626SiloRedeem({ identity: ctx.identity, read: { cutoff: response.source as Erc4626SiloRedeemIdentityV1["cutoff"], instanceKey: response.instanceKey, factsHash } }); if (materialized.status !== "verified" || artifact.factsRoot !== hashDomain("aloha/erc4626-silo-redeem/state-facts/v1", { factsHash, stateHash: materialized.state.stateHash, previewReturnDataHex: response.previewReturnDataHex })) throw new TypeError("erc4626 silo state facts root mismatch"); return response; }
const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== ERC4626_SILO_REDEEM_FAMILY_AUTHORING_HASH) throw new TypeError("erc4626 silo search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); const physical = readRequest(ctx); let raw: FamilySearchSourceReadResultV1; try { raw = await request.readPort.read({ request: physical, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: physical.requestId, error: String(error) }); } if (raw.kind !== "returned") return unavailable("state", raw.reasonCode || "source-read-unavailable", raw); if (raw.requestId !== physical.requestId || !sameSource(raw.source, physical.source)) throw new TypeError("erc4626 silo source response binding mismatch"); try { const response = stateResponse(ctx, physical.requestId, raw.dataHex); return Object.freeze({ kind: "verified" as const, artifact: stateArtifact(ctx, response) }); } catch (error) { return unavailable("state", "malformed-abi-return", { requestId: physical.requestId, dataHex: raw.dataHex, error: String(error) }); } } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); assertState(ctx, request.state); return unavailable("coarse", "coarse-capability-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash }); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); assertState(ctx, request.state); return unavailable("exact", "effect-observation-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, stateFactsRoot: request.state.factsRoot, required: "qualified-effect-observation-or-simulation" }); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "effect-observation-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, required: "qualified-effect-observation-or-simulation" }); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async request => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const ERC4626_SILO_REDEEM_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
