import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
export interface Erc4626SiloRedeemCutoffV1 { readonly chainId: string; readonly number: string; readonly hash: Hash; readonly stateRoot: Hash; }
export interface Erc4626SiloRedeemObservationV1 { readonly kind: "log" | "call" | "address-surface"; readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly target: string; readonly rawLocatorHash: Hash; readonly topic?: Hash | null; }
export interface Erc4626SiloRedeemCandidateV1 { readonly target: string; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly evidence: Erc4626SiloRedeemObservationV1; }
export interface Erc4626SiloRedeemIdentityReadFactsV1 { readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly target: string; readonly reverseTarget: string; readonly vault: string; readonly payoutToken: string; readonly actor: string; }
export interface Erc4626SiloRedeemIdentityV1 { readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: { readonly vault: string; readonly payoutToken: string; readonly actor: string; }; }
export interface Erc4626SiloRedeemStateReadFactsV1 { readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly instanceKey: string; readonly factsHash: Hash; }
export interface Erc4626SiloRedeemMaterializedStateV1 extends Erc4626SiloRedeemStateReadFactsV1 { readonly identityFactsHash: Hash; readonly stateHash: Hash; }
export interface Erc4626SiloRedeemRouteV1 { readonly instanceKey: string; readonly inputAsset: string; readonly outputAsset: string; readonly routeBindingHash: Hash; }
export interface Erc4626SiloRedeemQuoteV1 { readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly routeBindingHash: Hash; readonly amountIn: string; readonly amountOut: string; readonly quoteHash: Hash; }
export interface Erc4626SiloRedeemActionV1 { readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly target: string; readonly calldata: string; readonly exactQuoteHash: Hash; readonly actionHash: Hash; }
export interface Erc4626SiloRedeemExecutionIntentV1 { readonly kind: "erc4626-silo-redeem-execution-intent"; readonly cutoff: Erc4626SiloRedeemCutoffV1; readonly target: string; readonly calldata: string; readonly actionHash: Hash; readonly exactQuoteHash: Hash; }
export function canonicalAddress(value: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(value)) throw new TypeError("erc4626 silo address must be 20 bytes"); return `0x${value.slice(2).toLowerCase()}`; }
export function assertCutoff(value: Erc4626SiloRedeemCutoffV1): Erc4626SiloRedeemCutoffV1 { if (!/^\d+$/.test(value.chainId) || !/^\d+$/.test(value.number) || !/^0x[0-9a-f]{64}$/.test(value.hash) || !/^0x[0-9a-f]{64}$/.test(value.stateRoot)) throw new TypeError("erc4626 silo cutoff is not canonical"); return Object.freeze({ ...value }); }
export function cutoffEqual(left: Erc4626SiloRedeemCutoffV1, right: Erc4626SiloRedeemCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
export function familyCandidateKey(instanceNominationKey: string): Hash { return hashDomain("aloha/family-candidate/v1", { family: "erc4626-silo-redeem", instanceNominationKey }); }
