import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { GOLDX_ACTION_OWNER_ID, GOLDX_CAPABILITY_IDS, GOLDX_FAMILY_ID, GOLDX_FAMILY_VERSION, GOLDX_OWNER_REF, GOLDX_SOURCE_PLAN_ID, GOLDX_SOURCE_PLAN_SCHEMA_HASH, GOLDX_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(GOLDX_FAMILY_VERSION); const moduleRoot = "families/goldx/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${GOLDX_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/goldx/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([GOLDX_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(GOLDX_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/goldx/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/goldx/extension-interpreter/v1", name), dependencyIds: Object.freeze(name === "state" ? [] : [asCapabilityId(GOLDX_CAPABILITY_IDS.state)]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "GOLDX_RUNTIME" }); }
const n = core("nomination", "GOLDX_NOMINATION_DEFINITION"); const i = core("identity", "GOLDX_IDENTITY_DEFINITION"); const m = core("materialization", "GOLDX_MATERIALIZATION_DEFINITION"); const p = core("projection", "GOLDX_PROJECTION_DEFINITION"); const r = core("rehydration", "GOLDX_REHYDRATION_DEFINITION"); const state = present("state"); const coarse = present("coarse"); const exact = present("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.goldx.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/goldx/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.goldx.unit-wad-state", version, schemaHash: asSchemaRef(hashDomain("aloha/goldx/fact-schema/v1", "state")) })]);
const actionOwner = Object.freeze({ ownerId: GOLDX_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/goldx/action-schema/v1", "swap")), implementationHash: hashDomain("aloha/goldx/action-implementation/v1", "swap"), actionKinds: Object.freeze(["swap"]), modulePath: `${moduleRoot}/action.ts`, exportName: "GOLDX_SWAP_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: GOLDX_FAMILY_ID, version: GOLDX_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/goldx/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, actionOwner, facts }), authorityDeclarationHash: hashDomain("aloha/goldx/authority/v1", GOLDX_OWNER_REF), sourcePlans: [{ sourcePlanId: GOLDX_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: GOLDX_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "GOLDX_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/goldx/src/source-plan.ts", exportName: "GOLDX_SOURCE_NOMINATION_PROGRAM", schemaHash: GOLDX_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/goldx/src/nomination-qualification.ts", exportName: "GOLDX_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/goldx/src/nomination-qualification.ts", exportName: "GOLDX_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [GOLDX_CAPABILITY_IDS.state]: { kind: "present", module: state }, [GOLDX_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [GOLDX_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "GOLDX_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(GOLDX_CAPABILITY_IDS.state), coarse: asCapabilityId(GOLDX_CAPABILITY_IDS.coarse), exact: asCapabilityId(GOLDX_CAPABILITY_IDS.exact) }, actionOwnerIds: { swap: GOLDX_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const GOLDX_DEFINITION = defineFamily(input); export const GOLDX_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(GOLDX_DEFINITION); export { GOLDX_FAMILY_DEFINITION_HASH, GOLDX_OWNER_REF };
