import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ERC4626_ACTION_OWNER_ID, ERC4626_CAPABILITY_IDS, ERC4626_FAMILY_DEFINITION_HASH, ERC4626_FAMILY_ID, ERC4626_FAMILY_VERSION, ERC4626_HISTORY_SOURCE_PLAN_ID, ERC4626_HISTORY_SOURCE_PLAN_SCHEMA_HASH, ERC4626_OWNER_REF, ERC4626_SOURCE_PLAN_ID, ERC4626_SOURCE_PLAN_SCHEMA_HASH } from "./manifest.ts";
const version = asCapabilityVersion(ERC4626_FAMILY_VERSION); const moduleRoot = "families/erc4626/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${ERC4626_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/erc4626/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([ERC4626_SOURCE_PLAN_ID, ERC4626_HISTORY_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "coarse"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(ERC4626_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/erc4626/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "ERC4626_RUNTIME" }); }
const n = core("nomination", "ERC4626_NOMINATION_DEFINITION"); const i = core("identity", "ERC4626_IDENTITY_DEFINITION"); const m = core("materialization", "ERC4626_MATERIALIZATION_DEFINITION"); const p = core("projection", "ERC4626_PROJECTION_DEFINITION"); const r = core("rehydration", "ERC4626_REHYDRATION_DEFINITION"); const coarse = present("coarse");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.erc4626.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.erc4626.rounding-observation", version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626/fact-schema/v1", "rounding")) })]);
const actionOwner = Object.freeze({ ownerId: ERC4626_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/erc4626/action-schema/v1", "vault")), implementationHash: hashDomain("aloha/erc4626/action-implementation/v1", "vault"), actionKinds: Object.freeze(["vault-call"]), modulePath: `${moduleRoot}/action.ts`, exportName: "ERC4626_VAULT_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: ERC4626_FAMILY_ID, version: ERC4626_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/erc4626/plugin-code/v1", { n, i, m, p, r, coarse, actionOwner, facts }), authorityDeclarationHash: hashDomain("aloha/erc4626/authority/v1", ERC4626_OWNER_REF), sourcePlans: [{ sourcePlanId: ERC4626_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: ERC4626_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "ERC4626_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/erc4626/src/source-plan.ts", exportName: "ERC4626_SOURCE_NOMINATION_PROGRAM", schemaHash: ERC4626_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/erc4626/src/nomination-qualification.ts", exportName: "ERC4626_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/erc4626/src/nomination-qualification.ts", exportName: "ERC4626_NOMINATION_INDEPENDENT_ORACLE" } } } }, { sourcePlanId: ERC4626_HISTORY_SOURCE_PLAN_ID, completeness: "contiguous-history", historyStartBlock: "0", schemaHash: ERC4626_HISTORY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "ERC4626_HISTORY_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/erc4626/src/history-source-plan.ts", exportName: "ERC4626_HISTORY_NOMINATION_PROGRAM", schemaHash: ERC4626_HISTORY_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/erc4626/src/nomination-qualification.ts", exportName: "ERC4626_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/erc4626/src/nomination-qualification.ts", exportName: "ERC4626_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [ERC4626_CAPABILITY_IDS.state]: { kind: "absent", reason: "requires-future-extension" }, [ERC4626_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [ERC4626_CAPABILITY_IDS.exact]: { kind: "absent", reason: "requires-future-extension" } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "ERC4626_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { coarse: asCapabilityId(ERC4626_CAPABILITY_IDS.coarse) }, actionOwnerIds: { vault: ERC4626_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const ERC4626_DEFINITION = defineFamily(input); export const ERC4626_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(ERC4626_DEFINITION); export { ERC4626_OWNER_REF };
