import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { asSchemaRef } from "../../../packages/capability-contracts/src/index.ts";
export const ERC4626_FAMILY_ID = "erc4626" as const;
export const ERC4626_FAMILY_VERSION = "1.0.0" as const;
export const ERC4626_SOURCE_WINDOW_BLOCKS = 50 as const;
export const ERC4626_SOURCE_PLAN_ID = "erc4626.fixed-cutoff-50-block" as const;
export const ERC4626_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/erc4626/source-plan-schema/v1", ERC4626_SOURCE_PLAN_ID));
export const ERC4626_HISTORY_SOURCE_PLAN_ID = "erc4626.withdraw-rolling-observation" as const;
export const ERC4626_HISTORY_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/erc4626/history-source-plan-schema/v1", ERC4626_HISTORY_SOURCE_PLAN_ID));
export const ERC4626_WITHDRAW_TOPIC = "0xfbde797d201c681b91056529119e0b02407c7bb96a4a2c75c01fc9667232c8db" as const;
export const ERC4626_CAPABILITY_IDS = Object.freeze({ state: "family.erc4626.state", coarse: "family.erc4626.coarse", exact: "family.erc4626.exact" } as const);
export const ERC4626_ACTION_OWNER_ID = "family.erc4626.vault-action" as const;
export const ERC4626_MANIFEST = Object.freeze({ familyId: ERC4626_FAMILY_ID, version: ERC4626_FAMILY_VERSION, domain: "protocol" as const, sourcePlans: Object.freeze([{ id: ERC4626_SOURCE_PLAN_ID, windowBlocks: ERC4626_SOURCE_WINDOW_BLOCKS, evidenceChannel: "nominate" as const }, { id: ERC4626_HISTORY_SOURCE_PLAN_ID, historyStartBlock: null, evidenceChannel: "complete-denominator" as const }]), core: Object.freeze(["nomination", "identity", "materialization", "projection", "rehydration"] as const), extensions: Object.freeze(["state", "coarse", "exact"] as const), actionOwners: Object.freeze([ERC4626_ACTION_OWNER_ID]) });
export const ERC4626_FAMILY_DEFINITION_HASH: Hash = hashDomain("aloha/erc4626/family-definition/v1", ERC4626_MANIFEST);
export const ERC4626_OWNER_REF: Hash = hashDomain("aloha/erc4626/owner/v1", { familyId: ERC4626_FAMILY_ID, version: ERC4626_FAMILY_VERSION });
