import { assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { candidateSubjectHash, familyCandidateKey as discoveryFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchObjective, familySearchRouteBindingHash, familySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { ERC4626_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { ERC4626_FAMILY_ID } from "./manifest.ts";
import { assertErc4626Route, deriveErc4626Routes } from "./routes.ts";
import { canonicalAddress, type Erc4626IdentityV1 } from "./types.ts";

type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: ReturnType<typeof familySearchSource>; readonly amountHash: Hash; readonly identity: Erc4626IdentityV1 };
function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { if (typeof value !== "string" || value.length === 0) throw new TypeError(`${path} must be a non-empty string`); return value; }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, `erc4626-${reasonCode}`, canonical(evidence)); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function decodeIdentity(value: unknown): Erc4626IdentityV1 { const outer = record(value, "erc4626.route.identityMemo"); assertExactKeys(outer, ["kind", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "candidateEvidenceRoot", "identity"], "erc4626.identityMemo"); if (outer.kind !== "erc4626-identity-memo" || outer.familyId !== ERC4626_FAMILY_ID) throw new TypeError("erc4626 identity memo discriminator mismatch"); const definitionHash = assertHash(outer.familyDefinitionHash, "erc4626.identityMemo.familyDefinitionHash"); const nominationKey = canonicalAddress(text(outer.instanceNominationKey, "erc4626.identityMemo.instanceNominationKey")); const subjectHash = assertHash(outer.candidateSnapshotHash, "erc4626.identityMemo.candidateSnapshotHash"); assertHash(outer.candidateEvidenceRoot, "erc4626.identityMemo.candidateEvidenceRoot"); if (definitionHash !== ERC4626_FAMILY_AUTHORING_HASH || assertHash(outer.familyCandidateKey, "erc4626.identityMemo.familyCandidateKey") !== discoveryFamilyCandidateKey(definitionHash, nominationKey) || subjectHash !== candidateSubjectHash(definitionHash, nominationKey)) throw new TypeError("erc4626 identity memo family binding mismatch"); const source = record(outer.identity, "erc4626.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "erc4626.identity"); const facts = record(source.facts, "erc4626.identity.facts"); assertExactKeys(facts, ["target", "asset"], "erc4626.identity.facts"); const decodedFacts = Object.freeze({ target: canonicalAddress(text(facts.target, "erc4626.identity.facts.target")), asset: canonicalAddress(text(facts.asset, "erc4626.identity.facts.asset")) }); const identity = Object.freeze({ cutoff: familySearchSource(source.cutoff, "erc4626.identity.cutoff") as Erc4626IdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "erc4626.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "erc4626.identity.instanceKey")), factsHash: assertHash(source.factsHash, "erc4626.identity.factsHash"), facts: decodedFacts }); if (identity.instanceKey !== identity.facts.target || identity.factsHash !== hashDomain("aloha/erc4626/identity-facts/v1", identity.facts)) throw new TypeError("erc4626 identity facts hash mismatch"); if (nominationKey !== identity.instanceKey || subjectHash !== identity.candidateSnapshotHash) throw new TypeError("erc4626 identity memo lineage mismatch"); return identity; }
function context(input: FamilySearchLegRequestV1): Context { const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== ERC4626_FAMILY_ID || route.familyDefinitionHash !== ERC4626_FAMILY_AUTHORING_HASH) throw new TypeError("erc4626 search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("erc4626 identity memo hash mismatch"); const source = familySearchSource(input.currentSource.source); familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = decodeIdentity(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("erc4626 search instance binding mismatch"); const protocolRoute = deriveErc4626Routes(identity).find(item => erc20AssetRefV1(source.chainId, item.inputAsset) === amount.inputAssetRef && erc20AssetRefV1(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("erc4626 search amount assets do not match identity"); assertErc4626Route(protocolRoute, identity); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, amountHash: familySearchAmountHash(amount), identity }); }
function evidence(ctx: Context, stage: string): CanonicalJson { return canonical({ stage, familyDefinitionHash: ERC4626_FAMILY_AUTHORING_HASH, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, source: ctx.source }); }
const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== ERC4626_FAMILY_AUTHORING_HASH) throw new TypeError("erc4626 search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); return unavailable("state", "state-capability-not-in-release", evidence(ctx, "state")); } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); return unavailable("coarse", "state-prerequisite-not-in-release", evidence(ctx, "coarse")); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); return unavailable("exact", "exact-capability-not-in-release", evidence(ctx, "exact")); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "exact-prerequisite-not-verified", evidence(ctx, "action")); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async (request: FamilySearchRunRequestV1) => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const ERC4626_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
