import { lstatSync, readFileSync, realpathSync } from "node:fs";
import { join, resolve } from "node:path";
import { deepFreeze, gitSha40Schema, sha256Hex, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import {
  observeCleanGitCheckoutV1,
  observeExactPushedGitV1,
  withExactCommitTreeV1,
  type GitReleaseEvidenceV1,
} from "./git-release-evidence.ts";
import {
  buildQualifiedReleaseRunnerBundleV1,
  buildProductionRuntimeBundleV1,
  loadProductionLauncherArtifactV1,
} from "./internal/runtime-bundle-builder.ts";
import {
  buildExactPreReleaseRestartControllerArtifactV1,
  type ExactPreReleaseRestartControllerArtifactV1,
} from "../../pre-release-restart-controller/src/bundle-builder.ts";

function regularCanonicalPath(path: string, label: string): string {
  const absolute = resolve(path);
  if (absolute !== path || realpathSync(path) !== path || !lstatSync(path).isFile()) {
    throw new TypeError(`${label} is not a canonical regular file`);
  }
  return path;
}

interface ExactProductionRuntimeArtifactsV1 {
  readonly entrypointBytes: Uint8Array;
  readonly bundleBytes: Uint8Array;
  readonly catalogGenerationInputBytes: Uint8Array;
  readonly familyCatalogSourceBytes: Uint8Array;
  readonly runtimeCompositionSourceBytes: Uint8Array;
  readonly strategyCatalogSourceBytes: Uint8Array;
}

function buildExactProductionRuntimeArtifactsV1(
  repositoryRoot: string,
  git: GitReleaseEvidenceV1,
): ExactProductionRuntimeArtifactsV1 {
  return withExactCommitTreeV1(repositoryRoot, git.commit, snapshotRoot => {
    const launcher = loadProductionLauncherArtifactV1(snapshotRoot);
    const bundle = buildProductionRuntimeBundleV1(snapshotRoot);
    const read = (path: string, label: string): Uint8Array => new Uint8Array(readFileSync(
      regularCanonicalPath(join(snapshotRoot, path), label),
    ));
    return Object.freeze({
      entrypointBytes: launcher.bytes,
      bundleBytes: bundle.bytes,
      catalogGenerationInputBytes: read("generated/catalog-generation.inputs.json", "generated catalog input"),
      familyCatalogSourceBytes: read("generated/family-catalog/index.ts", "generated family catalog source"),
      runtimeCompositionSourceBytes: read("generated/runtime-composition/index.ts", "generated runtime composition source"),
      strategyCatalogSourceBytes: read("generated/strategy-catalog/index.ts", "generated strategy catalog source"),
    });
  });
}

export interface ExactPreReleaseStagingRuntimeArtifactsV1 {
  readonly candidateReleaseCommit: string;
  readonly launcherBytes: Uint8Array;
  readonly productionLauncherBytes: Uint8Array;
  readonly bundleBytes: Uint8Array;
  readonly catalogGenerationInputBytes: Uint8Array;
  readonly familyCatalogSourceBytes: Uint8Array;
  readonly runtimeCompositionSourceBytes: Uint8Array;
  readonly strategyCatalogSourceBytes: Uint8Array;
  readonly restartController: ExactPreReleaseRestartControllerArtifactV1;
}

/** Controller-only exact-commit source for every executable/generated byte
 * needed by the pre-release runtime. */
export function buildExactPreReleaseStagingRuntimeArtifactsV1(
  repositoryRootValue: string,
  expectedCommitValue: string,
): ExactPreReleaseStagingRuntimeArtifactsV1 {
  const repositoryRoot = realpathSync(resolve(repositoryRootValue));
  const expectedCommit = gitSha40Schema.decode(expectedCommitValue);
  const git = observeExactPushedGitV1(repositoryRoot);
  if (git.commit !== expectedCommit) throw new TypeError("pre-release staging source does not equal the Boundary candidate commit");
  const restartController = buildExactPreReleaseRestartControllerArtifactV1(repositoryRoot, expectedCommit);
  return withExactCommitTreeV1(repositoryRoot, expectedCommit, snapshotRoot => {
    const bundle = buildProductionRuntimeBundleV1(snapshotRoot);
    const read = (path: string, label: string): Uint8Array => new Uint8Array(readFileSync(
      regularCanonicalPath(join(snapshotRoot, path), label),
    ));
    const launcherBytes = new Uint8Array(readFileSync(regularCanonicalPath(
      join(snapshotRoot, "tools/runtime-release-packager/assets/pre-release-owner.mjs"),
      "pre-release owner launcher",
    )));
    const productionLauncherBytes = new Uint8Array(readFileSync(regularCanonicalPath(
      join(snapshotRoot, "tools/runtime-release-packager/assets/production-launcher.mjs"),
      "production launcher",
    )));
    return deepFreeze({
      candidateReleaseCommit: expectedCommit,
      launcherBytes,
      productionLauncherBytes,
      bundleBytes: bundle.bytes,
      catalogGenerationInputBytes: read("generated/catalog-generation.inputs.json", "generated catalog input"),
      familyCatalogSourceBytes: read("generated/family-catalog/index.ts", "generated family catalog source"),
      runtimeCompositionSourceBytes: read("generated/runtime-composition/index.ts", "generated runtime composition source"),
      strategyCatalogSourceBytes: read("generated/strategy-catalog/index.ts", "generated strategy catalog source"),
      restartController,
    });
  });
}

export interface ProductionRuntimeArtifactObservationV1 extends GitReleaseEvidenceV1 {
  readonly entrypointSha256: Hash;
  readonly bundleModuleSha256: Hash;
}

export function observeExactProductionRuntimeArtifactsV1(repositoryRootValue: string): ProductionRuntimeArtifactObservationV1 {
  const repositoryRoot = realpathSync(resolve(repositoryRootValue));
  const git = observeExactPushedGitV1(repositoryRoot);
  const artifacts = buildExactProductionRuntimeArtifactsV1(repositoryRoot, git);
  return deepFreeze({
    ...git,
    entrypointSha256: sha256Hex(artifacts.entrypointBytes),
    bundleModuleSha256: sha256Hex(artifacts.bundleBytes),
  });
}

export interface ExactQualifiedReleaseRunnerBundleV1 {
  readonly candidateReleaseCommit: string;
  readonly bytes: Uint8Array;
  readonly sha256: Hash;
}

export function buildExactQualifiedReleaseRunnerBundleV1(
  repositoryRootValue: string,
  expectedCommitValue: string,
): ExactQualifiedReleaseRunnerBundleV1 {
  const repositoryRoot = realpathSync(resolve(repositoryRootValue));
  const expectedCommit = gitSha40Schema.decode(expectedCommitValue);
  const checkout = observeCleanGitCheckoutV1(repositoryRoot);
  if (checkout.commit !== expectedCommit) throw new TypeError("qualified release runner checkout does not equal the Boundary candidate commit");
  const git = observeExactPushedGitV1(repositoryRoot);
  if (git.commit !== expectedCommit) throw new TypeError("qualified release runner checkout does not equal the Boundary candidate commit");
  return withExactCommitTreeV1(repositoryRoot, expectedCommit, snapshotRoot => {
    const bundle = buildQualifiedReleaseRunnerBundleV1(snapshotRoot);
    return Object.freeze({ candidateReleaseCommit: expectedCommit, bytes: bundle.bytes, sha256: bundle.sha256 });
  });
}
