import { hashDomain } from "../../../packages/canonical-codec/src/index.ts";
import { entryIdFor, type AdoptionMode, type DestinationDeclarationV2, type ReuseDeclarationV2, type SourceSymbolDeclarationV2 } from "./index.ts";

const s = (name: string, startLine: number, endLine: number): SourceSymbolDeclarationV2 => Object.freeze({ name, startLine, endLine });
const d = (modulePath: string, ...exportNames: string[]): DestinationDeclarationV2 => Object.freeze({ modulePath, exportNames: Object.freeze(exportNames) });
const evidence = (requirementExportName: string, testModulePath: string, testCaseName: string) => Object.freeze({ requirementExportName, testModulePath, testCaseName });
const row = (sourcePath: string, sourceBlob: string, sourceSymbols: readonly SourceSymbolDeclarationV2[], adoptionMode: AdoptionMode, destinations: readonly DestinationDeclarationV2[], requirementExportName: string, testModulePath: string, testCaseName: string): ReuseDeclarationV2 => Object.freeze({
  entryId: entryIdFor(sourcePath, sourceSymbols.map(symbol => symbol.name)), sourcePath, sourceBlob, sourceSymbols: Object.freeze(sourceSymbols), adoptionMode,
  creditStatus: "credited", nonCreditReason: null, destinations: Object.freeze(destinations), evidence: evidence(requirementExportName, testModulePath, testCaseName),
});

const R2 = "invariant-only-rewrite" as const;

export const CURRENT_REUSE_DECLARATIONS: readonly ReuseDeclarationV2[] = Object.freeze([
  row("listener/src/searcher/solver/curve-math.ts", "27cf1109ad546e23b33db33342d73f292064f343", [s("getD",36,52),s("curvePlainGetDy",86,99),s("curveNgGetDy",182,197)], R2, [d("families/curve-underlying/src/kernel/math.ts","getD","curvePlainGetDy","curveNgGetDy")], "CURVE_MATH_EVIDENCE", "families/curve-underlying/test/kernel.test.ts", "balanced invariant equals the independent N*x identity"),
  row("listener/src/searcher/solver/v2-constant-product-math.ts", "61e49626a24f9809cee4ef5b08aacba76c5cc2f3", [s("quoteV2ExactInput",4,14)], R2, [d("families/univ2-standard/src/kernel/math.ts","quoteV2ExactInput")], "UNIV2_MATH_EVIDENCE", "families/univ2-standard/test/kernel.test.ts", "constant-product quote matches the independent invariant oracle"),
  row("listener/src/searcher/solver/v3-math.ts", "8389fc16cc573e598c14a96bbd5df588dcc86640", [s("mulDiv",18,20),s("mulDivRoundingUp",22,25),s("getAmount0Delta",33,45),s("getAmount1Delta",48,58),s("getNextSqrtPriceFromInput",96,105),s("getNextSqrtPriceFromOutput",107,116),s("computeSwapStep",126,179),s("getSqrtRatioAtTick",190,219),s("nextInitializedTickWithinOneWord",263,292),s("v3SwapToState",321,373),s("v3SwapExactInput",380,382)], R2, [d("families/univ3-standard/src/kernel/math.ts","mulDiv","mulDivRoundingUp","getAmount0Delta","getAmount1Delta","getNextSqrtPriceFromInput","getNextSqrtPriceFromOutput","computeSwapStep","getSqrtRatioAtTick","nextInitializedTickWithinOneWord","v3SwapToState","v3SwapExactInput")], "UNIV3_MATH_EVIDENCE", "families/univ3-standard/test/kernel.test.ts", "tick and delta arithmetic matches independent boundary identities"),
  row("listener/src/searcher/venues/protocols/astra-multitoken-family/codec.ts", "7caf60f751561b7e5f13426f5e8e095e0570b46e", [s("canonicalAddress",32,34),s("lowerAddress",36,38),s("sameAddress",40,42),s("successfulResult",44,58),s("returnedResult",60,69),s("decodeOptionalBoolean",71,82),s("decodeOptionalUint",84,95),s("decodeUint",97,114),s("decodeToken",116,126),s("assertSameSource",128,144),s("assertSource",146,157),s("assertTokenSet",159,171),s("tokenPairKey",173,175)], R2, [d("families/astra-multitoken/src/abi.ts","decodeAstraUint256")], "ASTRA_CODEC_EVIDENCE", "families/astra-multitoken/test/plugin.test.ts", "Astra exact verification binds deltas to the observed caller and real Change topic"),
  row("listener/src/searcher/venues/protocols/astra-multitoken-family/identity.ts", "0ff3cd86b13748d41d2435707c19225e6ba4e061", [s("astraMultiTokenIdentity",55,114)], R2, [d("families/astra-multitoken/src/identity.ts","verifyAstraIdentity"),d("families/astra-multitoken/kernel/effects.ts","astraEffectProgram","validateAstraExchange")], "ASTRA_IDENTITY_EVIDENCE", "families/astra-multitoken/test/effects.test.ts", "Astra owns four exact pairs and rejects aggregate or scope mutation"),
  row("listener/src/searcher/venues/protocols/astra-multitoken-family/pricing.ts", "8854df4cc677e2eed1a5dfa7ff250ac5c9218470", [s("astraMultiTokenPricing",35,174)], R2, [d("families/astra-multitoken/src/pricing.ts","quoteAstra","conservativeAstraUpperBound")], "ASTRA_PRICING_EVIDENCE", "families/astra-multitoken/test/plugin.test.ts", "Astra exact verification binds deltas to the observed caller and real Change topic"),
  row("listener/src/searcher/venues/protocols/eigenpie-family/codec.ts", "360ddc59e6706cacdd340b17c36baf5156b1ae02", [s("decodeEigenpieQuote",19,31)], R2, [d("families/eigenpie/kernel/codec.ts","decodeEigenpieQuote")], "EIGENPIE_CODEC_EVIDENCE", "families/eigenpie/test/codec.test.ts", "Eigenpie decodes exact canonical ABI words"),
  row("listener/src/searcher/venues/protocols/eigenpie-family/identity.ts", "9172f0dd0407108a7581f83b2b67cd2374b1b917", [s("eigenpieIdentity",37,232)], R2, [d("families/eigenpie/src/identity.ts","verifyEigenpieIdentityStage","identityDescriptorHash")], "EIGENPIE_IDENTITY_EVIDENCE", "families/eigenpie/test/plugin.test.ts", "Eigenpie nomination is bounded and identity reverse binding is fail-closed"),
  row("listener/src/searcher/venues/protocols/erc4626-family/identity.ts", "32c2165f10b9308aa9b29705e708951b056cea27", [s("erc4626Identity",45,152),s("tolerance",154,156)], R2, [d("families/erc4626/kernel/tolerance.ts","erc4626RoundingTolerance","withinErc4626UpperRoundingBound")], "ERC4626_TOLERANCE_EVIDENCE", "families/erc4626/test/tolerance.test.ts", "ERC4626 bound accepts exact edge and rejects one-unit mutation"),
  row("listener/src/searcher/venues/protocols/erc4626-silo-redeem-family/shared.ts", "01bcb23c3b87a669ed948824918eb99f5d99ef5e", [s("erc4626SiloStaticProjection",40,49),s("erc4626SiloRedeemSimulation",73,109),s("validateErc4626SiloRedeemEffects",111,145)], R2, [d("families/erc4626-silo-redeem/kernel/effects.ts","validateErc4626SiloRedeem")], "ERC4626_SILO_EFFECTS_EVIDENCE", "families/erc4626-silo-redeem/test/effects.test.ts", "Silo binds returned amount, exact observation scope, share burn and payout"),
  row("listener/src/searcher/venues/protocols/ethertoken-native-redeem-family/shared.ts", "818eb8c6198554f6f4061eb8fa3f6ebfec522915", [s("etherTokenNativeStaticProjection",32,42),s("assertEtherTokenNativeInvocation",44,67),s("etherTokenWithdrawalSimulation",69,104),s("validateEtherTokenWithdrawal",106,135)], R2, [d("families/ethertoken-native-redeem/kernel/effects.ts","validateEtherTokenNativeRedeem")], "ETHERTOKEN_EFFECTS_EVIDENCE", "families/ethertoken-native-redeem/test/effects.test.ts", "EtherToken requires empty return bytes and exact native redemption scope"),
  row("listener/src/searcher/venues/protocols/goldx-family/codec.ts", "8a83a1ff60ba425b7e588c89defc4db89da6c73b", [s("goldxQuote",11,15)], R2, [d("families/goldx/kernel/quote.ts","goldxQuote")], "GOLDX_QUOTE_EVIDENCE", "families/goldx/test/quote.test.ts", "GOLDx quote floors multiplication by its positive unit"),
  row("listener/src/searcher/venues/protocols/metronome-hgusdc-family/shared.ts", "43fcd6d0c1f88d5841a1d5ded129ed9116551888", [s("metronomeHgUsdcStaticProjection",33,47),s("assertMetronomeHgUsdcInvocation",49,71)], R2, [d("families/metronome-hgusdc/kernel/projection.ts","metronomeHgUsdcProjection")], "METRONOME_HGUSDC_EVIDENCE", "families/metronome-hgusdc/test/projection.test.ts", "hgUSDC projection fixes ordered quote chain"),
  row("listener/src/searcher/venues/protocols/metronome-synth-family/shared.ts", "fff8db5ba84426cd0feaca357e71ea5ad656f8a7", [s("metronomeSynthDirectionsProjection",39,48),s("metronomeSynthStaticProjection",50,60),s("assertMetronomeSynthInvocation",62,83),s("metronomeSynthUniqueAddresses",85,94),s("metronomeSynthDirectedPairs",96,107),s("metronomeSynthActiveQuoteId",109,113),s("metronomeSynthCurrentRequestId",115,119)], R2, [d("families/metronome-synth/kernel/projection.ts","uniqueAddresses","directedPairs","pairRequestId","metronomeSynthProjection")], "METRONOME_SYNTH_EVIDENCE", "families/metronome-synth/test/projection.test.ts", "directed projection is canonical and direction-sensitive"),
  row("listener/src/searcher/venues/protocols/psm-family/codec.ts", "d25d78d9b2de49cd09d369e8afb21b95ba80eefb", [s("psmSellQuote",16,27)], R2, [d("families/psm/kernel/quote.ts","psmSellQuote")], "PSM_QUOTE_EVIDENCE", "families/psm/test/quote.test.ts", "PSM quote floors fixed-point fee and rejects invalid parameters"),
  row("listener/src/searcher/venues/protocols/self-burn-native-family/shared.ts", "5ba6f02757cbd57a5c9ac750960380ad0d01e862", [s("selfBurnNativeStaticProjection",36,47),s("assertSelfBurnNativeInvocation",49,71),s("selfBurnNativeProbeAmounts",73,80),s("selfBurnNativeSimulation",82,117),s("validateSelfBurnNativeEffects",119,151)], R2, [d("families/self-burn-native/kernel/effects.ts","selfBurnProbeAmounts","validateSelfBurnNativeRedeem")], "SELF_BURN_EFFECTS_EVIDENCE", "families/self-burn-native/test/effects.test.ts", "self-burn binds true return, exact effect scope and variable payout"),
  row("listener/src/searcher/venues/swaps/curve-underlying-family/codec.ts", "f012dd6315695d74c3385369e9e8b342f8207cbd", [s("canonicalAddress",47,49),s("lowerAddress",51,53),s("sameAddress",55,57),s("requireSuccessfulResult",59,74),s("normalizeAddressArray",76,88),s("decodeHandlers",90,98),s("decodeUnderlyingCoins",100,108),s("decodeUnderlyingDecimals",110,118),s("decodeUnderlyingBalances",120,128),s("decodeTokenDecimals",130,138),s("decodeGetDy",140,147),s("decodeUnderlyingIndicesFromCall",149,166),s("assertSameSource",168,182)], R2, [d("families/curve-underlying/src/types.ts","canonicalAddress","sameAddress"),d("families/curve-underlying/src/search-codec.ts","decodeCurveUint256","decodeCurveUint256Array","decodeCurveUint256Array8","trimCurveArray")], "CURVE_CODEC_EVIDENCE", "families/curve-underlying/test/search-codec.test.ts", "Curve search decodes fixed and dynamic ABI arrays without coercing shapes"),
  row("listener/src/searcher/venues/swaps/curve-underlying-family/identity.ts", "61a8477aeb695fbe8e823f98c4dfa9867b7035f6", [s("curveUnderlyingIdentity",38,73)], R2, [d("families/curve-underlying/src/identity.ts","verifyCurveUnderlyingIdentityStage","curveIdentityDescriptorHash")], "CURVE_IDENTITY_EVIDENCE", "families/curve-underlying/test/plugin.test.ts", "Curve identity is reverse registry plus complete underlying domain"),
  row("listener/src/searcher/venues/swaps/dodo-pmm-math.ts", "e7bfd107bf9bfc14ac7f41a2d77b71dca86beecd", [s("quoteDodoPmmExactInput",51,88)], R2, [d("families/dodo-v2/src/kernel/math.ts","quoteDodoPmmExactInput")], "DODO_MATH_EVIDENCE", "families/dodo-v2/test/kernel.test.ts", "K=0 matches the independent linear oracle and subtracts fees independently"),
  row("listener/src/searcher/venues/swaps/fluid-dex-family/codec.ts", "d8ce06cbe0b3be4eab25d64d7e4ec3a7f210b973", [s("canonicalAddress",35,37),s("lowerAddress",39,41),s("sameAddress",43,45),s("requireSuccessfulResult",47,55),s("decodeFluidDexConstants",57,83),s("decodeAddressResult",85,90),s("decodeDecimals",92,100),s("decodeDeclaredFluidDexQuote",107,127),s("assertSource",129,140)], R2, [d("families/fluid-dex/src/types.ts","canonicalAddress"),d("families/fluid-dex/src/abi.ts","decodeUint256","decodeConstantsView")], "FLUID_CODEC_EVIDENCE", "families/fluid-dex/test/plugin.test.ts", "Fluid DEX carries identity → materialization → route → exact → action → execution lineage"),
  row("listener/src/searcher/venues/swaps/fluid-dex-family/identity.ts", "6f6bf16604a8f89e67d06a77a80f7e49edcd938b", [s("fluidDexIdentity",46,85)], R2, [d("families/fluid-dex/src/stages.ts","verifyFluidDexIdentityStage","identityDescriptorHash")], "FLUID_IDENTITY_EVIDENCE", "families/fluid-dex/test/plugin.test.ts", "Fluid DEX reverse identity binds the instance before route and state"),
  row("listener/src/searcher/venues/swaps/univ2-family/codec.ts", "69c86a7e5dc79c149bf1d0e612b2e93d9b2e8622", [s("canonicalAddress",21,23),s("sameAddress",25,27),s("requireSuccessfulResult",29,42),s("decodeAddressResult",44,57),s("decodeReservesResult",59,88),s("lowerAddress",90,92)], R2, [d("families/univ2-standard/src/kernel/codec.ts","canonicalAddress","sameAddress","decodeAddressWord","decodeReserves","lowerAddress")], "UNIV2_CODEC_EVIDENCE", "families/univ2-standard/test/kernel.test.ts", "ABI word decoders reject padding and width mutations"),
  row("listener/src/searcher/venues/swaps/univ2-family/identity.ts", "6d88c8be0e4c4d2c5f3b80618b075ad6b08a96c9", [s("univ2Identity",34,105)], R2, [d("families/univ2-standard/src/kernel/identity.ts","verifyUniV2Identity")], "UNIV2_IDENTITY_EVIDENCE", "families/univ2-standard/test/kernel.test.ts", "both factory getPair directions are load-bearing in identity"),
  row("listener/src/searcher/venues/swaps/univ3-family/codec.ts", "8c98dd1e5edeb674febefc426092448c7dca9d81", [s("canonicalAddress",12,14),s("lowerAddress",16,18),s("sameAddress",20,22),s("requireSuccessfulResult",24,37),s("decodeAddressResult",39,52),s("decodeUint24Result",54,66),s("decodePositiveInt24Result",68,80)], R2, [d("families/univ3-standard/src/kernel/codec.ts","canonicalAddress","lowerAddress","sameAddress","decodeAddressWord","decodeUint24Word","decodePositiveInt24Word")], "UNIV3_CODEC_EVIDENCE", "families/univ3-standard/test/kernel.test.ts", "codec widths and reverse identity fields are load-bearing"),
  row("listener/src/searcher/venues/swaps/univ3-family/identity.ts", "3a0ff50064fdf87f106ba4b9a14866ab4687131e", [s("univ3Identity",41,130)], R2, [d("families/univ3-standard/src/kernel/identity.ts","verifyUniV3Identity")], "UNIV3_IDENTITY_EVIDENCE", "families/univ3-standard/test/kernel.test.ts", "codec widths and reverse identity fields are load-bearing"),
  row("listener/src/searcher/venues/swaps/univ4-common.ts", "ec2892f4d38220bf56d49b97d1f679cffa465e3e", [s("v4PoolId",13,20),s("v4HooksAffectSwap",22,24),s("normalizeV4PoolKey",26,34),s("normalizeV4Currency",36,43),s("realV4Currency",45,64),s("validateV4CurrencyPair",66,80),s("rejectNativeWethV4Pool",82,90)], R2, [d("families/univ4/src/abi.ts","assertPoolKey","poolIdForKey"),d("families/univ4/src/types.ts","canonicalAddress")], "UNIV4_POOL_KEY_EVIDENCE", "families/univ4/test/plugin.test.ts", "UniV4 PoolKey hashes to the independent Solidity/cast known vector"),
  row("listener/src/searcher/venues/swaps/univ4-family/codec.ts", "4d5d1603bc5ec34c210f0748d2b69e174de61113", [s("canonicalAddress",21,23),s("lowerAddress",25,27),s("sameAddress",29,31),s("canonicalPoolId",33,38),s("canonicalPoolKey",40,47),s("assertPoolKeyIdentity",49,56),s("graphCurrency",58,62),s("poolKeyProjection",64,72),s("poolKeyFingerprint",74,76),s("requireSuccessfulResult",78,91),s("assertSameSource",93,104),s("requireCodeHash",106,115)], R2, [d("families/univ4/src/abi.ts","decodeUniv4InitializeLog","assertPoolKey","poolIdForKey"),d("families/univ4/src/stages.ts","verifyUniv4IdentityStage")], "UNIV4_CODEC_EVIDENCE", "families/univ4/test/plugin.test.ts", "UniV4 reverse identity binds the instance before route and state"),
]);

export const REQUIRED_AUDIT_ENTRY_COUNT = 27 as const;
export const REQUIRED_AUDIT_ENTRY_SET_ROOT = "0xc8e5c4b703ff286557f4991b31ff103c5e40e8092c5d2036b7991d94aceb649e" as const;
export const REQUIRED_AUDIT_ENTRY_SET_DOMAIN = "aloha/reuse/required-audit-entry-set/v1" as const;
export const REQUIRED_AUDIT_ENTRY_IDS: readonly string[] = Object.freeze(CURRENT_REUSE_DECLARATIONS.map(item => item.entryId).sort());
if (REQUIRED_AUDIT_ENTRY_IDS.length !== REQUIRED_AUDIT_ENTRY_COUNT
  || hashDomain(REQUIRED_AUDIT_ENTRY_SET_DOMAIN, REQUIRED_AUDIT_ENTRY_IDS) !== REQUIRED_AUDIT_ENTRY_SET_ROOT) {
  throw new TypeError("current reuse declaration denominator differs from the frozen 27-entry audit set");
}
export const CURRENT_AUDIT_ENTRY_COUNT = CURRENT_REUSE_DECLARATIONS.length;
export const EVIDENCE_REQUIREMENT_MODULE_PATH = "specs/reuse-ledger/src/evidence-requirements.ts" as const;
