import { assertDecimalString, assertHash, assertNonEmptyString, decodeCanonicalJson, decodeExactObject, deepFreeze, encodeCanonicalJson, fieldArray, hashDomain, sha256Hex, type CanonicalJson, type Hash } from "../../../../packages/canonical-codec/src/index.ts";
import { erc20AssetPortBindingV1 } from "../../../../packages/asset-ref/src/index.ts";
import type { ExecutionFactSourceV1, ProgramInterpretationDraftV1, TransportFactV1 } from "../../../../packages/capability-interpreters/src/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type SchemaRef } from "../../../../packages/capability-contracts/src/index.ts";
import { decodeFamilySourcePlanPhysicalObservation, type FamilyRuntimeStageV1, type FamilyStageDefinitionV1, type FamilyStageGenericInvocationV1 } from "../../../../packages/family-sdk/runtime/index.ts";
import type { FrozenProgramEnvelopeV1, ProgramSourceAnchorV1 } from "../../../../packages/request-program/src/index.ts";
import { sealInstancePublication, validateInstancePublication, type InstancePublicationV1 } from "../../../../packages/catalog/src/index.ts";
import { candidateEvidenceRoot, candidateSubjectHash, decodeCanonicalCutoff, decodeCandidateEvidenceRef, familyCandidateKey as centralFamilyCandidateKey, type CandidateEvidenceRefV1, type CandidateRecordV1, type CanonicalCutoffV1 } from "../../../../packages/discovery/src/index.ts";
import { decodeEvmLogObservationBytes } from "../../../../packages/observation/src/index.ts";
import { DODO_V2_FAMILY_AUTHORING_HASH } from "../family-definition.ts";
import { DODO_V2_CAPABILITY_IDS, DODO_V2_FACTORIES, DODO_V2_FAMILY_ID, DODO_V2_FAMILY_VERSION, DODO_V2_HISTORY_SOURCE_PLAN_SCHEMA_HASH, DODO_V2_SWAP_TOPIC } from "../manifest.ts";
import { decodeDodoCreationHistoryEntries } from "../history-source-plan.ts";
import { verifyDodoIdentityStage, dodoIdentityDescriptorHash } from "../identity.ts";
import { materializeDodoV2, resealDodoState } from "../instance.ts";
import { deriveDodoRoutes } from "../routes.ts";
import { decodeDodoV2SwapLog } from "../swap-log.ts";
import type { DodoCandidateV1, DodoCutoffV1, DodoIdentityV1, DodoMaterializedStateV1, DodoStateReadFactsV1 } from "../types.ts";
import type { DodoPmmState } from "../kernel/math.ts";

const VERSION = asCapabilityVersion(DODO_V2_FAMILY_VERSION);
export const DODO_V2_STAGE_IDS = Object.freeze({ nomination: `family.${DODO_V2_FAMILY_ID}.nomination`, identity: `family.${DODO_V2_FAMILY_ID}.identity`, materialization: `family.${DODO_V2_FAMILY_ID}.materialization`, projection: `family.${DODO_V2_FAMILY_ID}.projection`, rehydration: `family.${DODO_V2_FAMILY_ID}.rehydration` });
export const DODO_V2_STAGE_SCHEMA_HASHES = Object.freeze({ nomination: hashDomain("aloha/dodo-v2/stage-schema/v1", "nomination"), identity: hashDomain("aloha/dodo-v2/stage-schema/v1", "identity"), materialization: hashDomain("aloha/dodo-v2/stage-schema/v1", "materialization"), projection: hashDomain("aloha/dodo-v2/stage-schema/v1", "projection"), rehydration: hashDomain("aloha/dodo-v2/stage-schema/v1", "rehydration") });
type Stage = keyof typeof DODO_V2_STAGE_IDS;
type CandidateRecord = CandidateRecordV1;
type PmmWire = { readonly i: string; readonly K: string; readonly B: string; readonly Q: string; readonly B0: string; readonly Q0: string; readonly R: 0 | 1 | 2 };
type IdentityWire = { readonly cutoff: DodoCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: { readonly pool: string; readonly factory: string; readonly registry: string; readonly baseToken: string; readonly quoteToken: string; readonly quoteActor: string; readonly pmm: PmmWire; readonly lpFeeRate: string; readonly mtFeeRate: string } };
type StateWire = { readonly cutoff: DodoCutoffV1; readonly pool: string; readonly pmm: PmmWire; readonly lpFeeRate: string; readonly mtFeeRate: string; readonly identityFactsHash: Hash; readonly stateHash: Hash };
interface IdentityMemo { readonly kind: "dodo-v2-identity-memo"; readonly familyId: typeof DODO_V2_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly candidateEvidenceRoot: Hash; readonly identity: IdentityWire }
interface NominationPayload { readonly kind: "dodo-v2-nomination-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["candidate"]; readonly requestId: Hash }
interface IdentityPayload { readonly kind: "dodo-v2-identity-input"; readonly candidate: CandidateRecord; readonly evidence: CandidateEvidenceRefV1; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["identity"]; readonly requestId: Hash }
interface MaterializationPayload { readonly kind: "dodo-v2-materialization-input"; readonly identityMemo: IdentityMemo; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash }
interface MaterializationOutput { readonly kind: "dodo-v2-materialization-output"; readonly familyId: typeof DODO_V2_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identityMemoHash: Hash; readonly identityFactsHash: Hash; readonly instanceKey: string; readonly state: StateWire; readonly evidenceRoot: Hash }
interface ProjectionPayload { readonly kind: "dodo-v2-projection-input"; readonly identityMemo: IdentityMemo; readonly materialization: MaterializationOutput; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash }
interface RehydrationPayload { readonly kind: "dodo-v2-rehydration-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["reference"]; readonly referenceHash: Hash; readonly requestId: Hash }

function canonical(value: unknown): CanonicalJson { return decodeCanonicalJson(encodeCanonicalJson(value)); }
function address(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x[0-9a-fA-F]{40}$/.test(text)) throw new TypeError(`${path} must be an address`); return `0x${text.slice(2).toLowerCase()}`; }
function bytes(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x(?:[0-9a-f]{2})*$/.test(text)) throw new TypeError(`${path} must be lowercase bytes`); return text; }
function cutoff(value: unknown, path: string): CanonicalCutoffV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function source(value: unknown, path: string): ProgramSourceAnchorV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function sameCutoff(left: DodoCutoffV1, right: DodoCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
function sameSource(left: ExecutionFactSourceV1, right: ProgramSourceAnchorV1): boolean { return left.chainId === right.chainId && left.blockNumber === right.number && left.blockHash === right.hash && left.stateRoot === right.stateRoot; }
function factData(value: string): CanonicalJson { const raw = value.slice(2); const bytesValue = new Uint8Array(raw.length / 2); for (let i = 0; i < bytesValue.length; i += 1) bytesValue[i] = Number.parseInt(raw.slice(i * 2, i * 2 + 2), 16); return decodeCanonicalJson(new TextDecoder().decode(bytesValue)); }
function invalidCode(error: unknown, fallback: string): string { const raw = error instanceof Error ? error.message : String(error); const code = raw.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); return /^[a-z][a-z0-9-]*$/.test(code) ? code : fallback; }
function requestId(phase: string, target: string, cutoffValue: CanonicalCutoffV1, snapshot: Hash, evidenceRoot: Hash, operation: string, evidence: CandidateEvidenceRefV1 | null = null): Hash { return hashDomain("aloha/dodo-v2/runtime-request/v1", { phase, target, cutoff: cutoffValue, candidateSnapshotHash: snapshot, candidateEvidenceRoot: evidenceRoot, operation, evidence }); }
function referenceHash(candidate: CandidateRecord, cutoffValue: CanonicalCutoffV1): Hash { return hashDomain("aloha/dodo-v2/rehydration-reference/v1", { familyDefinitionHash: candidate.familyDefinitionHash, familyCandidateKey: candidate.familyCandidateKey, candidateSubjectHash: candidate.candidateSubjectHash, instanceNominationKey: candidate.instanceNominationKey, cutoff: cutoffValue }); }
function pmmWire(value: unknown, path: string): PmmWire { return decodeExactObject(value, { i: (item, itemPath) => assertDecimalString(item, itemPath), K: (item, itemPath) => assertDecimalString(item, itemPath), B: (item, itemPath) => assertDecimalString(item, itemPath), Q: (item, itemPath) => assertDecimalString(item, itemPath), B0: (item, itemPath) => assertDecimalString(item, itemPath), Q0: (item, itemPath) => assertDecimalString(item, itemPath), R: (item, itemPath) => { if (item !== 0 && item !== 1 && item !== 2) throw new TypeError(`${itemPath} invalid R`); return item; } }, path); }
function pmm(value: PmmWire): DodoPmmState { return { i: BigInt(value.i), K: BigInt(value.K), B: BigInt(value.B), Q: BigInt(value.Q), B0: BigInt(value.B0), Q0: BigInt(value.Q0), R: value.R }; }
function wirePmm(value: DodoPmmState): PmmWire { return { i: value.i.toString(), K: value.K.toString(), B: value.B.toString(), Q: value.Q.toString(), B0: value.B0.toString(), Q0: value.Q0.toString(), R: value.R }; }
function identityWire(value: DodoIdentityV1): IdentityWire { return { cutoff: value.cutoff, candidateSnapshotHash: value.candidateSnapshotHash, instanceKey: value.instanceKey, factsHash: value.factsHash, facts: { ...value.facts, pmm: wirePmm(value.facts.pmm) } }; }
function identityKernel(value: IdentityWire): DodoIdentityV1 { return { cutoff: value.cutoff, candidateSnapshotHash: value.candidateSnapshotHash, instanceKey: value.instanceKey, factsHash: value.factsHash, facts: { ...value.facts, pmm: pmm(value.facts.pmm) } }; }
function stateWire(value: DodoMaterializedStateV1): StateWire { return { ...value, pmm: wirePmm(value.pmm) }; }
function stateKernel(value: StateWire): DodoMaterializedStateV1 { return { ...value, pmm: pmm(value.pmm) }; }

function candidateRecord(value: unknown, path = "dodo-v2.candidate"): CandidateRecord { const decoded = decodeExactObject<CandidateRecord>(value, { kind: (item, itemPath) => { if (item !== "aloha.candidate-record") throw new TypeError(`${itemPath} kind mismatch`); return item; }, version: (item, itemPath) => { if (item !== "2") throw new TypeError(`${itemPath} version mismatch`); return item; }, familyId: (item, itemPath) => { if (item !== DODO_V2_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return DODO_V2_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), evidence: (item, itemPath) => fieldArray(item, (entry, entryPath) => decodeCandidateEvidenceRef(entry, entryPath), itemPath) }, path); if (decoded.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH) throw new TypeError("dodo-v2 candidate definition mismatch"); if (decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("dodo-v2 candidate key mismatch"); if (decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("dodo-v2 candidate subject mismatch"); if (decoded.evidence.length === 0) throw new TypeError("dodo-v2 candidate evidence empty"); const keys = decoded.evidence.map(item => hashDomain("aloha/candidate-evidence-ref/v1", item)); if (new Set(keys).size !== keys.length || keys.some((item, index) => item !== [...keys].sort()[index])) throw new TypeError("dodo-v2 candidate evidence order"); if (decoded.candidateEvidenceRoot !== candidateEvidenceRoot(decoded.evidence)) throw new TypeError("dodo-v2 candidate evidence root mismatch"); if (decoded.evidence.some(item => item.kind === "recent-log" && (address(item.address, `${path}.evidence.address`) !== decoded.instanceNominationKey || item.topic !== DODO_V2_SWAP_TOPIC))) throw new TypeError("dodo-v2 recent evidence target/topic mismatch"); return deepFreeze(decoded); }
function primaryEvidence(record: CandidateRecord): CandidateEvidenceRefV1 { const evidence = record.evidence.find(item => item.kind === "source-plan") ?? record.evidence[0]; if (evidence === undefined) throw new TypeError("dodo-v2 candidate evidence empty"); return evidence; }
function identityMemo(value: unknown, path = "dodo-v2.identityMemo"): IdentityMemo { const decoded = decodeExactObject<IdentityMemo>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-identity-memo") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-identity-memo"; }, familyId: (item, itemPath) => { if (item !== DODO_V2_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return DODO_V2_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), identity: (item, itemPath) => decodeIdentityWire(item, itemPath) }, path); if (decoded.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.candidateSnapshotHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceNominationKey !== decoded.identity.instanceKey || decoded.candidateSnapshotHash !== decoded.identity.candidateSnapshotHash) throw new TypeError("dodo-v2 identity memo lineage mismatch"); return deepFreeze(decoded); }
function decodeIdentityWire(value: unknown, path: string): IdentityWire { const decoded = decodeExactObject<IdentityWire>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), factsHash: (item, itemPath) => assertHash(item, itemPath), facts: (item, itemPath) => decodeExactObject(item, { pool: (field, fieldPath) => address(field, fieldPath), factory: (field, fieldPath) => address(field, fieldPath), registry: (field, fieldPath) => address(field, fieldPath), baseToken: (field, fieldPath) => address(field, fieldPath), quoteToken: (field, fieldPath) => address(field, fieldPath), quoteActor: (field, fieldPath) => address(field, fieldPath), pmm: (field, fieldPath) => pmmWire(field, fieldPath), lpFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath), mtFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath) }, itemPath) }, path); if (decoded.instanceKey !== decoded.facts.pool || decoded.factsHash !== hashDomain("aloha/dodo-v2/identity-facts/v1", { ...decoded.facts, pmm: decoded.facts.pmm })) throw new TypeError("dodo-v2 identity hash mismatch"); return decoded; }
function decodeState(value: unknown, path: string): StateWire { const decoded = decodeExactObject<StateWire>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), pool: (item, itemPath) => address(item, itemPath), pmm: (item, itemPath) => pmmWire(item, itemPath), lpFeeRate: (item, itemPath) => assertDecimalString(item, itemPath), mtFeeRate: (item, itemPath) => assertDecimalString(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), stateHash: (item, itemPath) => assertHash(item, itemPath) }, path); if (decoded.stateHash !== resealDodoState(stateKernel(decoded))) throw new TypeError("dodo-v2 state hash mismatch"); return deepFreeze(decoded); }
function decodeMaterializationOutput(value: unknown, path = "dodo-v2.materializationOutput"): MaterializationOutput { const decoded = decodeExactObject<MaterializationOutput>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-materialization-output") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-materialization-output"; }, familyId: (item, itemPath) => { if (item !== DODO_V2_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return DODO_V2_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), state: (item, itemPath) => decodeState(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); if (decoded.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceKey !== decoded.state.pool || decoded.identityFactsHash !== decoded.state.identityFactsHash) throw new TypeError("dodo-v2 materialization lineage mismatch"); return deepFreeze(decoded); }
function readPlan(value: unknown, expected: readonly string[], path: string): readonly string[] { const result = fieldArray(value, (item, itemPath) => assertNonEmptyString(item, itemPath), path); if (result.length !== expected.length || result.some((item, index) => item !== expected[index])) throw new TypeError(`${path} read plan mismatch`); return Object.freeze([...result]); }
function hashValue(value: unknown, path: string): Hash { return assertHash(value, path); }
function nominationPayload(value: unknown, path = "dodo-v2.nominationPayload"): NominationPayload { const decoded = decodeExactObject<NominationPayload>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-nomination-input") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-nomination-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["candidate"], itemPath) as readonly ["candidate"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (decoded.requestId !== requestId("nomination", decoded.candidate.instanceNominationKey, decoded.cutoff, decoded.candidate.candidateSubjectHash, decoded.candidate.candidateEvidenceRoot, "candidate")) throw new TypeError("dodo-v2 nomination request mismatch"); return decoded; }
function identityPayload(value: unknown, path = "dodo-v2.identityPayload"): IdentityPayload { const decoded = decodeExactObject<IdentityPayload>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-identity-input") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-identity-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), evidence: (item, itemPath) => decodeCandidateEvidenceRef(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["identity"], itemPath) as readonly ["identity"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); const selected = primaryEvidence(decoded.candidate); if (encodeCanonicalJson(selected) !== encodeCanonicalJson(decoded.evidence)) throw new TypeError("dodo-v2 identity primary evidence mismatch"); if (decoded.requestId !== requestId("identity", decoded.candidate.instanceNominationKey, decoded.cutoff, decoded.candidate.candidateSubjectHash, decoded.candidate.candidateEvidenceRoot, "identity", decoded.evidence)) throw new TypeError("dodo-v2 identity request mismatch"); return decoded; }
function materializationPayload(value: unknown, path = "dodo-v2.materializationPayload"): MaterializationPayload { const decoded = decodeExactObject<MaterializationPayload>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-materialization-input") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-materialization-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.requestId !== requestId("materialization", decoded.identityMemo.identity.instanceKey, decoded.cutoff, decoded.identityMemo.candidateSnapshotHash, decoded.identityMemo.candidateEvidenceRoot, "state")) throw new TypeError("dodo-v2 materialization request mismatch"); return decoded; }
function projectionPayload(value: unknown, path = "dodo-v2.projectionPayload"): ProjectionPayload { const decoded = decodeExactObject<ProjectionPayload>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-projection-input") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-projection-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), materialization: (item, itemPath) => decodeMaterializationOutput(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.materialization.instanceKey !== decoded.identityMemo.identity.instanceKey || decoded.materialization.identityFactsHash !== decoded.identityMemo.identity.factsHash || decoded.materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", decoded.identityMemo) || decoded.materialization.candidateSnapshotHash !== decoded.identityMemo.candidateSnapshotHash || decoded.materialization.evidenceRoot !== decoded.identityMemo.candidateEvidenceRoot || decoded.requestId !== requestId("projection", decoded.identityMemo.identity.instanceKey, decoded.cutoff, decoded.identityMemo.candidateSnapshotHash, decoded.identityMemo.candidateEvidenceRoot, "state")) throw new TypeError("dodo-v2 projection lineage mismatch"); return decoded; }
function rehydrationPayload(value: unknown, path = "dodo-v2.rehydrationPayload"): RehydrationPayload { const decoded = decodeExactObject<RehydrationPayload>(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-rehydration-input") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-rehydration-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["reference"], itemPath) as readonly ["reference"], referenceHash: (item, itemPath) => hashValue(item, itemPath), requestId: (item, itemPath) => hashValue(item, itemPath) }, path); const expectedReference = referenceHash(decoded.candidate, decoded.cutoff); if (decoded.referenceHash !== expectedReference || decoded.requestId !== requestId("rehydration", decoded.candidate.instanceNominationKey, decoded.cutoff, decoded.candidate.candidateSubjectHash, decoded.candidate.candidateEvidenceRoot, expectedReference)) throw new TypeError("dodo-v2 rehydration request mismatch"); return decoded; }
function boundFact(program: FrozenProgramEnvelopeV1, facts: readonly TransportFactV1[], expected: Hash): Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }> { if (facts.length !== 1) throw new TypeError("dodo-v2 transport fact partition mismatch"); const fact = facts[0]!; if (fact.kind === "transportFailure" || fact.requestId !== expected || fact.requestFingerprint !== program.requestFingerprint || !sameSource(fact.source, program.source)) throw new TypeError("dodo-v2 transport fact binding mismatch"); return fact; }
function decodeFact(value: Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }>): CanonicalJson { return factData(bytes(value.dataHex, "dodo-v2.fact.dataHex")); }
function ack(value: unknown, kind: string): Hash { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== kind) throw new TypeError(`${itemPath} kind mismatch`); return kind; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, value: (item, itemPath) => assertHash(item, itemPath) }).value; }
function outputObject(value: unknown, path: string): CanonicalJson { const result = canonical(value); if (result === null || typeof result !== "object" || Array.isArray(result)) throw new TypeError(`${path} must be an object`); return result; }
function identityOutput(value: unknown): CanonicalJson { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "identityVerified") throw new TypeError(`${itemPath} kind mismatch`); return "identityVerified"; }, familyInstanceKey: (item, itemPath) => address(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }); const memo = decoded.identityMemo as IdentityMemo; if (decoded.familyInstanceKey !== memo.identity.instanceKey || decoded.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || decoded.descriptorHash !== dodoIdentityDescriptorHash(identityKernel(memo.identity)) || decoded.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("dodo-v2 identity output lineage mismatch"); return outputObject(decoded, "dodo-v2.identityOutput"); }
function nominationOutput(value: unknown): CanonicalJson { return outputObject(value, "dodo-v2.nominationOutput"); }
function rehydrationOutput(value: unknown): CanonicalJson { return outputObject(value, "dodo-v2.rehydrationOutput"); }
function publicationOutput(value: unknown): CanonicalJson { const decoded = canonical(value); if (decoded === null || typeof decoded !== "object" || Array.isArray(decoded)) throw new TypeError("dodo-v2 projection output must be object"); const publication = decoded as unknown as InstancePublicationV1; validateInstancePublication(publication); const memo = identityMemo(publication.identityMemo); if (publication.familyId !== DODO_V2_FAMILY_ID || publication.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH || publication.familyCandidateKey !== memo.familyCandidateKey || publication.instanceKey !== memo.identity.instanceKey || publication.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || publication.descriptorHash !== dodoIdentityDescriptorHash(identityKernel(memo.identity)) || publication.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("dodo-v2 projection publication lineage mismatch"); return decoded; }

function requireStage(input: FamilyStageGenericInvocationV1, expected: Stage): void { if (input.stage !== expected) throw new TypeError(`dodo-v2-${expected}-stage-mismatch`); }
function noPrior(input: FamilyStageGenericInvocationV1): void { if (input.identityMemo !== null || input.materializationOutput !== null) throw new TypeError("dodo-v2 unexpected prior output"); }
function prepareNomination(input: FamilyStageGenericInvocationV1): NominationPayload { requireStage(input, "nomination"); noPrior(input); const c = cutoff(input.cutoff, "dodo-v2.nomination.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "dodo-v2-nomination-input", candidate, cutoff: c, readPlan: ["candidate"], requestId: requestId("nomination", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, candidate.candidateEvidenceRoot, "candidate") }; }
function prepareIdentity(input: FamilyStageGenericInvocationV1): IdentityPayload { requireStage(input, "identity"); noPrior(input); const c = cutoff(input.cutoff, "dodo-v2.identity.cutoff"); const candidate = candidateRecord(input.candidate); const evidence = primaryEvidence(candidate); return { kind: "dodo-v2-identity-input", candidate, evidence, cutoff: c, readPlan: ["identity"], requestId: requestId("identity", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, candidate.candidateEvidenceRoot, "identity", evidence) }; }
function prepareMaterialization(input: FamilyStageGenericInvocationV1): MaterializationPayload { requireStage(input, "materialization"); if (input.identityMemo === null || input.materializationOutput !== null) throw new TypeError("dodo-v2 materialization prior output mismatch"); const c = cutoff(input.cutoff, "dodo-v2.materialization.cutoff"); const memo = identityMemo(input.identityMemo); if (!sameCutoff(c, memo.identity.cutoff)) throw new TypeError("dodo-v2 materialization cutoff mismatch"); return { kind: "dodo-v2-materialization-input", identityMemo: memo, cutoff: c, readPlan: ["state"], requestId: requestId("materialization", memo.identity.instanceKey, c, memo.candidateSnapshotHash, memo.candidateEvidenceRoot, "state") }; }
function prepareProjection(input: FamilyStageGenericInvocationV1): ProjectionPayload { requireStage(input, "projection"); if (input.identityMemo === null || input.materializationOutput === null) throw new TypeError("dodo-v2 projection prior output missing"); const c = cutoff(input.cutoff, "dodo-v2.projection.cutoff"); const memo = identityMemo(input.identityMemo); const materialization = decodeMaterializationOutput(input.materializationOutput); if (!sameCutoff(c, memo.identity.cutoff) || materialization.instanceKey !== memo.identity.instanceKey || materialization.identityFactsHash !== memo.identity.factsHash || materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || materialization.candidateSnapshotHash !== memo.candidateSnapshotHash || materialization.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("dodo-v2 projection lineage mismatch"); return { kind: "dodo-v2-projection-input", identityMemo: memo, materialization, cutoff: c, readPlan: ["state"], requestId: requestId("projection", memo.identity.instanceKey, c, memo.candidateSnapshotHash, memo.candidateEvidenceRoot, "state") }; }
function prepareRehydration(input: FamilyStageGenericInvocationV1): RehydrationPayload { requireStage(input, "rehydration"); noPrior(input); const c = cutoff(input.cutoff, "dodo-v2.rehydration.cutoff"); const candidate = candidateRecord(input.candidate); const ref = referenceHash(candidate, c); return { kind: "dodo-v2-rehydration-input", candidate, cutoff: c, readPlan: ["reference"], referenceHash: ref, requestId: requestId("rehydration", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, candidate.candidateEvidenceRoot, ref) }; }

function identityFact(value: unknown): { readonly candidateSnapshotHash: Hash; readonly candidateEvidenceBytesHex: string; readonly reads: Parameters<typeof verifyDodoIdentityStage>[0]["reads"] } { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-identity-facts") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-identity-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceBytesHex: (item, itemPath) => bytes(item, itemPath), reads: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), factory: (field, fieldPath) => address(field, fieldPath), registry: (field, fieldPath) => address(field, fieldPath), registryPool: (field, fieldPath) => address(field, fieldPath), baseToken: (field, fieldPath) => address(field, fieldPath), quoteToken: (field, fieldPath) => address(field, fieldPath), quoteActor: (field, fieldPath) => address(field, fieldPath), pmm: (field, fieldPath) => { const w = pmmWire(field, fieldPath); return pmm(w); }, lpFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath), mtFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath) }, itemPath) }, "dodo-v2.identityFact"); }

function hexBytes(value: string, path: string): Uint8Array { const hex = bytes(value, path); const raw = new Uint8Array((hex.length - 2) / 2); for (let index = 0; index < raw.length; index += 1) raw[index] = Number.parseInt(hex.slice(2 + index * 2, 4 + index * 2), 16); return raw; }
function blockTag(value: string): string { return `0x${BigInt(value).toString(16)}`; }
function candidateFromIdentityEvidence(payload: IdentityPayload, rawBytes: Uint8Array, reads: Parameters<typeof verifyDodoIdentityStage>[0]["reads"]): DodoCandidateV1 {
  if (sha256Hex(rawBytes) !== payload.evidence.rawLocatorHash) throw new TypeError("dodo-v2 identity raw locator mismatch");
  let blockNumber: string;
  let blockHash: Hash;
  let txHash: Hash;
  let logIndex: string;
  let topic0: Hash;
  if (payload.evidence.kind === "recent-log") {
    const raw = decodeEvmLogObservationBytes(rawBytes, "dodo-v2.identity.recentEvidence");
    if (raw.blockNumber !== payload.evidence.blockNumber || raw.blockHash !== payload.evidence.blockHash || raw.transactionHash !== payload.evidence.txHash || raw.logIndex !== payload.evidence.logIndex || raw.address !== payload.evidence.address || raw.address !== payload.candidate.instanceNominationKey || raw.topics[0] !== payload.evidence.topic) throw new TypeError("dodo-v2 recent evidence binding mismatch");
    const swap = decodeDodoV2SwapLog(raw, "dodo-v2.identity.DODOSwap");
    const tokenPairMatches = (swap.soldToken === reads.baseToken && swap.boughtToken === reads.quoteToken)
      || (swap.soldToken === reads.quoteToken && swap.boughtToken === reads.baseToken);
    if (!tokenPairMatches) throw new TypeError("dodo-v2 recent evidence token binding mismatch");
    if (BigInt(raw.blockNumber) > BigInt(payload.cutoff.number) || BigInt(raw.blockNumber) < BigInt(payload.cutoff.number) - 49n) throw new TypeError("dodo-v2 recent evidence window mismatch");
    blockNumber = raw.blockNumber; blockHash = raw.blockHash; txHash = raw.transactionHash; logIndex = raw.logIndex; topic0 = DODO_V2_SWAP_TOPIC;
  } else {
    const observed = decodeFamilySourcePlanPhysicalObservation(rawBytes, "dodo-v2.identity.historyEvidence");
    const declaration = DODO_V2_FACTORIES.find(item => item.address === reads.factory && item.address === reads.registry && item.address === observed.request.target && item.address === observed.request.manager && item.creationTopic === observed.request.topic);
    if (declaration === undefined || observed.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH || observed.plan.familyDefinitionHash !== DODO_V2_FAMILY_AUTHORING_HASH || observed.plan.ownerRef !== payload.evidence.ownerRef || observed.plan.sourcePlanRef !== payload.evidence.sourcePlanRef || observed.plan.completeness !== "contiguous-history" || observed.plan.historyStartBlock !== "0" || !sameCutoff(observed.cutoff, payload.cutoff) || observed.requestSchemaHash !== DODO_V2_HISTORY_SOURCE_PLAN_SCHEMA_HASH || observed.request.kind !== "family-source-plan-rpc" || observed.request.version !== 1 || observed.request.method !== "eth_getLogs") throw new TypeError("dodo-v2 history evidence binding mismatch");
    const lookback = decodeExactObject(observed.request.lookback, { from: (item, itemPath) => assertDecimalString(item, itemPath), through: (item, itemPath) => assertDecimalString(item, itemPath) }, "dodo-v2.identity.historyEvidence.lookback");
    const chunk = decodeExactObject(observed.request.chunk, { maxBlocks: (item, itemPath) => assertDecimalString(item, itemPath) }, "dodo-v2.identity.historyEvidence.chunk");
    if (chunk.maxBlocks !== "10000" || BigInt(lookback.from) > BigInt(lookback.through) || BigInt(lookback.through) > BigInt(payload.cutoff.number)) throw new TypeError("dodo-v2 history evidence range mismatch");
    const filter = Object.freeze({ address: declaration.address, fromBlock: blockTag(lookback.from), toBlock: blockTag(lookback.through), topics: Object.freeze([declaration.creationTopic]) });
    if (encodeCanonicalJson(observed.request.params) !== encodeCanonicalJson([filter])) throw new TypeError("dodo-v2 history evidence filter mismatch");
    const matches = decodeDodoCreationHistoryEntries(observed.response, declaration, BigInt(lookback.from), BigInt(lookback.through)).filter(entry => entry.pool === payload.candidate.instanceNominationKey && entry.factory === reads.factory && entry.baseToken === reads.baseToken && entry.quoteToken === reads.quoteToken);
    if (matches.length !== 1) throw new TypeError("dodo-v2 history evidence must contain exactly one creation witness");
    const match = matches[0]!; blockNumber = match.blockNumber; blockHash = match.blockHash; txHash = match.txHash; logIndex = match.logIndex; topic0 = match.creationTopic;
  }
  const evidence = Object.freeze({ kind: "log" as const, cutoff: payload.cutoff, blockNumber, blockHash, txHash, logIndex, target: payload.candidate.instanceNominationKey, rawLocatorHash: payload.evidence.rawLocatorHash, topic0 });
  return Object.freeze({ target: payload.candidate.instanceNominationKey, instanceNominationKey: payload.candidate.instanceNominationKey, candidateSnapshotHash: payload.candidate.candidateSubjectHash, evidence });
}
function stateFact(value: unknown): DodoStateReadFactsV1 { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "dodo-v2-state-facts") throw new TypeError(`${itemPath} kind mismatch`); return "dodo-v2-state-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, read: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), pmm: (field, fieldPath) => pmm(pmmWire(field, fieldPath)), lpFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath), mtFeeRate: (field, fieldPath) => assertDecimalString(field, fieldPath) }, itemPath) }, "dodo-v2.stateFact"); return decoded.read; }
function publication(payload: ProjectionPayload, program: FrozenProgramEnvelopeV1): InstancePublicationV1 { const identity = identityKernel(payload.identityMemo.identity); const routes = deriveDodoRoutes(identity); const state = stateKernel(payload.materialization.state); const transitions = routes.map(route => ({ inputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.inputToken), portRef: hashDomain("aloha/dodo-v2/port/v1", { instanceKey: route.instanceKey, role: "input", token: route.inputToken }), ordinal: "0" }], outputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.outputToken), portRef: hashDomain("aloha/dodo-v2/port/v1", { instanceKey: route.instanceKey, role: "output", token: route.outputToken }), ordinal: "0" }], opaqueTransitionRef: hashDomain("aloha/dodo-v2/transition/v1", route), constraintRefs: [state.stateHash], staticProjectionHash: hashDomain("aloha/dodo-v2/static-transition/v1", route) })); const memo = canonical(payload.identityMemo); return sealInstancePublication({ familyId: DODO_V2_FAMILY_ID, familyDefinitionHash: DODO_V2_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.materialization.familyCandidateKey, instanceKey: identity.instanceKey, cutoff: payload.cutoff, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: dodoIdentityDescriptorHash(identity), staticProjectionMemoHash: hashDomain("aloha/dodo-v2/static-projection/v1", { routes, stateHash: state.stateHash }), requestedArtifactDependencyRoot: hashDomain("aloha/dodo-v2/requested-artifacts/v1", { identityFactsHash: identity.factsHash, stateHash: state.stateHash }), validityDependencyRoot: hashDomain("aloha/dodo-v2/validity/v1", { source: program.source, identityFactsHash: identity.factsHash, stateHash: state.stateHash }), transitions, evidenceRoot: payload.materialization.evidenceRoot }); }
function interpretNomination(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = nominationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "dodo-v2-nomination-reverted" }; const value = ack(decodeFact(fact), "dodo-v2-nomination-facts"); if (value !== payload.candidate.candidateSubjectHash) throw new TypeError("dodo-v2 nomination acknowledgement mismatch"); return { kind: "verified", output: { kind: "dodo-v2-nomination-verified", familyId: DODO_V2_FAMILY_ID, candidateSubjectHash: value, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "dodo-v2-nomination-invalid") }; } }
function interpretIdentity(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = identityPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "dodo-v2-identity-reverted" }; const decoded = identityFact(decodeFact(fact)); if (decoded.candidateSnapshotHash !== payload.candidate.candidateSubjectHash || !sameCutoff(decoded.reads.cutoff, payload.cutoff)) throw new TypeError("dodo-v2 identity fact snapshot mismatch"); const candidate = candidateFromIdentityEvidence(payload, hexBytes(decoded.candidateEvidenceBytesHex, "dodo-v2.identityFact.candidateEvidenceBytesHex"), decoded.reads); const result = verifyDodoIdentityStage({ candidate, reads: decoded.reads }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const wire = identityWire(result.identity); const memo: IdentityMemo = { kind: "dodo-v2-identity-memo", familyId: DODO_V2_FAMILY_ID, familyDefinitionHash: DODO_V2_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSnapshotHash: payload.candidate.candidateSubjectHash, candidateEvidenceRoot: payload.candidate.candidateEvidenceRoot, identity: wire }; return { kind: "verified", output: { kind: "identityVerified", familyInstanceKey: result.identity.instanceKey, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: dodoIdentityDescriptorHash(result.identity), evidenceRoot: payload.candidate.candidateEvidenceRoot } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "dodo-v2-identity-invalid") }; } }
function interpretMaterialization(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = materializationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "dodo-v2-materialization-reverted" }; const read = stateFact(decodeFact(fact)); if (!sameCutoff(read.cutoff, payload.cutoff) || read.pool !== payload.identityMemo.identity.instanceKey) throw new TypeError("dodo-v2 state fact lineage mismatch"); const result = materializeDodoV2({ identity: identityKernel(payload.identityMemo.identity), read }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const output: MaterializationOutput = { kind: "dodo-v2-materialization-output", familyId: DODO_V2_FAMILY_ID, familyDefinitionHash: DODO_V2_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.identityMemo.familyCandidateKey, instanceNominationKey: payload.identityMemo.instanceNominationKey, candidateSnapshotHash: payload.identityMemo.candidateSnapshotHash, identityMemoHash: hashDomain("aloha/identity-memo/v1", payload.identityMemo), identityFactsHash: payload.identityMemo.identity.factsHash, instanceKey: result.state.pool, state: stateWire(result.state), evidenceRoot: payload.identityMemo.candidateEvidenceRoot }; return { kind: "verified", output }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "dodo-v2-materialization-invalid") }; } }
function interpretProjection(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = projectionPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "dodo-v2-projection-reverted" }; const read = stateFact(decodeFact(fact)); const result = materializeDodoV2({ identity: identityKernel(payload.identityMemo.identity), read }); if (result.status !== "verified") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; if (result.state.stateHash !== stateKernel(payload.materialization.state).stateHash) throw new TypeError("dodo-v2 projection state lineage mismatch"); return { kind: "verified", output: publication(payload, input.program) }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "dodo-v2-projection-invalid") }; } }
function interpretRehydration(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = rehydrationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "dodo-v2-rehydration-reverted" }; const value = ack(decodeFact(fact), "dodo-v2-rehydration-facts"); if (value !== payload.referenceHash) throw new TypeError("dodo-v2 rehydration acknowledgement mismatch"); return { kind: "verified", output: { kind: "dodo-v2-rehydration-verified", familyId: DODO_V2_FAMILY_ID, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: value } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "dodo-v2-rehydration-invalid") }; } }

function definitionBase(stage: Stage, payloadCodec: { readonly schemaRef: SchemaRef; readonly decodeExact: (value: unknown) => unknown }, outputSchemaRef: Hash, outputCodec: { readonly decodeExact: (value: unknown) => CanonicalJson }, prepareIssueValue: FamilyStageDefinitionV1["prepareIssueValue"], interpret: FamilyStageDefinitionV1["interpret"]): FamilyStageDefinitionV1 { return deepFreeze({ stage, capabilityId: asCapabilityId(DODO_V2_STAGE_IDS[stage]), version: VERSION, schemaHash: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES[stage]), payloadCodec: deepFreeze(payloadCodec), dependencyIds: Object.freeze([]), outputSchemaRef, implementationClosureHash: hashDomain("aloha/dodo-v2/runtime-implementation/v1", { stage, module: "families/dodo-v2/src/runtime/definitions.ts" }), outputCodecHash: hashDomain("aloha/dodo-v2/runtime-output-codec/v1", stage), outputCodec: deepFreeze(outputCodec), prepareIssueValue, interpret }); }
const codecs = Object.freeze({ nomination: { schemaRef: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES.nomination), decodeExact: (value: unknown) => nominationPayload(value) }, identity: { schemaRef: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES.identity), decodeExact: (value: unknown) => identityPayload(value) }, materialization: { schemaRef: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES.materialization), decodeExact: (value: unknown) => materializationPayload(value) }, projection: { schemaRef: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES.projection), decodeExact: (value: unknown) => projectionPayload(value) }, rehydration: { schemaRef: asSchemaRef(DODO_V2_STAGE_SCHEMA_HASHES.rehydration), decodeExact: (value: unknown) => rehydrationPayload(value) } });
const outputSchema = (stage: Stage): Hash => hashDomain("aloha/dodo-v2/runtime-output-schema/v1", stage);
export const DODO_V2_NOMINATION_DEFINITION = definitionBase("nomination", codecs.nomination, outputSchema("nomination"), { decodeExact: value => nominationOutput(value) }, prepareNomination, interpretNomination);
export const DODO_V2_IDENTITY_DEFINITION = definitionBase("identity", codecs.identity, outputSchema("identity"), { decodeExact: value => identityOutput(value) }, prepareIdentity, interpretIdentity);
export const DODO_V2_MATERIALIZATION_DEFINITION = definitionBase("materialization", codecs.materialization, outputSchema("materialization"), { decodeExact: value => outputObject(decodeMaterializationOutput(value), "dodo-v2.materializationOutput") }, prepareMaterialization, interpretMaterialization);
export const DODO_V2_PROJECTION_DEFINITION = definitionBase("projection", codecs.projection, outputSchema("projection"), { decodeExact: value => publicationOutput(value) }, prepareProjection, interpretProjection);
export const DODO_V2_REHYDRATION_DEFINITION = definitionBase("rehydration", codecs.rehydration, outputSchema("rehydration"), { decodeExact: value => rehydrationOutput(value) }, prepareRehydration, interpretRehydration);
export const DODO_V2_NOMINATION_RUNTIME = DODO_V2_NOMINATION_DEFINITION;
export const DODO_V2_IDENTITY_RUNTIME = DODO_V2_IDENTITY_DEFINITION;
export const DODO_V2_MATERIALIZATION_RUNTIME = DODO_V2_MATERIALIZATION_DEFINITION;
export const DODO_V2_PROJECTION_RUNTIME = DODO_V2_PROJECTION_DEFINITION;
export const DODO_V2_REHYDRATION_RUNTIME = DODO_V2_REHYDRATION_DEFINITION;
export const DODO_V2_STAGE_DEFINITIONS: readonly FamilyStageDefinitionV1[] = Object.freeze([DODO_V2_NOMINATION_DEFINITION, DODO_V2_IDENTITY_DEFINITION, DODO_V2_MATERIALIZATION_DEFINITION, DODO_V2_PROJECTION_DEFINITION, DODO_V2_REHYDRATION_DEFINITION]);
export function requireDodoV2StageDefinition(stage: FamilyRuntimeStageV1): FamilyStageDefinitionV1 { const definition = DODO_V2_STAGE_DEFINITIONS.find(item => item.stage === stage); if (!definition) throw new TypeError(`dodo-v2 stage definition missing: ${stage}`); return definition; }
