import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { METRONOME_HGUSDC_ACTION_OWNER_ID, METRONOME_HGUSDC_CAPABILITY_IDS, METRONOME_HGUSDC_FAMILY_ID, METRONOME_HGUSDC_FAMILY_VERSION, METRONOME_HGUSDC_OWNER_REF, METRONOME_HGUSDC_SOURCE_PLAN_ID, METRONOME_HGUSDC_SOURCE_PLAN_SCHEMA_HASH, METRONOME_HGUSDC_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(METRONOME_HGUSDC_FAMILY_VERSION); const moduleRoot = "families/metronome-hgusdc/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${METRONOME_HGUSDC_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/metronome-hgusdc/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([METRONOME_HGUSDC_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "state"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(METRONOME_HGUSDC_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-hgusdc/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/metronome-hgusdc/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "METRONOME_HGUSDC_RUNTIME" }); }
const n = core("nomination", "METRONOME_HGUSDC_NOMINATION_RUNTIME"); const i = core("identity", "METRONOME_HGUSDC_IDENTITY_RUNTIME"); const m = core("materialization", "METRONOME_HGUSDC_MATERIALIZATION_RUNTIME"); const p = core("projection", "METRONOME_HGUSDC_PROJECTION_RUNTIME"); const r = core("rehydration", "METRONOME_HGUSDC_REHYDRATION_RUNTIME"); const state = present("state");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.metronome-hgusdc.path-identity", version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-hgusdc/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.metronome-hgusdc.dependent-quote", version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-hgusdc/fact-schema/v1", "quote")) })]);
const actionOwner = Object.freeze({ ownerId: METRONOME_HGUSDC_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/metronome-hgusdc/action-schema/v1", "exit")), implementationHash: hashDomain("aloha/metronome-hgusdc/action-implementation/v1", "exit"), actionKinds: Object.freeze(["exit"]), modulePath: `${moduleRoot}/action.ts`, exportName: "METRONOME_HGUSDC_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: METRONOME_HGUSDC_FAMILY_ID, version: METRONOME_HGUSDC_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/metronome-hgusdc/plugin-code/v1", { n, i, m, p, r, state, actionOwner, facts }), authorityDeclarationHash: hashDomain("aloha/metronome-hgusdc/authority/v1", METRONOME_HGUSDC_OWNER_REF), sourcePlans: [{ sourcePlanId: METRONOME_HGUSDC_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: METRONOME_HGUSDC_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "METRONOME_HGUSDC_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/metronome-hgusdc/src/source-plan.ts", exportName: "METRONOME_HGUSDC_SOURCE_NOMINATION_PROGRAM", schemaHash: METRONOME_HGUSDC_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/metronome-hgusdc/src/nomination-qualification.ts", exportName: "METRONOME_HGUSDC_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/metronome-hgusdc/src/nomination-qualification.ts", exportName: "METRONOME_HGUSDC_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [METRONOME_HGUSDC_CAPABILITY_IDS.state]: { kind: "present", module: state }, [METRONOME_HGUSDC_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "requires-future-extension" }, [METRONOME_HGUSDC_CAPABILITY_IDS.exact]: { kind: "absent", reason: "requires-future-extension" } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "METRONOME_HGUSDC_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(METRONOME_HGUSDC_CAPABILITY_IDS.state) }, actionOwnerIds: { exit: METRONOME_HGUSDC_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const METRONOME_HGUSDC_DEFINITION = defineFamily(input); export const METRONOME_HGUSDC_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(METRONOME_HGUSDC_DEFINITION); export { METRONOME_HGUSDC_FAMILY_DEFINITION_HASH, METRONOME_HGUSDC_OWNER_REF };
