import { assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { familyCandidateKey as discoveryFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { METRONOME_HGUSDC_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { materializeMetronomeHgUsdc } from "./instance.ts";
import { assertMetronomeHgUsdcRoute, deriveMetronomeHgUsdcRoutes } from "./routes.ts";
import { canonicalAddress, type MetronomeHgUsdcIdentityV1, type MetronomeHgUsdcMaterializedStateV1, type MetronomeHgUsdcRouteV1 } from "./types.ts";

type Source = ReturnType<typeof familySearchSource>;
type Context = { readonly route: ReturnType<typeof validateFamilySearchRouteLegBinding>; readonly routeBindingHash: Hash; readonly source: Source; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly amountHash: Hash; readonly identity: MetronomeHgUsdcIdentityV1; readonly protocolRoute: MetronomeHgUsdcRouteV1 };
type StateResponse = { readonly kind: "metronome-hgusdc-state-read-response"; readonly requestId: Hash; readonly source: Source; readonly routeBindingHash: Hash; readonly amountHash: Hash; readonly instanceKey: string; readonly projectionHash: Hash; readonly curveReturnDataHex: string; readonly vaultReturnDataHex: string };

function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function text(value: unknown, path: string): string { return assertNonEmptyString(value, path); }
function bytes(value: unknown, path: string): string { const result = text(value, path); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result)) throw new TypeError(`${path} must be even-length hex bytes`); return result.toLowerCase(); }
function invalid(stage: "state" | "coarse" | "exact" | "action", error: unknown) { return Object.freeze({ kind: "invalidProgram" as const, stage, code: error instanceof Error ? error.message : `${stage}-invalid` }); }
function unavailable(stage: "state" | "coarse" | "exact" | "action", reasonCode: string, evidence: unknown) { return unavailableFamilySearchStage(stage, `metronome-hgusdc-${reasonCode}`, canonical(evidence)); }
function word(value: bigint, path: string): string { if (value < 0n || value >= (1n << 256n)) throw new RangeError(`${path} is outside uint256`); return value.toString(16).padStart(64, "0"); }
function call(selector: string, words: readonly string[]): string { if (!/^0x[0-9a-fA-F]{8}$/.test(selector)) throw new TypeError("metronome hgUSDC selector is not canonical"); return `${selector}${words.join("")}`.toLowerCase(); }
function abiUint256(value: string, path: string): string { const hex = bytes(value, path); if (hex.length !== 66) throw new TypeError(`${path} must be one ABI uint256 word`); return BigInt(`0x${hex.slice(2)}`).toString(); }
function decodeIdentity(value: unknown): MetronomeHgUsdcIdentityV1 {
  const outer = record(value, "metronome-hgusdc.route.identityMemo"); assertExactKeys(outer, ["kind", "familyId", "familyDefinitionHash", "familyCandidateKey", "instanceNominationKey", "candidateSnapshotHash", "identity"], "metronome-hgusdc.identityMemo");
  if (outer.kind !== "metronome-hgusdc-identity-memo") throw new TypeError("metronome-hgusdc identity memo discriminator mismatch"); const definitionHash = assertHash(outer.familyDefinitionHash, "metronome-hgusdc.identityMemo.familyDefinitionHash"); const nominationKey = canonicalAddress(text(outer.instanceNominationKey, "metronome-hgusdc.identityMemo.instanceNominationKey")); if (definitionHash !== METRONOME_HGUSDC_FAMILY_AUTHORING_HASH || assertHash(outer.familyCandidateKey, "metronome-hgusdc.identityMemo.familyCandidateKey") !== discoveryFamilyCandidateKey(definitionHash, nominationKey)) throw new TypeError("metronome-hgusdc identity memo family binding mismatch");
  const source = record(outer.identity, "metronome-hgusdc.identity"); assertExactKeys(source, ["cutoff", "candidateSnapshotHash", "instanceKey", "factsHash", "facts"], "metronome-hgusdc.identity"); const facts = record(source.facts, "metronome-hgusdc.identity.facts"); assertExactKeys(facts, ["router", "curve", "vault", "tokenIn", "curveIntermediate", "tokenOut", "curveDirection", "pathHash", "quoteChain"], "metronome-hgusdc.identity.facts"); const direction = facts.curveDirection; if (!Array.isArray(direction) || direction.length !== 2 || direction[0] !== 1 || direction[1] !== 0) throw new TypeError("metronome-hgusdc direction mismatch"); if (facts.quoteChain !== "curve-get-dy->vault-preview-redeem-v1") throw new TypeError("metronome-hgusdc quote chain mismatch");
  const decodedFacts = Object.freeze({ router: canonicalAddress(text(facts.router, "metronome-hgusdc.identity.facts.router")), curve: canonicalAddress(text(facts.curve, "metronome-hgusdc.identity.facts.curve")), vault: canonicalAddress(text(facts.vault, "metronome-hgusdc.identity.facts.vault")), tokenIn: canonicalAddress(text(facts.tokenIn, "metronome-hgusdc.identity.facts.tokenIn")), curveIntermediate: canonicalAddress(text(facts.curveIntermediate, "metronome-hgusdc.identity.facts.curveIntermediate")), tokenOut: canonicalAddress(text(facts.tokenOut, "metronome-hgusdc.identity.facts.tokenOut")), curveDirection: [1, 0] as const, pathHash: assertHash(facts.pathHash, "metronome-hgusdc.identity.facts.pathHash"), quoteChain: "curve-get-dy->vault-preview-redeem-v1" as const });
  const identity = Object.freeze({ cutoff: familySearchSource(source.cutoff, "metronome-hgusdc.identity.cutoff") as MetronomeHgUsdcIdentityV1["cutoff"], candidateSnapshotHash: assertHash(source.candidateSnapshotHash, "metronome-hgusdc.identity.candidateSnapshotHash"), instanceKey: canonicalAddress(text(source.instanceKey, "metronome-hgusdc.identity.instanceKey")), factsHash: assertHash(source.factsHash, "metronome-hgusdc.identity.factsHash"), facts: decodedFacts }); if (identity.instanceKey !== identity.facts.router || identity.factsHash !== hashDomain("aloha/metronome-hgusdc/identity-facts/v1", identity.facts)) throw new TypeError("metronome-hgusdc identity facts hash mismatch"); if (nominationKey !== identity.instanceKey || assertHash(outer.candidateSnapshotHash, "metronome-hgusdc.identityMemo.candidateSnapshotHash") !== identity.candidateSnapshotHash) throw new TypeError("metronome-hgusdc identity memo lineage mismatch"); return identity;
}
function context(input: FamilySearchLegRequestV1): Context { const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== "metronome-hgusdc" || route.familyDefinitionHash !== METRONOME_HGUSDC_FAMILY_AUTHORING_HASH) throw new TypeError("metronome-hgusdc search route family mismatch"); if (route.identityMemoHash !== hashDomain("aloha/identity-memo/v1", route.identityMemo)) throw new TypeError("metronome-hgusdc identity memo hash mismatch"); const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const identity = decodeIdentity(route.identityMemo); if (route.instanceKey !== identity.instanceKey) throw new TypeError("metronome-hgusdc search instance binding mismatch"); const protocolRoute = deriveMetronomeHgUsdcRoutes(identity).find(item => erc20AssetRefV1(source.chainId, item.inputAsset) === amount.inputAssetRef && erc20AssetRefV1(source.chainId, item.outputAsset) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("metronome-hgusdc search amount assets do not match identity"); assertMetronomeHgUsdcRoute(protocolRoute, identity); return Object.freeze({ route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, amountHash: familySearchAmountHash(amount), identity, protocolRoute }); }
function requestId(ctx: Context): Hash { return hashDomain("aloha/metronome-hgusdc/search-state-request/v3", { familyDefinitionHash: METRONOME_HGUSDC_FAMILY_AUTHORING_HASH, routeBindingHash: ctx.routeBindingHash, instanceKey: ctx.identity.instanceKey, amountHash: ctx.amountHash, source: ctx.source }); }
function readRequest(ctx: Context, phase: "curve" | "vault", amount: bigint): { readonly requestId: Hash; readonly request: { readonly kind: "family-search.current-source-read"; readonly requestId: Hash; readonly source: Source; readonly target: string; readonly data: string; readonly responseEncoding: "abi-uint256" } } {
  const root = requestId(ctx); const target = phase === "curve" ? ctx.identity.facts.curve : ctx.identity.facts.vault; const data = phase === "curve" ? call("0x5e0d443f", [word(1n, "metronome hgUSDC curve index i"), word(0n, "metronome hgUSDC curve index j"), word(amount, "metronome hgUSDC amountIn")]) : call("0x4cdad506", [word(amount, "metronome hgUSDC vault shares")]); const id = hashDomain("aloha/metronome-hgusdc/search-state-read/v3", { root, phase, target, data }); return Object.freeze({ requestId: id, request: Object.freeze({ kind: "family-search.current-source-read" as const, requestId: id, source: ctx.source, target, data, responseEncoding: "abi-uint256" }) });
}
function stateResponse(ctx: Context, id: Hash, curveReturnDataHex: string, vaultReturnDataHex: string): StateResponse { const curve = bytes(curveReturnDataHex, "metronome-hgusdc.state.curveReturnDataHex"); const vault = bytes(vaultReturnDataHex, "metronome-hgusdc.state.vaultReturnDataHex"); const projectionHash = hashDomain("aloha/metronome-hgusdc/search-projection/v3", { cutoff: ctx.source, instanceKey: ctx.identity.instanceKey, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, curveReturnDataHex: curve, vaultReturnDataHex: vault }); return Object.freeze({ kind: "metronome-hgusdc-state-read-response", requestId: id, source: ctx.source, routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, instanceKey: ctx.identity.instanceKey, projectionHash, curveReturnDataHex: curve, vaultReturnDataHex: vault }); }
function decodeStateResponse(value: CanonicalJson, ctx: Context, id: Hash): StateResponse { const source = record(value, "metronome-hgusdc.stateResponse"); assertExactKeys(source, ["kind", "requestId", "source", "routeBindingHash", "amountHash", "instanceKey", "projectionHash", "curveReturnDataHex", "vaultReturnDataHex"], "metronome-hgusdc.stateResponse"); if (source.kind !== "metronome-hgusdc-state-read-response" || assertHash(source.requestId, "metronome-hgusdc.stateResponse.requestId") !== id) throw new TypeError("metronome-hgusdc state response request mismatch"); const responseSource = familySearchSource(source.source, "metronome-hgusdc.stateResponse.source"); const routeBindingHash = assertHash(source.routeBindingHash, "metronome-hgusdc.stateResponse.routeBindingHash"); const amountHash = assertHash(source.amountHash, "metronome-hgusdc.stateResponse.amountHash"); const instanceKey = canonicalAddress(text(source.instanceKey, "metronome-hgusdc.stateResponse.instanceKey")); if (!sameFamilySearchSource(responseSource, ctx.source) || routeBindingHash !== ctx.routeBindingHash || amountHash !== ctx.amountHash || instanceKey !== ctx.identity.instanceKey) throw new TypeError("metronome-hgusdc state response lineage mismatch"); const curveReturnDataHex = bytes(source.curveReturnDataHex, "metronome-hgusdc.stateResponse.curveReturnDataHex"); const vaultReturnDataHex = bytes(source.vaultReturnDataHex, "metronome-hgusdc.stateResponse.vaultReturnDataHex"); const projectionHash = assertHash(source.projectionHash, "metronome-hgusdc.stateResponse.projectionHash"); if (projectionHash !== hashDomain("aloha/metronome-hgusdc/search-projection/v3", { cutoff: responseSource, instanceKey, routeBindingHash, amountHash, curveReturnDataHex, vaultReturnDataHex })) throw new TypeError("metronome-hgusdc projection hash mismatch"); return Object.freeze({ kind: "metronome-hgusdc-state-read-response", requestId: id, source: responseSource, routeBindingHash, amountHash, instanceKey, projectionHash, curveReturnDataHex, vaultReturnDataHex }); }
function stateArtifact(ctx: Context, response: StateResponse): FamilySearchStateArtifactV1 { const result = materializeMetronomeHgUsdc({ identity: ctx.identity, read: { cutoff: response.source as MetronomeHgUsdcMaterializedStateV1["cutoff"], instanceKey: response.instanceKey, projectionHash: response.projectionHash } }); if (result.status !== "verified") throw new TypeError(`metronome-hgusdc state ${result.reasonCode}`); const payload = canonical(response); const payloadHash = familySearchPayloadHash("state", payload); return Object.freeze({ kind: "state", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot: hashDomain("aloha/metronome-hgusdc/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, projectionHash: response.projectionHash, curveReturnDataHex: response.curveReturnDataHex, vaultReturnDataHex: response.vaultReturnDataHex }), sourceRequestId: response.requestId }); }
function assertState(ctx: Context, artifact: FamilySearchStateArtifactV1): StateResponse { if (artifact.kind !== "state" || artifact.status !== "verified" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("metronome-hgusdc state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("metronome-hgusdc state artifact hash mismatch"); const response = decodeStateResponse(payload, ctx, artifact.sourceRequestId); const state = materializeMetronomeHgUsdc({ identity: ctx.identity, read: { cutoff: response.source as MetronomeHgUsdcMaterializedStateV1["cutoff"], instanceKey: response.instanceKey, projectionHash: response.projectionHash } }); if (state.status !== "verified" || artifact.factsRoot !== hashDomain("aloha/metronome-hgusdc/state-facts/v1", { cutoff: response.source, instanceKey: response.instanceKey, projectionHash: response.projectionHash, curveReturnDataHex: response.curveReturnDataHex, vaultReturnDataHex: response.vaultReturnDataHex })) throw new TypeError("metronome-hgusdc state facts root mismatch"); return response; }

const factory: FamilySearchAdapterFactoryV1 = input => { if (input.familyDefinitionHash !== METRONOME_HGUSDC_FAMILY_AUTHORING_HASH) throw new TypeError("metronome-hgusdc search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); for (const ref of Object.values(input.actionOwnerRefs)) input.composition.resolveActionOwner(input.familyDefinitionHash, ref);
  const readState: FamilySearchAdapterV1["readState"] = async request => { try { const ctx = context(request); await request.currentSource.assertCurrent(); const curveRequest = readRequest(ctx, "curve", BigInt(ctx.amount.amountIn)); let curveRaw: FamilySearchSourceReadResultV1; try { curveRaw = await request.readPort.read({ request: curveRequest.request, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: curveRequest.requestId, error: String(error) }); } if (curveRaw.kind !== "returned") return unavailable("state", curveRaw.reasonCode || "source-read-unavailable", curveRaw); if (curveRaw.requestId !== curveRequest.requestId || !sameFamilySearchSource(curveRaw.source, curveRequest.request.source)) throw new TypeError("metronome-hgusdc curve response binding mismatch"); let curveReturnDataHex: string; let intermediate: bigint; try { curveReturnDataHex = bytes(curveRaw.dataHex, "metronome-hgusdc.curveReturnDataHex"); intermediate = BigInt(abiUint256(curveReturnDataHex, "metronome-hgusdc.curveReturnDataHex")); } catch (error) { return unavailable("state", "malformed-abi-return", { requestId: curveRequest.requestId, dataHex: curveRaw.dataHex, error: String(error) }); } await request.currentSource.assertCurrent(); const vaultRequest = readRequest(ctx, "vault", intermediate); let vaultRaw: FamilySearchSourceReadResultV1; try { vaultRaw = await request.readPort.read({ request: vaultRequest.request, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailable("state", "source-transport-error", { requestId: vaultRequest.requestId, error: String(error) }); } if (vaultRaw.kind !== "returned") return unavailable("state", vaultRaw.reasonCode || "source-read-unavailable", vaultRaw); if (vaultRaw.requestId !== vaultRequest.requestId || !sameFamilySearchSource(vaultRaw.source, vaultRequest.request.source)) throw new TypeError("metronome-hgusdc vault response binding mismatch"); let vaultReturnDataHex: string; try { vaultReturnDataHex = bytes(vaultRaw.dataHex, "metronome-hgusdc.vaultReturnDataHex"); abiUint256(vaultReturnDataHex, "metronome-hgusdc.vaultReturnDataHex"); } catch (error) { return unavailable("state", "malformed-abi-return", { requestId: vaultRequest.requestId, dataHex: vaultRaw.dataHex, error: String(error) }); } await request.currentSource.assertCurrent(); const response = stateResponse(ctx, requestId(ctx), curveReturnDataHex, vaultReturnDataHex); return Object.freeze({ kind: "verified" as const, artifact: stateArtifact(ctx, response) }); } catch (error) { return invalid("state", error); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); const state = assertState(ctx, request.state); return unavailable("coarse", "dependent-quote-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, curveReturnDataHex: state.curveReturnDataHex, vaultReturnDataHex: state.vaultReturnDataHex }); } catch (error) { return invalid("coarse", error); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); const state = assertState(ctx, request.state); return unavailable("exact", "dependent-quote-not-in-release", { routeBindingHash: ctx.routeBindingHash, amountHash: ctx.amountHash, curveReturnDataHex: state.curveReturnDataHex, vaultReturnDataHex: state.vaultReturnDataHex, coarse: request.coarse }); } catch (error) { return invalid("exact", error); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); return unavailable("action", "path-bytes-not-family-proven", { exact: request.exact, pathHash: ctx.identity.facts.pathHash }); } catch (error) { return invalid("action", error); } };
  const run: FamilySearchAdapterV1["run"] = async (request: FamilySearchRunRequestV1) => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const METRONOME_HGUSDC_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
