import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { metronomeHgUsdcProjection } from "../kernel/projection.ts";
import { METRONOME_HGUSDC_ACTION_OWNER_ID, METRONOME_HGUSDC_FAMILY_DEFINITION_HASH, METRONOME_HGUSDC_MANIFEST, METRONOME_HGUSDC_SOURCE_PLAN_ID, METRONOME_HGUSDC_SOURCE_WINDOW_BLOCKS } from "./manifest.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type MetronomeHgUsdcActionV1, type MetronomeHgUsdcCandidateV1, type MetronomeHgUsdcExecutionIntentV1, type MetronomeHgUsdcIdentityReadFactsV1, type MetronomeHgUsdcIdentityV1, type MetronomeHgUsdcMaterializedStateV1, type MetronomeHgUsdcRouteV1, type MetronomeHgUsdcStateReadFactsV1, type MetronomeHgUsdcObservationV1 } from "./types.ts";
export type MetronomeHgUsdcDiscoveryPatternV1 = "metronome-hgusdc-surface" | "metronome-hgusdc-call";
export interface MetronomeHgUsdcCandidateSeedV1 { readonly target: string; readonly evidence: MetronomeHgUsdcObservationV1; }
export function decodeMetronomeHgUsdcCandidate(observation: MetronomeHgUsdcObservationV1, pattern: MetronomeHgUsdcDiscoveryPatternV1): MetronomeHgUsdcCandidateSeedV1 | null { if ((pattern === "metronome-hgusdc-surface" || pattern === "metronome-hgusdc-call") && (observation.kind === "address-surface" || observation.kind === "call")) return Object.freeze({ target: canonicalAddress(observation.target), evidence: observation }); return null; }
export function instanceNominationKey(input: MetronomeHgUsdcCandidateSeedV1 | MetronomeHgUsdcCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: MetronomeHgUsdcObservationV1): Hash { return hashDomain("aloha/metronome-hgusdc/candidate-snapshot/v1", { familyDefinitionHash: METRONOME_HGUSDC_FAMILY_DEFINITION_HASH, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, rawLocatorHash: input.rawLocatorHash }); }
export type MetronomeHgUsdcNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: MetronomeHgUsdcCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominateMetronomeHgUsdc(input: MetronomeHgUsdcCandidateSeedV1): MetronomeHgUsdcNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff), n = BigInt(input.evidence.blockNumber), end = BigInt(cutoff.number); if (n > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (n < end - BigInt(METRONOME_HGUSDC_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target), key = instanceNominationKey({ target, evidence: input.evidence }); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: key, candidateSnapshotHash: candidateSnapshotHash({ ...input.evidence, target }), evidence: Object.freeze({ ...input.evidence, target, cutoff }) }) }); }
export function candidateFamilyKey(candidate: MetronomeHgUsdcCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }
export type MetronomeHgUsdcIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: MetronomeHgUsdcIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "reverse-identity-mismatch" };
export function verifyMetronomeHgUsdcIdentityStage(input: { readonly candidate: MetronomeHgUsdcCandidateV1; readonly reads: MetronomeHgUsdcIdentityReadFactsV1 }): MetronomeHgUsdcIdentityOutcomeV1 { const r = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), reverseTarget: canonicalAddress(input.reads.reverseTarget), router: canonicalAddress(input.reads.router), curve: canonicalAddress(input.reads.curve), vault: canonicalAddress(input.reads.vault), tokenIn: canonicalAddress(input.reads.tokenIn), curveIntermediate: canonicalAddress(input.reads.curveIntermediate), tokenOut: canonicalAddress(input.reads.tokenOut) }; if (!cutoffEqual(r.cutoff, input.candidate.evidence.cutoff)) throw new TypeError("metronome hgUSDC identity cutoff mismatch"); if (r.target !== canonicalAddress(input.candidate.target) || r.reverseTarget !== r.target || r.router !== r.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; const projection = metronomeHgUsdcProjection({ router: r.router, curve: r.curve, vault: r.vault, tokenIn: r.tokenIn, curveIntermediate: r.curveIntermediate, tokenOut: r.tokenOut, pathHash: r.pathHash }); const facts = Object.freeze({ ...projection }); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: r.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey: r.router, factsHash: hashDomain("aloha/metronome-hgusdc/identity-facts/v1", facts), facts }) }); }
export function identityDescriptorHash(identity: MetronomeHgUsdcIdentityV1): Hash { return hashDomain("aloha/metronome-hgusdc/instance-descriptor/v1", { familyDefinitionHash: METRONOME_HGUSDC_FAMILY_DEFINITION_HASH, factsHash: identity.factsHash, instanceKey: identity.instanceKey }); }
export type MetronomeHgUsdcMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: MetronomeHgUsdcMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" };
export function materializeMetronomeHgUsdc(input: { readonly identity: MetronomeHgUsdcIdentityV1; readonly read: MetronomeHgUsdcStateReadFactsV1 }): MetronomeHgUsdcMaterializationOutcomeV1 { const r = { ...input.read, cutoff: assertCutoff(input.read.cutoff), instanceKey: canonicalAddress(input.read.instanceKey) }; if (!cutoffEqual(r.cutoff, input.identity.cutoff)) throw new TypeError("metronome hgUSDC state cutoff mismatch"); if (r.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; const stateHash = hashDomain("aloha/metronome-hgusdc/materialized-state/v1", { identityFactsHash: input.identity.factsHash, projectionHash: r.projectionHash }); return Object.freeze({ status: "verified", state: Object.freeze({ ...r, identityFactsHash: input.identity.factsHash, stateHash }) }); }
export function deriveMetronomeHgUsdcRoutes(identity: MetronomeHgUsdcIdentityV1): readonly MetronomeHgUsdcRouteV1[] { const route = { instanceKey: identity.instanceKey, inputAsset: identity.facts.tokenIn, outputAsset: identity.facts.tokenOut }; return Object.freeze([Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/metronome-hgusdc/route-binding/v1", route) })]); }
export function assertMetronomeHgUsdcRoute(route: MetronomeHgUsdcRouteV1, identity: MetronomeHgUsdcIdentityV1): void { if (route.instanceKey !== identity.instanceKey || route.inputAsset !== identity.facts.tokenIn || route.outputAsset !== identity.facts.tokenOut) throw new TypeError("metronome hgUSDC route identity mismatch"); }
export type MetronomeHgUsdcCoarseOutcomeV1 = { readonly status: "unavailable"; readonly reasonCode: "dependent-quote-not-in-release" };
export function coarseMetronomeHgUsdc(): MetronomeHgUsdcCoarseOutcomeV1 { return Object.freeze({ status: "unavailable", reasonCode: "dependent-quote-not-in-release" }); }
export type MetronomeHgUsdcExactOutcomeV1 = { readonly status: "unavailable"; readonly reasonCode: "dependent-quote-not-in-release" };
export function exactMetronomeHgUsdc(): MetronomeHgUsdcExactOutcomeV1 { return Object.freeze({ status: "unavailable", reasonCode: "dependent-quote-not-in-release" }); }
export function buildMetronomeHgUsdcAction(input: { readonly identity: MetronomeHgUsdcIdentityV1; readonly calldata: string }): MetronomeHgUsdcActionV1 { if (!/^0x[0-9a-fA-F]*$/.test(input.calldata) || input.calldata.length % 2 !== 0) throw new TypeError("metronome hgUSDC calldata is not canonical"); const payload = { cutoff: input.identity.cutoff, target: canonicalAddress(input.identity.instanceKey), calldata: input.calldata, bindingHash: input.identity.factsHash }; return Object.freeze({ ...payload, actionHash: hashDomain("aloha/metronome-hgusdc/action/v1", payload) }); }
export const METRONOME_HGUSDC_ACTION_PORT = Object.freeze({ actionOwnerId: METRONOME_HGUSDC_ACTION_OWNER_ID, build: buildMetronomeHgUsdcAction });
export function compileMetronomeHgUsdcExecution(input: { readonly identity: MetronomeHgUsdcIdentityV1; readonly action: MetronomeHgUsdcActionV1 }): MetronomeHgUsdcExecutionIntentV1 { if (input.action.target !== canonicalAddress(input.identity.instanceKey)) throw new TypeError("metronome hgUSDC execution target mismatch"); return Object.freeze({ kind: "metronome-hgusdc-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, bindingHash: input.action.bindingHash }); }
export function captureMetronomeHgUsdcEvidence(input: { readonly observation: MetronomeHgUsdcObservationV1; readonly pattern: MetronomeHgUsdcDiscoveryPatternV1 }): MetronomeHgUsdcCandidateSeedV1 | null { return decodeMetronomeHgUsdcCandidate(input.observation, input.pattern); }
export const METRONOME_HGUSDC_RUNTIME = Object.freeze({ manifest: METRONOME_HGUSDC_MANIFEST, discover: decodeMetronomeHgUsdcCandidate, capture: captureMetronomeHgUsdcEvidence, nominate: nominateMetronomeHgUsdc, identity: verifyMetronomeHgUsdcIdentityStage, materialize: materializeMetronomeHgUsdc, routes: deriveMetronomeHgUsdcRoutes, coarse: coarseMetronomeHgUsdc, exact: exactMetronomeHgUsdc, execute: compileMetronomeHgUsdcExecution });
export const METRONOME_HGUSDC_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateMetronomeHgUsdc });
export const METRONOME_HGUSDC_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyMetronomeHgUsdcIdentityStage });
export const METRONOME_HGUSDC_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeMetronomeHgUsdc });
export const METRONOME_HGUSDC_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveMetronomeHgUsdcRoutes });
export const METRONOME_HGUSDC_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveMetronomeHgUsdcRoutes });
