import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { METRONOME_HGUSDC_FAMILY_ID } from "./manifest.ts";
export interface MetronomeHgUsdcCutoffV1 { readonly chainId: string; readonly number: string; readonly hash: Hash; readonly stateRoot: Hash; }
export interface MetronomeHgUsdcObservationV1 { readonly kind: "log" | "call" | "address-surface"; readonly cutoff: MetronomeHgUsdcCutoffV1; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly target: string; readonly rawLocatorHash: Hash; }
export interface MetronomeHgUsdcCandidateV1 { readonly target: string; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly evidence: MetronomeHgUsdcObservationV1; }
export interface MetronomeHgUsdcIdentityReadFactsV1 { readonly cutoff: MetronomeHgUsdcCutoffV1; readonly target: string; readonly reverseTarget: string; readonly router: string; readonly curve: string; readonly vault: string; readonly tokenIn: string; readonly curveIntermediate: string; readonly tokenOut: string; readonly pathHash: Hash; }
export interface MetronomeHgUsdcProjectionV1 { readonly router: string; readonly curve: string; readonly vault: string; readonly tokenIn: string; readonly curveIntermediate: string; readonly tokenOut: string; readonly curveDirection: readonly [1, 0]; readonly pathHash: Hash; readonly quoteChain: "curve-get-dy->vault-preview-redeem-v1"; }
export interface MetronomeHgUsdcIdentityV1 { readonly cutoff: MetronomeHgUsdcCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: Omit<MetronomeHgUsdcIdentityReadFactsV1, "cutoff" | "target" | "reverseTarget">; }
export interface MetronomeHgUsdcStateReadFactsV1 { readonly cutoff: MetronomeHgUsdcCutoffV1; readonly instanceKey: string; readonly projectionHash: Hash; }
export interface MetronomeHgUsdcMaterializedStateV1 extends MetronomeHgUsdcStateReadFactsV1 { readonly identityFactsHash: Hash; readonly stateHash: Hash; }
export interface MetronomeHgUsdcRouteV1 { readonly instanceKey: string; readonly inputAsset: string; readonly outputAsset: string; readonly routeBindingHash: Hash; }
export interface MetronomeHgUsdcActionV1 { readonly cutoff: MetronomeHgUsdcCutoffV1; readonly target: string; readonly calldata: string; readonly bindingHash: Hash; readonly actionHash: Hash; }
export interface MetronomeHgUsdcExecutionIntentV1 { readonly kind: "metronome-hgusdc-execution-intent"; readonly cutoff: MetronomeHgUsdcCutoffV1; readonly target: string; readonly calldata: string; readonly actionHash: Hash; readonly bindingHash: Hash; }
export function canonicalAddress(v: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(v)) throw new TypeError("metronome hgUSDC address must be 20 bytes"); return `0x${v.slice(2).toLowerCase()}`; }
export function assertCutoff(v: MetronomeHgUsdcCutoffV1): MetronomeHgUsdcCutoffV1 { if (!/^\d+$/.test(v.chainId) || !/^\d+$/.test(v.number) || !/^0x[0-9a-f]{64}$/.test(v.hash) || !/^0x[0-9a-f]{64}$/.test(v.stateRoot)) throw new TypeError("metronome hgUSDC cutoff is not canonical"); return Object.freeze({ ...v }); }
export function cutoffEqual(a: MetronomeHgUsdcCutoffV1, b: MetronomeHgUsdcCutoffV1): boolean { return a.chainId === b.chainId && a.number === b.number && a.hash === b.hash && a.stateRoot === b.stateRoot; }
export function familyCandidateKey(key: string): Hash { return hashDomain("aloha/family-candidate/v1", { family: METRONOME_HGUSDC_FAMILY_ID, instanceNominationKey: key }); }
