import {
  assertDecimalString,
  assertHash,
  assertNonEmptyString,
  decodeCanonicalJson,
  decodeExactObject,
  deepFreeze,
  encodeCanonicalJson,
  fieldArray,
  hashDomain,
  type CanonicalJson,
  type Hash,
} from "../../../../packages/canonical-codec/src/index.ts";
import { erc20AssetPortBindingV1 } from "../../../../packages/asset-ref/src/index.ts";
import type {
  ExecutionFactSourceV1,
  ProgramInterpretationDraftV1,
  TransportFactV1,
} from "../../../../packages/capability-interpreters/src/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type SchemaRef } from "../../../../packages/capability-contracts/src/index.ts";
import type { FamilyRuntimeStageV1, FamilyStageDefinitionV1, FamilyStageGenericInvocationV1 } from "../../../../packages/family-sdk/runtime/index.ts";
import type { FrozenProgramEnvelopeV1, ProgramSourceAnchorV1 } from "../../../../packages/request-program/src/index.ts";
import { sealInstancePublication, validateInstancePublication, type InstancePublicationV1 } from "../../../../packages/catalog/src/index.ts";
import { candidateEvidenceRoot, candidateSubjectHash, decodeCanonicalCutoff, decodeCandidateEvidenceRef, familyCandidateKey as centralFamilyCandidateKey, type CandidateEvidenceRefV1, type CandidateRecordV1, type CanonicalCutoffV1, type SourcePlanEvidenceRefV1 } from "../../../../packages/discovery/src/index.ts";
import { CURVE_UNDERLYING_FAMILY_AUTHORING_HASH } from "../family-definition.ts";
import { CURVE_METAREGISTRY, CURVE_UNDERLYING_FAMILY_ID, CURVE_UNDERLYING_FAMILY_VERSION, CURVE_UNDERLYING_I128_SWAP_TOPIC, CURVE_UNDERLYING_UINT_SWAP_TOPIC, CURVE_UNDERLYING_CAPABILITY_IDS } from "../manifest.ts";
import { decodeCurveUnderlyingCandidate, sourceCandidateSnapshotHash } from "../discovery.ts";
import { nominateCurveUnderlying } from "../nomination.ts";
import { verifyCurveUnderlyingIdentityStage, curveIdentityDescriptorHash } from "../identity.ts";
import { materializeCurveUnderlying, resealCurveState } from "../instance.ts";
import { deriveCurveUnderlyingRoutes } from "../routes.ts";
import type { CurveCandidateV1, CurveCutoffV1, CurveIdentityV1, CurveMaterializedStateV1, CurveStateReadFactsV1, CurveObservationV1 } from "../types.ts";

const VERSION = asCapabilityVersion(CURVE_UNDERLYING_FAMILY_VERSION);
export const CURVE_UNDERLYING_STAGE_IDS = Object.freeze({
  nomination: `family.${CURVE_UNDERLYING_FAMILY_ID}.nomination`,
  identity: `family.${CURVE_UNDERLYING_FAMILY_ID}.identity`,
  materialization: `family.${CURVE_UNDERLYING_FAMILY_ID}.materialization`,
  projection: `family.${CURVE_UNDERLYING_FAMILY_ID}.projection`,
  rehydration: `family.${CURVE_UNDERLYING_FAMILY_ID}.rehydration`,
});
export const CURVE_UNDERLYING_STAGE_SCHEMA_HASHES = Object.freeze({
  nomination: hashDomain("aloha/curve-underlying/stage-schema/v1", "nomination"),
  identity: hashDomain("aloha/curve-underlying/stage-schema/v1", "identity"),
  materialization: hashDomain("aloha/curve-underlying/stage-schema/v1", "materialization"),
  projection: hashDomain("aloha/curve-underlying/stage-schema/v1", "projection"),
  rehydration: hashDomain("aloha/curve-underlying/stage-schema/v1", "rehydration"),
});
type Stage = keyof typeof CURVE_UNDERLYING_STAGE_IDS;
type CandidateRecord = Omit<CandidateRecordV1, "evidence"> & { readonly evidence: readonly CandidateEvidenceRefV1[] };

interface IdentityMemo {
  readonly kind: "curve-underlying-identity-memo";
  readonly familyId: typeof CURVE_UNDERLYING_FAMILY_ID;
  readonly familyDefinitionHash: Hash;
  readonly familyCandidateKey: Hash;
  readonly instanceNominationKey: string;
  readonly candidateSubjectHash: Hash;
  readonly candidateEvidenceRoot: Hash;
  readonly identity: CurveIdentityV1;
}
interface NominationPayload { readonly kind: "curve-underlying-nomination-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["candidate"]; readonly requestId: Hash }
interface IdentityPayload { readonly kind: "curve-underlying-identity-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["identity"]; readonly requestId: Hash }
interface MaterializationPayload { readonly kind: "curve-underlying-materialization-input"; readonly identityMemo: IdentityMemo; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash }
interface MaterializationOutput { readonly kind: "curve-underlying-materialization-output"; readonly familyId: typeof CURVE_UNDERLYING_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSubjectHash: Hash; readonly candidateEvidenceRoot: Hash; readonly identityMemoHash: Hash; readonly identityFactsHash: Hash; readonly instanceKey: string; readonly state: CurveMaterializedStateV1 }
interface ProjectionPayload { readonly kind: "curve-underlying-projection-input"; readonly identityMemo: IdentityMemo; readonly materialization: MaterializationOutput; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash }
interface RehydrationPayload { readonly kind: "curve-underlying-rehydration-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly priorPublication: InstancePublicationV1; readonly identityMemo: IdentityMemo; readonly readPlan: readonly ["reference"]; readonly referenceHash: Hash; readonly requestId: Hash }

function canonical(value: unknown): CanonicalJson { return decodeCanonicalJson(encodeCanonicalJson(value)); }
function address(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x[0-9a-fA-F]{40}$/.test(text)) throw new TypeError(`${path} must be an address`); return `0x${text.slice(2).toLowerCase()}`; }
function bytes(value: unknown, path: string): string { const text = assertNonEmptyString(value, path); if (!/^0x(?:[0-9a-f]{2})*$/.test(text)) throw new TypeError(`${path} must be lowercase bytes`); return text; }
function cutoff(value: unknown, path: string): CanonicalCutoffV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function source(value: unknown, path: string): ProgramSourceAnchorV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function factSource(value: unknown, path: string): ExecutionFactSourceV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), blockNumber: (item, itemPath) => assertDecimalString(item, itemPath), blockHash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath), executorAuthorityRoot: (item, itemPath) => assertHash(item, itemPath), workerEpoch: (item, itemPath) => assertNonEmptyString(item, itemPath), executorSessionHash: (item, itemPath) => assertHash(item, itemPath) }, path); }
function sameCutoff(left: CurveCutoffV1, right: CurveCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
function sameSource(left: ExecutionFactSourceV1, right: ProgramSourceAnchorV1): boolean { return left.chainId === right.chainId && left.blockNumber === right.number && left.blockHash === right.hash && left.stateRoot === right.stateRoot; }
function factData(value: string, _path: string): CanonicalJson { const raw = value.slice(2); const bytesValue = new Uint8Array(raw.length / 2); for (let i = 0; i < bytesValue.length; i += 1) bytesValue[i] = Number.parseInt(raw.slice(i * 2, i * 2 + 2), 16); return decodeCanonicalJson(new TextDecoder().decode(bytesValue)); }
function invalidCode(error: unknown, fallback: string): string { const raw = error instanceof Error ? error.message : String(error); const code = raw.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); return /^[a-z][a-z0-9-]*$/.test(code) ? code : fallback; }
function requestId(phase: string, target: string, cutoffValue: CanonicalCutoffV1, candidateSnapshotHash: Hash, operation: string): Hash { return hashDomain("aloha/curve-underlying/runtime-request/v1", { phase, target, cutoff: cutoffValue, candidateSnapshotHash, operation }); }
function requestedArtifactDependencyRoot(identity: CurveIdentityV1): Hash { return hashDomain("aloha/curve-underlying/requested-artifacts/v2", { identityFactsHash: identity.factsHash }); }
function validityDependencyRoot(identity: CurveIdentityV1): Hash { return hashDomain("aloha/curve-underlying/identity-validity/v2", { identityFactsHash: identity.factsHash, descriptorHash: curveIdentityDescriptorHash(identity) }); }
function referenceHash(candidate: CandidateRecord, cutoffValue: CanonicalCutoffV1, publication: InstancePublicationV1): Hash { return hashDomain("aloha/curve-underlying/rehydration-reference/v3", { oldInstancePublicationHash: publication.instancePublicationHash, familyCandidateKey: candidate.familyCandidateKey, candidateSubjectHash: candidate.candidateSubjectHash, cutoff: cutoffValue, requestedArtifactDependencyRoot: publication.requestedArtifactDependencyRoot, descriptorHash: publication.descriptorHash, validityDependencyRoot: publication.validityDependencyRoot }); }

function candidateRecord(value: unknown, path = "curve-underlying.candidate"): CandidateRecord {
  const decoded = decodeExactObject<CandidateRecord>(value, {
    kind: (item, itemPath) => { if (item !== "aloha.candidate-record") throw new TypeError(`${itemPath} kind mismatch`); return item; },
    version: (item, itemPath) => { if (item !== "2") throw new TypeError(`${itemPath} version mismatch`); return item; },
    familyId: (item, itemPath) => { if (item !== CURVE_UNDERLYING_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return CURVE_UNDERLYING_FAMILY_ID; },
    familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath),
    instanceNominationKey: (item, itemPath) => address(item, itemPath),
    familyCandidateKey: (item, itemPath) => assertHash(item, itemPath),
    candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath),
    candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath),
    evidence: (item, itemPath) => fieldArray(item, (entry, entryPath) => decodeCandidateEvidenceRef(entry, entryPath), itemPath),
  }, path);
  if (decoded.familyDefinitionHash !== CURVE_UNDERLYING_FAMILY_AUTHORING_HASH) throw new TypeError("curve-underlying candidate definition mismatch");
  if (decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("curve-underlying candidate key mismatch");
  if (decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("curve-underlying candidate subject mismatch");
  if (decoded.candidateEvidenceRoot !== candidateEvidenceRoot(decoded.evidence)) throw new TypeError("curve-underlying candidate evidence root mismatch");
  if (decoded.evidence.length === 0) throw new TypeError("curve-underlying candidate evidence empty");
  const keys = decoded.evidence.map(item => hashDomain("aloha/candidate-evidence-ref/v1", item));
  if (new Set(keys).size !== keys.length || keys.some((item, index) => item !== [...keys].sort()[index])) throw new TypeError("curve-underlying candidate evidence order");
  return deepFreeze(decoded);
}
function reconstructCandidate(record: CandidateRecord, cutoffValue: CanonicalCutoffV1): CurveCandidateV1 {
  let selectedEvidence: CurveCandidateV1["evidence"] | null = null;
  for (const evidence of record.evidence) {
    if (evidence.kind === "source-plan") {
      const target = address(record.instanceNominationKey, "curve-underlying.sourceCandidate.target");
      sourceCandidateSnapshotHash(target, cutoffValue, evidence);
      if (selectedEvidence === null) selectedEvidence = Object.freeze({ kind: "source-plan", cutoff: cutoffValue, target, source: evidence as SourcePlanEvidenceRefV1 });
      continue;
    }
    const topic = evidence.topic.toLowerCase();
    const pattern = topic === CURVE_UNDERLYING_I128_SWAP_TOPIC ? "curve-underlying-i128-log" : topic === CURVE_UNDERLYING_UINT_SWAP_TOPIC ? "curve-underlying-uint-log" : null;
    if (pattern === null) throw new TypeError("curve-underlying candidate evidence pattern mismatch");
    const seed = decodeCurveUnderlyingCandidate({ kind: "log", target: evidence.address, blockNumber: evidence.blockNumber, blockHash: evidence.blockHash, txHash: evidence.txHash, logIndex: evidence.logIndex, rawLocatorHash: evidence.rawLocatorHash, cutoff: cutoffValue, topic0: evidence.topic } as CurveObservationV1, pattern);
    if (seed === null) throw new TypeError("curve-underlying candidate evidence decode failed");
    const nomination = nominateCurveUnderlying(seed);
    if (nomination.status !== "nominated") throw new TypeError(`curve-underlying candidate-${nomination.reasonCode}`);
    if (nomination.candidate.instanceNominationKey !== record.instanceNominationKey) throw new TypeError("curve-underlying candidate lineage mismatch");
    if (selectedEvidence === null) selectedEvidence = nomination.candidate.evidence;
  }
  if (selectedEvidence === null || !sameCutoff(selectedEvidence.cutoff, cutoffValue)) throw new TypeError("curve-underlying candidate evidence missing");
  const target = address(record.instanceNominationKey, "curve-underlying.candidate.target");
  return Object.freeze({ target, instanceNominationKey: target, candidateSnapshotHash: record.candidateSubjectHash, evidence: selectedEvidence });
}
function decodeIdentity(value: unknown, path: string): CurveIdentityV1 {
  const decoded = decodeExactObject<CurveIdentityV1>(value, {
    cutoff: (item, itemPath) => cutoff(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), factsHash: (item, itemPath) => assertHash(item, itemPath),
    facts: (item, itemPath) => decodeExactObject(item, { pool: (field, fieldPath) => address(field, fieldPath), metaRegistry: (field, fieldPath) => address(field, fieldPath), poolHasCode: (field, fieldPath) => { if (typeof field !== "boolean") throw new TypeError(`${fieldPath} must be boolean`); return field; }, handlers: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), underlyingCoins: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), underlyingDecimals: (field, fieldPath) => fieldArray(field, (entry, entryPath) => { if (!Number.isInteger(entry) || (entry as number) < 0 || (entry as number) > 36) throw new TypeError(`${entryPath} invalid decimals`); return entry as number; }, fieldPath), verifiedDirections: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { i: (v, p) => { if (!Number.isInteger(v)) throw new TypeError(`${p} invalid i`); return v as number; }, j: (v, p) => { if (!Number.isInteger(v)) throw new TypeError(`${p} invalid j`); return v as number; }, amountIn: (v, p) => assertDecimalString(v, p), amountOut: (v, p) => assertDecimalString(v, p) }, entryPath), fieldPath) }, itemPath),
  }, path);
  if (decoded.instanceKey !== decoded.facts.pool || decoded.factsHash !== hashDomain("aloha/curve-underlying/identity-facts/v1", decoded.facts)) throw new TypeError("curve-underlying identity hash mismatch");
  return deepFreeze(decoded);
}
function identityMemo(value: unknown, path = "curve-underlying.identityMemo"): IdentityMemo {
  const decoded = decodeExactObject<IdentityMemo>(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-identity-memo") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-identity-memo"; }, familyId: (item, itemPath) => { if (item !== CURVE_UNDERLYING_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return CURVE_UNDERLYING_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), identity: (item, itemPath) => decodeIdentity(item, itemPath) }, path);
  if (decoded.familyDefinitionHash !== CURVE_UNDERLYING_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceNominationKey !== decoded.identity.instanceKey || decoded.candidateSubjectHash !== decoded.identity.candidateSnapshotHash) throw new TypeError("curve-underlying identity memo lineage mismatch");
  return deepFreeze(decoded);
}
function assertCandidateMemoLineage(candidate: CandidateRecord, memo: IdentityMemo): void {
  if (candidate.familyDefinitionHash !== memo.familyDefinitionHash || candidate.familyCandidateKey !== memo.familyCandidateKey || candidate.instanceNominationKey !== memo.instanceNominationKey || candidate.candidateSubjectHash !== memo.candidateSubjectHash || candidate.candidateEvidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("curve-underlying candidate memo lineage mismatch");
}
function decodeState(value: unknown, path: string): CurveMaterializedStateV1 {
  const raw = decodeExactObject<CurveMaterializedStateV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), pool: (item, itemPath) => address(item, itemPath), variant: (item, itemPath) => { if (item !== "plain" && item !== "ng") throw new TypeError(`${itemPath} variant mismatch`); return item; }, A: (item, itemPath) => assertDecimalString(item, itemPath), fee: (item, itemPath) => assertDecimalString(item, itemPath), balances: (item, itemPath) => fieldArray(item, (entry, entryPath) => assertDecimalString(entry, entryPath), itemPath), rates: (item, itemPath) => fieldArray(item, (entry, entryPath) => assertDecimalString(entry, entryPath), itemPath), offpegFeeMultiplier: (item, itemPath) => assertDecimalString(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), stateHash: (item, itemPath) => assertHash(item, itemPath) }, path);
  if (raw.stateHash !== resealCurveState(raw)) throw new TypeError("curve-underlying state hash mismatch");
  return deepFreeze(raw);
}
function decodeMaterializationOutput(value: unknown, path = "curve-underlying.materializationOutput"): MaterializationOutput {
  const decoded = decodeExactObject<MaterializationOutput>(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-materialization-output") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-materialization-output"; }, familyId: (item, itemPath) => { if (item !== CURVE_UNDERLYING_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return CURVE_UNDERLYING_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), state: (item, itemPath) => decodeState(item, itemPath) }, path);
  if (decoded.familyDefinitionHash !== CURVE_UNDERLYING_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.candidateSubjectHash !== candidateSubjectHash(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceKey !== decoded.instanceNominationKey || decoded.instanceKey !== decoded.state.pool || decoded.identityFactsHash !== decoded.state.identityFactsHash) throw new TypeError("curve-underlying materialization lineage mismatch");
  return deepFreeze(decoded);
}
function candidatePayload(value: unknown, path: string): CandidateRecord { return candidateRecord(value, path); }
function readPlan(value: unknown, expected: readonly string[], path: string): readonly string[] { const result = fieldArray(value, (item, itemPath) => assertNonEmptyString(item, itemPath), path); if (result.length !== expected.length || result.some((item, index) => item !== expected[index])) throw new TypeError(`${path} read plan mismatch`); return Object.freeze([...result]); }
function hashValue(value: unknown, path: string): Hash { return assertHash(value, path); }
function nominationPayload(value: unknown, path = "curve-underlying.nominationPayload"): NominationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-nomination-input") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-nomination-input"; }, candidate: (item, itemPath) => candidatePayload(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["candidate"], itemPath) as readonly ["candidate"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function identityPayload(value: unknown, path = "curve-underlying.identityPayload"): IdentityPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-identity-input") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-identity-input"; }, candidate: (item, itemPath) => candidatePayload(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["identity"], itemPath) as readonly ["identity"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function materializationPayload(value: unknown, path = "curve-underlying.materializationPayload"): MaterializationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-materialization-input") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-materialization-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function projectionPayload(value: unknown, path = "curve-underlying.projectionPayload"): ProjectionPayload { const decoded = decodeExactObject<ProjectionPayload>(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-projection-input") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-projection-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), materialization: (item, itemPath) => decodeMaterializationOutput(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.materialization.instanceKey !== decoded.identityMemo.identity.instanceKey || decoded.materialization.identityFactsHash !== decoded.identityMemo.identity.factsHash || decoded.materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", decoded.identityMemo) || decoded.materialization.candidateSubjectHash !== decoded.identityMemo.candidateSubjectHash || decoded.materialization.candidateEvidenceRoot !== decoded.identityMemo.candidateEvidenceRoot) throw new TypeError("curve-underlying projection lineage mismatch"); return decoded; }
function rehydrationPayload(value: unknown, path = "curve-underlying.rehydrationPayload"): RehydrationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-rehydration-input") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-rehydration-input"; }, candidate: (item, itemPath) => candidatePayload(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), priorPublication: (item, itemPath) => { const publication = canonical(item) as unknown as InstancePublicationV1; validateInstancePublication(publication); return publication; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["reference"], itemPath) as readonly ["reference"], referenceHash: (item, itemPath) => hashValue(item, itemPath), requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }

function boundFact(program: FrozenProgramEnvelopeV1, facts: readonly TransportFactV1[], expectedRequestId: Hash): Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }> {
  if (facts.length !== 1) throw new TypeError("curve-underlying transport fact partition mismatch");
  const fact = facts[0]!;
  if (fact.kind === "transportFailure" || fact.requestId !== expectedRequestId || fact.requestFingerprint !== program.requestFingerprint || !sameSource(fact.source, program.source)) throw new TypeError("curve-underlying transport fact binding mismatch");
  return fact;
}
function decodeFact(value: Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }>, path: string): CanonicalJson { return factData(bytes(value.dataHex, `${path}.dataHex`), path); }
function outputObject(value: unknown, path: string): CanonicalJson { const result = canonical(value); if (result === null || typeof result !== "object" || Array.isArray(result)) throw new TypeError(`${path} must be an object`); return result; }
function identityOutput(value: unknown, path = "curve-underlying.identityOutput"): CanonicalJson { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "identityVerified") throw new TypeError(`${itemPath} kind mismatch`); return "identityVerified"; }, familyInstanceKey: (item, itemPath) => address(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); const memo = decoded.identityMemo as IdentityMemo; if (decoded.familyInstanceKey !== memo.identity.instanceKey || decoded.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || decoded.descriptorHash !== curveIdentityDescriptorHash(memo.identity) || decoded.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("curve-underlying identity output lineage mismatch"); return outputObject({ ...decoded, identityMemo: memo }, path); }
function materializationOutput(value: unknown, path = "curve-underlying.materializationOutput"): CanonicalJson { return outputObject(decodeMaterializationOutput(value, path), path); }
function publicationOutput(value: unknown, path = "curve-underlying.projectionOutput"): CanonicalJson { const decoded = canonical(value); if (decoded === null || typeof decoded !== "object" || Array.isArray(decoded)) throw new TypeError(`${path} must be an object`); const publication = decoded as unknown as InstancePublicationV1; validateInstancePublication(publication); const memo = identityMemo(publication.identityMemo, `${path}.identityMemo`); if (publication.familyId !== CURVE_UNDERLYING_FAMILY_ID || publication.familyDefinitionHash !== memo.familyDefinitionHash || publication.familyCandidateKey !== memo.familyCandidateKey || publication.instanceKey !== memo.identity.instanceKey || publication.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || publication.descriptorHash !== curveIdentityDescriptorHash(memo.identity) || publication.evidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("curve-underlying publication lineage mismatch"); return decoded; }
function nominationOutput(value: unknown, path = "curve-underlying.nominationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-nomination-verified") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-nomination-verified"; }, familyId: (item, itemPath) => { if (item !== CURVE_UNDERLYING_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return CURVE_UNDERLYING_FAMILY_ID; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }
function rehydrationOutput(value: unknown, path = "curve-underlying.rehydrationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "verifiedMemoReuseProof") throw new TypeError(`${itemPath} kind mismatch`); return "verifiedMemoReuseProof"; }, familyId: (item, itemPath) => { if (item !== CURVE_UNDERLYING_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return CURVE_UNDERLYING_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), oldInstancePublicationHash: (item, itemPath) => assertHash(item, itemPath), requestedArtifactDependencyRoot: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), validityDependencyRoot: (item, itemPath) => assertHash(item, itemPath), candidateToCanonicalIdentityBindingProof: (item, itemPath) => assertHash(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath), proofHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }

function requireStage(input: FamilyStageGenericInvocationV1, expected: Stage): void { if (input.stage !== expected) throw new TypeError(`curve-underlying-${expected}-stage-mismatch`); }
function requireNoPrior(input: FamilyStageGenericInvocationV1): void { if (input.identityMemo !== null || input.materializationOutput !== null || input.reusePublication != null) throw new TypeError("curve-underlying unexpected prior output"); }
function prepareNomination(input: FamilyStageGenericInvocationV1): NominationPayload { requireStage(input, "nomination"); requireNoPrior(input); const cutoffValue = cutoff(input.cutoff, "curve-underlying.nomination.cutoff"); const candidate = candidateRecord(input.candidate, "curve-underlying.nomination.candidate"); return { kind: "curve-underlying-nomination-input", candidate, cutoff: cutoffValue, readPlan: ["candidate"], requestId: requestId("nomination", candidate.instanceNominationKey, cutoffValue, candidate.candidateSubjectHash, "candidate") }; }
function prepareIdentity(input: FamilyStageGenericInvocationV1): IdentityPayload { requireStage(input, "identity"); requireNoPrior(input); const cutoffValue = cutoff(input.cutoff, "curve-underlying.identity.cutoff"); const candidate = candidateRecord(input.candidate, "curve-underlying.identity.candidate"); return { kind: "curve-underlying-identity-input", candidate, cutoff: cutoffValue, readPlan: ["identity"], requestId: requestId("identity", candidate.instanceNominationKey, cutoffValue, candidate.candidateSubjectHash, "identity") }; }
function prepareMaterialization(input: FamilyStageGenericInvocationV1): MaterializationPayload { requireStage(input, "materialization"); if (input.identityMemo === null || input.materializationOutput !== null) throw new TypeError("curve-underlying materialization prior output mismatch"); const cutoffValue = cutoff(input.cutoff, "curve-underlying.materialization.cutoff"); const candidate = candidateRecord(input.candidate, "curve-underlying.materialization.candidate"); const memo = identityMemo(input.identityMemo, "curve-underlying.materialization.identityMemo"); assertCandidateMemoLineage(candidate, memo); if (!sameCutoff(cutoffValue, memo.identity.cutoff)) throw new TypeError("curve-underlying materialization cutoff mismatch"); return { kind: "curve-underlying-materialization-input", identityMemo: memo, cutoff: cutoffValue, readPlan: ["state"], requestId: requestId("materialization", memo.identity.instanceKey, cutoffValue, memo.candidateSubjectHash, "state") }; }
function prepareProjection(input: FamilyStageGenericInvocationV1): ProjectionPayload { requireStage(input, "projection"); if (input.identityMemo === null || input.materializationOutput === null) throw new TypeError("curve-underlying projection prior output missing"); const cutoffValue = cutoff(input.cutoff, "curve-underlying.projection.cutoff"); const candidate = candidateRecord(input.candidate, "curve-underlying.projection.candidate"); const memo = identityMemo(input.identityMemo, "curve-underlying.projection.identityMemo"); assertCandidateMemoLineage(candidate, memo); const materialization = decodeMaterializationOutput(input.materializationOutput, "curve-underlying.projection.materialization"); if (!sameCutoff(cutoffValue, memo.identity.cutoff) || materialization.instanceKey !== memo.identity.instanceKey || materialization.identityFactsHash !== memo.identity.factsHash || materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || materialization.candidateSubjectHash !== memo.candidateSubjectHash || materialization.candidateEvidenceRoot !== memo.candidateEvidenceRoot) throw new TypeError("curve-underlying projection lineage mismatch"); return { kind: "curve-underlying-projection-input", identityMemo: memo, materialization, cutoff: cutoffValue, readPlan: ["state"], requestId: requestId("projection", memo.identity.instanceKey, cutoffValue, memo.candidateSubjectHash, "state") }; }
function prepareRehydration(input: FamilyStageGenericInvocationV1): RehydrationPayload { requireStage(input, "rehydration"); if (input.identityMemo !== null || input.materializationOutput !== null || input.reusePublication === null) throw new TypeError("curve-underlying rehydration prior publication required"); const cutoffValue = cutoff(input.cutoff, "curve-underlying.rehydration.cutoff"); const candidate = candidateRecord(input.candidate, "curve-underlying.rehydration.candidate"); const priorPublication = canonical(input.reusePublication) as unknown as InstancePublicationV1; validateInstancePublication(priorPublication); const priorMemo = identityMemo(priorPublication.identityMemo, "curve-underlying.rehydration.priorIdentityMemo"); if (priorPublication.familyId !== CURVE_UNDERLYING_FAMILY_ID || priorPublication.familyDefinitionHash !== CURVE_UNDERLYING_FAMILY_AUTHORING_HASH || priorPublication.instanceKey !== candidate.instanceNominationKey || priorPublication.requestedArtifactDependencyRoot !== requestedArtifactDependencyRoot(priorMemo.identity) || priorPublication.descriptorHash !== curveIdentityDescriptorHash(priorMemo.identity) || priorPublication.validityDependencyRoot !== validityDependencyRoot(priorMemo.identity)) throw new TypeError("curve-underlying memo reuse dependency or identity mismatch"); const identity = deepFreeze({ ...priorMemo.identity, cutoff: cutoffValue, candidateSnapshotHash: candidate.candidateSubjectHash }); const currentIdentityMemo = deepFreeze({ kind: "curve-underlying-identity-memo" as const, familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: CURVE_UNDERLYING_FAMILY_AUTHORING_HASH, familyCandidateKey: candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSubjectHash: candidate.candidateSubjectHash, candidateEvidenceRoot: candidate.candidateEvidenceRoot, identity }); const ref = referenceHash(candidate, cutoffValue, priorPublication); return { kind: "curve-underlying-rehydration-input", candidate, cutoff: cutoffValue, priorPublication, identityMemo: currentIdentityMemo, readPlan: ["reference"], referenceHash: ref, requestId: requestId("rehydration", candidate.instanceNominationKey, cutoffValue, candidate.candidateSubjectHash, ref) }; }

function identityFact(value: unknown, path = "curve-underlying.identityFact"): { readonly candidateSnapshotHash: Hash; readonly reads: Parameters<typeof verifyCurveUnderlyingIdentityStage>[0]["reads"] } { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-identity-facts") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-identity-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), reads: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), metaRegistry: (field, fieldPath) => address(field, fieldPath), registryPool: (field, fieldPath) => address(field, fieldPath), poolHasCode: (field, fieldPath) => { if (typeof field !== "boolean") throw new TypeError(`${fieldPath} must be boolean`); return field; }, handlers: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), underlyingCoins: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), underlyingDecimals: (field, fieldPath) => fieldArray(field, (entry, entryPath) => { if (!Number.isInteger(entry)) throw new TypeError(`${entryPath} invalid decimal`); return entry as number; }, fieldPath), verifiedDirections: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { i: (v, p) => { if (!Number.isInteger(v)) throw new TypeError(`${p} invalid i`); return v as number; }, j: (v, p) => { if (!Number.isInteger(v)) throw new TypeError(`${p} invalid j`); return v as number; }, amountIn: (v, p) => assertDecimalString(v, p), amountOut: (v, p) => assertDecimalString(v, p) }, entryPath), fieldPath) }, itemPath) }, path); return decoded; }
function stateFact(value: unknown, path = "curve-underlying.stateFact"): CurveStateReadFactsV1 { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "curve-underlying-state-facts") throw new TypeError(`${itemPath} kind mismatch`); return "curve-underlying-state-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, read: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), variant: (field, fieldPath) => { if (field !== "plain" && field !== "ng") throw new TypeError(`${fieldPath} variant mismatch`); return field; }, A: (field, fieldPath) => assertDecimalString(field, fieldPath), fee: (field, fieldPath) => assertDecimalString(field, fieldPath), balances: (field, fieldPath) => fieldArray(field, (entry, entryPath) => assertDecimalString(entry, entryPath), fieldPath), rates: (field, fieldPath) => fieldArray(field, (entry, entryPath) => assertDecimalString(entry, entryPath), fieldPath), offpegFeeMultiplier: (field, fieldPath) => assertDecimalString(field, fieldPath) }, itemPath) }, path); return decoded.read; }
function ack(value: unknown, path: string, kind: string): Hash { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== kind) throw new TypeError(`${itemPath} kind mismatch`); return kind; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, value: (item, itemPath) => assertHash(item, itemPath) }, path); return decoded.value; }
function publication(payload: ProjectionPayload, _program: FrozenProgramEnvelopeV1): InstancePublicationV1 { const identity = payload.identityMemo.identity; const routes = deriveCurveUnderlyingRoutes(identity); const transitions = routes.map(route => ({ inputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.inputToken), portRef: hashDomain("aloha/curve-underlying/port/v1", { instanceKey: route.instanceKey, role: "input", token: route.inputToken }), ordinal: "0" }], outputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.outputToken), portRef: hashDomain("aloha/curve-underlying/port/v1", { instanceKey: route.instanceKey, role: "output", token: route.outputToken }), ordinal: "0" }], opaqueTransitionRef: hashDomain("aloha/curve-underlying/transition/v1", route), constraintRefs: [payload.materialization.state.stateHash], staticProjectionHash: hashDomain("aloha/curve-underlying/static-transition/v1", route) })); const memo = canonical(payload.identityMemo); return sealInstancePublication({ familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: CURVE_UNDERLYING_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.materialization.familyCandidateKey, instanceKey: identity.instanceKey, cutoff: payload.cutoff, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: curveIdentityDescriptorHash(identity), staticProjectionMemoHash: hashDomain("aloha/curve-underlying/static-projection/v1", { routes, stateHash: payload.materialization.state.stateHash }), requestedArtifactDependencyRoot: requestedArtifactDependencyRoot(identity), validityDependencyRoot: validityDependencyRoot(identity), transitions, evidenceRoot: payload.materialization.candidateEvidenceRoot }); }
function interpretNomination(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = nominationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "curve-underlying-nomination-reverted" }; const snapshot = ack(decodeFact(fact, "curve-underlying.nomination"), "curve-underlying.nomination", "curve-underlying-nomination-facts"); if (snapshot !== payload.candidate.candidateSubjectHash) throw new TypeError("curve-underlying nomination acknowledgement mismatch"); return { kind: "verified", output: { kind: "curve-underlying-nomination-verified", familyId: CURVE_UNDERLYING_FAMILY_ID, candidateSnapshotHash: snapshot, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: hashDomain("aloha/curve-underlying/nomination-reference/v1", { candidateSnapshotHash: snapshot, cutoff: payload.cutoff }) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "curve-underlying-nomination-invalid") }; } }
function interpretIdentity(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = identityPayload(input.payload); const candidate = reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "curve-underlying-identity-reverted" }; const decoded = identityFact(decodeFact(fact, "curve-underlying.identity")); if (decoded.candidateSnapshotHash !== payload.candidate.candidateSubjectHash) throw new TypeError("curve-underlying identity fact snapshot mismatch"); const result = verifyCurveUnderlyingIdentityStage({ candidate, reads: decoded.reads }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const memo: IdentityMemo = { kind: "curve-underlying-identity-memo", familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: CURVE_UNDERLYING_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, candidateEvidenceRoot: payload.candidate.candidateEvidenceRoot, identity: result.identity }; return { kind: "verified", output: { kind: "identityVerified", familyInstanceKey: result.identity.instanceKey, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: curveIdentityDescriptorHash(result.identity), evidenceRoot: memo.candidateEvidenceRoot } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "curve-underlying-identity-invalid") }; } }
function interpretMaterialization(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = materializationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "curve-underlying-materialization-reverted" }; const read = stateFact(decodeFact(fact, "curve-underlying.state")); if (!sameCutoff(read.cutoff, payload.cutoff) || read.pool !== payload.identityMemo.identity.instanceKey) throw new TypeError("curve-underlying state fact lineage mismatch"); const result = materializeCurveUnderlying({ identity: payload.identityMemo.identity, read }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const output: MaterializationOutput = { kind: "curve-underlying-materialization-output", familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: CURVE_UNDERLYING_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.identityMemo.familyCandidateKey, instanceNominationKey: payload.identityMemo.instanceNominationKey, candidateSubjectHash: payload.identityMemo.candidateSubjectHash, candidateEvidenceRoot: payload.identityMemo.candidateEvidenceRoot, identityMemoHash: hashDomain("aloha/identity-memo/v1", payload.identityMemo), identityFactsHash: payload.identityMemo.identity.factsHash, instanceKey: result.state.pool, state: result.state }; return { kind: "verified", output }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "curve-underlying-materialization-invalid") }; } }
function interpretProjection(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = projectionPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "curve-underlying-projection-reverted" }; const read = stateFact(decodeFact(fact, "curve-underlying.projection.state")); const result = materializeCurveUnderlying({ identity: payload.identityMemo.identity, read }); if (result.status !== "verified") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; if (result.state.stateHash !== payload.materialization.state.stateHash) throw new TypeError("curve-underlying projection state lineage mismatch"); return { kind: "verified", output: publication(payload, input.program) }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "curve-underlying-projection-invalid") }; } }
function interpretRehydration(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = rehydrationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "curve-underlying-rehydration-reverted" }; const actual = ack(decodeFact(fact, "curve-underlying.rehydration"), "curve-underlying.rehydration", "curve-underlying-rehydration-facts"); if (actual !== payload.referenceHash) throw new TypeError("curve-underlying rehydration acknowledgement mismatch"); const identityMemoHash = hashDomain("aloha/identity-memo/v1", payload.identityMemo); const candidateToCanonicalIdentityBindingProof = hashDomain("aloha/candidate-to-canonical-identity-binding/v1", { familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: payload.candidate.familyDefinitionHash, familyCandidateKey: payload.candidate.familyCandidateKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, oldInstancePublicationHash: payload.priorPublication.instancePublicationHash, identityMemoHash, descriptorHash: payload.priorPublication.descriptorHash }); const proofPayload = { kind: "verifiedMemoReuseProof" as const, familyId: CURVE_UNDERLYING_FAMILY_ID, familyDefinitionHash: payload.candidate.familyDefinitionHash, familyCandidateKey: payload.candidate.familyCandidateKey, candidateSubjectHash: payload.candidate.candidateSubjectHash, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, oldInstancePublicationHash: payload.priorPublication.instancePublicationHash, requestedArtifactDependencyRoot: payload.priorPublication.requestedArtifactDependencyRoot, descriptorHash: payload.priorPublication.descriptorHash, validityDependencyRoot: payload.priorPublication.validityDependencyRoot, candidateToCanonicalIdentityBindingProof, identityMemo: payload.identityMemo, identityMemoHash, evidenceRoot: payload.candidate.candidateEvidenceRoot }; return { kind: "verified", output: { ...proofPayload, proofHash: hashDomain("aloha/verified-memo-reuse-proof/v1", proofPayload) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "curve-underlying-rehydration-invalid") }; } }

function definitionBase(stage: Stage, payloadCodec: { readonly schemaRef: SchemaRef; readonly decodeExact: (value: unknown) => unknown }, outputSchemaRef: Hash, outputCodec: { readonly decodeExact: (value: unknown) => CanonicalJson }, prepareIssueValue: FamilyStageDefinitionV1["prepareIssueValue"], interpret: FamilyStageDefinitionV1["interpret"]): FamilyStageDefinitionV1 { return deepFreeze({ stage, capabilityId: asCapabilityId(CURVE_UNDERLYING_STAGE_IDS[stage]), version: VERSION, schemaHash: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES[stage]), payloadCodec: deepFreeze(payloadCodec), dependencyIds: Object.freeze([]), outputSchemaRef, implementationClosureHash: hashDomain("aloha/curve-underlying/runtime-implementation/v1", { stage, module: "families/curve-underlying/src/runtime/definitions.ts" }), outputCodecHash: hashDomain("aloha/curve-underlying/runtime-output-codec/v1", stage), outputCodec: deepFreeze(outputCodec), prepareIssueValue, interpret }); }
const nominationCodec = { schemaRef: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES.nomination), decodeExact: (value: unknown) => nominationPayload(value) };
const identityCodec = { schemaRef: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES.identity), decodeExact: (value: unknown) => identityPayload(value) };
const materializationCodec = { schemaRef: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES.materialization), decodeExact: (value: unknown) => materializationPayload(value) };
const projectionCodec = { schemaRef: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES.projection), decodeExact: (value: unknown) => projectionPayload(value) };
const rehydrationCodec = { schemaRef: asSchemaRef(CURVE_UNDERLYING_STAGE_SCHEMA_HASHES.rehydration), decodeExact: (value: unknown) => rehydrationPayload(value) };
const outputSchema = (stage: Stage): Hash => hashDomain("aloha/curve-underlying/runtime-output-schema/v1", stage);
export const CURVE_UNDERLYING_NOMINATION_DEFINITION = definitionBase("nomination", nominationCodec, outputSchema("nomination"), { decodeExact: value => nominationOutput(value) }, prepareNomination, interpretNomination);
export const CURVE_UNDERLYING_IDENTITY_DEFINITION = definitionBase("identity", identityCodec, outputSchema("identity"), { decodeExact: value => identityOutput(value) }, prepareIdentity, interpretIdentity);
export const CURVE_UNDERLYING_MATERIALIZATION_DEFINITION = definitionBase("materialization", materializationCodec, outputSchema("materialization"), { decodeExact: value => materializationOutput(value) }, prepareMaterialization, interpretMaterialization);
export const CURVE_UNDERLYING_PROJECTION_DEFINITION = definitionBase("projection", projectionCodec, outputSchema("projection"), { decodeExact: value => publicationOutput(value) }, prepareProjection, interpretProjection);
export const CURVE_UNDERLYING_REHYDRATION_DEFINITION = definitionBase("rehydration", rehydrationCodec, outputSchema("rehydration"), { decodeExact: value => rehydrationOutput(value) }, prepareRehydration, interpretRehydration);
export const CURVE_UNDERLYING_NOMINATION_RUNTIME = CURVE_UNDERLYING_NOMINATION_DEFINITION;
export const CURVE_UNDERLYING_IDENTITY_RUNTIME = CURVE_UNDERLYING_IDENTITY_DEFINITION;
export const CURVE_UNDERLYING_MATERIALIZATION_RUNTIME = CURVE_UNDERLYING_MATERIALIZATION_DEFINITION;
export const CURVE_UNDERLYING_PROJECTION_RUNTIME = CURVE_UNDERLYING_PROJECTION_DEFINITION;
export const CURVE_UNDERLYING_REHYDRATION_RUNTIME = CURVE_UNDERLYING_REHYDRATION_DEFINITION;
export const CURVE_UNDERLYING_STAGE_DEFINITIONS: readonly FamilyStageDefinitionV1[] = Object.freeze([CURVE_UNDERLYING_NOMINATION_DEFINITION, CURVE_UNDERLYING_IDENTITY_DEFINITION, CURVE_UNDERLYING_MATERIALIZATION_DEFINITION, CURVE_UNDERLYING_PROJECTION_DEFINITION, CURVE_UNDERLYING_REHYDRATION_DEFINITION]);
export function requireCurveUnderlyingStageDefinition(stage: FamilyRuntimeStageV1): FamilyStageDefinitionV1 { const definition = CURVE_UNDERLYING_STAGE_DEFINITIONS.find(item => item.stage === stage); if (!definition) throw new TypeError(`curve-underlying stage definition missing: ${stage}`); return definition; }
