import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { defineCreditFamilyContract } from "../../../packages/credit/src/index.ts";
import { FLUID_CREDIT_ACTION_OWNER_ID, FLUID_CREDIT_CAPABILITY_IDS, FLUID_CREDIT_FACTORY_SOURCE_PLAN_ID, FLUID_CREDIT_FAMILY_ID, FLUID_CREDIT_FAMILY_VERSION, FLUID_CREDIT_INSTANCE_CONTRACT_SCHEMA_HASH, FLUID_CREDIT_OWNER_REF, FLUID_CREDIT_SOURCE_PLAN_ID } from "./manifest.ts";

const moduleRoot = "families/fluid-credit/src"; const version = asCapabilityVersion(FLUID_CREDIT_FAMILY_VERSION);
export const FLUID_CREDIT_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/fluid-credit/source-plan-schema/v1", FLUID_CREDIT_SOURCE_PLAN_ID));
export const FLUID_CREDIT_FACTORY_SOURCE_PLAN_SCHEMA_HASH = asSchemaRef(hashDomain("aloha/fluid-credit/source-plan-schema/v1", FLUID_CREDIT_FACTORY_SOURCE_PLAN_ID));
export const FLUID_CREDIT_CONTRACT = defineCreditFamilyContract({ familyId: FLUID_CREDIT_FAMILY_ID, version: FLUID_CREDIT_FAMILY_VERSION, actionOwnerId: FLUID_CREDIT_ACTION_OWNER_ID });
type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.fluid-credit.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/fluid-credit/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([FLUID_CREDIT_SOURCE_PLAN_ID, FLUID_CREDIT_FACTORY_SOURCE_PLAN_ID]) } : {}) }); }
function slot(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { const dependencyIds = name === "state" ? [] : [asCapabilityId(FLUID_CREDIT_CAPABILITY_IDS.state)]; return Object.freeze({ capabilityId: asCapabilityId(FLUID_CREDIT_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/fluid-credit/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/fluid-credit/extension-interpreter/v1", name), dependencyIds: Object.freeze(dependencyIds), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "FLUID_CREDIT_RUNTIME" }); }
const nomination = core("nomination", "FLUID_CREDIT_NOMINATION_DEFINITION"); const identity = core("identity", "FLUID_CREDIT_IDENTITY_DEFINITION"); const materialization = core("materialization", "FLUID_CREDIT_MATERIALIZATION_DEFINITION"); const projection = core("projection", "FLUID_CREDIT_PROJECTION_DEFINITION"); const rehydration = core("rehydration", "FLUID_CREDIT_REHYDRATION_DEFINITION"); const state = slot("state"); const coarse = slot("coarse"); const exact = slot("exact");
export const FLUID_CREDIT_ACTION_OWNER = Object.freeze({ ownerId: FLUID_CREDIT_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/fluid-credit/action-schema/v1", "credit-borrow")), implementationHash: hashDomain("aloha/fluid-credit/action-implementation/v1", "credit-borrow"), actionKinds: Object.freeze(["credit-borrow"]), modulePath: `${moduleRoot}/action.ts`, exportName: "FLUID_CREDIT_ACTION_PORT" });
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.fluid-credit.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/fluid-credit/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.fluid-credit.state-observation", version, schemaHash: asSchemaRef(hashDomain("aloha/fluid-credit/fact-schema/v1", "state")) }), Object.freeze({ factContractId: "family.fluid-credit.credit-obligation", version, schemaHash: asSchemaRef(FLUID_CREDIT_CONTRACT.schemaHash) }), Object.freeze({ factContractId: "family.fluid-credit.optional-instance-partition", version, schemaHash: asSchemaRef(FLUID_CREDIT_INSTANCE_CONTRACT_SCHEMA_HASH) })]);
const runtimeAdapter = Object.freeze({ modulePath: `${moduleRoot}/search-adapter.ts`, exportName: "FLUID_CREDIT_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: Object.freeze({ state: asCapabilityId(FLUID_CREDIT_CAPABILITY_IDS.state), coarse: asCapabilityId(FLUID_CREDIT_CAPABILITY_IDS.coarse), exact: asCapabilityId(FLUID_CREDIT_CAPABILITY_IDS.exact) }), actionOwnerIds: Object.freeze({ action: FLUID_CREDIT_ACTION_OWNER_ID }) });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: FLUID_CREDIT_FAMILY_ID, version: FLUID_CREDIT_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/fluid-credit/plugin-code/v1", { moduleRoot, core: [nomination, identity, materialization, projection, rehydration], extensions: [state, coarse, exact], runtimeAdapter, actionOwner: FLUID_CREDIT_ACTION_OWNER, facts }), authorityDeclarationHash: hashDomain("aloha/fluid-credit/authority/v1", FLUID_CREDIT_OWNER_REF), sourcePlans: [{ sourcePlanId: FLUID_CREDIT_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: FLUID_CREDIT_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "FLUID_CREDIT_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "FLUID_CREDIT_SOURCE_NOMINATION_PROGRAM", schemaHash: FLUID_CREDIT_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "FLUID_CREDIT_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "FLUID_CREDIT_NOMINATION_INDEPENDENT_ORACLE" } } } }, { sourcePlanId: FLUID_CREDIT_FACTORY_SOURCE_PLAN_ID, completeness: "complete-snapshot", historyStartBlock: null, schemaHash: FLUID_CREDIT_FACTORY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "FLUID_CREDIT_FACTORY_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "FLUID_CREDIT_FACTORY_NOMINATION_PROGRAM", schemaHash: FLUID_CREDIT_FACTORY_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "FLUID_CREDIT_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "FLUID_CREDIT_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: nomination as never, identity: identity as never, materialization: materialization as never, projection: projection as never, rehydration: rehydration as never }, extensions: { [FLUID_CREDIT_CAPABILITY_IDS.state]: { kind: "present", module: state }, [FLUID_CREDIT_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [FLUID_CREDIT_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: runtimeAdapter }, actionOwners: [FLUID_CREDIT_ACTION_OWNER], acceptanceDeclarations: facts };
export const FLUID_CREDIT_DEFINITION_INPUT = defineFamily(input); export const FLUID_CREDIT_AUTHORING_HASH: Hash = familyAuthoringDigest(FLUID_CREDIT_DEFINITION_INPUT);
