import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { assertCreditObligationSet, makeCreditObligationSet, type CreditEffectObservationV1 } from "../../../packages/credit/src/index.ts";
import { FLUID_CREDIT_ACTION_OWNER_ID, FLUID_CREDIT_EVIDENCE_TOPIC, FLUID_CREDIT_FAMILY_ID, FLUID_CREDIT_FAMILY_VERSION, FLUID_CREDIT_MANIFEST, FLUID_CREDIT_SOURCE_WINDOW_BLOCKS } from "./manifest.ts";
import { encodeFluidOperate, effectRoot, fluidDebtAmount, positiveAmount, validDecimals } from "./kernel/math.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type FluidCreditActionV1, type FluidCreditCandidateV1, type FluidCreditCutoffV1, type FluidCreditEffectProofV1, type FluidCreditExecutionIntentV1, type FluidCreditIdentityReadFactsV1, type FluidCreditIdentityV1, type FluidCreditMaterializedStateV1, type FluidCreditObservationV1, type FluidCreditQuoteV1, type FluidCreditRouteV1, type FluidCreditStateReadFactsV1 } from "./types.ts";

export const FLUID_CREDIT_CONTRACT_PATTERN = "fluid-credit-operate-log" as const;
export interface FluidCreditCandidateSeedV1 { readonly target: string; readonly evidence: FluidCreditObservationV1 }
export function decodeFluidCreditCandidate(observation: FluidCreditObservationV1, pattern: typeof FLUID_CREDIT_CONTRACT_PATTERN): FluidCreditCandidateSeedV1 | null { if (pattern !== FLUID_CREDIT_CONTRACT_PATTERN || observation.kind !== "log" || observation.topic !== FLUID_CREDIT_EVIDENCE_TOPIC) return null; const target = canonicalAddress(observation.target); return Object.freeze({ target, evidence: Object.freeze({ ...observation, target }) }); }
export function instanceNominationKey(input: FluidCreditCandidateSeedV1 | FluidCreditCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: FluidCreditObservationV1): Hash { return hashDomain("aloha/fluid-credit/candidate-snapshot/v1", { familyId: FLUID_CREDIT_FAMILY_ID, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, topic: input.topic, rawLocatorHash: input.rawLocatorHash }); }
export type FluidCreditNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: FluidCreditCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominateFluidCredit(input: FluidCreditCandidateSeedV1): FluidCreditNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff); const block = BigInt(input.evidence.blockNumber); const end = BigInt(cutoff.number); if (block > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (block < end - BigInt(FLUID_CREDIT_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target); const evidence = Object.freeze({ ...input.evidence, target, cutoff }); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: instanceNominationKey({ target, evidence }), candidateSnapshotHash: candidateSnapshotHash(evidence), evidence }) }); }
export function candidateFamilyKey(candidate: FluidCreditCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }

export type FluidCreditIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: FluidCreditIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "reverse-identity-mismatch" | "vault-invalid" | "asset-pair-invalid" | "code-missing" | "inactive-behavior" };
export function verifyFluidCreditIdentityStage(input: { readonly candidate: FluidCreditCandidateV1; readonly reads: FluidCreditIdentityReadFactsV1 }): FluidCreditIdentityOutcomeV1 { const reads = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), factory: canonicalAddress(input.reads.factory), reverseVault: canonicalAddress(input.reads.reverseVault), collateralAsset: canonicalAddress(input.reads.collateralAsset), debtAsset: canonicalAddress(input.reads.debtAsset), vaultId: positiveAmount(input.reads.vaultId, "vaultId").toString(), collateralDecimals: validDecimals(input.reads.collateralDecimals, "collateral"), debtDecimals: validDecimals(input.reads.debtDecimals, "debt") }; if (!cutoffEqual(reads.cutoff, input.candidate.evidence.cutoff)) throw new TypeError("fluid-credit identity cutoff mismatch"); if (reads.target !== canonicalAddress(input.candidate.target) || reads.reverseVault !== reads.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; if (reads.target === "0x0000000000000000000000000000000000000000" || reads.factory === "0x0000000000000000000000000000000000000000") return { status: "chain-proven-rejected", reasonCode: "vault-invalid" }; if (reads.collateralAsset === reads.debtAsset || reads.collateralAsset === "0x0000000000000000000000000000000000000000" || reads.debtAsset === "0x0000000000000000000000000000000000000000") return { status: "chain-proven-rejected", reasonCode: "asset-pair-invalid" }; if (!reads.vaultHasCode || !reads.collateralAssetHasCode || !reads.debtAssetHasCode) return { status: "chain-proven-rejected", reasonCode: "code-missing" }; const active = reads.activeProbe.actor !== "0x0000000000000000000000000000000000000000" && positiveAmount(reads.activeProbe.nftId) > 0n && positiveAmount(reads.activeProbe.finalSupply) > 0n && positiveAmount(reads.activeProbe.finalBorrow) > 0n && reads.activeProbe.collateralDelta === `-${reads.activeProbe.collateralAmount}` && reads.activeProbe.debtDelta === reads.activeProbe.debtAmount; if (!active) return { status: "chain-proven-rejected", reasonCode: "inactive-behavior" }; const facts = Object.freeze({ vault: reads.target, factory: reads.factory, vaultId: reads.vaultId, collateralAsset: reads.collateralAsset, debtAsset: reads.debtAsset, collateralDecimals: reads.collateralDecimals, debtDecimals: reads.debtDecimals, activeProbeActor: canonicalAddress(reads.activeProbe.actor) }); const factsHash = hashDomain("aloha/fluid-credit/identity-facts/v1", facts); const instanceKey = hashDomain("aloha/fluid-credit/instance/v1", facts); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: reads.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey, factsHash, facts }) }); }
export function identityDescriptorHash(identity: FluidCreditIdentityV1): Hash { return hashDomain("aloha/fluid-credit/instance-descriptor/v1", { familyId: FLUID_CREDIT_FAMILY_ID, version: FLUID_CREDIT_FAMILY_VERSION, instanceKey: identity.instanceKey, factsHash: identity.factsHash }); }

export type FluidCreditMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: FluidCreditMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" | "state-invalid" };
export function materializeFluidCredit(input: { readonly identity: FluidCreditIdentityV1; readonly read: FluidCreditStateReadFactsV1 }): FluidCreditMaterializationOutcomeV1 { const read = { ...input.read, cutoff: assertCutoff(input.read.cutoff) }; if (!cutoffEqual(read.cutoff, input.identity.cutoff)) throw new TypeError("fluid-credit materialization cutoff mismatch"); if (read.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; try { positiveAmount(read.availableCollateral); positiveAmount(read.debtCapacity); } catch { return { status: "chain-proven-rejected", reasonCode: "state-invalid" }; } const stateHash = hashDomain("aloha/fluid-credit/materialized-state/v1", { identityFactsHash: input.identity.factsHash, availableCollateral: read.availableCollateral, debtCapacity: read.debtCapacity }); return Object.freeze({ status: "verified", state: Object.freeze({ ...read, identityFactsHash: input.identity.factsHash, stateHash }) }); }
export function resealFluidCreditState(state: FluidCreditMaterializedStateV1): Hash { return hashDomain("aloha/fluid-credit/materialized-state/v1", { identityFactsHash: state.identityFactsHash, availableCollateral: state.availableCollateral, debtCapacity: state.debtCapacity }); }

export function deriveFluidCreditRoutes(identity: FluidCreditIdentityV1): readonly FluidCreditRouteV1[] { const route = { instanceKey: identity.instanceKey, vault: identity.facts.vault, collateralAsset: identity.facts.collateralAsset, debtAsset: identity.facts.debtAsset, lifecycle: "standing-position" as const }; return Object.freeze([Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/fluid-credit/route-binding/v1", route) })]); }
export function assertFluidCreditRoute(route: FluidCreditRouteV1, identity: FluidCreditIdentityV1): void { const expected = hashDomain("aloha/fluid-credit/route-binding/v1", { instanceKey: route.instanceKey, vault: route.vault, collateralAsset: route.collateralAsset, debtAsset: route.debtAsset, lifecycle: route.lifecycle }); if (route.instanceKey !== identity.instanceKey || route.vault !== identity.facts.vault || route.collateralAsset !== identity.facts.collateralAsset || route.debtAsset !== identity.facts.debtAsset || route.lifecycle !== "standing-position" || route.routeBindingHash !== expected) throw new TypeError("fluid-credit route identity mismatch"); }

export type FluidCreditCoarseOutcomeV1 = { readonly status: "rankable"; readonly quote: { readonly cutoff: FluidCreditCutoffV1; readonly routeBindingHash: Hash; readonly collateralAmount: string; readonly debtBps: string } } | { readonly status: "unavailable"; readonly reasonCode: "invalid-observation" | "route-mismatch" | "capacity-insufficient" };
export function coarseFluidCredit(input: { readonly identity: FluidCreditIdentityV1; readonly state: FluidCreditMaterializedStateV1; readonly route: FluidCreditRouteV1; readonly collateralAmount: string; readonly debtBps: string }): FluidCreditCoarseOutcomeV1 { try { assertFluidCreditRoute(input.route, input.identity); const collateral = positiveAmount(input.collateralAmount); const debt = BigInt(fluidDebtAmount({ collateralAmount: collateral.toString(), debtBps: input.debtBps, collateralDecimals: input.identity.facts.collateralDecimals, debtDecimals: input.identity.facts.debtDecimals })); if (collateral > BigInt(input.state.availableCollateral) || debt > BigInt(input.state.debtCapacity)) return { status: "unavailable", reasonCode: "capacity-insufficient" }; return Object.freeze({ status: "rankable", quote: Object.freeze({ cutoff: input.identity.cutoff, routeBindingHash: input.route.routeBindingHash, collateralAmount: collateral.toString(), debtBps: positiveAmount(input.debtBps).toString() }) }); } catch (error) { return { status: "unavailable", reasonCode: error instanceof TypeError && error.message.includes("route") ? "route-mismatch" : "invalid-observation" }; } }
export function exactFluidCredit(input: { readonly identity: FluidCreditIdentityV1; readonly state: FluidCreditMaterializedStateV1; readonly route: FluidCreditRouteV1; readonly collateralAmount: string; readonly debtBps: string; readonly executor: string; readonly effectProof: FluidCreditEffectProofV1 }): FluidCreditCoarseOutcomeV1 & { readonly status: "rankable"; readonly quote: FluidCreditQuoteV1 } { assertFluidCreditRoute(input.route, input.identity); const collateralAmount = positiveAmount(input.collateralAmount).toString(); const debtAmount = fluidDebtAmount({ collateralAmount, debtBps: input.debtBps, collateralDecimals: input.identity.facts.collateralDecimals, debtDecimals: input.identity.facts.debtDecimals }); assertFluidCreditEffectProof(input.effectProof, input.identity, input.route, input.executor, collateralAmount, debtAmount); if (BigInt(collateralAmount) > BigInt(input.state.availableCollateral) || BigInt(debtAmount) > BigInt(input.state.debtCapacity)) throw new TypeError("fluid-credit exact capacity insufficient"); const effectProofHash = fluidCreditEffectProofHash(input.effectProof); const payload = { cutoff: input.identity.cutoff, routeBindingHash: input.route.routeBindingHash, collateralAmount, debtBps: positiveAmount(input.debtBps).toString(), debtAmount, effectProofHash }; return Object.freeze({ status: "rankable", quote: Object.freeze({ ...payload, effectProof: input.effectProof, quoteHash: hashDomain("aloha/fluid-credit/quote/v2", payload) }) }); }
export function assertFluidCreditEffectProof(proof: FluidCreditEffectProofV1, identity: FluidCreditIdentityV1, route: FluidCreditRouteV1, executor: string, collateralAmount: string, debtAmount: string): void { if (proof.kind !== "fluid-credit-effect-proof" || !cutoffEqual(proof.cutoff, identity.cutoff) || proof.routeBindingHash !== route.routeBindingHash || canonicalAddress(proof.executor) !== canonicalAddress(executor) || proof.collateralAmount !== collateralAmount || proof.debtAmount !== debtAmount || positiveAmount(proof.nftId) <= 0n || positiveAmount(proof.finalSupply) <= 0n || positiveAmount(proof.finalBorrow) <= 0n || proof.effects.length !== 2 || proof.effects[0]?.token !== identity.facts.collateralAsset || proof.effects[0]?.account !== "executor" || proof.effects[0]?.delta !== `-${collateralAmount}` || proof.effects[1]?.token !== identity.facts.debtAsset || proof.effects[1]?.account !== "executor" || proof.effects[1]?.delta !== debtAmount || proof.effectRoot !== effectRoot(proof.effects)) throw new TypeError("fluid-credit effect proof mismatch"); }
function fluidCreditEffectProofHash(proof: FluidCreditEffectProofV1): Hash { return hashDomain("aloha/fluid-credit/effect-proof/v1", { kind: proof.kind, cutoff: assertCutoff(proof.cutoff), routeBindingHash: proof.routeBindingHash, executor: canonicalAddress(proof.executor), collateralAmount: positiveAmount(proof.collateralAmount).toString(), debtAmount: positiveAmount(proof.debtAmount).toString(), nftId: positiveAmount(proof.nftId).toString(), finalSupply: positiveAmount(proof.finalSupply).toString(), finalBorrow: positiveAmount(proof.finalBorrow).toString(), effects: proof.effects, effectRoot: proof.effectRoot }); }

export function buildFluidCreditAction(input: { readonly identity: FluidCreditIdentityV1; readonly quote: FluidCreditQuoteV1; readonly executor: string }): FluidCreditActionV1 { const route = deriveFluidCreditRoutes(input.identity)[0]!; assertFluidCreditEffectProof(input.quote.effectProof, input.identity, route, input.executor, input.quote.collateralAmount, input.quote.debtAmount); const effectProofHash = fluidCreditEffectProofHash(input.quote.effectProof); const quotePayload = { cutoff: input.identity.cutoff, routeBindingHash: route.routeBindingHash, collateralAmount: positiveAmount(input.quote.collateralAmount).toString(), debtBps: positiveAmount(input.quote.debtBps).toString(), debtAmount: positiveAmount(input.quote.debtAmount).toString(), effectProofHash }; if (!cutoffEqual(input.quote.cutoff, input.identity.cutoff) || input.quote.routeBindingHash !== route.routeBindingHash || input.quote.effectProofHash !== effectProofHash || input.quote.quoteHash !== hashDomain("aloha/fluid-credit/quote/v2", quotePayload)) throw new TypeError("fluid-credit quote lineage mismatch"); const target = input.identity.facts.vault; const calldata = encodeFluidOperate("0", input.quote.collateralAmount, input.quote.debtAmount, input.executor); const actionIntentHash = hashDomain("aloha/fluid-credit/action-intent/v1", { cutoff: input.identity.cutoff, target, calldata, exactQuoteHash: input.quote.quoteHash }); const effects: readonly CreditEffectObservationV1[] = [{ asset: input.identity.facts.collateralAsset, account: "executor", delta: `-${input.quote.collateralAmount}` }, { asset: input.identity.facts.debtAsset, account: "executor", delta: input.quote.debtAmount }]; const obligationSet = makeCreditObligationSet({ familyId: FLUID_CREDIT_FAMILY_ID, instanceKey: input.identity.instanceKey, positionKey: hashDomain("aloha/fluid-credit/position/v1", { instanceKey: input.identity.instanceKey, executor: canonicalAddress(input.executor) }), collateralAsset: input.identity.facts.collateralAsset, collateralAmount: input.quote.collateralAmount, debtAsset: input.identity.facts.debtAsset, debtAmount: input.quote.debtAmount, actionIntentHash, effects }); const payload = { cutoff: input.identity.cutoff, target, calldata, exactQuoteHash: input.quote.quoteHash, actionIntentHash, obligationRoot: obligationSet.obligationRoot }; return Object.freeze({ ...payload, obligationSet, actionHash: hashDomain("aloha/fluid-credit/action/v1", payload) }); }
export const FLUID_CREDIT_ACTION_PORT = Object.freeze({ actionOwnerId: FLUID_CREDIT_ACTION_OWNER_ID, actionKind: "credit-borrow", build: buildFluidCreditAction });
export function compileFluidCreditExecution(input: { readonly identity: FluidCreditIdentityV1; readonly action: FluidCreditActionV1 }): FluidCreditExecutionIntentV1 { if (input.action.target !== input.identity.facts.vault || !cutoffEqual(input.action.cutoff, input.identity.cutoff)) throw new TypeError("fluid-credit execution binding mismatch"); const expectedIntent = hashDomain("aloha/fluid-credit/action-intent/v1", { cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, exactQuoteHash: input.action.exactQuoteHash }); if (expectedIntent !== input.action.actionIntentHash) throw new TypeError("fluid-credit action intent mismatch"); const obligationSet = assertCreditObligationSet(input.action.obligationSet); if (obligationSet.standingPosition.actionIntentHash !== expectedIntent || obligationSet.standingPosition.finalSafety !== "repayment-and-position-safe" || input.action.actionHash !== hashDomain("aloha/fluid-credit/action/v1", { cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, exactQuoteHash: input.action.exactQuoteHash, actionIntentHash: expectedIntent, obligationRoot: obligationSet.obligationRoot })) throw new TypeError("fluid-credit execution obligation lineage mismatch"); const expectedEffects: readonly FluidCreditEffectProofV1["effects"][number][] = [{ token: obligationSet.standingPosition.collateralAsset, account: "executor", delta: `-${obligationSet.standingPosition.collateralAmount}` }, { token: obligationSet.standingPosition.debtAsset, account: "executor", delta: obligationSet.standingPosition.debtAmount }]; return Object.freeze({ kind: "fluid-credit-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, exactQuoteHash: input.action.exactQuoteHash, obligationRoot: obligationSet.obligationRoot, finalSafety: "repayment-and-position-safe", expectedEffects: Object.freeze(expectedEffects) }); }
export function captureFluidCreditEvidence(input: { readonly observation: FluidCreditObservationV1; readonly pattern: typeof FLUID_CREDIT_CONTRACT_PATTERN }): FluidCreditCandidateSeedV1 | null { return decodeFluidCreditCandidate(input.observation, input.pattern); }
export const FLUID_CREDIT_RUNTIME = Object.freeze({ manifest: FLUID_CREDIT_MANIFEST, discover: decodeFluidCreditCandidate, capture: captureFluidCreditEvidence, nominate: nominateFluidCredit, identity: verifyFluidCreditIdentityStage, materialize: materializeFluidCredit, routes: deriveFluidCreditRoutes, coarse: coarseFluidCredit, exact: exactFluidCredit, execute: compileFluidCreditExecution });
export const FLUID_CREDIT_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateFluidCredit });
export const FLUID_CREDIT_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifyFluidCreditIdentityStage });
export const FLUID_CREDIT_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeFluidCredit });
export const FLUID_CREDIT_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveFluidCreditRoutes });
export const FLUID_CREDIT_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveFluidCreditRoutes });
