import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FLUID_CREDIT_FAMILY_ID } from "./manifest.ts";

export interface FluidCreditCutoffV1 { readonly chainId: string; readonly number: string; readonly hash: Hash; readonly stateRoot: Hash }
export interface FluidCreditObservationV1 { readonly kind: "log"; readonly cutoff: FluidCreditCutoffV1; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly target: string; readonly topic: Hash; readonly rawLocatorHash: Hash }
export interface FluidCreditCandidateV1 { readonly target: string; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly evidence: FluidCreditObservationV1 }
export interface FluidCreditActiveProbeV1 { readonly actor: string; readonly collateralAmount: string; readonly debtAmount: string; readonly nftId: string; readonly finalSupply: string; readonly finalBorrow: string; readonly collateralDelta: string; readonly debtDelta: string }
export interface FluidCreditIdentityReadFactsV1 { readonly cutoff: FluidCreditCutoffV1; readonly target: string; readonly factory: string; readonly reverseVault: string; readonly vaultId: string; readonly collateralAsset: string; readonly debtAsset: string; readonly collateralDecimals: number; readonly debtDecimals: number; readonly vaultHasCode: boolean; readonly collateralAssetHasCode: boolean; readonly debtAssetHasCode: boolean; readonly activeProbe: FluidCreditActiveProbeV1 }
export interface FluidCreditIdentityV1 { readonly cutoff: FluidCreditCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: Readonly<{ vault: string; factory: string; vaultId: string; collateralAsset: string; debtAsset: string; collateralDecimals: number; debtDecimals: number; activeProbeActor: string }> }
export interface FluidCreditStateReadFactsV1 { readonly cutoff: FluidCreditCutoffV1; readonly instanceKey: string; readonly availableCollateral: string; readonly debtCapacity: string }
export interface FluidCreditMaterializedStateV1 extends FluidCreditStateReadFactsV1 { readonly identityFactsHash: Hash; readonly stateHash: Hash }
export interface FluidCreditRouteV1 { readonly instanceKey: string; readonly vault: string; readonly collateralAsset: string; readonly debtAsset: string; readonly lifecycle: "standing-position"; readonly routeBindingHash: Hash }
export interface FluidCreditEffectV1 { readonly token: string; readonly account: "executor" | "vault"; readonly delta: string }
export interface FluidCreditEffectProofV1 { readonly kind: "fluid-credit-effect-proof"; readonly cutoff: FluidCreditCutoffV1; readonly routeBindingHash: Hash; readonly executor: string; readonly collateralAmount: string; readonly debtAmount: string; readonly nftId: string; readonly finalSupply: string; readonly finalBorrow: string; readonly effects: readonly FluidCreditEffectV1[]; readonly effectRoot: Hash }
export interface FluidCreditQuoteV1 { readonly cutoff: FluidCreditCutoffV1; readonly routeBindingHash: Hash; readonly collateralAmount: string; readonly debtBps: string; readonly debtAmount: string; readonly effectProof: FluidCreditEffectProofV1; readonly effectProofHash: Hash; readonly quoteHash: Hash }
export interface FluidCreditActionV1 { readonly cutoff: FluidCreditCutoffV1; readonly target: string; readonly calldata: string; readonly exactQuoteHash: Hash; readonly actionIntentHash: Hash; readonly obligationSet: import("../../../packages/credit/src/index.ts").CreditObligationSetV1; readonly actionHash: Hash }
export interface FluidCreditExecutionIntentV1 { readonly kind: "fluid-credit-execution-intent"; readonly cutoff: FluidCreditCutoffV1; readonly target: string; readonly calldata: string; readonly actionHash: Hash; readonly exactQuoteHash: Hash; readonly obligationRoot: Hash; readonly finalSafety: "repayment-and-position-safe"; readonly expectedEffects: readonly FluidCreditEffectV1[] }

export function canonicalAddress(value: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(value)) throw new TypeError("fluid-credit address must be 20 bytes"); return `0x${value.slice(2).toLowerCase()}`; }
export function assertCutoff(value: FluidCreditCutoffV1): FluidCreditCutoffV1 { if (!/^\d+$/.test(value.chainId) || !/^\d+$/.test(value.number) || !/^0x[0-9a-f]{64}$/.test(value.hash) || !/^0x[0-9a-f]{64}$/.test(value.stateRoot)) throw new TypeError("fluid-credit cutoff is not canonical"); return Object.freeze({ ...value }); }
export function cutoffEqual(left: FluidCreditCutoffV1, right: FluidCreditCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
export function familyCandidateKey(instanceNominationKey: string): Hash { return hashDomain("aloha/family-candidate/v1", { family: FLUID_CREDIT_FAMILY_ID, instanceNominationKey }); }
