import {
  assertNonEmptyString,
  decodeJson,
  encodeCanonicalBytes,
  sha256Hex,
  type CanonicalJson,
  type Hash,
} from "../../../packages/canonical-codec/src/index.ts";

const GENERATED_HEADER = "/* generated by @aloha/catalog-generator; DO NOT EDIT */\n";

export interface GeneratedJsonConstantSelectorV1 {
  readonly sourceFileName: string;
  readonly constantName: string;
  readonly requireExported: boolean;
  /** Exact inert TypeScript assertion emitted after Object.freeze, or null. */
  readonly assertionTypeName: string | null;
}

export interface GeneratedJsonConstantObservationV1 {
  readonly sourceContentSha256: Hash;
  readonly canonicalValueContentSha256: Hash;
  readonly canonicalValueBytes: Uint8Array;
  readonly value: CanonicalJson;
}

function concreteBytes(value: unknown): Uint8Array {
  if (
    value === null
    || typeof value !== "object"
    || !ArrayBuffer.isView(value)
    || Object.getPrototypeOf(value) !== Uint8Array.prototype
  ) {
    throw new TypeError("generated source bytes must be a concrete Uint8Array");
  }
  return Uint8Array.from(value as Uint8Array);
}

function uniqueLineMarker(source: string, marker: string): number {
  let match = -1;
  let cursor = 0;
  while (cursor < source.length) {
    const found = source.indexOf(marker, cursor);
    if (found === -1) break;
    if (found === 0 || source[found - 1] === "\n") {
      if (match !== -1) throw new TypeError("generated source declares the selected constant more than once");
      match = found;
    }
    cursor = found + marker.length;
  }
  if (match === -1) throw new TypeError("generated source does not contain the exact selected declaration");
  return match;
}

function skipJsonWhitespace(source: string, start: number): number {
  let index = start;
  while (source[index] === " " || source[index] === "\t" || source[index] === "\n" || source[index] === "\r") {
    index += 1;
  }
  return index;
}

/** Find one object/array JSON literal without parsing or executing surrounding TypeScript. */
function jsonLiteralEnd(source: string, start: number): number {
  if (source[start] !== "{" && source[start] !== "[") {
    throw new TypeError("generated constant must contain one object or array JSON literal");
  }
  const stack: string[] = [];
  let inString = false;
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const current = source[index]!;
    if (inString) {
      if (escaped) escaped = false;
      else if (current === "\\") escaped = true;
      else if (current === "\"") inString = false;
      continue;
    }
    if (current === "\"") {
      inString = true;
      continue;
    }
    if (current === "{" || current === "[") {
      stack.push(current);
      continue;
    }
    if (current === "}" || current === "]") {
      const expected = current === "}" ? "{" : "[";
      if (stack.pop() !== expected) throw new TypeError("generated JSON literal has mismatched delimiters");
      if (stack.length === 0) return index + 1;
    }
  }
  throw new TypeError("generated JSON literal is unterminated");
}

function exactSuffix(source: string, jsonEnd: number, assertionTypeName: string | null): void {
  const suffixStart = skipJsonWhitespace(source, jsonEnd);
  const expected = assertionTypeName === null
    ? ");"
    : `) as unknown as ${assertionTypeName};`;
  if (source.slice(suffixStart, suffixStart + expected.length) !== expected) {
    throw new TypeError("generated constant has a non-exact inert suffix");
  }
  const next = source[suffixStart + expected.length];
  if (next !== undefined && next !== "\n" && next !== "\r") {
    throw new TypeError("generated constant suffix is not line terminated");
  }
}

/**
 * Reads one catalog-generator-owned JSON projection as inert bytes. Production
 * never imports the generated module and never loads the TypeScript compiler.
 * The surrounding declaration and optional type assertion must equal the
 * generator's fixed grammar; JSON duplicate keys and executable expressions
 * are rejected by the canonical codec.
 */
export function observeGeneratedJsonConstant(
  rawSourceBytes: Uint8Array,
  selector: GeneratedJsonConstantSelectorV1,
): GeneratedJsonConstantObservationV1 {
  const sourceBytes = concreteBytes(rawSourceBytes);
  assertNonEmptyString(selector.sourceFileName, "generatedJsonConstant.sourceFileName");
  const constantName = assertNonEmptyString(selector.constantName, "generatedJsonConstant.constantName");
  if (!/^[$A-Z_a-z][$0-9A-Z_a-z]*$/.test(constantName)) throw new TypeError("generated constant name is invalid");
  if (typeof selector.requireExported !== "boolean") throw new TypeError("generated constant export policy is invalid");
  if (selector.assertionTypeName !== null
    && !/^[$A-Z_a-z][$0-9A-Z_a-z]*$/.test(assertNonEmptyString(selector.assertionTypeName, "generatedJsonConstant.assertionTypeName"))) {
    throw new TypeError("generated constant assertion type is invalid");
  }
  if (selector.requireExported === (selector.assertionTypeName !== null)) {
    throw new TypeError("generated constant export/assertion contract is invalid");
  }
  const source = new TextDecoder("utf-8", { fatal: true }).decode(sourceBytes);
  if (!source.startsWith(GENERATED_HEADER)) throw new TypeError("generated source owner header is invalid");
  const marker = `${selector.requireExported ? "export " : ""}const ${constantName} = Object.freeze(`;
  const declarationStart = uniqueLineMarker(source, marker);
  const jsonStart = skipJsonWhitespace(source, declarationStart + marker.length);
  const jsonEnd = jsonLiteralEnd(source, jsonStart);
  exactSuffix(source, jsonEnd, selector.assertionTypeName);
  const value = decodeJson(source.slice(jsonStart, jsonEnd));
  const canonicalValueBytes = encodeCanonicalBytes(value);
  return Object.freeze({
    sourceContentSha256: sha256Hex(sourceBytes),
    canonicalValueContentSha256: sha256Hex(canonicalValueBytes),
    canonicalValueBytes,
    value,
  });
}
