import {
  assertDecimalString,
  assertHash,
  assertNonEmptyString,
  decodeCanonicalJson,
  decodeExactObject,
  deepFreeze,
  encodeCanonicalJson,
  fieldArray,
  hashDomain,
  type CanonicalJson,
  type Hash,
} from "../../../../packages/canonical-codec/src/index.ts";
import { erc20AssetPortBindingV1 } from "../../../../packages/asset-ref/src/index.ts";
import type { ExecutionFactSourceV1, ProgramInterpretationDraftV1, TransportFactV1 } from "../../../../packages/capability-interpreters/src/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type SchemaRef } from "../../../../packages/capability-contracts/src/index.ts";
import type { FamilyRuntimeStageV1, FamilyStageDefinitionV1, FamilyStageGenericInvocationV1 } from "../../../../packages/family-sdk/runtime/index.ts";
import type { FrozenProgramEnvelopeV1, ProgramSourceAnchorV1 } from "../../../../packages/request-program/src/index.ts";
import { sealInstancePublication, validateInstancePublication, type InstancePublicationV1 } from "../../../../packages/catalog/src/index.ts";
import { decodeCandidateEvidenceRef, familyCandidateKey as centralFamilyCandidateKey, type CandidateRecordV1, type CanonicalCutoffV1, type RecentLogEvidenceRefV1 } from "../../../../packages/discovery/src/index.ts";
import { METRONOME_SYNTH_FAMILY_AUTHORING_HASH } from "../family-definition.ts";
import { METRONOME_SYNTH_FAMILY_ID, METRONOME_SYNTH_FAMILY_VERSION } from "../manifest.ts";
import { decodeMetronomeSynthCandidate, nominateMetronomeSynth, verifyMetronomeSynthIdentityStage, identityDescriptorHash, materializeMetronomeSynth, deriveMetronomeSynthRoutes } from "../stages.ts";
import type { MetronomeSynthCandidateV1, MetronomeSynthCutoffV1, MetronomeSynthIdentityV1, MetronomeSynthMaterializedStateV1, MetronomeSynthStateReadFactsV1, MetronomeSynthObservationV1, MetronomeSynthIdentityReadFactsV1 } from "../types.ts";

const VERSION = asCapabilityVersion(METRONOME_SYNTH_FAMILY_VERSION);
export const METRONOME_SYNTH_STAGE_IDS = Object.freeze({ nomination: `family.${METRONOME_SYNTH_FAMILY_ID}.nomination`, identity: `family.${METRONOME_SYNTH_FAMILY_ID}.identity`, materialization: `family.${METRONOME_SYNTH_FAMILY_ID}.materialization`, projection: `family.${METRONOME_SYNTH_FAMILY_ID}.projection`, rehydration: `family.${METRONOME_SYNTH_FAMILY_ID}.rehydration` });
export const METRONOME_SYNTH_STAGE_SCHEMA_HASHES = Object.freeze({ nomination: hashDomain("aloha/metronome-synth/stage-schema/v1", "nomination"), identity: hashDomain("aloha/metronome-synth/stage-schema/v1", "identity"), materialization: hashDomain("aloha/metronome-synth/stage-schema/v1", "materialization"), projection: hashDomain("aloha/metronome-synth/stage-schema/v1", "projection"), rehydration: hashDomain("aloha/metronome-synth/stage-schema/v1", "rehydration") });
type Stage = keyof typeof METRONOME_SYNTH_STAGE_IDS;
type CandidateRecord = Omit<CandidateRecordV1, "evidence"> & { readonly evidence: readonly RecentLogEvidenceRefV1[] };
interface IdentityMemo { readonly kind: "metronome-synth-identity-memo"; readonly familyId: typeof METRONOME_SYNTH_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identity: MetronomeSynthIdentityV1; }
interface NominationPayload { readonly kind: "metronome-synth-nomination-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["candidate"]; readonly requestId: Hash; }
interface IdentityPayload { readonly kind: "metronome-synth-identity-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["identity"]; readonly requestId: Hash; }
interface MaterializationPayload { readonly kind: "metronome-synth-materialization-input"; readonly identityMemo: IdentityMemo; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface MaterializationOutput { readonly kind: "metronome-synth-materialization-output"; readonly familyId: typeof METRONOME_SYNTH_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identityMemoHash: Hash; readonly identityFactsHash: Hash; readonly instanceKey: string; readonly state: MetronomeSynthMaterializedStateV1; readonly evidenceRoot: Hash; }
interface ProjectionPayload { readonly kind: "metronome-synth-projection-input"; readonly identityMemo: IdentityMemo; readonly materialization: MaterializationOutput; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["state"]; readonly requestId: Hash; }
interface RehydrationPayload { readonly kind: "metronome-synth-rehydration-input"; readonly candidate: CandidateRecord; readonly cutoff: CanonicalCutoffV1; readonly readPlan: readonly ["reference"]; readonly referenceHash: Hash; readonly requestId: Hash; }

function canonical(value: unknown): CanonicalJson { return decodeCanonicalJson(encodeCanonicalJson(value)); }
function address(value: unknown, path: string): `0x${string}` { const text = assertNonEmptyString(value, path); if (!/^0x[0-9a-fA-F]{40}$/.test(text)) throw new TypeError(`${path} must be an address`); return `0x${text.slice(2).toLowerCase()}`; }
function bytes(value: unknown, path: string): `0x${string}` { const text = assertNonEmptyString(value, path); if (!/^0x(?:[0-9a-f]{2})+$/.test(text)) throw new TypeError(`${path} must be non-empty lowercase bytes`); return text as `0x${string}`; }
function cutoff(value: unknown, path: string): CanonicalCutoffV1 { return decodeExactObject(value, { chainId: (item, itemPath) => assertDecimalString(item, itemPath), number: (item, itemPath) => assertDecimalString(item, itemPath), hash: (item, itemPath) => assertHash(item, itemPath), stateRoot: (item, itemPath) => assertHash(item, itemPath) }, path); }
function sameCutoff(left: MetronomeSynthCutoffV1, right: MetronomeSynthCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
function sameSource(left: ExecutionFactSourceV1, right: ProgramSourceAnchorV1): boolean { return left.chainId === right.chainId && left.blockNumber === right.number && left.blockHash === right.hash && left.stateRoot === right.stateRoot; }
function factData(value: string): CanonicalJson { const raw = value.slice(2); const bytesValue = new Uint8Array(raw.length / 2); for (let i = 0; i < bytesValue.length; i += 1) bytesValue[i] = Number.parseInt(raw.slice(i * 2, i * 2 + 2), 16); return decodeCanonicalJson(new TextDecoder().decode(bytesValue)); }
function invalidCode(error: unknown, fallback: string): string { const raw = error instanceof Error ? error.message : String(error); const code = raw.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); return /^[a-z][a-z0-9-]*$/.test(code) ? code : fallback; }
function requestId(phase: string, target: string, cutoffValue: CanonicalCutoffV1, snapshot: Hash, operation: string): Hash { return hashDomain("aloha/metronome-synth/runtime-request/v1", { phase, target, cutoff: cutoffValue, candidateSnapshotHash: snapshot, operation }); }
function referenceHash(candidate: CandidateRecord, cutoffValue: CanonicalCutoffV1): Hash { return hashDomain("aloha/metronome-synth/rehydration-reference/v1", { familyDefinitionHash: candidate.familyDefinitionHash, familyCandidateKey: candidate.familyCandidateKey, candidateSubjectHash: candidate.candidateSubjectHash, instanceNominationKey: candidate.instanceNominationKey, cutoff: cutoffValue }); }

function candidateRecord(value: unknown, path = "metronome-synth.candidate"): CandidateRecord {
  const decoded = decodeExactObject<CandidateRecord>(value, { kind: (item, itemPath) => { if (item !== "aloha.candidate-record") throw new TypeError(`${itemPath} kind mismatch`); return item; }, version: (item, itemPath) => { if (item !== "2") throw new TypeError(`${itemPath} version mismatch`); return item; }, familyId: (item, itemPath) => { if (item !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return METRONOME_SYNTH_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), candidateSubjectHash: (item, itemPath) => assertHash(item, itemPath), candidateEvidenceRoot: (item, itemPath) => assertHash(item, itemPath), evidence: (item, itemPath) => fieldArray(item, (entry, entryPath) => { const evidence = decodeCandidateEvidenceRef(entry, entryPath); if (evidence.kind !== "recent-log") throw new TypeError("metronome-synth candidate evidence must be recent-log"); return evidence; }, itemPath) }, path);
  if (decoded.familyDefinitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH) throw new TypeError("metronome-synth candidate definition mismatch");
  if (decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey)) throw new TypeError("metronome-synth candidate key mismatch");
  if (decoded.evidence.length === 0) throw new TypeError("metronome-synth candidate evidence empty");
  const keys = decoded.evidence.map(item => hashDomain("aloha/candidate-evidence-ref/v1", item));
  if (new Set(keys).size !== keys.length || keys.some((item, index) => item !== [...keys].sort()[index])) throw new TypeError("metronome-synth candidate evidence order");
  if (decoded.evidence.some(item => address(item.address, "metronome-synth.candidate.evidence.address") !== decoded.instanceNominationKey)) throw new TypeError("metronome-synth candidate evidence target mismatch");
  return deepFreeze(decoded);
}
function reconstructCandidate(record: CandidateRecord, cutoffValue: CanonicalCutoffV1): MetronomeSynthCandidateV1 {
  let selected: MetronomeSynthCandidateV1 | null = null;
  for (const evidence of record.evidence) {
    const observation: MetronomeSynthObservationV1 = { kind: "log", target: evidence.address, blockNumber: evidence.blockNumber, blockHash: evidence.blockHash, txHash: evidence.txHash, logIndex: evidence.logIndex, rawLocatorHash: evidence.rawLocatorHash, cutoff: cutoffValue };
    const seed = decodeMetronomeSynthCandidate(observation, "metronome-synth-surface");
    if (seed === null) throw new TypeError("metronome-synth candidate evidence decode failed");
    const nomination = nominateMetronomeSynth(seed);
    if (nomination.status !== "nominated" || nomination.candidate.instanceNominationKey !== record.instanceNominationKey || nomination.candidate.candidateSnapshotHash !== record.candidateSubjectHash) throw new TypeError("metronome-synth candidate lineage mismatch");
    if (selected !== null) throw new TypeError("metronome-synth candidate has multiple snapshots");
    selected = nomination.candidate;
  }
  if (selected === null || !sameCutoff(selected.evidence.cutoff, cutoffValue)) throw new TypeError("metronome-synth candidate snapshot missing");
  return selected;
}
function identity(value: unknown, path: string): MetronomeSynthIdentityV1 {
  const decoded = decodeExactObject<MetronomeSynthIdentityV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), factsHash: (item, itemPath) => assertHash(item, itemPath), facts: (item, itemPath) => decodeExactObject(item, { pool: (field, fieldPath) => address(field, fieldPath), tokens: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), directions: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { tokenIn: (pairField, pairPath) => address(pairField, pairPath), tokenOut: (pairField, pairPath) => address(pairField, pairPath) }, entryPath), fieldPath), oracleBinding: (field, fieldPath) => bytes(field, fieldPath), quoteSemantics: (field, fieldPath) => { if (field !== "metronome-quote-swap-out-v1") throw new TypeError(`${fieldPath} quote semantics mismatch`); return "metronome-quote-swap-out-v1"; } }, itemPath) }, path);
  if (decoded.instanceKey !== decoded.facts.pool || decoded.factsHash !== hashDomain("aloha/metronome-synth/identity-facts/v1", decoded.facts)) throw new TypeError("metronome-synth identity hash mismatch");
  return deepFreeze(decoded);
}
function identityMemo(value: unknown, path = "metronome-synth.identityMemo"): IdentityMemo { const decoded = decodeExactObject<IdentityMemo>(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-identity-memo") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-identity-memo"; }, familyId: (item, itemPath) => { if (item !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return METRONOME_SYNTH_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), identity: (item, itemPath) => identity(item, itemPath) }, path); if (decoded.familyDefinitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceNominationKey !== decoded.identity.instanceKey || decoded.candidateSnapshotHash !== decoded.identity.candidateSnapshotHash) throw new TypeError("metronome-synth identity memo lineage mismatch"); return deepFreeze(decoded); }
function state(value: unknown, path: string): MetronomeSynthMaterializedStateV1 { const decoded = decodeExactObject<MetronomeSynthMaterializedStateV1>(value, { cutoff: (item, itemPath) => cutoff(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), projectionHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), stateHash: (item, itemPath) => assertHash(item, itemPath) }, path); const expected = hashDomain("aloha/metronome-synth/materialized-state/v1", { identityFactsHash: decoded.identityFactsHash, projectionHash: decoded.projectionHash }); if (decoded.stateHash !== expected) throw new TypeError("metronome-synth state hash mismatch"); return deepFreeze(decoded); }
function materializationOutput(value: unknown, path = "metronome-synth.materializationOutput"): MaterializationOutput { const decoded = decodeExactObject<MaterializationOutput>(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-materialization-output") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-materialization-output"; }, familyId: (item, itemPath) => { if (item !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return METRONOME_SYNTH_FAMILY_ID; }, familyDefinitionHash: (item, itemPath) => assertHash(item, itemPath), familyCandidateKey: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), identityFactsHash: (item, itemPath) => assertHash(item, itemPath), instanceKey: (item, itemPath) => address(item, itemPath), state: (item, itemPath) => state(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); if (decoded.familyDefinitionHash !== METRONOME_SYNTH_FAMILY_AUTHORING_HASH || decoded.familyCandidateKey !== centralFamilyCandidateKey(decoded.familyDefinitionHash, decoded.instanceNominationKey) || decoded.instanceKey !== decoded.state.instanceKey || decoded.identityFactsHash !== decoded.state.identityFactsHash || decoded.candidateSnapshotHash !== decoded.evidenceRoot) throw new TypeError("metronome-synth materialization lineage mismatch"); return deepFreeze(decoded); }
function readPlan(value: unknown, expected: readonly string[], path: string): readonly string[] { const result = fieldArray(value, (item, itemPath) => assertNonEmptyString(item, itemPath), path); if (result.length !== expected.length || result.some((item, index) => item !== expected[index])) throw new TypeError(`${path} read plan mismatch`); return Object.freeze([...result]); }
function hashValue(value: unknown, path: string): Hash { return assertHash(value, path); }
function nominationPayload(value: unknown, path = "metronome-synth.nominationPayload"): NominationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-nomination-input") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-nomination-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["candidate"], itemPath) as readonly ["candidate"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function identityPayload(value: unknown, path = "metronome-synth.identityPayload"): IdentityPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-identity-input") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-identity-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["identity"], itemPath) as readonly ["identity"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function materializationPayload(value: unknown, path = "metronome-synth.materializationPayload"): MaterializationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-materialization-input") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-materialization-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function projectionPayload(value: unknown, path = "metronome-synth.projectionPayload"): ProjectionPayload { const decoded = decodeExactObject<ProjectionPayload>(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-projection-input") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-projection-input"; }, identityMemo: (item, itemPath) => identityMemo(item, itemPath), materialization: (item, itemPath) => materializationOutput(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["state"], itemPath) as readonly ["state"], requestId: (item, itemPath) => hashValue(item, itemPath) }, path); if (!sameCutoff(decoded.cutoff, decoded.identityMemo.identity.cutoff) || decoded.materialization.instanceKey !== decoded.identityMemo.identity.instanceKey || decoded.materialization.identityFactsHash !== decoded.identityMemo.identity.factsHash || decoded.materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", decoded.identityMemo)) throw new TypeError("metronome-synth projection lineage mismatch"); return decoded; }
function rehydrationPayload(value: unknown, path = "metronome-synth.rehydrationPayload"): RehydrationPayload { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-rehydration-input") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-rehydration-input"; }, candidate: (item, itemPath) => candidateRecord(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), readPlan: (item, itemPath) => readPlan(item, ["reference"], itemPath) as readonly ["reference"], referenceHash: (item, itemPath) => hashValue(item, itemPath), requestId: (item, itemPath) => hashValue(item, itemPath) }, path); }
function boundFact(program: FrozenProgramEnvelopeV1, facts: readonly TransportFactV1[], expected: Hash): Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }> { if (facts.length !== 1) throw new TypeError("metronome-synth transport fact partition mismatch"); const fact = facts[0]!; if (fact.kind === "transportFailure" || fact.requestId !== expected || fact.requestFingerprint !== program.requestFingerprint || !sameSource(fact.source, program.source)) throw new TypeError("metronome-synth transport fact binding mismatch"); return fact; }
function decodeFact(value: Extract<TransportFactV1, { readonly kind: "returned" | "reverted" }>): CanonicalJson { return factData(bytes(value.dataHex, "metronome-synth.fact.dataHex")); }
function ack(value: unknown, kind: string): Hash { return decodeExactObject(value, { kind: (item, itemPath) => { if (item !== kind) throw new TypeError(`${itemPath} kind mismatch`); return kind; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, value: (item, itemPath) => assertHash(item, itemPath) }).value; }
function outputObject(value: unknown, path: string): CanonicalJson { const result = canonical(value); if (result === null || typeof result !== "object" || Array.isArray(result)) throw new TypeError(`${path} must be an object`); return result; }
function nominationOutput(value: unknown, path = "metronome-synth.nominationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-nomination-verified") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-nomination-verified"; }, familyId: (item, itemPath) => { if (item !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return METRONOME_SYNTH_FAMILY_ID; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }
function identityOutput(value: unknown, path = "metronome-synth.identityOutput"): CanonicalJson { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "identityVerified") throw new TypeError(`${itemPath} kind mismatch`); return "identityVerified"; }, familyInstanceKey: (item, itemPath) => address(item, itemPath), identityMemo: (item, itemPath) => identityMemo(item, itemPath), identityMemoHash: (item, itemPath) => assertHash(item, itemPath), descriptorHash: (item, itemPath) => assertHash(item, itemPath), evidenceRoot: (item, itemPath) => assertHash(item, itemPath) }, path); const memo = decoded.identityMemo; if (decoded.familyInstanceKey !== memo.identity.instanceKey || decoded.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo) || decoded.descriptorHash !== identityDescriptorHash(memo.identity) || decoded.evidenceRoot !== memo.candidateSnapshotHash) throw new TypeError("metronome-synth identity output lineage mismatch"); return outputObject(decoded, path); }
function materializationOutputCodec(value: unknown): CanonicalJson { return outputObject(materializationOutput(value), "metronome-synth.materializationOutput"); }
function publicationOutput(value: unknown): CanonicalJson { const decoded = canonical(value); if (decoded === null || typeof decoded !== "object" || Array.isArray(decoded)) throw new TypeError("metronome-synth projection output must be object"); validateInstancePublication(decoded as unknown as InstancePublicationV1); return decoded; }
function rehydrationOutput(value: unknown, path = "metronome-synth.rehydrationOutput"): CanonicalJson { return outputObject(decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-rehydration-verified") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-rehydration-verified"; }, familyId: (item, itemPath) => { if (item !== METRONOME_SYNTH_FAMILY_ID) throw new TypeError(`${itemPath} family mismatch`); return METRONOME_SYNTH_FAMILY_ID; }, instanceNominationKey: (item, itemPath) => address(item, itemPath), cutoff: (item, itemPath) => cutoff(item, itemPath), referenceHash: (item, itemPath) => assertHash(item, itemPath) }, path), path); }

function requireStage(input: FamilyStageGenericInvocationV1, expected: Stage): void { if (input.stage !== expected) throw new TypeError(`metronome-synth-${expected}-stage-mismatch`); }
function noPrior(input: FamilyStageGenericInvocationV1): void { if (input.identityMemo !== null || input.materializationOutput !== null) throw new TypeError("metronome-synth unexpected prior output"); }
function prepareNomination(input: FamilyStageGenericInvocationV1): NominationPayload { requireStage(input, "nomination"); noPrior(input); const c = cutoff(input.cutoff, "metronome-synth.nomination.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "metronome-synth-nomination-input", candidate, cutoff: c, readPlan: ["candidate"], requestId: requestId("nomination", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "candidate") }; }
function prepareIdentity(input: FamilyStageGenericInvocationV1): IdentityPayload { requireStage(input, "identity"); noPrior(input); const c = cutoff(input.cutoff, "metronome-synth.identity.cutoff"); const candidate = candidateRecord(input.candidate); return { kind: "metronome-synth-identity-input", candidate, cutoff: c, readPlan: ["identity"], requestId: requestId("identity", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, "identity") }; }
function prepareMaterialization(input: FamilyStageGenericInvocationV1): MaterializationPayload { requireStage(input, "materialization"); if (input.identityMemo === null || input.materializationOutput !== null) throw new TypeError("metronome-synth materialization prior output mismatch"); const c = cutoff(input.cutoff, "metronome-synth.materialization.cutoff"); const memo = identityMemo(input.identityMemo); if (!sameCutoff(c, memo.identity.cutoff)) throw new TypeError("metronome-synth materialization cutoff mismatch"); return { kind: "metronome-synth-materialization-input", identityMemo: memo, cutoff: c, readPlan: ["state"], requestId: requestId("materialization", memo.identity.instanceKey, c, memo.candidateSnapshotHash, "state") }; }
function prepareProjection(input: FamilyStageGenericInvocationV1): ProjectionPayload { requireStage(input, "projection"); if (input.identityMemo === null || input.materializationOutput === null) throw new TypeError("metronome-synth projection prior output missing"); const c = cutoff(input.cutoff, "metronome-synth.projection.cutoff"); const memo = identityMemo(input.identityMemo); const materialization = materializationOutput(input.materializationOutput); if (!sameCutoff(c, memo.identity.cutoff) || materialization.instanceKey !== memo.identity.instanceKey || materialization.identityFactsHash !== memo.identity.factsHash || materialization.identityMemoHash !== hashDomain("aloha/identity-memo/v1", memo)) throw new TypeError("metronome-synth projection lineage mismatch"); return { kind: "metronome-synth-projection-input", identityMemo: memo, materialization, cutoff: c, readPlan: ["state"], requestId: requestId("projection", memo.identity.instanceKey, c, memo.candidateSnapshotHash, "state") }; }
function prepareRehydration(input: FamilyStageGenericInvocationV1): RehydrationPayload { requireStage(input, "rehydration"); noPrior(input); const c = cutoff(input.cutoff, "metronome-synth.rehydration.cutoff"); const candidate = candidateRecord(input.candidate); const reference = referenceHash(candidate, c); return { kind: "metronome-synth-rehydration-input", candidate, cutoff: c, readPlan: ["reference"], referenceHash: reference, requestId: requestId("rehydration", candidate.instanceNominationKey, c, candidate.candidateSubjectHash, reference) }; }

function identityFact(value: unknown): { readonly candidateSnapshotHash: Hash; readonly reads: MetronomeSynthIdentityReadFactsV1 } { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-identity-facts") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-identity-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, candidateSnapshotHash: (item, itemPath) => assertHash(item, itemPath), reads: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), target: (field, fieldPath) => address(field, fieldPath), reverseTarget: (field, fieldPath) => address(field, fieldPath), pool: (field, fieldPath) => address(field, fieldPath), tokens: (field, fieldPath) => fieldArray(field, (entry, entryPath) => address(entry, entryPath), fieldPath), activeDirections: (field, fieldPath) => fieldArray(field, (entry, entryPath) => decodeExactObject(entry, { tokenIn: (pairField, pairPath) => address(pairField, pairPath), tokenOut: (pairField, pairPath) => address(pairField, pairPath) }, entryPath), fieldPath), oracleBinding: (field, fieldPath) => bytes(field, fieldPath) }, itemPath) }, "metronome-synth.identityFact"); return decoded; }
function stateFact(value: unknown): MetronomeSynthStateReadFactsV1 { const decoded = decodeExactObject(value, { kind: (item, itemPath) => { if (item !== "metronome-synth-state-facts") throw new TypeError(`${itemPath} kind mismatch`); return "metronome-synth-state-facts"; }, version: (item, itemPath) => { if (item !== 1) throw new TypeError(`${itemPath} version mismatch`); return 1; }, read: (item, itemPath) => decodeExactObject(item, { cutoff: (field, fieldPath) => cutoff(field, fieldPath), instanceKey: (field, fieldPath) => address(field, fieldPath), projectionHash: (field, fieldPath) => assertHash(field, fieldPath) }, itemPath) }, "metronome-synth.stateFact"); return decoded.read; }
function publication(payload: ProjectionPayload, program: FrozenProgramEnvelopeV1): InstancePublicationV1 { const identityValue = payload.identityMemo.identity; const routes = deriveMetronomeSynthRoutes(identityValue); const transitions = routes.map(route => ({ inputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.inputAsset), portRef: hashDomain("aloha/metronome-synth/port/v1", { instanceKey: route.instanceKey, role: "input", asset: route.inputAsset }), ordinal: "0" }], outputAssetPorts: [{ ...erc20AssetPortBindingV1(payload.cutoff.chainId, route.outputAsset), portRef: hashDomain("aloha/metronome-synth/port/v1", { instanceKey: route.instanceKey, role: "output", asset: route.outputAsset }), ordinal: "0" }], opaqueTransitionRef: hashDomain("aloha/metronome-synth/transition/v1", route), constraintRefs: [payload.materialization.state.stateHash], staticProjectionHash: hashDomain("aloha/metronome-synth/static-transition/v1", route) })); const memo = canonical(payload.identityMemo); return sealInstancePublication({ familyId: METRONOME_SYNTH_FAMILY_ID, familyDefinitionHash: METRONOME_SYNTH_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.materialization.familyCandidateKey, instanceKey: identityValue.instanceKey, cutoff: payload.cutoff, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(identityValue), staticProjectionMemoHash: hashDomain("aloha/metronome-synth/static-projection/v1", { routes, stateHash: payload.materialization.state.stateHash }), requestedArtifactDependencyRoot: hashDomain("aloha/metronome-synth/requested-artifacts/v1", { identityFactsHash: identityValue.factsHash, stateHash: payload.materialization.state.stateHash }), validityDependencyRoot: hashDomain("aloha/metronome-synth/validity/v1", { source: program.source, identityFactsHash: identityValue.factsHash, stateHash: payload.materialization.state.stateHash }), transitions, evidenceRoot: payload.materialization.evidenceRoot }); }
function interpretNomination(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = nominationPayload(input.payload); reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "metronome-synth-nomination-reverted" }; const value = ack(decodeFact(fact), "metronome-synth-nomination-facts"); if (value !== payload.candidate.candidateSubjectHash) throw new TypeError("metronome-synth nomination acknowledgement mismatch"); return { kind: "verified", output: { kind: "metronome-synth-nomination-verified", familyId: METRONOME_SYNTH_FAMILY_ID, candidateSubjectHash: value, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: hashDomain("aloha/metronome-synth/nomination-reference/v1", { candidateSubjectHash: value, cutoff: payload.cutoff }) } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "metronome-synth-nomination-invalid") }; } }
function interpretIdentity(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = identityPayload(input.payload); const candidate = reconstructCandidate(payload.candidate, payload.cutoff); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "metronome-synth-identity-reverted" }; const decoded = identityFact(decodeFact(fact)); if (decoded.candidateSnapshotHash !== candidate.candidateSnapshotHash) throw new TypeError("metronome-synth identity fact snapshot mismatch"); const result = verifyMetronomeSynthIdentityStage({ candidate, reads: decoded.reads }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const memo: IdentityMemo = { kind: "metronome-synth-identity-memo", familyId: METRONOME_SYNTH_FAMILY_ID, familyDefinitionHash: METRONOME_SYNTH_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.candidate.familyCandidateKey, instanceNominationKey: candidate.instanceNominationKey, candidateSnapshotHash: candidate.candidateSnapshotHash, identity: result.identity }; return { kind: "verified", output: { kind: "identityVerified", familyInstanceKey: result.identity.instanceKey, identityMemo: memo, identityMemoHash: hashDomain("aloha/identity-memo/v1", memo), descriptorHash: identityDescriptorHash(result.identity), evidenceRoot: candidate.candidateSnapshotHash } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "metronome-synth-identity-invalid") }; } }
function interpretMaterialization(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = materializationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "metronome-synth-materialization-reverted" }; const read = stateFact(decodeFact(fact)); if (!sameCutoff(read.cutoff, payload.cutoff) || read.instanceKey !== payload.identityMemo.identity.instanceKey) throw new TypeError("metronome-synth state fact lineage mismatch"); const result = materializeMetronomeSynth({ identity: payload.identityMemo.identity, read }); if (result.status === "chain-proven-rejected") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; const output: MaterializationOutput = { kind: "metronome-synth-materialization-output", familyId: METRONOME_SYNTH_FAMILY_ID, familyDefinitionHash: METRONOME_SYNTH_FAMILY_AUTHORING_HASH, familyCandidateKey: payload.identityMemo.familyCandidateKey, instanceNominationKey: payload.identityMemo.instanceNominationKey, candidateSnapshotHash: payload.identityMemo.candidateSnapshotHash, identityMemoHash: hashDomain("aloha/identity-memo/v1", payload.identityMemo), identityFactsHash: payload.identityMemo.identity.factsHash, instanceKey: result.state.instanceKey, state: result.state, evidenceRoot: payload.identityMemo.candidateSnapshotHash }; return { kind: "verified", output }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "metronome-synth-materialization-invalid") }; } }
function interpretProjection(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = projectionPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "metronome-synth-projection-reverted" }; const read = stateFact(decodeFact(fact)); const result = materializeMetronomeSynth({ identity: payload.identityMemo.identity, read }); if (result.status !== "verified") return { kind: "chainProvenRejected", factSet: input.factSet, decisionCode: result.reasonCode }; if (result.state.stateHash !== payload.materialization.state.stateHash) throw new TypeError("metronome-synth projection state lineage mismatch"); return { kind: "verified", output: publication(payload, input.program) }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "metronome-synth-projection-invalid") }; } }
function interpretRehydration(input: Parameters<FamilyStageDefinitionV1["interpret"]>[0]): ProgramInterpretationDraftV1 { try { const payload = rehydrationPayload(input.payload); const fact = boundFact(input.program, input.facts, payload.requestId); if (fact.kind === "reverted") return { kind: "invalidProgram", code: "metronome-synth-rehydration-reverted" }; const value = ack(decodeFact(fact), "metronome-synth-rehydration-facts"); if (value !== payload.referenceHash) throw new TypeError("metronome-synth rehydration acknowledgement mismatch"); return { kind: "verified", output: { kind: "metronome-synth-rehydration-verified", familyId: METRONOME_SYNTH_FAMILY_ID, instanceNominationKey: payload.candidate.instanceNominationKey, cutoff: payload.cutoff, referenceHash: value } }; } catch (error) { return { kind: "invalidProgram", code: invalidCode(error, "metronome-synth-rehydration-invalid") }; } }

function definitionBase(stage: Stage, payloadCodec: { readonly schemaRef: SchemaRef; readonly decodeExact: (value: unknown) => unknown }, outputSchemaRef: Hash, outputCodec: { readonly decodeExact: (value: unknown) => CanonicalJson }, prepareIssueValue: FamilyStageDefinitionV1["prepareIssueValue"], interpret: FamilyStageDefinitionV1["interpret"]): FamilyStageDefinitionV1 { return deepFreeze({ stage, capabilityId: asCapabilityId(METRONOME_SYNTH_STAGE_IDS[stage]), version: VERSION, schemaHash: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES[stage]), payloadCodec: deepFreeze(payloadCodec), dependencyIds: Object.freeze([]), outputSchemaRef, implementationClosureHash: hashDomain("aloha/metronome-synth/runtime-implementation/v1", { stage, module: "families/metronome-synth/src/runtime/definitions.ts" }), outputCodecHash: hashDomain("aloha/metronome-synth/runtime-output-codec/v1", stage), outputCodec: deepFreeze(outputCodec), prepareIssueValue, interpret }); }
const codecs = Object.freeze({ nomination: { schemaRef: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES.nomination), decodeExact: (value: unknown) => nominationPayload(value) }, identity: { schemaRef: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES.identity), decodeExact: (value: unknown) => identityPayload(value) }, materialization: { schemaRef: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES.materialization), decodeExact: (value: unknown) => materializationPayload(value) }, projection: { schemaRef: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES.projection), decodeExact: (value: unknown) => projectionPayload(value) }, rehydration: { schemaRef: asSchemaRef(METRONOME_SYNTH_STAGE_SCHEMA_HASHES.rehydration), decodeExact: (value: unknown) => rehydrationPayload(value) } });
const outputSchema = (stage: Stage): Hash => hashDomain("aloha/metronome-synth/runtime-output-schema/v1", stage);
export const METRONOME_SYNTH_NOMINATION_DEFINITION = definitionBase("nomination", codecs.nomination, outputSchema("nomination"), { decodeExact: value => nominationOutput(value) }, prepareNomination, interpretNomination);
export const METRONOME_SYNTH_IDENTITY_DEFINITION = definitionBase("identity", codecs.identity, outputSchema("identity"), { decodeExact: value => identityOutput(value) }, prepareIdentity, interpretIdentity);
export const METRONOME_SYNTH_MATERIALIZATION_DEFINITION = definitionBase("materialization", codecs.materialization, outputSchema("materialization"), { decodeExact: value => materializationOutputCodec(value) }, prepareMaterialization, interpretMaterialization);
export const METRONOME_SYNTH_PROJECTION_DEFINITION = definitionBase("projection", codecs.projection, outputSchema("projection"), { decodeExact: value => publicationOutput(value) }, prepareProjection, interpretProjection);
export const METRONOME_SYNTH_REHYDRATION_DEFINITION = definitionBase("rehydration", codecs.rehydration, outputSchema("rehydration"), { decodeExact: value => rehydrationOutput(value) }, prepareRehydration, interpretRehydration);
export const METRONOME_SYNTH_STAGE_DEFINITIONS: readonly FamilyStageDefinitionV1[] = Object.freeze([METRONOME_SYNTH_NOMINATION_DEFINITION, METRONOME_SYNTH_IDENTITY_DEFINITION, METRONOME_SYNTH_MATERIALIZATION_DEFINITION, METRONOME_SYNTH_PROJECTION_DEFINITION, METRONOME_SYNTH_REHYDRATION_DEFINITION]);
export function requireMetronomeSynthStageDefinition(stage: FamilyRuntimeStageV1): FamilyStageDefinitionV1 { const definition = METRONOME_SYNTH_STAGE_DEFINITIONS.find(item => item.stage === stage); if (!definition) throw new TypeError(`metronome-synth stage definition missing: ${stage}`); return definition; }
