import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_PHYSICAL_LIFECYCLE_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/runtime/index.ts";
import { CURVE_UNDERLYING_ACTION_OWNER_ID, CURVE_UNDERLYING_CAPABILITY_IDS, CURVE_UNDERLYING_FAMILY_ID, CURVE_UNDERLYING_FAMILY_VERSION, CURVE_UNDERLYING_OWNER_REF, CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_ID, CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_SCHEMA_HASH, CURVE_UNDERLYING_SOURCE_PLAN_ID, CURVE_UNDERLYING_SOURCE_PLAN_SCHEMA_HASH } from "./manifest.ts";
const version = asCapabilityVersion(CURVE_UNDERLYING_FAMILY_VERSION); const moduleRoot = "families/curve-underlying/src";
type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { const capabilityId = asCapabilityId(`family.${CURVE_UNDERLYING_FAMILY_ID}.${stage}`); const schemaHash = asSchemaRef(hashDomain("aloha/curve-underlying/stage-schema/v1", stage)); return Object.freeze({ modulePath: `${moduleRoot}/runtime.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([capabilityId]), schemaRefs: Object.freeze([schemaHash]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([CURVE_UNDERLYING_SOURCE_PLAN_ID, CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_ID].sort()) } : {}) }); }
function ext(name: "state" | "coarse" | "exact"): CapabilityAuthoringDeclarationV1 { const capabilityId = asCapabilityId(CURVE_UNDERLYING_CAPABILITY_IDS[name]); return Object.freeze({ capabilityId, version, schemaHash: asSchemaRef(hashDomain("aloha/curve-underlying/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/curve-underlying/extension-interpreter/v1", name), dependencyIds: Object.freeze(name === "state" ? [] : [asCapabilityId(CURVE_UNDERLYING_CAPABILITY_IDS.state)]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "CURVE_UNDERLYING_RUNTIME" }); }
const n = core("nomination", "CURVE_NOMINATION_RUNTIME"); const i = core("identity", "CURVE_IDENTITY_RUNTIME"); const m = core("materialization", "CURVE_MATERIALIZATION_RUNTIME"); const p = core("projection", "CURVE_PROJECTION_RUNTIME"); const r = core("rehydration", "CURVE_REHYDRATION_RUNTIME"); const state = ext("state"); const coarse = ext("coarse"); const exact = ext("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.curve-underlying.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/curve-underlying/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.curve-underlying.state-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/curve-underlying/fact-schema/v1", "state")) })]);
const actionOwner = Object.freeze({ ownerId: CURVE_UNDERLYING_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/curve-underlying/action-schema/v1", "swap")), implementationHash: hashDomain("aloha/curve-underlying/action-implementation/v1", "swap"), actionKinds: Object.freeze(["swap"]), modulePath: `${moduleRoot}/action.ts`, exportName: "CURVE_UNDERLYING_SWAP_ACTION_PORT" });
const physicalAdapter = Object.freeze({ modulePath: `${moduleRoot}/runtime/physical-adapter.ts`, exportName: "CURVE_UNDERLYING_PHYSICAL_LIFECYCLE_ADAPTER_FACTORY", capabilityIds: Object.freeze({}), actionOwnerIds: Object.freeze({}) });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: CURVE_UNDERLYING_FAMILY_ID, version: CURVE_UNDERLYING_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/curve-underlying/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, actionOwner, facts, physicalAdapter }), authorityDeclarationHash: hashDomain("aloha/curve-underlying/authority/v1", CURVE_UNDERLYING_OWNER_REF), sourcePlans: [{ sourcePlanId: CURVE_UNDERLYING_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: CURVE_UNDERLYING_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "CURVE_UNDERLYING_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "CURVE_UNDERLYING_SOURCE_NOMINATION_PROGRAM", schemaHash: CURVE_UNDERLYING_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "CURVE_UNDERLYING_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "CURVE_UNDERLYING_NOMINATION_INDEPENDENT_ORACLE" } } } }, { sourcePlanId: CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_ID, completeness: "complete-snapshot", historyStartBlock: null, schemaHash: CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: `${moduleRoot}/source-plan.ts`, exportName: "CURVE_UNDERLYING_REGISTRY_NOMINATION_PROGRAM", schemaHash: CURVE_UNDERLYING_REGISTRY_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "CURVE_UNDERLYING_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "CURVE_UNDERLYING_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [CURVE_UNDERLYING_CAPABILITY_IDS.state]: { kind: "present", module: state }, [CURVE_UNDERLYING_CAPABILITY_IDS.coarse]: { kind: "present", module: coarse }, [CURVE_UNDERLYING_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { "search/v1": { modulePath: `${moduleRoot}/search-adapter.ts`, exportName: "CURVE_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { state: asCapabilityId(CURVE_UNDERLYING_CAPABILITY_IDS.state), coarse: asCapabilityId(CURVE_UNDERLYING_CAPABILITY_IDS.coarse), exact: asCapabilityId(CURVE_UNDERLYING_CAPABILITY_IDS.exact) }, actionOwnerIds: { swap: CURVE_UNDERLYING_ACTION_OWNER_ID } }, [FAMILY_PHYSICAL_LIFECYCLE_ADAPTER_ROLE_V1]: physicalAdapter }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const CURVE_UNDERLYING_DEFINITION = defineFamily(input); export const CURVE_UNDERLYING_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(CURVE_UNDERLYING_DEFINITION); export const CURVE_UNDERLYING_FAMILY_DEFINITION_HASH = CURVE_UNDERLYING_FAMILY_AUTHORING_HASH;
