import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { familyCandidateKey as centralFamilyCandidateKey, type SourcePlanEvidenceRefV1 } from "../../../packages/discovery/src/index.ts";
import { CURVE_UNDERLYING_FAMILY_AUTHORING_HASH } from "./family-definition.ts";

export interface CurveCutoffV1 { readonly chainId: string; readonly number: string; readonly hash: Hash; readonly stateRoot: Hash; }
export interface CurveEvidenceV1 { readonly kind: "log" | "call" | "address-surface"; readonly cutoff: CurveCutoffV1; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly target: string; readonly rawLocatorHash: Hash; readonly topic0?: Hash; readonly selector?: string; readonly i?: number; readonly j?: number; }
export interface CurveSourceEvidenceV1 { readonly kind: "source-plan"; readonly cutoff: CurveCutoffV1; readonly target: string; readonly source: SourcePlanEvidenceRefV1; readonly i?: undefined; readonly j?: undefined; }
export interface CurveCandidateV1 { readonly target: string; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly evidence: CurveEvidenceV1 | CurveSourceEvidenceV1; }
export type CurveSelectorVariantV1 = "int128" | "uint256";
export interface CurveVerifiedDirectionV1 { readonly i: number; readonly j: number; readonly selectorVariant: CurveSelectorVariantV1; readonly amountIn: string; readonly amountOut: string; }
export interface CurveIdentityReadFactsV1 { readonly cutoff: CurveCutoffV1; readonly pool: string; readonly metaRegistry: string; readonly registryPool: string; readonly poolHasCode: boolean; readonly handlers: readonly string[]; readonly underlyingCoins: readonly string[]; readonly underlyingDecimals: readonly number[]; readonly verifiedDirections: readonly CurveVerifiedDirectionV1[]; }
export interface CurveIdentityV1 { readonly cutoff: CurveCutoffV1; readonly candidateSnapshotHash: Hash; readonly instanceKey: string; readonly factsHash: Hash; readonly facts: { readonly pool: string; readonly metaRegistry: string; readonly poolHasCode: boolean; readonly handlers: readonly string[]; readonly underlyingCoins: readonly string[]; readonly underlyingDecimals: readonly number[]; readonly verifiedDirections: readonly CurveVerifiedDirectionV1[]; }; }
export type CurveVariantV1 = "plain" | "ng";
export interface CurveStateReadFactsV1 { readonly cutoff: CurveCutoffV1; readonly pool: string; readonly variant: CurveVariantV1; readonly A: string; readonly fee: string; readonly balances: readonly string[]; readonly rates: readonly string[]; readonly offpegFeeMultiplier?: string; /** Current-source get_dy_underlying result for this route amount. */ readonly exactAmountOut?: string; readonly exactSelectorVariant?: CurveSelectorVariantV1; }
export interface CurveMaterializedStateV1 extends CurveStateReadFactsV1 { readonly identityFactsHash: Hash; readonly stateHash: Hash; }
export interface CurveRouteV1 { readonly instanceKey: string; readonly inputToken: string; readonly outputToken: string; readonly i: number; readonly j: number; readonly selectorVariant: CurveSelectorVariantV1; readonly routeBindingHash: Hash; }
export interface CurveQuoteV1 { readonly cutoff: CurveCutoffV1; readonly routeBindingHash: Hash; readonly amountIn: string; readonly amountOut: string; readonly stateHash: Hash; readonly quoteHash: Hash; }
export interface CurveActionV1 { readonly cutoff: CurveCutoffV1; readonly routeBindingHash: Hash; readonly exactQuoteHash: Hash; readonly target: string; readonly selector: string; readonly calldata: string; readonly actionHash: Hash; }
export interface CurveExecutionIntentV1 { readonly kind: "curve-underlying-execution-intent"; readonly cutoff: CurveCutoffV1; readonly target: string; readonly calldata: string; readonly actionHash: Hash; readonly exactQuoteHash: Hash; }
export interface CurveObservationV1 { readonly kind: "log" | "call" | "address-surface"; readonly target: string; readonly blockNumber: string; readonly blockHash: Hash; readonly txHash: Hash; readonly logIndex: string; readonly rawLocatorHash: Hash; readonly cutoff: CurveCutoffV1; readonly topic0?: Hash; readonly selector?: string; readonly i?: number; readonly j?: number; }

export function canonicalAddress(value: string): string { if (!/^0x[0-9a-fA-F]{40}$/.test(value)) throw new TypeError("curve address must be 20 bytes"); return `0x${value.slice(2).toLowerCase()}`; }
export function sameAddress(left: string, right: string): boolean { return canonicalAddress(left) === canonicalAddress(right); }
export function cutoffEqual(left: CurveCutoffV1, right: CurveCutoffV1): boolean { return left.chainId === right.chainId && left.number === right.number && left.hash === right.hash && left.stateRoot === right.stateRoot; }
export function assertCutoff(value: CurveCutoffV1): CurveCutoffV1 { if (!/^\d+$/.test(value.chainId) || !/^\d+$/.test(value.number) || !/^0x[0-9a-f]{64}$/.test(value.hash) || !/^0x[0-9a-f]{64}$/.test(value.stateRoot)) throw new TypeError("curve cutoff is not canonical"); return Object.freeze({ ...value }); }
export function assertDecimal(value: string, label: string): string { if (!/^\d+$/.test(value)) throw new TypeError(`${label} must be an unsigned decimal string`); return value; }
export function familyCandidateKey(instanceNominationKey: string): Hash { return centralFamilyCandidateKey(CURVE_UNDERLYING_FAMILY_AUTHORING_HASH, instanceNominationKey); }
