import { assertDecimalString, assertExactKeys, assertHash, assertNonEmptyString, decodeCanonicalJson, deepFreeze, encodeCanonicalJson, hashDomain, type CanonicalJson, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { erc20AssetRefV1 } from "../../../packages/asset-ref/src/index.ts";
import { familyCandidateKey as centralFamilyCandidateKey } from "../../../packages/discovery/src/index.ts";
import { familySearchAmount, familySearchAmountHash, familySearchArtifactHash, familySearchExecutionContext, familySearchExecutionContextHash, familySearchObjective, familySearchPayloadHash, familySearchRouteBindingHash, familySearchSource, sameFamilySearchSource, unavailableFamilySearchStage, validateFamilySearchRouteLegBinding, type FamilySearchActionArtifactV1, type FamilySearchAdapterFactoryV1, type FamilySearchAdapterV1, type FamilySearchCoarseArtifactV1, type FamilySearchExactArtifactV1, type FamilySearchLegRequestV1, type FamilySearchRunRequestV1, type FamilySearchSourceReadResultV1, type FamilySearchStateArtifactV1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { DODO_V2_FAMILY_AUTHORING_HASH as DODO_V2_FAMILY_DEFINITION_HASH } from "./family-definition.ts";
import { DODO_V2_SWAP_ACTION_PORT } from "./action.ts";
import { exactDodoV2 } from "./exact.ts";
import { materializeDodoV2 } from "./instance.ts";
import { DODO_V2_FAMILY_ID } from "./manifest.ts";
import { coarseDodoV2 } from "./pricing.ts";
import { assertDodoRoute, deriveDodoRoutes } from "./routes.ts";
import { decodeDodoFeeRate, decodeDodoPmm, decodeDodoQuery, encodeDodoStateCall } from "./search-codec.ts";
import { canonicalAddress, cutoffEqual, type DodoIdentityV1, type DodoMaterializedStateV1, type DodoQuoteV1, type DodoRouteV1, type DodoStateReadFactsV1 } from "./types.ts";
import type { DodoPmmState } from "./kernel/math.ts";

type Memo = { readonly kind: "dodo-v2-identity-memo"; readonly familyId: typeof DODO_V2_FAMILY_ID; readonly familyDefinitionHash: Hash; readonly familyCandidateKey: Hash; readonly instanceNominationKey: string; readonly candidateSnapshotHash: Hash; readonly identity: DodoIdentityV1 };
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function exact(value: unknown, keys: readonly string[], path: string): Record<string, unknown> { const result = record(value, path); assertExactKeys(result, keys, path); return result; }
function text(value: unknown, path: string): string { return assertNonEmptyString(value, path); }
function address(value: unknown, path: string): string { return canonicalAddress(text(value, path)); }
function decimal(value: unknown, path: string): string { return assertDecimalString(value, path); }
function hash(value: unknown, path: string): Hash { return assertHash(value, path); }
function integer(value: unknown, path: string): number { if (!Number.isInteger(value)) throw new TypeError(`${path} must be an integer`); return value as number; }
function cutoff(value: unknown, path: string): ReturnType<typeof familySearchSource> { return familySearchSource(value, path); }
function canonical(value: unknown): CanonicalJson { return deepFreeze(decodeCanonicalJson(encodeCanonicalJson(value))); }
function sameCutoff(left: ReturnType<typeof familySearchSource>, right: ReturnType<typeof familySearchSource>): boolean { return cutoffEqual(left, right); }
function pmm(value: unknown, path: string): DodoPmmState {
  const source = exact(value, ["B", "B0", "K", "Q", "Q0", "R", "i"], path);
  const R = source.R; if (R !== 0 && R !== 1 && R !== 2) throw new TypeError(`${path}.R must be 0, 1 or 2`);
  return Object.freeze({ i: BigInt(decimal(source.i, `${path}.i`)), K: BigInt(decimal(source.K, `${path}.K`)), B: BigInt(decimal(source.B, `${path}.B`)), Q: BigInt(decimal(source.Q, `${path}.Q`)), B0: BigInt(decimal(source.B0, `${path}.B0`)), Q0: BigInt(decimal(source.Q0, `${path}.Q0`)), R });
}
function pmmWire(value: DodoPmmState): { readonly i: string; readonly K: string; readonly B: string; readonly Q: string; readonly B0: string; readonly Q0: string; readonly R: 0 | 1 | 2 } { return { i: value.i.toString(), K: value.K.toString(), B: value.B.toString(), Q: value.Q.toString(), B0: value.B0.toString(), Q0: value.Q0.toString(), R: value.R }; }
function identity(value: unknown, path: string): DodoIdentityV1 {
  const source = exact(value, ["candidateSnapshotHash", "cutoff", "facts", "factsHash", "instanceKey"], path); const facts = exact(source.facts, ["baseToken", "factory", "lpFeeRate", "mtFeeRate", "pmm", "pool", "quoteActor", "quoteToken", "registry"], `${path}.facts`);
  const pmmValue = pmm(facts.pmm, `${path}.facts.pmm`); const decodedFacts = Object.freeze({ pool: address(facts.pool, `${path}.facts.pool`), factory: address(facts.factory, `${path}.facts.factory`), registry: address(facts.registry, `${path}.facts.registry`), baseToken: address(facts.baseToken, `${path}.facts.baseToken`), quoteToken: address(facts.quoteToken, `${path}.facts.quoteToken`), quoteActor: address(facts.quoteActor, `${path}.facts.quoteActor`), pmm: pmmValue, lpFeeRate: decimal(facts.lpFeeRate, `${path}.facts.lpFeeRate`), mtFeeRate: decimal(facts.mtFeeRate, `${path}.facts.mtFeeRate`) });
  const decoded = Object.freeze({ cutoff: cutoff(source.cutoff, `${path}.cutoff`), candidateSnapshotHash: hash(source.candidateSnapshotHash, `${path}.candidateSnapshotHash`), instanceKey: address(source.instanceKey, `${path}.instanceKey`), factsHash: hash(source.factsHash, `${path}.factsHash`), facts: decodedFacts });
  if (decoded.instanceKey !== decoded.facts.pool) throw new TypeError("dodo identity instance mismatch");
  if (decoded.factsHash !== hashDomain("aloha/dodo-v2/identity-facts/v1", { ...decoded.facts, pmm: pmmWire(decoded.facts.pmm) })) throw new TypeError("dodo identity facts hash mismatch");
  return decoded;
}
function decodeMemo(value: unknown, path = "route.identityMemo"): Memo {
  const source = exact(value, ["candidateSnapshotHash", "familyCandidateKey", "familyDefinitionHash", "familyId", "instanceNominationKey", "identity", "kind"], path); if (source.kind !== "dodo-v2-identity-memo" || source.familyId !== DODO_V2_FAMILY_ID) throw new TypeError("dodo identity memo discriminator mismatch");
  const familyDefinitionHash = hash(source.familyDefinitionHash, `${path}.familyDefinitionHash`); if (familyDefinitionHash !== DODO_V2_FAMILY_DEFINITION_HASH) throw new TypeError("dodo identity memo definition mismatch"); const instanceNominationKey = address(source.instanceNominationKey, `${path}.instanceNominationKey`);
  const memo = Object.freeze({ kind: "dodo-v2-identity-memo" as const, familyId: DODO_V2_FAMILY_ID, familyDefinitionHash, familyCandidateKey: hash(source.familyCandidateKey, `${path}.familyCandidateKey`), instanceNominationKey, candidateSnapshotHash: hash(source.candidateSnapshotHash, `${path}.candidateSnapshotHash`), identity: identity(source.identity, `${path}.identity`) });
  if (memo.familyCandidateKey !== centralFamilyCandidateKey(familyDefinitionHash, instanceNominationKey) || memo.instanceNominationKey !== memo.identity.instanceKey || memo.candidateSnapshotHash !== memo.identity.candidateSnapshotHash) throw new TypeError("dodo identity memo lineage mismatch"); return memo;
}
function stateFact(value: unknown, path = "dodo-v2.stateFact"): DodoStateReadFactsV1 {
  const source = exact(value, ["kind", "read", "version"], path); if (source.kind !== "dodo-v2-state-facts" || source.version !== 1) throw new TypeError("dodo state fact discriminator mismatch"); const read = record(source.read, `${path}.read`); assertExactKeys(read, ["cutoff", "exactAmountOut", "lpFeeRate", "mtFeeRate", "pmm", "pool", "quoteActor"], `${path}.read`);
  return Object.freeze({ cutoff: cutoff(read.cutoff, `${path}.read.cutoff`), pool: address(read.pool, `${path}.read.pool`), quoteActor: address(read.quoteActor, `${path}.read.quoteActor`), pmm: pmm(read.pmm, `${path}.read.pmm`), lpFeeRate: decimal(read.lpFeeRate, `${path}.read.lpFeeRate`), mtFeeRate: decimal(read.mtFeeRate, `${path}.read.mtFeeRate`), exactAmountOut: decimal(read.exactAmountOut, `${path}.read.exactAmountOut`) });
}
function protocolAssetRef(chainId: string, token: string): Hash { return erc20AssetRefV1(chainId, token); }
interface Context extends FamilySearchLegRequestV1 { readonly routeBindingHash: Hash; readonly source: ReturnType<typeof familySearchSource>; readonly objective: ReturnType<typeof familySearchObjective>; readonly amount: ReturnType<typeof familySearchAmount>; readonly execution: ReturnType<typeof familySearchExecutionContext>; readonly executionContextHash: Hash; readonly identity: DodoIdentityV1; readonly protocolRoute: DodoRouteV1; }
function context(input: FamilySearchLegRequestV1): Context {
  const route = validateFamilySearchRouteLegBinding(input.route); if (route.familyId !== DODO_V2_FAMILY_ID || route.familyDefinitionHash !== DODO_V2_FAMILY_DEFINITION_HASH) throw new TypeError("dodo search route family mismatch"); const memo = decodeMemo(route.identityMemo); if (hashDomain("aloha/identity-memo/v1", route.identityMemo) !== route.identityMemoHash || route.instanceKey !== memo.identity.instanceKey) throw new TypeError("dodo search identity memo binding mismatch"); const source = familySearchSource(input.currentSource.source); const objective = familySearchObjective(input.objective); const amount = familySearchAmount(input.amount); const rawExecution = familySearchExecutionContext(input.execution); const execution = Object.freeze({ transactionOrigin: canonicalAddress(rawExecution.transactionOrigin), executorAddress: canonicalAddress(rawExecution.executorAddress) }); if (execution.executorAddress !== canonicalAddress(amount.recipient)) throw new TypeError("dodo search executor/recipient mismatch"); const executionContextHash = familySearchExecutionContextHash(execution); const protocolRoute = deriveDodoRoutes(memo.identity).find(item => protocolAssetRef(source.chainId, item.inputToken) === amount.inputAssetRef && protocolAssetRef(source.chainId, item.outputToken) === amount.outputAssetRef); if (protocolRoute === undefined) throw new TypeError("dodo search amount assets do not match identity"); assertDodoRoute(protocolRoute, memo.identity); return Object.freeze({ ...input, route, routeBindingHash: familySearchRouteBindingHash(route), source, objective, amount, execution, executionContextHash, identity: memo.identity, protocolRoute });
}
function materializedState(ctx: Context, artifact: FamilySearchStateArtifactV1): DodoMaterializedStateV1 {
  if (artifact.kind !== "state" || artifact.status !== "verified" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash) throw new TypeError("dodo search state artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("state", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash })) throw new TypeError("dodo search state artifact hash mismatch"); const read = stateFact(payload); if (!sameCutoff(read.cutoff, ctx.source) || read.pool !== ctx.identity.instanceKey || read.quoteActor !== ctx.execution.transactionOrigin) throw new TypeError("dodo search state lineage mismatch"); if (artifact.factsRoot !== hashDomain("aloha/dodo-v2/state-facts/v1", { ...read, pmm: pmmWire(read.pmm) })) throw new TypeError("dodo search state facts root mismatch"); const result = materializeDodoV2({ identity: ctx.identity, read }); if (result.status !== "verified") throw new TypeError(`dodo search state ${result.reasonCode}`); return result.state;
}
function quoteFromPayload(value: unknown, path: string): DodoQuoteV1 {
  const source = exact(value, ["amountIn", "amountOut", "cutoff", "grossAmountOut", "lpFee", "mtFee", "quoteHash", "routeBindingHash", "stateHash"], path); const quote = Object.freeze({ cutoff: cutoff(source.cutoff, `${path}.cutoff`), routeBindingHash: hash(source.routeBindingHash, `${path}.routeBindingHash`), amountIn: decimal(source.amountIn, `${path}.amountIn`), amountOut: decimal(source.amountOut, `${path}.amountOut`), grossAmountOut: decimal(source.grossAmountOut, `${path}.grossAmountOut`), lpFee: decimal(source.lpFee, `${path}.lpFee`), mtFee: decimal(source.mtFee, `${path}.mtFee`), stateHash: hash(source.stateHash, `${path}.stateHash`), quoteHash: hash(source.quoteHash, `${path}.quoteHash`) }); if (quote.quoteHash !== hashDomain("aloha/dodo-v2/quote/v1", { cutoff: quote.cutoff, routeBindingHash: quote.routeBindingHash, amountIn: quote.amountIn, amountOut: quote.amountOut, grossAmountOut: quote.grossAmountOut, lpFee: quote.lpFee, mtFee: quote.mtFee, stateHash: quote.stateHash })) throw new TypeError("dodo search quote hash mismatch"); return quote;
}
function coarseArtifact(ctx: Context, stateArtifact: FamilySearchStateArtifactV1, state: DodoMaterializedStateV1, quote: DodoQuoteV1): FamilySearchCoarseArtifactV1 { const payload = canonical(quote); const payloadHash = familySearchPayloadHash("coarse", payload); const amountHash = familySearchAmountHash(ctx.amount); const projectionHash = hashDomain("aloha/dodo-v2/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }); const rankKey = hashDomain("aloha/dodo-v2/search-coarse-rank/v1", { objectiveRef: ctx.objective.objectiveRef, routeBindingHash: ctx.routeBindingHash, quoteHash: quote.quoteHash }); return Object.freeze({ kind: "coarse", status: "rankable", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payloadHash }), projectionHash, stateFactsRoot: stateArtifact.factsRoot, input: { assetRef: ctx.amount.inputAssetRef, amount: ctx.amount.amountIn }, output: { assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }, conservativeOutputUpperBound: quote.amountOut, inputCapacityUpperBound: null, rankKey, reasonCode: null }); }
function validateCoarse(ctx: Context, stateArtifact: FamilySearchStateArtifactV1, state: DodoMaterializedStateV1, artifact: FamilySearchCoarseArtifactV1): DodoQuoteV1 { const amountHash = familySearchAmountHash(ctx.amount); if (artifact.kind !== "coarse" || artifact.status !== "rankable" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash || artifact.objectiveRef !== ctx.objective.objectiveRef || artifact.amountHash !== amountHash) throw new TypeError("dodo search coarse artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("coarse", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "coarse", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payloadHash })) throw new TypeError("dodo search coarse artifact hash mismatch"); const quote = quoteFromPayload(payload, "dodo.search.coarse.payload"); if (quote.routeBindingHash !== ctx.protocolRoute.routeBindingHash || quote.amountIn !== ctx.amount.amountIn || quote.stateHash !== state.stateHash || artifact.stateFactsRoot !== stateArtifact.factsRoot || artifact.output?.assetRef !== ctx.amount.outputAssetRef || artifact.output.amount !== quote.amountOut || artifact.projectionHash !== hashDomain("aloha/dodo-v2/search-coarse-projection/v1", { quoteHash: quote.quoteHash, stateHash: state.stateHash }) || artifact.rankKey !== hashDomain("aloha/dodo-v2/search-coarse-rank/v1", { objectiveRef: ctx.objective.objectiveRef, routeBindingHash: ctx.routeBindingHash, quoteHash: quote.quoteHash })) throw new TypeError("dodo search coarse artifact lineage mismatch"); return quote; }
function exactArtifact(ctx: Context, stateArtifact: FamilySearchStateArtifactV1, quote: DodoQuoteV1): FamilySearchExactArtifactV1 { const payload = canonical(quote); const payloadHash = familySearchPayloadHash("exact", payload); const amountHash = familySearchAmountHash(ctx.amount); const evaluationHash = hashDomain("aloha/dodo-v2/search-exact-evaluation/v1", { quoteHash: quote.quoteHash, stateHash: quote.stateHash }); const obligationRoot = hashDomain("aloha/dodo-v2/search-obligation/v1", { evaluationHash, routeBindingHash: ctx.routeBindingHash }); return Object.freeze({ kind: "exact", status: "verified", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "exact", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payloadHash }), evaluationHash, stateFactsRoot: stateArtifact.factsRoot, inputs: [{ assetRef: ctx.amount.inputAssetRef, amount: quote.amountIn }], outputs: [{ assetRef: ctx.amount.outputAssetRef, amount: quote.amountOut }], obligationRoot, reasonCode: null }); }
function validateExact(ctx: Context, artifact: FamilySearchExactArtifactV1): DodoQuoteV1 { const amountHash = familySearchAmountHash(ctx.amount); if (artifact.kind !== "exact" || artifact.status !== "verified" || !sameFamilySearchSource(artifact.source, ctx.source) || artifact.routeBindingHash !== ctx.routeBindingHash || artifact.objectiveRef !== ctx.objective.objectiveRef || artifact.amountHash !== amountHash) throw new TypeError("dodo search exact artifact binding mismatch"); const payload = canonical(artifact.payload); const payloadHash = familySearchPayloadHash("exact", payload); if (artifact.payloadHash !== payloadHash || artifact.artifactHash !== familySearchArtifactHash({ kind: "exact", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash, payloadHash })) throw new TypeError("dodo search exact artifact hash mismatch"); const quote = quoteFromPayload(payload, "dodo.search.exact.payload"); const evaluationHash = hashDomain("aloha/dodo-v2/search-exact-evaluation/v1", { quoteHash: quote.quoteHash, stateHash: quote.stateHash }); if (quote.routeBindingHash !== ctx.protocolRoute.routeBindingHash || quote.amountIn !== ctx.amount.amountIn || artifact.evaluationHash !== evaluationHash || artifact.inputs[0]?.assetRef !== ctx.amount.inputAssetRef || artifact.outputs[0]?.assetRef !== ctx.amount.outputAssetRef || artifact.outputs[0]?.amount !== quote.amountOut || artifact.obligationRoot !== hashDomain("aloha/dodo-v2/search-obligation/v1", { evaluationHash, routeBindingHash: ctx.routeBindingHash })) throw new TypeError("dodo search exact artifact lineage mismatch"); return quote; }
type DodoActionPort = typeof DODO_V2_SWAP_ACTION_PORT;
function resolvedActionPort(value: object): DodoActionPort { if (value !== DODO_V2_SWAP_ACTION_PORT) throw new TypeError("generated dodo action owner identity mismatch"); return value as DodoActionPort; }
function actionArtifact(ctx: Context, exact: FamilySearchExactArtifactV1, quote: DodoQuoteV1, actionOwnerRef: Hash, actionPort: DodoActionPort): FamilySearchActionArtifactV1 { const rawAction = actionPort.build({ identity: ctx.identity, route: ctx.protocolRoute, quote, receiver: ctx.amount.recipient }); const action = actionPort.buildSearchAction({ rawAction, quote, route: ctx.protocolRoute, sellBase: ctx.protocolRoute.sellBase, recipient: ctx.amount.recipient, searchRouteBindingHash: ctx.routeBindingHash, stateFactsRoot: exact.stateFactsRoot, inputs: exact.inputs, outputs: exact.outputs, exactEvaluationHash: exact.evaluationHash, obligationRoot: exact.obligationRoot }); const payload = canonical(action); const sealedAction = actionPort.decode(payload); if (sealedAction.actionHash !== action.actionHash || sealedAction.opaqueBytes !== action.opaqueBytes) throw new TypeError("dodo action artifact binding mismatch"); const payloadHash = familySearchPayloadHash("action", payload); return Object.freeze({ kind: "action", status: "ready", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: familySearchAmountHash(ctx.amount), payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "action", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: ctx.objective.objectiveRef, amountHash: familySearchAmountHash(ctx.amount), payloadHash }), actionHash: sealedAction.actionHash, exactEvaluationHash: exact.evaluationHash, actionOwnerId: actionPort.actionOwnerId, actionOwnerRef, opaqueBytes: sealedAction.opaqueBytes, effectTransport: sealedAction.effectTransport, inputs: exact.inputs, outputs: exact.outputs, obligationRoot: exact.obligationRoot }); }
function unavailableReason(result: Exclude<FamilySearchSourceReadResultV1, { readonly kind: "returned" }>): string { return result.kind === "unavailable" ? result.reasonCode : "unexpected-reverted-response"; }
function decodeReadResult(result: FamilySearchSourceReadResultV1, requestId: Hash, source: ReturnType<typeof familySearchSource>): string { if (result.kind !== "returned") throw new Error(unavailableReason(result)); if (result.requestId !== requestId || !sameFamilySearchSource(result.source, source)) throw new TypeError("dodo search source response binding mismatch"); if (!/^0x(?:[0-9a-fA-F]{2})*$/.test(result.dataHex)) throw new TypeError("dodo search source response is not canonical"); return result.dataHex.toLowerCase(); }

const factory: FamilySearchAdapterFactoryV1 = input => {
  if (input.familyDefinitionHash !== DODO_V2_FAMILY_DEFINITION_HASH) throw new TypeError("dodo search factory definition mismatch"); for (const ref of Object.values(input.capabilityRefs)) input.composition.resolveCapability(input.familyDefinitionHash, ref); const actionOwnerRef = assertHash(input.actionOwnerRefs.swap, "dodo actionOwnerRefs.swap"); const actionPort = resolvedActionPort(input.composition.resolveActionOwner(input.familyDefinitionHash, input.actionOwnerRefs.swap));
  const readState: FamilySearchAdapterV1["readState"] = async request => { try {
    const ctx = context(request);
    const specs = ["pmm", "userFeeRate"] as const;
    const responses = new Map<string, { readonly requestId: Hash; readonly dataHex: string }>();
    for (const key of specs) {
      const physical = encodeDodoStateCall(key, ctx.identity.instanceKey, ctx.execution.transactionOrigin);
      const requestId = hashDomain("aloha/dodo-v2/search-state-read/v1", { route: ctx.routeBindingHash, source: ctx.source, key, executionContextHash: ctx.executionContextHash, quoteActor: ctx.execution.transactionOrigin });
      await request.currentSource.assertCurrent();
      let result: FamilySearchSourceReadResultV1;
      try { result = await request.readPort.read({ request: { kind: "family-search.current-source-read", requestId, source: ctx.source, target: physical.target, data: physical.data, responseEncoding: physical.responseEncoding }, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailableFamilySearchStage("state", "source-transport-unavailable", { requestId, key, error: String(error) }); }
      if (result.kind !== "returned") return unavailableFamilySearchStage("state", unavailableReason(result), { requestId, key });
      responses.set(key, { requestId, dataHex: decodeReadResult(result, requestId, ctx.source) });
    }
    const queryKey = ctx.protocolRoute.sellBase ? "querySellBase" as const : "querySellQuote" as const;
    const queryPhysical = encodeDodoStateCall(queryKey, ctx.identity.instanceKey, ctx.execution.transactionOrigin, ctx.amount.amountIn);
    const queryRequestId = hashDomain("aloha/dodo-v2/search-state-read/v1", { route: ctx.routeBindingHash, source: ctx.source, key: "exactAmountOut", amount: ctx.amount.amountIn, executionContextHash: ctx.executionContextHash, quoteActor: ctx.execution.transactionOrigin });
    await request.currentSource.assertCurrent();
    let queryResult: FamilySearchSourceReadResultV1;
    try { queryResult = await request.readPort.read({ request: { kind: "family-search.current-source-read", requestId: queryRequestId, source: ctx.source, target: queryPhysical.target, data: queryPhysical.data, responseEncoding: queryPhysical.responseEncoding }, signal: request.signal, ...(request.deadlineAtMs === undefined ? {} : { deadlineAtMs: request.deadlineAtMs }) }); } catch (error) { return unavailableFamilySearchStage("state", "source-transport-unavailable", { requestId: queryRequestId, key: "exactAmountOut", error: String(error) }); }
    if (queryResult.kind !== "returned") return unavailableFamilySearchStage("state", unavailableReason(queryResult), { requestId: queryRequestId, key: "exactAmountOut" });
    responses.set("exactAmountOut", { requestId: queryRequestId, dataHex: decodeReadResult(queryResult, queryRequestId, ctx.source) });
    await request.currentSource.assertCurrent();
    const pmm = decodeDodoPmm(responses.get("pmm")!.dataHex);
    const fee = decodeDodoFeeRate(responses.get("userFeeRate")!.dataHex);
    const read: DodoStateReadFactsV1 = Object.freeze({ cutoff: ctx.source, pool: ctx.identity.instanceKey, quoteActor: ctx.execution.transactionOrigin, pmm, lpFeeRate: fee.lpFeeRate.toString(10), mtFeeRate: fee.mtFeeRate.toString(10), exactAmountOut: decodeDodoQuery(responses.get("exactAmountOut")!.dataHex).toString(10) });
    const materialized = materializeDodoV2({ identity: ctx.identity, read });
    if (materialized.status !== "verified") return unavailableFamilySearchStage("state", `state-${materialized.reasonCode}`, { pool: read.pool });
    const wireRead = Object.freeze({ ...read, pmm: pmmWire(read.pmm) });
    const payload = canonical({ kind: "dodo-v2-state-facts", version: 1, read: wireRead }); const payloadHash = familySearchPayloadHash("state", payload); const factsRoot = hashDomain("aloha/dodo-v2/state-facts/v1", wireRead); const sourceRequestId = hashDomain("aloha/dodo-v2/search-state-reads/v1", [...responses.values()].map(value => value.requestId)); const artifact = Object.freeze({ kind: "state" as const, status: "verified" as const, source: ctx.source, routeBindingHash: ctx.routeBindingHash, payload, payloadHash, artifactHash: familySearchArtifactHash({ kind: "state", source: ctx.source, routeBindingHash: ctx.routeBindingHash, objectiveRef: null, amountHash: null, payloadHash }), factsRoot, sourceRequestId }); return Object.freeze({ kind: "verified" as const, artifact });
  } catch (error) { return Object.freeze({ kind: "invalidProgram" as const, stage: "state", code: error instanceof Error ? error.message : "dodo-state-invalid" }); } };
  const projectCoarse: FamilySearchAdapterV1["projectCoarse"] = request => { try { const ctx = context(request); const state = materializedState(ctx, request.state); const result = coarseDodoV2({ identity: ctx.identity, state, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn }); if (result.status !== "rankable") return unavailableFamilySearchStage("coarse", result.reasonCode, { stateHash: state.stateHash }); return Object.freeze({ kind: "verified" as const, artifact: coarseArtifact(ctx, request.state, state, result.quote) }); } catch (error) { return Object.freeze({ kind: "invalidProgram" as const, stage: "coarse", code: error instanceof Error ? error.message : "dodo-coarse-invalid" }); } };
  const evaluateExact: FamilySearchAdapterV1["evaluateExact"] = request => { try { const ctx = context(request); const state = materializedState(ctx, request.state); validateCoarse(ctx, request.state, state, request.coarse); const result = exactDodoV2({ identity: ctx.identity, state, route: ctx.protocolRoute, amountIn: ctx.amount.amountIn }); if (result.status !== "verified") return unavailableFamilySearchStage("exact", result.status === "unavailable" ? result.reasonCode : result.reasonCode, { stateHash: state.stateHash }); if (state.exactAmountOut === undefined || state.exactAmountOut !== result.quote.amountOut) throw new TypeError("dodo exact ABI query diverges from local PMM quote"); return Object.freeze({ kind: "verified" as const, artifact: exactArtifact(ctx, request.state, result.quote) }); } catch (error) { return Object.freeze({ kind: "invalidProgram" as const, stage: "exact", code: error instanceof Error ? error.message : "dodo-exact-invalid" }); } };
  const buildAction: FamilySearchAdapterV1["buildAction"] = request => { try { const ctx = context(request); if (request.exact.kind !== "exact" || request.exact.status !== "verified") return unavailableFamilySearchStage("action", "exact-unavailable", request.exact); const quote = validateExact(ctx, request.exact); return Object.freeze({ kind: "verified" as const, artifact: actionArtifact(ctx, request.exact, quote, actionOwnerRef, actionPort) }); } catch (error) { return Object.freeze({ kind: "invalidProgram" as const, stage: "action", code: error instanceof Error ? error.message : "dodo-action-invalid" }); } };
  const run: FamilySearchAdapterV1["run"] = async (request: FamilySearchRunRequestV1) => { const state = await readState(request); if (state.kind !== "verified") return state; const coarse = projectCoarse({ ...request, state: state.artifact }); if (coarse.kind !== "verified") return coarse; if (coarse.artifact.status !== "rankable") return unavailableFamilySearchStage("coarse", coarse.artifact.reasonCode ?? "coarse-unavailable", coarse.artifact); const exact = evaluateExact({ ...request, state: state.artifact, coarse: coarse.artifact }); if (exact.kind !== "verified") return exact; if (exact.artifact.status !== "verified") return unavailableFamilySearchStage("exact", exact.artifact.reasonCode ?? "exact-unavailable", exact.artifact); const action = buildAction({ ...request, exact: exact.artifact }); if (action.kind !== "verified") return action; return Object.freeze({ kind: "verified" as const, artifact: Object.freeze({ state: state.artifact, coarse: coarse.artifact, exact: exact.artifact, action: action.artifact }) }); };
  return Object.freeze({ readState, projectCoarse, evaluateExact, buildAction, run });
};
export const DODO_SEARCH_RUNTIME_ADAPTER_FACTORY = factory;
