import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { SELF_BURN_NATIVE_ACTION_OWNER_ID, SELF_BURN_NATIVE_CAPABILITY_IDS, SELF_BURN_NATIVE_FAMILY_ID, SELF_BURN_NATIVE_FAMILY_VERSION, SELF_BURN_NATIVE_OWNER_REF, SELF_BURN_NATIVE_SOURCE_PLAN_ID, SELF_BURN_NATIVE_SOURCE_PLAN_SCHEMA_HASH, SELF_BURN_NATIVE_FAMILY_DEFINITION_HASH } from "./manifest.ts";
const version = asCapabilityVersion(SELF_BURN_NATIVE_FAMILY_VERSION); const moduleRoot = "families/self-burn-native/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([asCapabilityId(`family.${SELF_BURN_NATIVE_FAMILY_ID}.${stage}`)]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/self-burn-native/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([SELF_BURN_NATIVE_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "exact" | "trigger"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(SELF_BURN_NATIVE_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/self-burn-native/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/self-burn-native/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "SELF_BURN_NATIVE_RUNTIME" }); }
function absent(name: "state" | "coarse"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(SELF_BURN_NATIVE_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/self-burn-native/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/self-burn-native/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "SELF_BURN_NATIVE_RUNTIME" }); }
const n = core("nomination", "SELF_BURN_NATIVE_NOMINATION_DEFINITION"); const i = core("identity", "SELF_BURN_NATIVE_IDENTITY_DEFINITION"); const m = core("materialization", "SELF_BURN_NATIVE_MATERIALIZATION_DEFINITION"); const p = core("projection", "SELF_BURN_NATIVE_PROJECTION_DEFINITION"); const r = core("rehydration", "SELF_BURN_NATIVE_REHYDRATION_DEFINITION"); const state = absent("state"); const coarse = absent("coarse"); const exact = present("exact"); const trigger = present("trigger");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.self-burn-native.identity", version, schemaHash: asSchemaRef(hashDomain("aloha/self-burn-native/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.self-burn-native.effects", version, schemaHash: asSchemaRef(hashDomain("aloha/self-burn-native/fact-schema/v1", "effects")) })]);
const actionOwner = Object.freeze({ ownerId: SELF_BURN_NATIVE_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/self-burn-native/action-schema/v1", "redeem")), implementationHash: hashDomain("aloha/self-burn-native/action-implementation/v1", "redeem"), actionKinds: Object.freeze(["redeem"]), modulePath: `${moduleRoot}/action.ts`, exportName: "SELF_BURN_NATIVE_ACTION_PORT" });
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: SELF_BURN_NATIVE_FAMILY_ID, version: SELF_BURN_NATIVE_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/self-burn-native/plugin-code/v1", { n, i, m, p, r, state, coarse, exact, trigger, facts, actionOwner }), authorityDeclarationHash: hashDomain("aloha/self-burn-native/authority/v1", SELF_BURN_NATIVE_OWNER_REF), sourcePlans: [{ sourcePlanId: SELF_BURN_NATIVE_SOURCE_PLAN_ID, completeness: "nomination-only", historyStartBlock: null, schemaHash: SELF_BURN_NATIVE_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "SELF_BURN_NATIVE_SOURCE_PLAN_RUNTIME", nominationProgram: { kind: "present", program: { modulePath: "families/self-burn-native/src/source-plan.ts", exportName: "SELF_BURN_NATIVE_SOURCE_NOMINATION_PROGRAM", schemaHash: SELF_BURN_NATIVE_SOURCE_PLAN_SCHEMA_HASH, mutationCorpus: { modulePath: "families/self-burn-native/src/nomination-qualification.ts", exportName: "SELF_BURN_NATIVE_NOMINATION_MUTATION_CORPUS" }, independentOracle: { modulePath: "families/self-burn-native/src/nomination-qualification.ts", exportName: "SELF_BURN_NATIVE_NOMINATION_INDEPENDENT_ORACLE" } } } }] }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [SELF_BURN_NATIVE_CAPABILITY_IDS.state]: { kind: "absent", reason: "requires-future-extension" }, [SELF_BURN_NATIVE_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "requires-future-extension" }, [SELF_BURN_NATIVE_CAPABILITY_IDS.exact]: { kind: "present", module: exact }, [SELF_BURN_NATIVE_CAPABILITY_IDS.trigger]: { kind: "present", module: trigger } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "SELF_BURN_NATIVE_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { exact: asCapabilityId(SELF_BURN_NATIVE_CAPABILITY_IDS.exact), trigger: asCapabilityId(SELF_BURN_NATIVE_CAPABILITY_IDS.trigger) }, actionOwnerIds: { redeem: SELF_BURN_NATIVE_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const SELF_BURN_NATIVE_DEFINITION = defineFamily(input); export const SELF_BURN_NATIVE_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(SELF_BURN_NATIVE_DEFINITION); export { SELF_BURN_NATIVE_FAMILY_DEFINITION_HASH, SELF_BURN_NATIVE_OWNER_REF };
