import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { selfBurnProbeAmounts, validateSelfBurnNativeRedeem } from "../kernel/effects.ts";
import { SELF_BURN_NATIVE_ACTION_OWNER_ID, SELF_BURN_NATIVE_MANIFEST, SELF_BURN_NATIVE_SOURCE_WINDOW_BLOCKS } from "./manifest.ts";
import { SELF_BURN_NATIVE_FAMILY_AUTHORING_HASH } from "./family-definition.ts";
import { assertCutoff, canonicalAddress, cutoffEqual, familyCandidateKey, type SelfBurnNativeActionV1, type SelfBurnNativeCandidateV1, type SelfBurnNativeExactReadFactsV1, type SelfBurnNativeExactV1, type SelfBurnNativeExecutionIntentV1, type SelfBurnNativeIdentityReadFactsV1, type SelfBurnNativeIdentityV1, type SelfBurnNativeMaterializedStateV1, type SelfBurnNativeObservationV1, type SelfBurnNativeRouteV1, type SelfBurnNativeStateReadFactsV1 } from "./types.ts";
export type SelfBurnNativeDiscoveryPatternV1 = "self-burn-native-surface" | "self-burn-native-call";
export const SELF_BURN_NATIVE_OWNED_LOG_TOPIC = "0x5dd085b6070b4cae004f84daafd199fd55b0bdfa11c3a802baffe89c2419d8c2" as const;
export interface SelfBurnNativeCandidateSeedV1 { readonly target: string; readonly evidence: SelfBurnNativeObservationV1; }
export function decodeSelfBurnNativeCandidate(observation: SelfBurnNativeObservationV1, pattern: SelfBurnNativeDiscoveryPatternV1): SelfBurnNativeCandidateSeedV1 | null { if ((pattern === "self-burn-native-surface" || pattern === "self-burn-native-call") && (observation.kind === "call" || observation.kind === "address-surface" || (observation.kind === "log" && observation.topic === SELF_BURN_NATIVE_OWNED_LOG_TOPIC))) return Object.freeze({ target: canonicalAddress(observation.target), evidence: observation }); return null; }
export function instanceNominationKey(input: SelfBurnNativeCandidateSeedV1 | SelfBurnNativeCandidateV1): string { return canonicalAddress(input.target); }
export function candidateSnapshotHash(input: SelfBurnNativeObservationV1): Hash { return hashDomain("aloha/self-burn-native/candidate-snapshot/v1", { familyDefinitionHash: SELF_BURN_NATIVE_FAMILY_AUTHORING_HASH, target: canonicalAddress(input.target), cutoff: input.cutoff, blockNumber: input.blockNumber, blockHash: input.blockHash, txHash: input.txHash, logIndex: input.logIndex, topic: input.topic ?? null, rawLocatorHash: input.rawLocatorHash }); }
export type SelfBurnNativeNominationOutcomeV1 = { readonly status: "nominated"; readonly candidate: SelfBurnNativeCandidateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "evidence-before-window" | "evidence-after-cutoff" };
export function nominateSelfBurnNative(input: SelfBurnNativeCandidateSeedV1): SelfBurnNativeNominationOutcomeV1 { const cutoff = assertCutoff(input.evidence.cutoff), block = BigInt(input.evidence.blockNumber), end = BigInt(cutoff.number); if (block > end) return { status: "chain-proven-rejected", reasonCode: "evidence-after-cutoff" }; if (block < end - BigInt(SELF_BURN_NATIVE_SOURCE_WINDOW_BLOCKS - 1)) return { status: "chain-proven-rejected", reasonCode: "evidence-before-window" }; const target = canonicalAddress(input.target); return Object.freeze({ status: "nominated", candidate: Object.freeze({ target, instanceNominationKey: instanceNominationKey({ target, evidence: input.evidence }), candidateSnapshotHash: candidateSnapshotHash({ ...input.evidence, target }), evidence: Object.freeze({ ...input.evidence, target, cutoff }) }) }); }
export function candidateFamilyKey(candidate: SelfBurnNativeCandidateV1): Hash { return familyCandidateKey(candidate.instanceNominationKey); }
export type SelfBurnNativeIdentityOutcomeV1 = { readonly status: "verified"; readonly identity: SelfBurnNativeIdentityV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "reverse-identity-mismatch" };
export function verifySelfBurnNativeIdentityStage(input: { readonly candidate: SelfBurnNativeCandidateV1; readonly reads: SelfBurnNativeIdentityReadFactsV1 }): SelfBurnNativeIdentityOutcomeV1 { const r = { ...input.reads, cutoff: assertCutoff(input.reads.cutoff), target: canonicalAddress(input.reads.target), reverseTarget: canonicalAddress(input.reads.reverseTarget), token: canonicalAddress(input.reads.token), actor: canonicalAddress(input.reads.actor), redeemSelector: input.reads.redeemSelector.toLowerCase() as `0x${string}` }; if (!cutoffEqual(r.cutoff, input.candidate.evidence.cutoff)) throw new TypeError("self-burn-native identity cutoff mismatch"); if (r.target !== canonicalAddress(input.candidate.target) || r.reverseTarget !== r.target) return { status: "chain-proven-rejected", reasonCode: "reverse-identity-mismatch" }; const facts = Object.freeze({ target: r.target, token: r.token, actor: r.actor, redeemSelector: r.redeemSelector }); return Object.freeze({ status: "verified", identity: Object.freeze({ cutoff: r.cutoff, candidateSnapshotHash: input.candidate.candidateSnapshotHash, instanceKey: r.target, factsHash: hashDomain("aloha/self-burn-native/identity-facts/v1", facts), facts }) }); }
export function identityDescriptorHash(identity: SelfBurnNativeIdentityV1): Hash { return hashDomain("aloha/self-burn-native/instance-descriptor/v1", { familyDefinitionHash: SELF_BURN_NATIVE_FAMILY_AUTHORING_HASH, factsHash: identity.factsHash, instanceKey: identity.instanceKey }); }
export type SelfBurnNativeMaterializationOutcomeV1 = { readonly status: "verified"; readonly state: SelfBurnNativeMaterializedStateV1 } | { readonly status: "chain-proven-rejected"; readonly reasonCode: "instance-mismatch" };
export function materializeSelfBurnNative(input: { readonly identity: SelfBurnNativeIdentityV1; readonly read: SelfBurnNativeStateReadFactsV1 }): SelfBurnNativeMaterializationOutcomeV1 { const read = { ...input.read, cutoff: assertCutoff(input.read.cutoff), instanceKey: canonicalAddress(input.read.instanceKey) }; if (!cutoffEqual(read.cutoff, input.identity.cutoff)) throw new TypeError("self-burn-native state cutoff mismatch"); if (read.instanceKey !== input.identity.instanceKey) return { status: "chain-proven-rejected", reasonCode: "instance-mismatch" }; const materializedHash = hashDomain("aloha/self-burn-native/materialized-state/v1", { identityFactsHash: input.identity.factsHash, stateHash: read.stateHash }); return Object.freeze({ status: "verified", state: Object.freeze({ ...read, identityFactsHash: input.identity.factsHash, materializedHash }) }); }
export function deriveSelfBurnNativeRoutes(identity: SelfBurnNativeIdentityV1): readonly SelfBurnNativeRouteV1[] { const route = { instanceKey: identity.instanceKey, inputAsset: identity.facts.token, outputAsset: "native" }; return Object.freeze([Object.freeze({ ...route, routeBindingHash: hashDomain("aloha/self-burn-native/route-binding/v1", route) })]); }
export function assertSelfBurnNativeRoute(route: SelfBurnNativeRouteV1, identity: SelfBurnNativeIdentityV1): void { if (route.instanceKey !== identity.instanceKey || route.inputAsset !== identity.facts.token || route.outputAsset !== "native") throw new TypeError("self-burn-native route identity mismatch"); }
export type SelfBurnNativeCoarseOutcomeV1 = { readonly status: "unavailable"; readonly reasonCode: "coarse-quote-not-defined" };
export function coarseSelfBurnNative(): SelfBurnNativeCoarseOutcomeV1 { return Object.freeze({ status: "unavailable", reasonCode: "coarse-quote-not-defined" }); }
export function exactSelfBurnNative(input: { readonly identity: SelfBurnNativeIdentityV1; readonly route: SelfBurnNativeRouteV1; readonly amountIn: string; readonly effects: SelfBurnNativeExactReadFactsV1 }): { readonly status: "verified"; readonly exact: SelfBurnNativeExactV1 } | { readonly status: "unavailable"; readonly reasonCode: "effect-observation-unavailable" } { assertSelfBurnNativeRoute(input.route, input.identity); try { const payout = validateSelfBurnNativeRedeem({ ...input.effects, token: input.identity.facts.token, actor: input.identity.facts.actor, amountIn: BigInt(input.amountIn) }); const payload = { cutoff: input.identity.cutoff, routeBindingHash: input.route.routeBindingHash, amountIn: input.amountIn, nativePayout: payout.toString() }; const effects = { completion: input.effects.completion, returnDataHex: input.effects.returnDataHex, tokenDeltas: input.effects.tokenDeltas.map(value => ({ token: value.token, account: value.account, delta: value.delta.toString() })), nativeDeltas: input.effects.nativeDeltas.map(value => ({ account: value.account, delta: value.delta.toString() })), supplyDeltas: input.effects.supplyDeltas.map(value => ({ token: value.token, delta: value.delta.toString() })), token: input.effects.token, actor: input.effects.actor, amountIn: input.effects.amountIn }; return Object.freeze({ status: "verified", exact: Object.freeze({ ...payload, effectsHash: hashDomain("aloha/self-burn-native/exact-effects/v1", { payload, effects }) }) }); } catch { return Object.freeze({ status: "unavailable", reasonCode: "effect-observation-unavailable" }); } }
export function triggerSelfBurnNative(amountIn: string): readonly string[] { return Object.freeze(selfBurnProbeAmounts(BigInt(amountIn)).map(value => value.toString())); }
export function buildSelfBurnNativeAction(input: { readonly identity: SelfBurnNativeIdentityV1; readonly exact: SelfBurnNativeExactV1; readonly calldata: string }): SelfBurnNativeActionV1 { if (!/^0x[0-9a-fA-F]*$/.test(input.calldata) || input.calldata.length % 2 !== 0) throw new TypeError("self-burn-native calldata is not canonical"); const payload = { cutoff: input.identity.cutoff, target: canonicalAddress(input.identity.instanceKey), calldata: input.calldata, exactEffectsHash: input.exact.effectsHash }; return Object.freeze({ ...payload, actionHash: hashDomain("aloha/self-burn-native/action/v1", payload) }); }
export const SELF_BURN_NATIVE_ACTION_PORT = Object.freeze({ actionOwnerId: SELF_BURN_NATIVE_ACTION_OWNER_ID, build: buildSelfBurnNativeAction });
export function compileSelfBurnNativeExecution(input: { readonly identity: SelfBurnNativeIdentityV1; readonly action: SelfBurnNativeActionV1 }): SelfBurnNativeExecutionIntentV1 { if (input.action.target !== canonicalAddress(input.identity.instanceKey)) throw new TypeError("self-burn-native execution target mismatch"); return Object.freeze({ kind: "self-burn-native-execution-intent", cutoff: input.action.cutoff, target: input.action.target, calldata: input.action.calldata, actionHash: input.action.actionHash, exactEffectsHash: input.action.exactEffectsHash }); }
export function captureSelfBurnNativeEvidence(input: { readonly observation: SelfBurnNativeObservationV1; readonly pattern: SelfBurnNativeDiscoveryPatternV1 }): SelfBurnNativeCandidateSeedV1 | null { return decodeSelfBurnNativeCandidate(input.observation, input.pattern); }
export const SELF_BURN_NATIVE_RUNTIME = Object.freeze({ manifest: SELF_BURN_NATIVE_MANIFEST, discover: decodeSelfBurnNativeCandidate, capture: captureSelfBurnNativeEvidence, nominate: nominateSelfBurnNative, identity: verifySelfBurnNativeIdentityStage, materialize: materializeSelfBurnNative, routes: deriveSelfBurnNativeRoutes, coarse: coarseSelfBurnNative, exact: exactSelfBurnNative, execute: compileSelfBurnNativeExecution });
export const SELF_BURN_NATIVE_NOMINATION_RUNTIME = Object.freeze({ stage: "nomination", run: nominateSelfBurnNative });
export const SELF_BURN_NATIVE_IDENTITY_RUNTIME = Object.freeze({ stage: "identity", run: verifySelfBurnNativeIdentityStage });
export const SELF_BURN_NATIVE_MATERIALIZATION_RUNTIME = Object.freeze({ stage: "materialization", run: materializeSelfBurnNative });
export const SELF_BURN_NATIVE_PROJECTION_RUNTIME = Object.freeze({ stage: "projection", run: deriveSelfBurnNativeRoutes });
export const SELF_BURN_NATIVE_REHYDRATION_RUNTIME = Object.freeze({ stage: "rehydration", run: deriveSelfBurnNativeRoutes });
