import { defineFamily, familyAuthoringDigest, type AuthoringModuleRefV1, type FamilyAuthoringDefinitionV1 } from "../../../packages/family-sdk/authoring/index.ts";
import { asCapabilityId, asCapabilityVersion, asSchemaRef, type CapabilityAuthoringDeclarationV1, type FamilyFactContractRefV1 } from "../../../packages/capability-contracts/src/index.ts";
import { hashDomain, type Hash } from "../../../packages/canonical-codec/src/index.ts";
import { FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1 } from "../../../packages/family-sdk/search-runtime/index.ts";
import { EIGENPIE_ACTION_OWNER_ID, EIGENPIE_CAPABILITY_IDS, EIGENPIE_FAMILY_DEFINITION_HASH, EIGENPIE_FAMILY_ID, EIGENPIE_FAMILY_VERSION, EIGENPIE_HISTORY_SOURCE_PLAN_ID, EIGENPIE_HISTORY_SOURCE_PLAN_SCHEMA_HASH, EIGENPIE_OWNER_REF, EIGENPIE_SOURCE_PLAN_ID, EIGENPIE_SOURCE_PLAN_SCHEMA_HASH } from "./manifest.ts";
const version = asCapabilityVersion(EIGENPIE_FAMILY_VERSION); const moduleRoot = "families/eigenpie/src"; type CoreStage = "nomination" | "identity" | "materialization" | "projection" | "rehydration";
function core<S extends CoreStage>(stage: S, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: S } & (S extends "nomination" ? { readonly sourcePlanIds: readonly string[] } : {});
function core(stage: CoreStage, exportName: string): AuthoringModuleRefV1 & { readonly artifactKind: CoreStage; readonly sourcePlanIds?: readonly string[] } { const capabilityId = asCapabilityId(`family.${EIGENPIE_FAMILY_ID}.${stage}`); return Object.freeze({ modulePath: `${moduleRoot}/runtime/definitions.ts`, exportName, artifactKind: stage, capabilityIds: Object.freeze([capabilityId]), schemaRefs: Object.freeze([asSchemaRef(hashDomain("aloha/eigenpie/stage-schema/v1", stage))]), ...(stage === "nomination" ? { sourcePlanIds: Object.freeze([EIGENPIE_SOURCE_PLAN_ID, EIGENPIE_HISTORY_SOURCE_PLAN_ID]) } : {}) }); }
function present(name: "exact"): CapabilityAuthoringDeclarationV1 { return Object.freeze({ capabilityId: asCapabilityId(EIGENPIE_CAPABILITY_IDS[name]), version, schemaHash: asSchemaRef(hashDomain("aloha/eigenpie/extension-schema/v1", name)), interpreterHash: hashDomain("aloha/eigenpie/extension-interpreter/v1", name), dependencyIds: Object.freeze([]), artifactKinds: Object.freeze([name]), modulePath: `${moduleRoot}/runtime.ts`, exportName: "EIGENPIE_RUNTIME" }); }
const n = core("nomination", "EIGENPIE_NOMINATION_DEFINITION"); const i = core("identity", "EIGENPIE_IDENTITY_DEFINITION"); const m = core("materialization", "EIGENPIE_MATERIALIZATION_DEFINITION"); const p = core("projection", "EIGENPIE_PROJECTION_DEFINITION"); const r = core("rehydration", "EIGENPIE_REHYDRATION_DEFINITION"); const exact = present("exact");
const facts: readonly FamilyFactContractRefV1[] = Object.freeze([Object.freeze({ factContractId: "family.eigenpie.identity-reads", version, schemaHash: asSchemaRef(hashDomain("aloha/eigenpie/fact-schema/v1", "identity")) }), Object.freeze({ factContractId: "family.eigenpie.quote-return", version, schemaHash: asSchemaRef(hashDomain("aloha/eigenpie/fact-schema/v1", "quote")) })]);
const actionOwner = Object.freeze({ ownerId: EIGENPIE_ACTION_OWNER_ID, version, schemaHash: asSchemaRef(hashDomain("aloha/eigenpie/action-schema/v1", "protocol")), implementationHash: hashDomain("aloha/eigenpie/action-implementation/v1", "protocol"), actionKinds: Object.freeze(["protocol-call"]), modulePath: `${moduleRoot}/action.ts`, exportName: "EIGENPIE_PROTOCOL_ACTION_PORT" });
const qualificationRefs = Object.freeze({ mutationCorpus: Object.freeze({ modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "EIGENPIE_NOMINATION_MUTATION_CORPUS" }), independentOracle: Object.freeze({ modulePath: `${moduleRoot}/nomination-qualification.ts`, exportName: "EIGENPIE_NOMINATION_INDEPENDENT_ORACLE" }) });
const sourcePlans = Object.freeze([
  Object.freeze({ sourcePlanId: EIGENPIE_SOURCE_PLAN_ID, completeness: "nomination-only" as const, historyStartBlock: null, schemaHash: EIGENPIE_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/source-plan.ts`, exportName: "EIGENPIE_SOURCE_PLAN_RUNTIME", nominationProgram: Object.freeze({ kind: "present" as const, program: Object.freeze({ modulePath: `${moduleRoot}/source-plan.ts`, exportName: "EIGENPIE_SOURCE_NOMINATION_PROGRAM", schemaHash: EIGENPIE_SOURCE_PLAN_SCHEMA_HASH, ...qualificationRefs }) }) }),
  Object.freeze({ sourcePlanId: EIGENPIE_HISTORY_SOURCE_PLAN_ID, completeness: "rolling-observation" as const, historyStartBlock: null, schemaHash: EIGENPIE_HISTORY_SOURCE_PLAN_SCHEMA_HASH, modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "EIGENPIE_HISTORY_SOURCE_PLAN_RUNTIME", nominationProgram: Object.freeze({ kind: "present" as const, program: Object.freeze({ modulePath: `${moduleRoot}/history-source-plan.ts`, exportName: "EIGENPIE_HISTORY_NOMINATION_PROGRAM", schemaHash: EIGENPIE_HISTORY_SOURCE_PLAN_SCHEMA_HASH, ...qualificationRefs }) }) }),
]);
const input: FamilyAuthoringDefinitionV1 = { manifest: { familyId: EIGENPIE_FAMILY_ID, version: EIGENPIE_FAMILY_VERSION, pluginCodeHash: hashDomain("aloha/eigenpie/plugin-code/v1", { n, i, m, p, r, exact, actionOwner, facts, sourcePlans }), authorityDeclarationHash: hashDomain("aloha/eigenpie/authority/v1", EIGENPIE_OWNER_REF), sourcePlans }, core: { nomination: n, identity: i, materialization: m, projection: p, rehydration: r }, extensions: { [EIGENPIE_CAPABILITY_IDS.state]: { kind: "absent", reason: "requires-future-extension" }, [EIGENPIE_CAPABILITY_IDS.coarse]: { kind: "absent", reason: "not-in-release" }, [EIGENPIE_CAPABILITY_IDS.exact]: { kind: "present", module: exact } }, runtimeAdapters: { [FAMILY_SEARCH_RUNTIME_ADAPTER_ROLE_V1]: { modulePath: `${moduleRoot}/runtime.ts`, exportName: "EIGENPIE_SEARCH_RUNTIME_ADAPTER_FACTORY", capabilityIds: { exact: asCapabilityId(EIGENPIE_CAPABILITY_IDS.exact) }, actionOwnerIds: { protocol: EIGENPIE_ACTION_OWNER_ID } } }, actionOwners: [actionOwner], acceptanceDeclarations: facts };
export const EIGENPIE_DEFINITION = defineFamily(input); export const EIGENPIE_FAMILY_AUTHORING_HASH: Hash = familyAuthoringDigest(EIGENPIE_DEFINITION); export { EIGENPIE_OWNER_REF };
